### ISSUE TITLE
Visits numbering is wrong in Visitor Profile bug

### ISSUE THREAD

**Issue by viktorix** [piwik/piwik#11996] opened 2017-09-04 01:21 UTC
Not sure if this is a bug or by design, it looks like a bug. Visits numbering is inaccurate in the Visitor Profile modal popup. 

Here's an example:
![ze2dvvua0n](https://user-images.githubusercontent.com/1692600/30008394-34933c9e-90ed-11e7-9b2e-e8ed7dc19b9d.png)

First visit should be #1, second visit #2, and so on. Right now that's not how it's numbered, so it's a bit confusing at first glance. I believe it's been there before, but I never really paid attention to it until now.

Version: Piwik 3.0.5-b2

**Comment by tsteur** [comment] 2017-09-04 01:32
This will be fixed in https://github.com/piwik/piwik/pull/11579

**Comment by tsteur** [comment] 2017-09-04 01:33
and is duplicate of https://github.com/piwik/piwik/issues/8491

**Closed** 2017-09-04 04:55 UTC
Labels: duplicate

**Comment by blynch11p** [comment] 2017-12-19 19:59
Apologies for commenting on a closed ticket (I can't find anyone else referencing my situation), but looking at this issue, and the comment in #8491 ...

> I think the only solution will be to actually fetch the number of visits for a certain user. There is an index on idsite, idvisitor so it should be pretty fast actually.

Did that suggestion not actually happen? I've been tinkering with v3.2 and I have many users that top 100 visits.  The Visit count is starting at `#100` (not a big deal, really) but the secondary issue is that the "First Visit" date is (in my case) whatever the date for `Visit #91` is in the Visitor Profile window (ie: the date for the oldest of the 10 visits that load initially. This does not update when I click 'Load more visits').  So if the user visits a site every day, `visit #91` / First Visit is only 10 days back, rather than >100 days or > 3 years or whatever.  I believe in prior Piwik versions (I'm coming from 3.0.4) "First Visit" only every showed `Visit #100` for these use cases, but now "First Visit" is less accurate.

**Comment by sgiehl** [comment] 2017-12-20 09:22
If you want to have full summarized visitor profiles for more than 100 visits you can increase the config value for `live_visitor_profile_max_visits_to_aggregate`. It defaults to the limit of 100.
Besides that we could only add a small text like `The information in this profile summarizes the last 100 visits. This user had 157 visits in total.` to the profile if the user had more visits than the limit defined.

**Comment by blynch11p** [comment] 2017-12-20 13:32
@sgiehl, I didn't see this until I posted here (https://github.com/piwik/piwik/issues/12373#issuecomment-353052949).  
I'm ok with a 100 visit limit, but thank you for pointing out that config value.  It's the First Visit date that changed from previous Piwik versions (and/or counting back to the date of the 100th visit)
