### ISSUE TITLE
Average time spent on each page is incorrect

### ISSUE THREAD

**Issue by mkassir95** [piwik/piwik#18270] opened 2021-11-03 21:47 UTC
I am tracking events and pages , matomo is calacating the time spent on each page as the difference between the last event done on the page and the next page view and not the difference between the two page views. How to solve this

**Comment by peterbo** [comment] 2021-11-11 01:31
+1 - Time on page is currently calculated incorrectly on pages that trigger events or site searches (and probably others like outlinks). The time on page timer should only be stopped by another pageview.

![time on page1](https://user-images.githubusercontent.com/1018973/141221344-a04e6f5c-8eb6-4b30-8737-4a599fb6f077.png)

Time on page should be 14s here, because the second pageview happened 14s after the first one. But it is only 1s, because the timer is stopped by (in this case) the site search. The exact same behaviour happens with events.

**Comment by sgiehl** [comment] 2021-11-11 07:45
That indeed sounds like a bug. @peterbo Are you able to say if that only has effect on the visits log, or is that also the case for the overall time one page calculation you can see in the pages reports?

**Comment by sgiehl** [comment] 2021-11-11 08:26
@peterbo Had a quick look at the visits log implementation. This might possibly fix it: https://github.com/matomo-org/matomo/compare/vlogtimeonpage
But I'm currently not able to finish that PR by adding some tests as my time is quite limited. Will try to finish that another time if no one else is able to pick that up till then.

**Comment by peterbo** [comment] 2021-11-11 15:19
> 
> 
> That indeed sounds like a bug. @peterbo Are you able to say if that only has effect on the visits log, or is that also the case for the overall time one page calculation you can see in the pages reports?

That's a good question. It definitely reflects the wrong behaviour in the link_visit_action table (time_spent_ref_action), but perhaps the archiver uses another logic. I'll check later in a smaller instance and replicate this.

**Comment by peterbo** [comment] 2021-11-11 16:32
> 
> 
> That indeed sounds like a bug. @peterbo Are you able to say if that only has effect on the visits log, or is that also the case for the overall time one page calculation you can see in the pages reports?

Luckily, it looks like it doesn't affect the calculation of the pages report "avg. time on page", but just the display within the Visitor log:

![time_on_page2](https://user-images.githubusercontent.com/1018973/141325340-8631e6b9-2c1c-436d-a6bc-041f5151507f.png)

**Comment by tsteur** [comment] 2021-11-11 19:06
Is this a duplicate of https://github.com/matomo-org/matomo/issues/9198 ?

**Comment by sgiehl** [comment] 2021-11-11 20:12
@tsteur it's not a duplicate. #9198 is about the average metric, which is also wrong for a similar reason. This is about the time on page displayed is the visits log tooltips. The linked PR aims to fix that, even though it's not yet complete.

**Closed as completed** 2021-11-26 14:35 UTC
Labels: Bug
