### ISSUE TITLE
Widget "Become a Matomo expert" does not work right (Add user)

### ISSUE THREAD

**Issue by Alpengreis** [piwik/piwik#20569] opened 2023-04-07 19:56 UTC
At least in Matomo 4.14.1, the Widget "Become a Matomo expert" does not work right. The Add user goal does not work.

Here you can see that I have added 2 additionally user:

![matomo_plg__become_a_expert__problem_1-2](https://user-images.githubusercontent.com/11355601/230668941-242af3a7-03eb-46db-97b0-7dced12f819b.PNG)
![matomo_plg__become_a_expert__problem_2-2](https://user-images.githubusercontent.com/11355601/230668942-b01a5a11-d6bf-43ed-8e95-42c2c9f15c14.PNG)

* Matomo Version: 4.14.1
* PHP Version: 8.2.4
* Server Operating System: Apache 2.4 on FreeBSD

**Comment by bx80** [comment] 2023-04-10 23:43
Thanks for reporting this @Alpengreis, I can confirm that the 'Become a Matomo Expert' widget isn't detecting that the 'Add a user' goal has been completed :+1:

This may be a regression caused by recent changes the the add user / invite user process, I'll assign this bug for prioritization by the product team.

**Closed as completed** 2023-07-16 04:12 UTC
Labels: Bug, Regression
