### ISSUE TITLE
Invalid Response - Response does not have the correct format. (iOS 10 - iPhone 7 Plus)

### ISSUE THREAD

**Issue by ytodae** [piwik/piwik#10948] opened 2016-12-03 00:19 UTC
Hi,

when i track my websites on my macbook browser, everything works fine, but on my iphone i get always this response:

![img_1152](https://cloud.githubusercontent.com/assets/22525170/20854716/6d556e8c-b8f6-11e6-8cfd-e4243d61381f.PNG)

**Comment by tsteur** [comment] 2016-12-03 00:51
which Piwik version are you using?

**Comment by ytodae** [comment] 2016-12-03 01:17
iOS = 2.3.0
Web = 3.0.0-b4

I changed nothing, it was working until yesterday.

**Comment by tsteur** [comment] 2016-12-03 02:12
@mattab I reckon the format change broke it with the latest beta which is bit of a problem since Android 4, 5 & 6 + iOS 8 & 9 users cannot upgrade and it will obviously also affect older Android & iOS users that use Piwik Mobile 1 but that shouldn't be too many. Not sure what would be best to fix it

**Comment by tsteur** [comment] 2016-12-04 18:52
I can reproduce it @ytodae and getting the very same error. 

It fails because of `index.php?idSite=1&module=API&date=today&period=day&format=json&method=SitesManager.getSiteFromId&language=en`

**Comment by ytodae** [comment] 2016-12-04 19:41
so, what i have to do, to be able to use the piwik ios app again?

**Comment by tsteur** [comment] 2016-12-04 19:46
It is a regression in Piwik itself and we might have to release a new Piwik update. Alternatively we need to update Piwik Mobile app but there won't be anything to do on your side.

**Comment by mattab** [comment] 2016-12-05 08:00
Thanks for the report! Will be fixed with: #10959

**Closed** 2016-12-05 08:57 UTC
Labels: Regression
