### ISSUE TITLE
SegmentEditorUI

### ISSUE THREAD

**Issue by jorgeuos** [piwik/piwik#17125] opened 2021-01-20 16:40 UTC
Our clients are frequent users of Segments, it's one of their most used feature actually.
We have taken the first steps to create an MVP.

Progress will be updated here and if anyone interested in helping out, just reach out.
Any thoughts or ideas are highly appreciated.

Features:
- Create a menu item for Segments
- Add user permission checks
- List segments
- Add intuitive buttons for manipulating segments using SegmentEditor plugin
- Add tests (Unit tests, Behavioural tests)
- Create PR to Matomo; plugin-SegmentEditorUI

Nice to have features:
- Quick link to overview
- Validate segment

Quick mockup:
![SegmentEditorUI](https://user-images.githubusercontent.com/21176316/105206191-5feae500-5b46-11eb-8f1a-c0ce4b9f1c4a.jpg)

Br, Jorge

**Comment by jorgeuos** [comment] 2021-01-20 16:41
Interesting features/issues:
https://github.com/search?l=&q=segments+repo%3Amatomo-org%2Fmatomo+label%3Aenhancement&state=open&type=Issues

**Comment by tsteur** [comment] 2021-01-20 21:38
@jorgeuos nice mockup. I reckon some of the things we wouldn't want in core so there would be always the possibility to put this into a plugin. For example we wouldn't want to have this in the left menu as entities are usually not really managed there unless it is a reporting entity like "Goals" etc. Maybe there could be instead some button in the segment selector similar to 
![image](https://user-images.githubusercontent.com/273120/105243787-6aec5680-5bd4-11eb-8e7e-dacf94d7b9fb.png)

In the table we would likely also hide some information like "idsegment" and maybe even "definition" (as they can be quite long and cryptic to most users and the name should already say enough). Other columns could be technically only shown if it's a superuser or so like "login". Or maybe it be not too important and could only be shown when editing a segment etc.

**Comment by mattab** [comment] 2023-05-15 10:46
Duplicate of #https://github.com/matomo-org/matomo/issues/20659

**Closed as not planned by mattab** 2023-05-15 10:46 UTC
Labels: Enhancement, duplicate
