### ISSUE TITLE
Add INI setting to disable Password Confirmation

### ISSUE THREAD

**Issue by Starker3** [piwik/piwik#19904] opened 2022-10-24 19:49 UTC
# Proposed solution

Proposed solution

-    introduce a new INI setting to let people disable the password confirmation.
-    create a new FAQ "How do I disable the password confirmation prompt?" that explains how it's not recommended because it lowers security, but when it's required for some reason, it's possible.
-    both core & WP users could leverage this setting if needed

For now i'd say we don't need to link to the FAQ within the app itself, as I guess it's very rarely needed so not worth maybe.

# Note: workaround available

* Create a file in  path/to/matomo/config/config.php
* with the content: https://github.com/matomo-org/matomo/issues/19904#issuecomment-1308497307

# Bug description
Similar to https://github.com/matomo-org/plugin-LoginLdap/issues/310

In some cases a Matomo admin might want to disable the password prompt that they get when performing any admin actions in a Matomo instance (Eg. creating a new user, changing settings, etc.)

For Matomo instances that have a high number of users and/or measurables this can mean that a Matomo admin enters their password for confirmation many times in a potentially short period of time.

With the new Password prompt implementation it is possible to disable the requirement for a password and instead just have a "Yes/No" prompt: https://github.com/matomo-org/matomo/pull/19525

However, from a security standpoint it would likely be best to have this still enabled by default and perhaps add a config option that could disable the password prompt.

**Comment by peterhashair** [comment] 2022-10-25 02:26
I will put this in the backlog for prioritization. But this may be will cause a security concern.

**Comment by xpufx** [comment] 2022-10-28 14:24
I installed matomo 10 minutes ago and I am about ready to give up due to this weird behavior. Please make it optional as soon as possible. It's super annoying.

**Comment by justinvelluppillai** [comment] 2022-10-31 04:31
@mattab this is a fairly regular request after we made changes for security purposes. Perhaps we could provide workarounds for certain use cases.

See also #19772

**Comment by mattab** [comment] 2022-10-31 05:03
How do other Saas tools like Github handle this? Do they remember for like 5minutes that the password was given, or something like this? There must be a common way to solve this problem and it would be great to learn what it is so we don't have to reinvent the wheel (and ideally we don't introduce a new setting...)

**Comment by lance-matomo** [comment] 2022-11-08 19:43
There are a couple of Wordpress plugin users that can't use these password protected features at all, they keep getting incorrect password notifications. They tried updating their passwords, using simpler passwords, using more complex passwords and updating their passwords directly in the db. Nothing worked for them. I was unable to reproduce this locally.

**Comment by mattab** [comment] 2022-11-08 23:12
Proposed solution 

* introduce a new INI setting to let people disable the password confirmation.  
* create a new FAQ "How do I disable the password confirmation prompt?" that explains how it's not recommended because it lowers security, but when it's required for some reason, it's possible.
* both core & WP users could leverage this setting if needed

For now i'd say we don't need to link to the FAQ within the app itself, as I guess it's very rarely needed so not worth maybe.

**Comment by sgiehl** [comment] 2022-11-09 09:56
It is kind of already possible to disable the password check by adding this to `config/config.php`
```
<?php

return [
    'observers.global' => \DI\add([
        ['Login.userRequiresPasswordConfirmation', \DI\value(function (&$requiresPasswordConfirmation, $login) {
            $requiresPasswordConfirmation = false;
        })],
    ]),
];
```

That way the password confirmation boxes are still shown, but you can simply click ok, without entring a password.
Might be a suitable solution for the users currently having a problem.

**Comment by mattab** [comment] 2022-12-21 19:37
Based on @sgiehl assessment, i'm moving this out of the milestone.
Instead @lance-matomo @mattmary could you collaborate with the WP users who have this issue to reproduce the issue so we can understand the root cause and fix it?

**Comment by MatomoForumNotifications** [comment] 2023-03-02 16:36
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/how-to-disable-confirmpassword-feature/49834/2

**Comment by mattab** [comment] 2023-03-10 23:10
Because  a workaround is available and documented here: https://github.com/matomo-org/matomo/issues/19904#issuecomment-1308497307

And because disabling this feature in theory shouldn't be required (and SAML / LDAP plugins handle it correctly) then we can close this issue I think. please comment or reopen if i missed something.

**Closed as not planned by mattab** 2023-03-10 23:10 UTC
Labels: wontfix, Enhancement
