### ISSUE TITLE
Improve error message language when core newer than what plugins require

### ISSUE THREAD

**Issue by michalkleiner** [piwik/piwik#20625] opened 2023-04-24 13:03 UTC
It can happen that the installed version of core is newer than what a plugin requires, but it still asks to upgrade to a newer version.

<img width="438" alt="233987144-84fa6da2-4c79-4482-b57c-20f9fe0a9323" src="https://user-images.githubusercontent.com/233342/234003910-26004f12-0f48-4706-b839-a85a1e3fc969.png">

**Comment by sgiehl** [comment] 2023-05-01 18:24
The "problem" here is, that we actually only check if the requirements for a plugin are set. If that is not the case we always use the same message without checking if the version is actually too high or too low.
Guess such a check might need to be added here:
https://github.com/matomo-org/matomo/blob/115527353a9e75e01aa4d263408956ae45403bea/plugins/CorePluginsAdmin/PluginInstaller.php#L210-L213

**Comment by sgiehl** [comment] 2023-06-27 08:37
@michalkleiner Do you remember how to reproduce that one? For me plugins always get disabled if they don't match the requirements.

**Comment by michalkleiner** [comment] 2023-06-27 08:54
@sgiehl I'll have a look and try to recall how I got the error.

**Comment by Stan-vw** [comment] 2023-07-10 21:53
Can't reproduce this anymore, so we're closing this for now.
If you still come across this problem, please reopen and explain how to reproduce.

**Closed as completed by Stan-vw** 2023-07-10 21:53 UTC
Labels: Enhancement, invalid
