### ISSUE TITLE
visits/location report: show "TOP 5" of  provider(IPS) & organisation from geo-ip separately

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#9760] opened 2016-02-11 19:54 UTC
**Show provider(IPS) & organisation from geo-ip separately in visits/location report.**
At this place it is especially interesting because otherwise real organisations including companies are (often) not visible within top 5. see example attached (each providers has millions of customers and dominate top 5 by far)
But **for business websites the visiting companies are extremly interesting** and should be visible within this summary too.

Before this could become reality "store both Provider and Organisation details" #6615 has to be solved....

![2016-02-11_21h32_06](https://cloud.githubusercontent.com/assets/5681880/12989756/01b8408c-d107-11e5-891d-f47936b038d3.png)

**Comment by mattab** [comment] 2016-03-31 03:26
Thanks for suggestion. Marking as duplicate of https://github.com/piwik/piwik/issues/6615

**Closed by mattab** 2016-03-31 03:26 UTC
