### ISSUE TITLE
RAW Data deletion checkbox is unchecked even when data deletion is enabled

### ISSUE THREAD

**Issue by Starker3** [piwik/piwik#19976] opened 2022-11-09 02:28 UTC
It looks as though the RAW data deletion checkbox in the UI does not show when the RAW data deletion is actually enabled in the database.

This can be confirmed by navigating to Administration > Privacy > Anonymize Data > Regularly delete old raw data
In a install where this was enabled, it will look as though it is no longer enabled. When changing the setting to enabled in a install where it was not previously enabled, refreshing the page after saving the setting shows the checkbox as unchecked:
![image](https://user-images.githubusercontent.com/20905821/200722194-42f34f8f-5b6d-4999-8aa6-3206fa3a95c9.png)
Even though it is enabled in the database:
![image](https://user-images.githubusercontent.com/20905821/200722243-a9a699e6-5407-4695-87be-96a7dc543d27.png)

**Comment by sgiehl** [comment] 2022-11-09 08:14
Guess that's a duplicate of #19919 and should have been fixed with #19936

**Closed as completed by sgiehl** 2022-11-09 08:14 UTC
Labels: duplicate
