### ISSUE TITLE
Goals Overview widget: Zend_Session is currently marked as read-only.

### ISSUE THREAD

**Issue by peterbo** [piwik/piwik#7274] opened 2015-02-23 12:55 UTC
Session handling refactoring introduced an error in the goal widget: Goals Overview widget: Zend_Session is currently marked as read-only.

Reproduced in 2 different instances after updating to 2.11.1.

**Comment by peterbo** [comment] 2015-02-23 13:10
In Piwik\Plugin\Controller, the method "setGeneralVariablesView" (called from Goals\Controller.php)  tries to retrieve and reset the notifications in the session. This triggers the read-only session error.

**Comment by SystemZ** [comment] 2015-02-23 20:16
I can confirm this "Goals Overview widget: Zend_Session is currently marked as read-only."

**Comment by dkulchenko** [comment] 2015-02-23 20:17
+1, having this issue as well.

**Comment by mattab** [comment] 2015-02-23 20:20
Hi guys, thanks for the report. Please comment if you experience the issue.

Btw have you configured the session to use [DB sessions](http://piwik.org/faq/how-to-install/faq_133/) in the config.ini.php or do you maybe use the default "file" session?

**Comment by dkulchenko** [comment] 2015-02-23 20:22
I've tried both ways, and am seeing the same error in either case.

**Comment by codejunky** [comment] 2015-02-23 20:50
Hi there, I have this error too!

Kind regards
Jan

**Comment by Stelefanten** [comment] 2015-02-23 21:36
Just upgraded. Same issue with Goals

**Comment by twpol** [comment] 2015-02-23 21:54
Same issue here, nothing else seems amiss - just the Goals Overview. Using the default file sessions.

**Comment by chihoko** [comment] 2015-02-24 00:40
Same problem after upgrading to 2.11.1

**Comment by tsteur** [comment] 2015-02-24 01:24
This is most likely caused by https://github.com/piwik/piwik/pull/7252/files

Can you explain what you do step by step? Just opening Step By Step works fine here

**Comment by tsteur** [comment] 2015-02-24 01:31
@peterbo can you maybe check which notifications it wants to show? 

Just comment the line with `NotificationManager::cancelAllNonPersistent();` and / or do a `var_export($view->notifications)`

**Comment by mnapoli** [comment] 2015-02-24 03:23
Can reproduce by simply creating a new goal and adding the "Goals overview" widget on the dashboard. (nginx, php 5.6)

**Comment by jensmc** [comment] 2015-02-24 07:26
Same here after updating to 2.11.1

**Comment by yepa74** [comment] 2015-02-24 08:39
Same issue after upgrading to 2.11.1

**Comment by robertccs** [comment] 2015-02-24 08:54
+1

**Comment by peterbo** [comment] 2015-02-24 09:03
@tsteur $notifications is NULL, that's why it's running into the if clause. It is not trying to add a message, just to get all pending and then reset the notification stack. So both (or better all methods in /core/Notification/Manager.php) should check if the session is writeable.

```
if (empty($notifications)) {
   $view->notifications = NotificationManager::getAllNotificationsToDisplay(); //tries to sort the notifications by reference: uasort($notifications, function ($n1, $n2) []
   NotificationManager::cancelAllNonPersistent(); //Calls unset($session->notifications[$id]);
}
```

**Comment by HeiaSamaHi** [comment] 2015-02-24 09:03
Same here after updating to 2.11.1

**Comment by peterkraume** [comment] 2015-02-24 12:04
I can confirm this issue too.

**Comment by althaus** [comment] 2015-02-24 13:24
+1

**Comment by BeldarConehead** [comment] 2015-02-24 14:44
Same problem here.

**Comment by solarlaus** [comment] 2015-02-24 17:49
same problem after Update...

**Comment by sgiehl** [comment] 2015-02-24 17:50
Problem is imho that the NotificationManager always tries to write the session if no notifications are available. See https://github.com/piwik/piwik/blob/master/core/Notification/Manager.php#L134-L136
Maybe it would be better to check with ```isset``` or ```!is_array``` at that point?

**Comment by sgiehl** [comment] 2015-02-24 18:01
Just tested that on a local instance. It fixed the exception in the widget

**Comment by solarlaus** [comment] 2015-02-24 18:21
Hi sgiel: what needs to be done?

**Comment by sgiehl** [comment] 2015-02-24 18:23
Checking with ```!isset``` instead of ```empty``` in the code part linked above. But I don't know if that has any other impact.

**Comment by fushnisoft** [comment] 2015-02-24 18:34
After upgrade to 2.11.1 I see this on goals as described but also on Visits Overview widget (with or without graph).

![image](https://cloud.githubusercontent.com/assets/1259015/6356215/192419c8-bc5c-11e4-8bb5-827a91dfbcf2.png)

**Comment by tsteur** [comment] 2015-02-24 19:57
thanks @sgiehl that's it! Didn't see it would always try to write something there.

I fixed it in #7283 

If anyone wants to fix it just replace content of the file `core/Notification/Manager.php` with this content: https://raw.githubusercontent.com/piwik/piwik/7274/core/Notification/Manager.php

**Comment by DrTyrell** [comment] 2015-02-24 21:13
@tsteur +1, fixed it for me, thanks.

**Comment by SystemZ** [comment] 2015-02-24 21:21
@tsteur +1, works for me too :)

**Comment by BeldarConehead** [comment] 2015-02-24 21:23
Worked for me as well.

**Comment by HeiaSamaHi** [comment] 2015-02-24 21:24
perfect!

**Comment by KevinNash** [comment] 2015-02-24 23:09
Perfect fix for me too +1:

**Comment by codejunky** [comment] 2015-02-25 14:05
Fixed it for me!

**Comment by solarlaus** [comment] 2015-02-25 15:15
thanks, it work fine.

**Comment by Trance-Man** [comment] 2015-02-26 15:43
Had same problem below info worked for me as well...

== QUOTE ==
If anyone wants to fix it just replace content of the file core/Notification/Manager.php with this content: https://raw.githubusercontent.com/piwik/piwik/7274/core/Notification/Manager.php
== END QUOTE ==

**Comment by tobybaier** [comment] 2015-02-27 14:19
thanks for fixing, looking forward to the next release :)

**Comment by mattab** [comment] 2015-03-02 04:10
fixed in #7283

**Closed by mattab** 2015-03-02 04:10 UTC
Labels: Bug, Major

**Comment by lksnmnn** [comment] 2015-03-03 15:57
Can you guys reupload the fixed version of Manager.php ? (or provide a working link)
I only see "not found".

Thanks ! :+1:

**Comment by tsteur** [comment] 2015-03-03 19:44
Sure, thx for letting us know. I updated the link in previous comment: https://raw.githubusercontent.com/piwik/piwik/3699f22e0410b39ff4bcb2cafdf2f38e0669b146/core/Notification/Manager.php

**Comment by mattab** [comment] 2015-03-03 21:22
Btw to get the fix, it's recommended to use the latest beta which includes several fixes: http://piwik.org/faq/how-to-update/faq_159/
