### ISSUE TITLE
Piwik 3.0.1 Segments with an OR not working

### ISSUE THREAD

**Issue by robles-design** [piwik/piwik#11170] opened 2017-01-10 14:22 UTC
I created a segment with an OR and get the following error:
The segment 'deviceType%3D%3DSmartphone%2CdeviceType%3D%3DTablet%2CdeviceType%3D%3DPhablet' is not valid.

When clicking on the admin panel after this message there is some more information:
ERROR: Failed to get data from API: The segment 'deviceType%3D%3DSmartphone%2CdeviceType%3D%3DTablet%2CdeviceType%3D%3DPhablet' is not valid. #0 /www/.../statistik/piwik/core/Segment.php(155): Piwik\Segment\SegmentExpression-&gt;parseSubExpressions() #1 /www/.../statistik/piwik/core/Segment.php(106): Piwik\Segment-&gt;initializeSegment('deviceType%253D...', Array) #2 /www/.../statistik/piwik/core/Archive.php(225): Piwik\Segment-&gt;__construct('deviceType%253D...', Array) #3 /www/.../statistik/piwik/core/Archive.php(459): Piwik\Archive::build('2', 'range', '2016-12-12,2017...', 'deviceType%253D...', false) #4 /www/.../statistik/piwik/plugins/Referrers/API.php(297): Piwik\Archive::createDataTableFromArchive('Referrers_urlBy...', '2', 'range', '2016-12-12,2017...', 'deviceType%253D...', false, false, NULL) #5 [internal function]: Piwik\Plugins\Referrers\API-&gt;getWebsites('2', 'range', '2016-12-12,2017...', 'deviceType%253D...', false, false) #6 /www/.../statistik/piwik/core/API/Proxy.php(219): call_user_func_array(Array, Array) #7 /www/.../statistik/piwik/core/Plugin/Visualization.php(264): Piwik\API\Proxy-&gt;call('\\Piwik\\Plugins\\...', 'getWebsites', Array) #8 /www/.../statistik/piwik/core/Plugin/Visualization.php(181): Piwik\Plugin\Visualization-&gt;loadDataTableFromAPI() #9 /www/.../statistik/piwik/core/Plugin/Report.php(309): Piwik\Plugin\Visualization-&gt;render() #10 /www/.../statistik/piwik/plugins/CoreHome/Controller.php(59): Piwik\Plugin\Report-&gt;render() #11 [internal function]: Piwik\Plugins\CoreHome\Controller-&gt;renderReportWidget(Object(Piwik\Plugins\Referrers\Reports\GetWebsites)) #12 /www/.../statistik/piwik/core/FrontController.php(542): call_user_func_array(Array, Array) #13 /www/.../statistik/piwik/core/FrontController.php(137): Piwik\FrontController-&gt;doDispatch('Referrers', 'getWebsites', Array) #14 /www/.../statistik/piwik/core/dispatch.php(34): Piwik\FrontController-&gt;dispatch() #15 /www/.../statistik/piwik/index.php(27): require_once('/www/...') #16 {main}

In Piwik 2.x the segments with an OR worked. The issue started with Piwik 3.0.0. I deleted the segment and created a new one and tried different browsers, same error. Segments with an AND work well. Any idea?

**Comment by sezuan** [comment] 2017-01-30 13:30
That's somewhat funny, for me, all AND segments are broken. I must edit and save them, then they work for the current session. After logout/login it's gonna be broken again.

Simple example:

Error: The segment 'referrerType%3D%3Dcampaign%3BreferrerName%3D%3DGOOGLE' is not valid.

**Comment by sgiehl** [comment] 2017-01-30 13:32
Which browsers are you using? Can you reproduce that behavior in another browser?

**Comment by sezuan** [comment] 2017-01-30 13:43
I tried Firefox and Vivaldi. Same result.

**Comment by OlafDoering** [comment] 2017-01-30 13:45
I did a short test.
My segment is a long list of "or" statements.
Chrome is showing no accesses when selecting the segment. After editing the segment, correct accesses are shown.
Internet Explorer is showing all accesses after selecting the segment. After editing, it is showing some errors.

**Comment by sezuan** [comment] 2017-01-30 14:15
After editing I got an error, too:

ERROR: Failed to get data from API: The segment 'referrerType%3D%3Dcampaign%3BreferrerName%3D%3DGOOGLE' is not valid. #0 /var/www/core/Segment.php(155): Piwik\Segment\SegmentExpression-&gt;parseSubExpressions() #1 /var/www/core/Segment.php(106): Piwik\Segment-&gt;initializeSegment('referrerType%25...', Array) #2 /var/www/core/Archive.php(225): Piwik\Segment-&gt;__construct('referrerType%25...', Array) #3 /var/www/plugins/Goals/API.php(433): Piwik\Archive::build('3', 'day', '2017-01-01,2017...', 'referrerType%25...') #4 [internal function]: Piwik\Plugins\Goals\API-&gt;getMetrics('3', 'day', '2017-01-01,2017...', 'referrerType%25...', 'ecommerceOrder', Array) #5 /var/www/core/API/Proxy.php(219): call_user_func_array(Array, Array) #6 /var/www/core/API/Request.php(236): Piwik\API\Proxy-&gt;call('\Piwik\Plugins\...', 'getMetrics', Array) #7 /var/www/core/API/Request.php(398): Piwik\API\Request-&gt;process() #8 /var/www/plugins/Goals/API.php(406): Piwik\API\Request::processRequest('Goals.getMetric...', Array) #9 [internal function]: Piwik\Plugins\Goals\API-&gt;get('3', 'day', '2017-01-01,2017...', 'referrerType%25...', 'ecommerceOrder', Array) #10 /var/www/core/API/Proxy.php(219): call_user_func_array(Array, Array) #11 /var/www/core/Plugin/Visualization.php(264): Piwik\API\Proxy-&gt;call('\Piwik\Plugins\...', 'get', Array) #12 /var/www/core/Plugin/Visualization.php(181): Piwik\Plugin\Visualization-&gt;loadDataTableFromAPI() #13 /var/www/core/Plugin/Controller.php(249): Piwik\Plugin\Visualization-&gt;render() #14 /var/www/plugins/Goals/Controller.php(226): Piwik\Plugin\Controller-&gt;renderView(Object(Piwik\Plugins\CoreVisualizations\Visualizations\JqplotGraph\Evolution)) #15 [internal function]: Piwik\Plugins\Goals\Controller-&gt;getEvolutionGraph() #16 /var/www/core/FrontController.php(542): call_user_func_array(Array, Array) #17 /var/www/core/FrontController.php(137): Piwik\FrontController-&gt;doDispatch(NULL, NULL, NULL) #18 /var/www/core/dispatch.php(34): Piwik\FrontController-&gt;dispatch() #19 /var/www/index.php(27): require_once('/var/www/core/d...') #20 {main}

**Comment by robles-design** [comment] 2017-01-31 01:13
Chromium, Firefox, Opera, Vivaldi and Otter on Linux.

**Comment by phip1611** [comment] 2017-02-05 21:08
this is probably not a problem of AND/OR but filtering for operating systems or device types in general! Device-Type-Filtering works for me but filtering for operating system does not: see: #11321

**Comment by sezuan** [comment] 2017-02-07 08:56
I don't think so. My filter rule is simple, contains no operating system and filters only a certain campain and fails.

**Comment by tsteur** [comment] 2017-02-10 00:57
It may be related to https://github.com/piwik/piwik/issues/11321

**Comment by sezuan** [comment] 2017-02-13 08:34
@tsteur Yes, that's possible.

**Comment by mattab** [comment] 2017-02-20 08:47
Should be duplicate of #11321

**Closed by mattab** 2017-02-20 08:47 UTC
