### ISSUE TITLE
Debugview crashed after any click

### ISSUE THREAD

**Issue by mattoii** [piwik/piwik#19297] opened 2022-05-31 06:27 UTC
Hello

I used Matomo GTM for tracking events, i want to view data layer events, but when i viewed click debug crashed.

Before click: http://joxi.ru/gmvw71bHeaLkD2  (view debugger)

After click: http://joxi.ru/J2bG3xDTqNXP9A  (debugger disappeared after click **mtm.AllElementsClick**)

i tried used:

1) mac os Monterey 12.4 , Сhrome ver. 101.0.4951.64 
2) Windows 11, Сhrome ver. 101.0.4951.67

Ыituation is identical

**Comment by AltamashShaikh** [comment] 2022-05-31 06:30
Duplicate of https://github.com/matomo-org/tag-manager/issues/487

**Comment by AltamashShaikh** [comment] 2022-05-31 06:31
@mattoii refer https://github.com/matomo-org/tag-manager/issues/487

**Closed as completed by AltamashShaikh** 2022-05-31 06:31 UTC
Labels: duplicate
