### ISSUE TITLE
[Bug] Numeric event value is sometimes changed to zero

### ISSUE THREAD

**Issue by luukdv** [piwik/piwik#21314] opened 2023-09-27 05:30 UTC
_Environment: Matomo Cloud_

When sending an event value like `_paq.push(['trackEvent', 'Event', 'action', undefined, 1000.2555])`, it will get rounded to `1.256`. But if you send an event value that has more than 10 decimal places (like `1000.25555555555`), the event value will be converted to `0`. This is only the case for numbers that are _higher_ than `999`, an event value like `999.25555555555` will not be converted to `0`.

I'm not sure what the expected behavior should be, since I couldn't find anything in the documentation about Matomo's rounding rules for numeric values. In any case, the current behavior is unexpected and seems buggy.

**Comment by sgiehl** [comment] 2023-10-06 14:45
Hi @luukdv 
Thanks for raising this issue. A possible "rounding" might happen in MySQL, as the field is stored as FLOAT.
I was able to reproduce that. It's indeed a bit weird that a value like `1000.2555555555` is stored as `1000.256`, while `1000.25555555555` ends up being `0`.

We need to investigate that a bit further.

**Comment by sgiehl** [comment] 2023-10-06 15:05
Just debugged that through. The problem is actually in PHP code. The code that fetches the data from the request has a rounding issue causing the value to be thrown away.
It happens here:
https://github.com/matomo-org/matomo/blob/b90f53c6bbaadecd513c4d01b6ef5314ac772676/core/Common.php#L556-L561

$value is `1000.25555555555`, but the cast to float and string ends up in `1000.2555555556`, resulting in the value being marked as not ok.

**Closed as completed** 2024-02-29 00:23 UTC
Labels: Bug, c: Tracking
