### ISSUE TITLE
javascript site search reports results count from previous search

### ISSUE THREAD

**Issue by kevinb456** [piwik/piwik#7816] opened 2015-05-03 18:16 UTC
I am using Piwik 1.12.1 with opencart 2.0.2 , using the default site search query parameters which Piwik automatically gets the keywords from, then adding the count into the javascript footer as follows (as recommended on piwik documentation);

`_paq.push(['setCustomUrl', document.URL + '&search_count=x']);`

where x is the count value rendered by PHP for that results page.

When on a search results page for a product, with say 4 results, the javascript source correctly has "search_count=4" in it. However when I view the site search in Piwik the results count reported is not 4, but whatever number the **previous** site search had.

I can't think of anything I'm doing wrong so I'm assuming this is Piwiks bug. Happy to be proven wrong!

**Comment by tsteur** [comment] 2015-05-03 22:34
Can you try with latest Piwik version? We do no longer support Piwik 1.X

**Comment by kevinb456** [comment] 2015-05-03 23:25
Sorry, typo, I'm using 2.12.1!

**Comment by tsteur** [comment] 2015-05-05 00:24
I just tried to reproduce and thought I can but then I noticed there was a problem with my URL. 

Is it possible that you use fragments in the URL? Such as `http://example.org?query=test&search_count=45#&search_count=42`? Sending `http://example.org?query=test#45&search_count=42` should be OK though as we concatenate the query part and the fragment part. It might have other side effects though. The `search_count` in fragment takes in general precedence over the `search_count` in the query part.

Can you also make sure it is not a problem in PHP? Eg can you check in the browser that the actual correct value is set in the HTML/JavaScript?

**Comment by kevinb456** [comment] 2015-05-08 11:25
No, no URL fragments. To illustrate further I've just done a test with the default Opencart 2.0.2.0 store (fresh install) and Piwik 2.12.1 as mentioned. I tried searching for 'mac' (4 results) then 'iphone' (1 result) then 'ipod' (4 results). The search URL is of the form `index.php?route=product/search&search=ipod`. Piwik then picks up correctly on the `&search=` term.

However what I see in the Piwik visitor log is the first search 'mac' which should be 4 results, not show a result count figure at all, 'iphone' which should be 1 shows a results count of 4, and 'ipod' which should be 4 shows a results count of 1. See below when hovering over 'ipod' search;

![image](https://cloud.githubusercontent.com/assets/4441138/7535432/f43d8586-f57c-11e4-9f85-5802473a7747.png)

Yes its definitely not a PHP issue, e.g. on the final search results page for 'ipod' with four results this is the piwik javascript in the HTML source; 

`<script type="text/javascript">
var _paq = _paq || [];
_paq.push(["setEcommerceView",productSKU = false,productName = false,categoryName = false,price = false]);
_paq.push(['setCustomUrl', document.URL + '&search_count=4']);
_paq.push(["trackPageView"]);
_paq.push(["enableLinkTracking"]);
(function() {
var u=(("https:" == document.location.protocol) ? "..." : "...");
_paq.push(["setTrackerUrl", u+"piwik.php"]);
_paq.push(["setSiteId", "1"]);
var d=document, g=d.createElement("script"), s=d.getElementsByTagName("script")[0]; g.type="text/javascript"; g.async=true; g.defer=true; g.src=u+"piwik.js"; s.parentNode.insertBefore(g,s);
})();</script>`

**Comment by tsteur** [comment] 2015-05-12 22:26
I'm trying to reproduce this already for a while and might think this could be a JavaScript issue somewhere here: https://github.com/piwik/piwik/blob/2.13.1/plugins/Live/javascripts/visitorLog.js#L43

I noticed kinda a similar issue. I had 3 searches under the same action, but they were grouped in JS so only the last search result was shown in the tooltip (or the first one not sure)

![visitorlog_search](https://cloud.githubusercontent.com/assets/273120/7599935/7dd9104a-f95a-11e4-8e8d-4d6e4e30d8ee.png)

**Comment by tsteur** [comment] 2015-05-12 22:48
It's actually because we use the `pageTitle` for `siteSearchKeyword`. Can anyone confirm this is on purpose? https://github.com/piwik/piwik/blob/2.13.1/plugins/Live/Visitor.php#L290 This code been there already for a long time. This causes the page title to be displayed here: https://github.com/piwik/piwik/blob/2.13.1/plugins/Live/templates/_actionsList.twig#L88

**Comment by tsteur** [comment] 2015-05-14 03:43
As discussed, the search term should be shown next to the search icon, not the page title. This seems to be not the case currently.

**Comment by tsteur** [comment] 2015-05-14 03:45
@kevinb456 is the title of the page, after searching for something, the used search term? Your title/popover looks a bit different than mine as it does not show the used search term.

**Comment by mattab** [comment] 2015-07-15 04:51
@tsteur whatever is done should be on purpose, but if it causes this bug, something needs to be fixed :-) let's take a look at it for 2.15.0

**Comment by tsteur** [comment] 2015-08-07 08:50
FYI: In the tracker debug log I get:

```
Search bot detected, visit excluded
Visit is already excluded, no need to check DoNotTrack support.
```

**Comment by tsteur** [comment] 2015-08-07 09:03
Here's some more info from `$_SERVER` (I removed some keys and some information):

```
array(73) {
  string(11) "en_US.UTF-8"
  ["LC_ALL"]=>
  string(11) "en_US.UTF-8"
  ["ORIG_PATH_INFO"]=>
  string(10) "/piwik.php"
  ["SCRIPT_NAME"]=>
  string(10) "/piwik.php"
  ["REQUEST_URI"]=>
  string(498) "/piwik.php?action_name=Testimonials%20-%20Analytics%20Platform%20-%20Piwik&idsite=1&rec=1&r=592202&h=10&m=49&s=38&url=http%3A%2F%2Fpiwik.org%2Ftestimonials%2F&urlref=http%3A%2F%2Fpiwik.org%2Fhosting%2F&_id=8ef979f20d4f641e&_idts=1433737138&_idvc=29&_idn=0&_refts=1438936067&_viewts=1438847822&_ref=https%3A%2F%2Fwww.google.de%2F&send_image=0&pdf=1&qt=0&realp=0&wma=0&dir=0&fla=1&java=1&gears=0&ag=0&cookie=1&res=1280x800&_cvar=%7B%221%22%3A%5B%22Domain%20landed%22%2C%22piwik.org%22%5D%7D&gt_ms=379"
  ["QUERY_STRING"]=>
  string(487) "action_name=Testimonials%20-%20Analytics%20Platform%20-%20Piwik&idsite=1&rec=1&r=592202&h=10&m=49&s=38&url=http%3A%2F%2Fpiwik.org%2Ftestimonials%2F&urlref=http%3A%2F%2Fpiwik.org%2Fhosting%2F&_id=8ef979f20d4f641e&_idts=1433737138&_idvc=29&_idn=0&_refts=1438936067&_viewts=1438847822&_ref=https%3A%2F%2Fwww.google.de%2F&send_image=0&pdf=1&qt=0&realp=0&wma=0&dir=0&fla=1&java=1&gears=0&ag=0&cookie=1&res=1280x800&_cvar=%7B%221%22%3A%5B%22Domain%20landed%22%2C%22piwik.org%22%5D%7D&gt_ms=379"
  ["REQUEST_METHOD"]=>
  string(3) "GET"
  ["SERVER_PROTOCOL"]=>
  string(8) "HTTP/1.1"
  ["GATEWAY_INTERFACE"]=>
  string(7) "CGI/1.1"
  ["REDIRECT_URL"]=>
  string(10) "/piwik.php"
  ["REDIRECT_QUERY_STRING"]=>
  string(487) "action_name=Testimonials%20-%20Analytics%20Platform%20-%20Piwik&idsite=1&rec=1&r=592202&h=10&m=49&s=38&url=http%3A%2F%2Fpiwik.org%2Ftestimonials%2F&urlref=http%3A%2F%2Fpiwik.org%2Fhosting%2F&_id=8ef979f20d4f641e&_idts=1433737138&_idvc=29&_idn=0&_refts=1438936067&_viewts=1438847822&_ref=https%3A%2F%2Fwww.google.de%2F&send_image=0&pdf=1&qt=0&realp=0&wma=0&dir=0&fla=1&java=1&gears=0&ag=0&cookie=1&res=1280x800&_cvar=%7B%221%22%3A%5B%22Domain%20landed%22%2C%22piwik.org%22%5D%7D&gt_ms=379"
  ["SERVER_ADMIN"]=>
  string(18) "[no address given]"
  ["REMOTE_ADDR"]=>
  string(13) "66.XXX.XXX.XXX"
  ["SERVER_SIGNATURE"]=>
  string(0) ""
  ["HTTP_X_REAL_IP"]=>
  string(13) "66.XXX.XXX.XXXX"
  ["HTTP_USER_AGENT"]=>
  string(121) "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.130 Safari/537.36"
  ["HTTP_CONNECTION"]=>
  string(5) "close"
  ["HTTP_X_FORWARDED_FOR"]=>
  string(14) "84.XXX.XXX.XXX"
  ["HTTP_VIA"]=>
  string(28) "1.1 Chrome-Compression-Proxy"
  ["HTTP_UPGRADE_INSECURE_REQUESTS"]=>
  string(1) "1"
  ["HTTP_SCHEME"]=>
  string(4) "http"
  ["HTTP_FORWARDED"]=>
  string(18) "for=84.XXX.XXX.XXX"
  ["HTTP_CACHE_CONTROL"]=>
  string(9) "max-age=0"
  ["HTTP_ACCEPT_LANGUAGE"]=>
  string(35) "en-US,en;q=0.8,de-DE;q=0.6,de;q=0.4"
  ["HTTP_ACCEPT_ENCODING"]=>
  string(19) "gzip, deflate, sdch"
  ["HTTP_ACCEPT"]=>
  string(74) "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
  ["GEOIP_ORGANIZATION"]=>
  string(6) "Google"
  ["GEOIP_ISP"]=>
  string(6) "Google"
  ["GEOIP_POSTAL_CODE"]=>
  string(5) "94043"
  ["GEOIP_LONGITUDE"]=>
  string(11) "-XXX.XX7404"
  ["GEOIP_LATITUDE"]=>
  string(9) "XX.XXXXXX"
  ["GEOIP_AREA_CODE"]=>
  string(3) "XXX"
  ["GEOIP_DMA_CODE"]=>
  string(3) "XXX"
  ["GEOIP_CITY"]=>
  string(13) "Mountain View"
  ["GEOIP_REGION"]=>
  string(2) "CA"
  ["GEOIP_COUNTRY_NAME"]=>
  string(13) "United States"
  ["GEOIP_COUNTRY_CODE"]=>
  string(2) "US"
  ["REDIRECT_STATUS"]=>
  string(3) "200"
  ["REDIRECT_GEOIP_ORGANIZATION"]=>
  string(6) "Google"
  ["REDIRECT_GEOIP_ISP"]=>
  string(6) "Google"
  ["REDIRECT_GEOIP_POSTAL_CODE"]=>
  string(5) "94043"
  ["REDIRECT_GEOIP_LONGITUDE"]=>
  string(11) "-XXX.XXXXXX"
  ["REDIRECT_GEOIP_LATITUDE"]=>
  string(9) "XX.XXXXXX"
  ["REDIRECT_GEOIP_AREA_CODE"]=>
  string(3) "XXX"
  ["REDIRECT_GEOIP_DMA_CODE"]=>
  string(3) "XXX"
  ["REDIRECT_GEOIP_CITY"]=>
  string(13) "Mountain View"
  ["REDIRECT_GEOIP_REGION"]=>
  string(2) "CA"
  ["REDIRECT_GEOIP_COUNTRY_NAME"]=>
  string(13) "United States"
  ["REDIRECT_GEOIP_COUNTRY_CODE"]=>
  string(2) "US"
  ["FCGI_ROLE"]=>
  string(9) "RESPONDER"
  ["PHP_SELF"]=>
  string(10) "/piwik.php"
  ["REQUEST_TIME_FLOAT"]=>
  float(1438937793.5144)
  ["REQUEST_TIME"]=>
  int(1438937793)
  ["argv"]=>
  array(1) {
    [0]=>
    string(487) "action_name=Testimonials%20-%20Analytics%20Platform%20-%20Piwik&idsite=1&rec=1&r=592202&h=10&m=49&s=38&url=http%3A%2F%2Fpiwik.org%2Ftestimonials%2F&urlref=http%3A%2F%2Fpiwik.org%2Fhosting%2F&_id=8ef979f20d4f641e&_idts=1433737138&_idvc=29&_idn=0&_refts=1438936067&_viewts=1438847822&_ref=https%3A%2F%2Fwww.google.de%2F&send_image=0&pdf=1&qt=0&realp=0&wma=0&dir=0&fla=1&java=1&gears=0&ag=0&cookie=1&res=1280x800&_cvar=%7B%221%22%3A%5B%22Domain%20landed%22%2C%22piwik.org%22%5D%7D&gt_ms=379"
  }
  ["argc"]=>
  int(1)
}
```

Interesting could be eg 
```
 ["HTTP_VIA"]=> string(28) "1.1 Chrome-Compression-Proxy"
```

**Comment by tsteur** [comment] 2015-08-07 09:14
FYI: Deleted 2 comments as they belong to a different issue

**Comment by tsteur** [comment] 2015-08-07 14:09
I tried to reproduce for quite a while but couldn't. I also debugged the part from fetching the visitors from DB to displaying them in the UI and everything seems to be straight forward. So the only thing where something could go wrong would be the tracker but I kinda doubt that this is the problem. 

Can you maybe send us a link to your website and maybe a few steps to reproduce? Maybe it helps us to reproduce. If so, feel free to send us an email to "hello at piwik.org" then comment here (just in case the mail goes into spam).

**Comment by mattab** [comment] 2015-08-09 16:54
Thanks @tsteur for investigating

@kevinb456 hopefully you can send us more information, we may not be able to fix it otherwise.

**Comment by mattab** [comment] 2015-08-14 15:37
Closing, @kevinb456 feel free to re-open and post more information. thx

**Closed by mattab** 2015-08-14 15:37 UTC
Labels: Bug
