### ISSUE TITLE
Toggle menu off

### ISSUE THREAD

**Issue by philgruneich** [piwik/piwik#9287] opened 2015-11-26 11:32 UTC
I enjoy the new design, but I think the current navigation occupies a real estate I'd rather spread across my dashboard widgets instead. Previously, while this menu was atop, I could ignore it.

Can we have a toggle somewhere? Is there a workaround to remove it other than running custom CSS?

**Comment by dev-101** [comment] 2015-11-26 13:41
Hi, I was just about to post the same suggestion. The new design is great, but the sidebar could be collapsed on medium desktop devices & screens initially (e.g. between 800px and 1360px width treshold) and auto-expanded on mouse hover at the corner:

![piwik-sidebar](https://cloud.githubusercontent.com/assets/5383059/11424223/895b0f04-944b-11e5-81a2-5086d03e9ee5.png)

Another related improvement in Dashboard is that users who do not use more than 2 columns for widgets, get 3rd column space reserved / blank:

![piwik-dashboard-column](https://cloud.githubusercontent.com/assets/5383059/11424238/b533b3c4-944b-11e5-8a0f-a61dff0541a3.png)

With the above combined layout space will be used rationally.

**Comment by tsteur** [comment] 2015-11-26 20:17
Thx for suggestion. Would be really useful. I'm closing it as a duplicate of https://github.com/piwik/piwik/issues/9263 . Please watch that issue.

**Closed by tsteur** 2015-11-26 20:17 UTC
