### ISSUE TITLE
The problem of GeoIp statistic in China

### ISSUE THREAD

**Issue by zw231212** [piwik/piwik#10768] opened 2016-10-19 13:01 UTC
### 在地图数据显示中：西藏和台湾都被排除在了中国之外，请问这样的问题该如何解决？如何自定义地图？

> There are some problems when I upload a screenshot to show the problem.

## The Question is in a GeoIP map,Taiwang and Tibet are not in china! How is this happen in a map? how can I fix this problem?

**Comment by MrSlawa** [comment] 2016-10-28 06:30
duplicate of https://github.com/piwik/piwik/issues/10757

Answer to your question
https://github.com/piwik/piwik/issues/10757#issuecomment-254802633

**Comment by zw231212** [comment] 2016-10-28 06:50
Thanks for your answers! TaiWang maybe is a issue,but Tibet is not ,I read #6994 ,and @mattab 's answer has a very strong personal emotion on Tibet! 
still thanks for you!

**Closed** 2016-10-28 06:51 UTC
