### ISSUE TITLE
The Real Time Visitors World Map is not showing data.

### ISSUE THREAD

**Issue by 28harishkumar** [piwik/piwik#9381] opened 2015-12-13 08:30 UTC
![pwkerror](https://cloud.githubusercontent.com/assets/8288450/11766192/0345091a-a1a2-11e5-935e-da7db81a96ee.png)
I have followed the instructions given here http://piwik.org/faq/troubleshooting/faq_17051/. I am using apache server and rewrite mode is on.

On my website, I can check that XHR are requests are working well using chrome console(I am getting user responses with users). But real time map is showing "There is no data for this report".

I am also using google analytics which is showing 3 users.

Error in my console is:

Uncaught TypeError: Cannot read property 'replace' of undefinedpiwikHelper.htmlEntities @ index.php?module=Proxy&action=getCoreJs&cb=ea8d07f28d67611ab8fca869e0c5a63d:686(anonymous function) @ index.php?module=Proxy&action=getCoreJs&cb=ea8d07f28d67611ab8fca869e0c5a63d:1890m.event.dispatch @ index.php?module=Proxy&action=getCoreJs&cb=ea8d07f28d67611ab8fca869e0c5a63d:5r.handle @ index.php?module=Proxy&action=getCoreJs&cb=ea8d07f28d67611ab8fca869e0c5a63d:5m.event.trigger @ index.php?module=Proxy&action=getCoreJs&cb=ea8d07f28d67611ab8fca869e0c5a63d:5(anonymous function) @ index.php?module=Proxy&action=getCoreJs&cb=ea8d07f28d67611ab8fca869e0c5a63d:5m.extend.each @ index.php?module=Proxy&action=getCoreJs&cb=ea8d07f28d67611ab8fca869e0c5a63d:4m.fn.m.each @ index.php?module=Proxy&action=getCoreJs&cb=ea8d07f28d67611ab8fca869e0c5a63d:4m.fn.extend.trigger @ index.php?module=Proxy&action=getCoreJs&cb=ea8d07f28d67611ab8fca869e0c5a63d:5handleMouseMove @ index.php?module=Proxy&action=getCoreJs&cb=ea8d07f28d67611ab8fca869e0c5a63d:1856m.event.dispatch @ index.php?module=Proxy&action=getCoreJs&cb=ea8d07f28d67611ab8fca869e0c5a63d:5r.handle @ index.php?module=Proxy&action=getCoreJs&cb=ea8d07f28d67611ab8fca869e0c5a63d:5m.event.trigger @ index.php?module=Proxy&action=getCoreJs&cb=ea8d07f28d67611ab8fca869e0c5a63d:5(anonymous function) @ index.php?module=Proxy&action=getCoreJs&cb=ea8d07f28d67611ab8fca869e0c5a63d:5m.extend.each @ index.php?module=Proxy&action=getCoreJs&cb=ea8d07f28d67611ab8fca869e0c5a63d:4m.fn.m.each @ index.php?module=Proxy&action=getCoreJs&cb=ea8d07f28d67611ab8fca869e0c5a63d:4m.fn.extend.trigger @ index.php?module=Proxy&action=getCoreJs&cb=ea8d07f28d67611ab8fca869e0c5a63d:5onMouseMove @ index.php?module=Proxy&action=getCoreJs&cb=ea8d07f28d67611ab8fca869e0c5a63d:519m.event.dispatch @ index.php?module=Proxy&action=getCoreJs&cb=ea8d07f28d67611ab8fca869e0c5a63d:5r.handle @ index.php?module=Proxy&action=getCoreJs&cb=ea8d07f28d67611ab8fca869e0c5a63d:5)

**Comment by tsteur** [comment] 2015-12-13 19:50
Is it maybe possible that we can access your Piwik installation to debug this error? It's a bit hard to tell what the error is otherwise. If so, please send us an email with credentials and URL to "hello at piwik.org" and comment here afterwards (in case email goes into spam folder)

**Comment by mattab** [comment] 2015-12-18 03:51
Can you try with a different browser? maybe you are using an adblocker or some other browser extension that could block the map?

**Comment by mattab** [comment] 2015-12-23 04:30
Could you try again with 2.16.0-b1 version? http://piwik.org/faq/how-to-update/faq_159/

please comment if you have more info or can reproduce in our latest beta

**Comment by 28harishkumar** [comment] 2015-12-24 05:01
@tsteur Sorry for late response. I have sent the url along with admin credentials to "hello at piwik.org".

**Comment by tsteur** [comment] 2016-01-10 20:30
I just had a look and indeed there are no visitors shown in the map but in the visitor log. I noticed all regions and cities are set to unknown maybe that is the reason. Maybe you need to install the Maxmind database for cities see https://piwik.org/faq/how-to/faq_163/#faq_163 but I'm not sure if this makes them appear in the real time map

**Comment by tsteur** [comment] 2016-01-10 21:08
Same problem in https://github.com/piwik/piwik/issues/9487

This is the 2nd user reporting the same problem so maybe there's an actual issue with the database or with the auto updater? Which PHP version are you using? By any chance, are you using PHP 7?

**Comment by standupgirl** [comment] 2016-01-10 21:58
Hi Tsteur,
Downloading and renaming the dat file worked for me in the how-to above.  Thank you so much!
Diana

**Comment by tsteur** [comment] 2016-01-10 22:42
Thx for letting me know. Do you mind letting us know your PHP version if possible?
I'll close it for now. Anyone feel free to comment here if you experience this issue.

**Closed by tsteur** 2016-01-10 22:42 UTC

**Comment by 28harishkumar** [comment] 2016-01-11 06:45
Hi @tsteur I am using PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46).
@standupgirl Can you please tell me which file you had replaced?

**Comment by standupgirl** [comment] 2016-01-11 15:56
Hi Tsteur,
Here are my server details:
Apache Version 	2.2.26
PHP Version 	5.4.25
MySQL Version 	5.5.47-cll
Architecture 	x86_64
Operating System 	linux
**********************************************
To 28harishkumar,

The file I updated was the GeoLiteCity.dat   but change the name to GeoIPCity.dat before you upload it.
