### ISSUE TITLE
Small design tweaks to apply  

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#8035] opened 2015-06-03 05:31 UTC
This issue aims to collect small feedback about UI & design:

 * [x] Notification should have higher contrast #7943
 * ~~In admin forms, website selector should be to the right of the label (Got: below the label)~~
![form website selector could be to the right of the label](https://cloud.githubusercontent.com/assets/466765/7953178/9390e39c-0a15-11e5-9723-989f132a3083.png)

 * [x] In admin forms, when displaying warning notifications, maybe we could show the warning notification as part of the form so that its width would be limited to 50% rather than 100%? 

What we got does not look ideal imho:
![form warning too wide](https://cloud.githubusercontent.com/assets/466765/7953179/93941120-0a15-11e5-9588-d3df26b49348.png)

 * [x] Segment editor search field has extra border on Chrome:

![form search looks wrong](https://cloud.githubusercontent.com/assets/466765/7953176/93905a8a-0a15-11e5-96de-8df34ffabf7f.png)

Looks broken on Firefox:
![form broken search](https://cloud.githubusercontent.com/assets/466765/7953208/0d2e53b0-0a16-11e5-8494-bfca339efbdb.png)
Feel free to add here any other design 'regression' or improvements that should be made before 2.14.0 :+1:

**Comment by mnapoli** [comment] 2015-06-03 15:15
I cannot reproduce this one:

![](https://cloud.githubusercontent.com/assets/466765/7953177/93906818-0a15-11e5-9416-837c4c5194e0.png)

Do you still see it?

Problems with this text field should be fixed now:

![](https://cloud.githubusercontent.com/assets/466765/7953208/0d2e53b0-0a16-11e5-8494-bfca339efbdb.png)

**Comment by mnapoli** [comment] 2015-06-03 15:16
For this one:

![](https://cloud.githubusercontent.com/assets/466765/7953178/9390e39c-0a15-11e5-9723-989f132a3083.png)

The problem is that the label + the select are wider than the left column (left column = fields, right column = help boxes). So I don't really see a solution for that.

**Comment by mattab** [comment] 2015-06-05 00:40
> The problem is that the label + the select are wider than the left column (left column = fields, right column = help boxes). So I don't really see a solution for that.

@mnapoli when there is enough space to fit both,
 * Got: stacked. 
 * Expected: could fit on line?

Example on wide screen:

![enough space](https://cloud.githubusercontent.com/assets/466765/7997370/f4d2e874-0b7f-11e5-8d9b-fa8431203b10.png)

**Comment by mattab** [comment] 2015-06-05 01:12
* [ ] When anonymous can view statistics for a website, display the message in a "Warning" info box. Got: the notification is displayed in normal black font on white background. Expected: warning alert about the `Note: [...]` notification

![anonymous](https://cloud.githubusercontent.com/assets/466765/7997640/836a8c50-0b84-11e5-8dfd-a7f2c2909aaf.png)

**Comment by mattab** [comment] 2015-06-05 01:17
> I cannot reproduce this one:
> Do you still see it?

My bad, this is not a bug actually (I had created a new Segment locally in a file causing this extra empty category to display)

> Problems with this text field should be fixed now

:+1:

**Comment by mnapoli** [comment] 2015-06-05 14:08
I have changed the alerts:

![capture d ecran 2015-06-05 a 16 05 54](https://cloud.githubusercontent.com/assets/720328/8007595/06d153cc-0b9d-11e5-9b45-7ed80b955427.png)

I have fixed some other things listed here.

**Comment by mnapoli** [comment] 2015-06-05 14:26
I've given another try to this:

![](https://cloud.githubusercontent.com/assets/466765/7953178/9390e39c-0a15-11e5-9723-989f132a3083.png)

This is just too messy to make it on one line (mostly the vertical aligning of the checkbox + text + site selector). I don't believe it's worth inserting so many hacks for something that will not look good visually. If you want to give it a try feel free but I'll leave it as it is.

Except that all other points should be fixed now.

**Comment by mattab** [comment] 2015-06-08 00:00
> I have changed the alerts:
> I have fixed some other things listed here.

it looks good!

> I don't believe it's worth inserting so many hacks for something that will not look good visually. If you want to give it a try feel free but I'll leave it as it is.

if it's hard to solve then +1 to skip it for now, it was a small feedback and not "required"

**Comment by mattab** [comment] 2015-06-08 00:15
I tried to test all features manually, here is additional feedback:


 * [ ] H1 style in our UI demo page, looks out of place. Can we set a better H1 style? I guess it's not used anywhere beside this UI demo page, but it's good enough reason to improve it :-)

Current H1 style in UI demo:

![h1 style looks wrong](https://cloud.githubusercontent.com/assets/466765/8026702/ee1aca76-0dd5-11e5-9149-2d72d1585247.png)

 * [ ] SMS settings page is not yet themed with the new admin style:

![sms configuration](https://cloud.githubusercontent.com/assets/466765/8026701/ee19efca-0dd5-11e5-8529-72e44df9b016.png)

*  [ ] Device detection table in Admin: could it be themed with new style?

![device detection table](https://cloud.githubusercontent.com/assets/466765/8026703/ee74a6a4-0dd5-11e5-910a-37f036468325.png)

 * [ ] JavaScript Tracking code: Custom variable Name/Value labels are not themed. Got: bold text. Expected: "Name"/"value" to maybe use the same style as "campaign name parameter" / "campaign keyword parameter" below?

![js code cvar not style](https://cloud.githubusercontent.com/assets/466765/8026719/d4224404-0dd6-11e5-9506-affb480dcd78.png)

 * [ ] Similarly the Image Tracking Code > Track a goal is not styled. 
![image tracking with optional revenue](https://cloud.githubusercontent.com/assets/466765/8026728/4d922ebc-0dd7-11e5-916a-422860426765.png)
    * Maybe the $ sign could be put to the right of the input field as you did for the general settings `Seconds`:
![seconds](https://cloud.githubusercontent.com/assets/466765/8026732/5c4dcf9c-0dd7-11e5-8061-9f5b853bcfa0.png)

 * Would it make sense to have a different style for the Input set as Disabled? eg for the username input, Expected: maybe background color?. Got: looks like a normal input field.

![disabled input](https://cloud.githubusercontent.com/assets/466765/8026740/9ed479f6-0dd7-11e5-8134-bed5c6c130f9.png)


(some of these refs #7587)

**Comment by mattab** [comment] 2015-06-08 00:26
Note, a regression in JS Tracking Code:

 * [ ] JS Tracking Code > Advanced > "Track Custom variables for this visitor", does not work. The values are not set in HTTP request:

![js tracking code advanced custom variables are not set in http requests](https://cloud.githubusercontent.com/assets/466765/8026777/7b5354d2-0dd9-11e5-8690-4449c273be58.png)

**Comment by mnapoli** [comment] 2015-06-08 15:13
@mattab all points should be addressed now. FYI the "disabled fields" where styled (since the forms redesign) but it was lost in a regression -> fixed.

For this:

![](https://cloud.githubusercontent.com/assets/466765/8026719/d4224404-0dd6-11e5-9506-affb480dcd78.png)

I have changed the style to this:

![capture d ecran 2015-06-08 a 17 09 20](https://cloud.githubusercontent.com/assets/720328/8038083/be73bdec-0e01-11e5-9011-778e5e36f9d8.png)

**Comment by mattab** [comment] 2015-06-09 02:57
:+1: 

New points:

 * [ ] JS Tracking Code > Advanced > "Track Custom variables for this visitor" -> set Name to `hello"world` -> in the JS code Expected to get `"hello\"world"`, Got instead: `"hello"world"`
 * [ ] Website Manager > When clicking on Next/Previous button, the whole table jumps. We need to avoid this screen jump. There are two places where we display "Loading...". One is above Next button and one is below the button and above the websites table. Could we only display the `Loading...` at the top of the buttons to prevent the jump?

![extra loading](https://cloud.githubusercontent.com/assets/466765/8049643/c21cd30c-0eb5-11e5-89e0-a7416dde4768.png)

 * [ ] All Websites dashboard. In the first row, last column "Evolution", could we make the metric  SELECTor vertically aligned with the "Evolution" column name? Expected: vertical aligned, Got instead the SELECT Is kinda below the text:

![align evolution visites](https://cloud.githubusercontent.com/assets/466765/8049660/ec9a8192-0eb5-11e5-8e72-933f389e8ce8.png)

**Comment by mattab** [comment] 2015-06-09 03:19
* [ ] When creating a new custom dashboard, Got: one label is displayed below the Radio box. Expected: label displayed on same line as radio box:

![creating new dashboard popover](https://cloud.githubusercontent.com/assets/466765/8050022/e726e250-0eba-11e5-81f2-8d604be4c3ad.png)

**Comment by mnapoli** [comment] 2015-06-15 14:04
Regarding this:

>  JS Tracking Code > Advanced > "Track Custom variables for this visitor" -> set Name to `hello"world` -> in the JS code Expected to get `"hello\"world"`, Got instead: `"hello"world"`

This is an unrelated issue that has nothing to do with the redesign. Let's stay on topic and open these in separate tickets. I created #8109 for this.

**Closed** 2015-06-16 13:34 UTC
Labels: c: Design / UI, not-in-changelog

**Comment by mattab** [comment] 2015-06-17 03:28
>      This is an unrelated issue that has nothing to do with the redesign. Let's stay on topic and open these in separate tickets. 

:+1:  


If anyone notices a UI element not displayed correctly let us know! As far as I can see, it looks all good now.

**Comment by mnapoli** [comment] 2015-06-17 07:38
For the record I'll update the UI screenshots now, I forgot to do that yesterday while waiting for the build
