### ISSUE TITLE
Performance degradation after update from 2.9.2 -> 2.11.2

### ISSUE THREAD

**Issue by sdosg** [piwik/piwik#7416] opened 2015-03-12 12:39 UTC
After upgrading from 2.9.2 to 2.11.2 our server can handle only about half of the requests than before the upgrade (from ~740 req/s to ~400 req/s). Due to the database upgrades, i can't go back to 2.9.2. 
The bottleneck is cpu, mostly consumed by php fcgi threads.

Server Setup:
FreeBSD 10.1, lighttpd 1.35, php 5.6.6, mysql 5.6

**Comment by GreenReaper** [comment] 2015-03-14 12:41
Do you have munin or some similar monitoring platform? I saw what appears to be a doubling in mysql temp tables (and worse, disk tables) in 2.10 - would be interested to know if others have as well.

**Comment by cybernet** [comment] 2015-03-14 21:32
+1

**Comment by diosmosis** [comment] 2015-03-14 22:33
@GreenReaper Is the table size increase in the archive tables? If so, this issue is tracked here: https://github.com/piwik/piwik/issues/7181 . Can you take a look at the last comment there and see if it helps you?

**Comment by GreenReaper** [comment] 2015-03-15 17:22
I'm not sure that the table size has increased markedly - the issue is that it is creating temporary disk tables where it wasn't before (where before = around 2.9), seemingly on each hit - like this:
![mysql_tmp_tables-month](https://cloud.githubusercontent.com/assets/383043/6657070/d686da48-cb37-11e4-9b9f-e1146892e753.png)

**Comment by mattab** [comment] 2015-03-16 05:00
Hi there,
Please test with latest Piwik beta: http://builds.piwik.org/ where this issue should be fixed. If you still have issue with this, please open new separate issue. Thanks

**Closed by mattab** 2015-03-16 05:00 UTC

**Comment by diosmosis** [comment] 2015-03-16 16:28
@GreenReaper Those queries use temporary tables, but I wouldn't expect them to be stored on disk, as they should not select much data. Can you see what happens when you run those queries yourself w/o the GROUP BY/MIN and ORDER BY/LIMIT? How many rows do they end up selecting?

**Comment by mattab** [comment] 2015-03-16 23:24
Let's continue discussion in #7440
