### ISSUE TITLE
4.8.0: Archiving fails with "SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '...' for key 'PRIMARY' - in plugin VisitFrequency."

### ISSUE THREAD

**Issue by EreMaijala** [piwik/piwik#19015] opened 2022-03-29 06:23 UTC
## Expected Behavior

When running archiving from cron, it is expected to work without errors. That was the case up to Matomo 4.7.

## Current Behavior

After upgrading to Matomo 4.8.0, cron archiving fails repeatedly with the following error message:

```
ERROR [2022-03-29 05:29:34] 5139  Got invalid response from API request: ?module=API&method=CoreAdminHome.archiveReports&idSite=712&period=week&date=2022-03-28&format=json&trigger=archivephp. Response was '{"result":"error","message":"SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '361822039' for key 'PRIMARY' - in plugin VisitFrequency. #0 \/data\/matomo\/core\/ArchiveProcessor\/Loader.php(284): Piwik\\ArchiveProcessor\\PluginsArchiver-&gt;callAggregateAllPlugins() #1 \/data\/matomo\/core\/ArchiveProcessor\/Loader.php(176): Piwik\\ArchiveProcessor\\Loader-&gt;prepareAllPluginsArchive() #2 \/data\/matomo\/core\/ArchiveProcessor\/Loader.php(159): Piwik\\ArchiveProcessor\\Loader-&gt;insertArchiveData() #3 \/data\/matomo\/core\/ArchiveProcessor\/Loader.php(99): Piwik\\ArchiveProcessor\\Loader-&gt;prepareArchiveImpl() #4 \/data\/matomo\/core\/Context.php(75): Piwik\\ArchiveProcessor\\Loader-&gt;Piwik\\ArchiveProcessor\\{closure}() [...]
```

## Your Environment

* Matomo Version: 4.8.0
* PHP Version: 7.4.28
* Server Operating System: CentOS 7.9.2009
* Additionally installed plugins: API, Actions, Annotations, BulkTracking, Contents, CoreAdminHome, CoreConsole, CoreHome, CorePluginsAdmin, CoreUpdater, CoreVisualizations, CoreVue, CustomDimensions, CustomDimensionsManager 0.1.0, CustomVariables 4.0.1, DBStats, Dashboard, DevicePlugins, DevicesDetection, Diagnostics, Ecommerce, Events, Feedback, GeoIp2, Goals, Heartbeat, ImageGraph, Installation, Intl, IntranetMeasurable, InvalidateReports 4.0.1, LanguagesManager, Live, Login, Marketplace, MobileMessaging, Monolog, Morpheus, MultiSites, Overlay, PagePerformance, PrivacyManager, Provider 4.0.3, Proxy, QueuedTracking 4.0.2, Referrers, Resolution, RssWidget, SEO, ScheduledReports, SegmentEditor, SitesManager, Tour, Transitions, TwoFactorAuth, UserCountry, UserCountryMap, UserId, UserLanguage, UsersManager, VisitFrequency, VisitTime, VisitorInterest, VisitsSummary, WebsiteMeasurable, Widgetize

**Comment by EreMaijala** [comment] 2022-03-29 07:30
Downgraded to 4.7.1, and archiving is back to working properly.

**Comment by tomper00** [comment] 2022-03-29 11:24
We just found the same issue here!

**Comment by mikkeschiren** [comment] 2022-03-29 12:40
The error mostly looks like this:
```
ERROR [2022-03-28 13:42:14] 1  Got invalid response from API request: ?module=API&method=CoreAdminHome.archiveReports&idSite=1&period=day&date=2022-03-28&format=json&segment=referrerType%3D%3Dsearch%3BvisitIp%21%3D192.121.0.0&trigger=archivephp. Response was '{"result":"error","message":"SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '317881120' for key 'PRIMARY' - in plugin Goals. - in plugin Goals. #0 \/var\/www\/html\/core\/ArchiveProcessor\/Loader.php(284): Piwik\\ArchiveProcessor\\PluginsArchiver-&gt;callAggregateAllPlugins() #1 \/var\/www\/html\/core\/ArchiveProcessor\/Loader.php(176): Piwik\\ArchiveProcessor\\Loader-&gt;prepareAllPluginsArchive() #2 \/var\/www\/html\/core\/ArchiveProcessor\/Loader.php(159): Piwik\\ArchiveProcessor\\Loader-&gt;insertArchiveData() #3 \/var\/www\/html\/core\/ArchiveProcessor\/Loader.php(99): Piwik\\ArchiveProcessor\\Loader-&gt;prepareArchiveImpl() #4 \/var\/www\/html\/core\/Context.php(75): Piwik\\ArchiveProcessor\\Loader-&gt;Piwik\\ArchiveProcessor\\{closure}() #5 \/var\/www\/html\/core\/ArchiveProcessor\/Loader.php(103): Piwik\\Context::changeIdSite() #6 \/var\/www\/html\/plugins\/CoreAdminHome\/API.php(277): Piwik\\ArchiveProcessor\\Loader-&gt;prepareArchive() #7 [internal function]: Piwik\\Plugins\\CoreAdminHome\\API-&gt;archiveReports() #8 \/var\/www\/html\/core\/API\/Proxy.php(244): call_user_func_array() #9 \/var\/www\/html\/core\/Context.php(28): Piwik\\API\\Proxy-&gt;Piwik\\API\\{closure}() #10 \/var\/www\/html\/core\/API\/Proxy.php(335): Piwik\\Context::executeWithQueryParameters() #11 \/var\/www\/html\/core\/API\/Request.php(266): Piwik\\API\\Proxy-&gt;call() #12 \/var\/www\/html\/plugins\/API\/Controller.php(45): Piwik\\API\\Request-&gt;process() #13 [internal function]: Piwik\\Plugins\\API\\Controller-&gt;index() #14 \/var\/www\/html\/core\/FrontController.php(626): call_user_func_array() #15 \/var\/www\/html\/core\/FrontController.php(168): Piwik\\FrontController-&gt;doDispatch() #16 \/var\/www\/html\/core\/dispatch.php(32): Piwik\\FrontController-&gt;dispatch() #17 \/var\/www\/html\/index.php(25): require_once('\/var\/www\/html\/c...') #18 \/var\/www\/html\/core\/CliMulti\/RequestCommand.php(79): require_once('\/var\/www\/html\/i...') #19 \/var\/www\/html\/vendor\/symfony\/console\/Symfony\/Component\/Console\/Command\/Command.php(257): Piwik\\CliMulti\\RequestCommand-&gt;execute() #20 \/var\/www\/html\/vendor\/symfony\/console\/Symfony\/Component\/Console\/Application.php(874): Symfony\\Component\\Console\\Command\\Command-&gt;run() #21 \/var\/www\/html\/vendor\/symfony\/console\/Symfony\/Component\/Console\/Application.php(195): Symfony\\Component\\Console\\Application-&gt;doRunCommand() #22 [internal function]: Symfony\\Component\\Console\\Application-&gt;doRun() #23 \/var\/www\/html\/core\/Console.php(135): call_user_func() #24 \/var\/www\/html\/core\/Access.php(670): Piwik\\Console-&gt;Piwik\\{closure}() #25 \/var\/www\/html\/core\/Console.php(136): Piwik\\Access::doAsSuperUser() #26 \/var\/www\/html\/core\/Console.php(87): Piwik\\Console-&gt;doRunImpl() #27 \/var\/www\/html\/vendor\/symfony\/console\/Symfony\/Component\/Console\/Application.php(126): Piwik\\Console-&gt;doRun() #28 \/var\/www\/html\/console(32): Symfony\\Component\\Console\\Application-&gt;run() #29 {main}, caused by: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '317881120' for key 'PRIMARY' - in plugin Goals. #0 \/var\/www\/html\/core\/ArchiveProcessor\/Loader.php(284): Piwik\\ArchiveProcessor\\PluginsArchiver-&gt;callAggregateAllPlugins() #1 \/var\/www\/html\/core\/ArchiveProcessor\/Loader.php(176): Piwik\\ArchiveProcessor\\Loader-&gt;prepareAllPluginsArchive() #2 \/var\/www\/html\/core\/ArchiveProcessor\/Loader.php(159): Piwik\\ArchiveProcessor\\Loader-&gt;insertArchiveData() #3 \/var\/www\/html\/core\/ArchiveProcessor\/Loader.php(99): Piwik\\ArchiveProcessor\\Loader-&gt;prepareArchiveImpl() #4 \/var\/www\/html\/core\/Context.php(75): Piwik\\ArchiveProcessor\\Loader-&gt;Piwik\\ArchiveProcessor\\{closure}() #5 \/var\/www\/html\/core\/ArchiveProcessor\/Loader.php(103): Piwik\\Context::changeIdSite() #6 \/var\/www\/html\/core\/ArchiveProcessor.php(699): Piwik\\ArchiveProcessor\\Loader-&gt;prepareArchive() #7 \/var\/www\/html\/plugins\/Goals\/Archiver.php(126): Piwik\\ArchiveProcessor-&gt;processDependentArchive() #8 \/var\/www\/html\/core\/Plugin\/Archiver.php(89): Piwik\\Plugins\\Goals\\Archiver-&gt;aggregateDayReport() #9 \/var\/www\/html\/core\/ArchiveProcessor\/PluginsArchiver.php(164): Piwik\\Plugin\\Archiver-&gt;callAggregateDayReport() #10 \/var\/www\/html\/core\/ArchiveProcessor\/Loader.php(284): Piwik\\ArchiveProcessor\\PluginsArchiver-&gt;callAggregateAllPlugins() #11 \/var\/www\/html\/core\/ArchiveProcessor\/Loader.php(176): Piwik\\ArchiveProcessor\\Loader-&gt;prepareAllPluginsArchive() #12 \/var\/www\/html\/core\/ArchiveProcessor\/Loader.php(159): Piwik\\ArchiveProcessor\\Loader-&gt;insertArchiveData() #13 \/var\/www\/html\/core\/ArchiveProcessor\/Loader.php(99): Piwik\\ArchiveProcessor\\Loader-&gt;prepareArchiveImpl() #14 \/var\/www\/html\/core\/Context.php(75): Piwik\\ArchiveProcessor\\Loader-&gt;Piwik\\ArchiveProcessor\\{closure}() #15 \/var\/www\/html\/core\/ArchiveProcessor\/Loader.php(103): Piwik\\Context::changeIdSite() #16 \/var\/www\/html\/plugins\/CoreAdminHome\/API.php(277): Piwik\\ArchiveProcessor\\Loader-&gt;prepareArchive() #17 [internal function]: Piwik\\Plugins\\CoreAdminHome\\API-&gt;archiveReports() #18 \/var\/www\/html\/core\/API\/Proxy.php(244): call_user_func_array() #19 \/var\/www\/html\/core\/Context.php(28): Piwik\\API\\Proxy-&gt;Piwik\\API\\{closure}() #20 \/var\/www\/html\/core\/API\/Proxy.php(335): Piwik\\Context::executeWithQueryParameters() #21 \/var\/www\/html\/core\/API\/Request.php(266): Piwik\\API\\Proxy-&gt;call() #22 \/var\/www\/html\/plugins\/API\/Controller.php(45): Piwik\\API\\Request-&gt;process() # ... )\n#50 \/var\/www\/html\/console(32): Symfony\\Component\\Console\\Application->run()\n#51 {main}"}'
```

**Comment by mikkeschiren** [comment] 2022-03-29 15:00
We also downgraded btw.

**Comment by tsteur** [comment] 2022-03-29 18:48
Hi everyone, I'll close this as a duplicate of https://github.com/matomo-org/matomo/issues/18937 . Please follow this issue to see the progress on it.

**Closed as completed by tsteur** 2022-03-29 18:48 UTC
Labels: duplicate
