### ISSUE TITLE
PHP: Using ${var} deprecated.

### ISSUE THREAD

**Issue by SnakebiteEF2000** [piwik/piwik#21133] opened 2023-08-08 13:16 UTC
PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /var/www/html/vendor/symfony/console/Symfony/Component/Console/Helper/DialogHelper.php on line 52
PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /var/www/html/vendor/symfony/console/Symfony/Component/Console/Helper/QuestionHelper.php on line 120

## Possible Solution
I fixed this by simply changing the old syntax to the newone.
I now get a warning in the systemcheck because of a lack of Dataintegrity.
This worked fine for me and the cronjob is running withouth any errors.

``` bash
sed -i 's/\$\({[^}]*}\)/{\1}/g' /var/www/html/vendor/symfony/console/Symfony/Component/Console/Helper/DialogHelper.php 
sed -i 's/\$\({[^}]*}\)/{\1}/g' /var/www/html/vendor/symfony/console/Symfony/Component/Console/Helper/QuestionHelper.php
```

## Your Environment
* Matomo Version: 4.15.1
* PHP Version: 8.2.9
* Server Operating System: Alma Linux
* Additionally installed plugins: Ldap Login

**Comment by michalkleiner** [comment] 2023-08-08 15:22
Hi @SnakebiteEF2000,
thank you for taking the time to create the issue. As you can see in the path of the affected file, the issue is in a vendor dependency which we don't control. I believe the issue has been fixed in a newer version of symfony/console which we have updated for the upcoming Matomo 5 release and won't be fixing for Matomo 4.x.
As an interim measure until Matomo 5 is available it should be safe to disable deprecation warnings within your PHP config.

**Comment by michalkleiner** [comment] 2023-08-08 15:24
Duplicate of #20514

**Closed as completed** 2023-08-08 15:24 UTC
Labels: duplicate, not-in-changelog

**Comment by ssvx** [comment] 2023-11-29 12:38
@michalkleiner 
> won't be fixing for Matomo 4.x. As an interim measure until Matomo 5 is available it should be safe to disable deprecation warnings within your PHP config.

I think that is terrible advise because Matomo ain't the only thing running on any given site. IMO it's not ok to just "disable deprecation warnings" on the whole PHP config, while ignoring that this would also affect the actual website the person likely wants to track (and possibly still actively develops/changes).

Active support for PHP 8.1 ended 4 days ago and Matomo 5 ain't available just yet - at least not as default upgrade. Not sure how easy/safe it is to just switch to 5.0.0.rc8. So may i suggest to change that advise to "just ignore the integrity check for the files you know you changed yourself"?

Even better would be if devs here just jumped their shadow and shifted those silly 2 characters in 2 files by 2 positions to the right and be done with it. After all the symfony license grants all permissions including modifications and redistribution. Telling ppl who try to contribute working fixes to shove it and wait for 5.x ... and @sgiehl even claimed you ([quote](https://github.com/matomo-org/matomo/issues/20514#issuecomment-1481468957)) "are not able to fix this error within Matomo 4" ... not ... able? People are literally writing the solution into their reports. Even i found the solution by just reading the log message and was about to create a new issue but found multiple existing ones. Even the log message itself literally outputs the solution _and_ points to the 2 files and according lines where to apply the fix. But you are _not able_ fo fix it?

2 $ characters keep every Matomo user from switching to PHP 8.2 ...? Just change them, push 4.16.1 and let ppl upgrade their servers in anticipation of Matomo 5.

Just an opinion ¯\_(ツ)_/¯

**Comment by sgiehl** [comment] 2023-11-29 15:01
@ssvx Those problems are in files of symfony, which we include using composer. Code-wise they are very easy to fix. But it's not within our code, so we would only be able to fix them by forking the library and use a custom one instead, which would make updating those library a lot more complex. Over all this is by for more effort than a deprecation warning is worth.

And the suggestions to disabled deprecation warnings is a valid one. There is no need to have such warnings enabled on a production system. Those warnings are only helpful for development, so a developer sees what might need to be changed.
