### ISSUE TITLE
Styles and other stuff not loading

### ISSUE THREAD

**Issue by andrewfam** [piwik/piwik#9288] opened 2015-11-26 14:05 UTC
Not too sure what I've done wrong.

I'm getting this error in my chrome and none of the styles seem to be loading.

http://snagfin.sg/plugins/Morpheus/images/loading-blue.gif Failed to load resource: net::ERR_EMPTY_RESPONSE
http://snagfin.sg/plugins/Morpheus/stylesheets/base/bootstrap.css Failed to load resource: net::ERR_EMPTY_RESPONSE
http://snagfin.sg/plugins/Morpheus/stylesheets/base/icons.css Failed to load resource: net::ERR_EMPTY_RESPONSE
http://snagfin.sg/plugins/Morpheus/images/forms-sprite.png Failed to load resource: net::ERR_EMPTY_RESPONSE
http://snagfin.sg/libs/jquery/themes/base/images/ui-bg_flat_75_ffffff_40x100.png Failed to load resource: net::ERR_EMPTY_RESPONSE
http://snagfin.sg/plugins/MultiSites/angularjs/dashboard/dashboard.directive.html?cb=dd268e674ff585f030ba16f2288c268a Failed to load resource: net::ERR_EMPTY_RESPONSE
index.php?module=Proxy&action=getCoreJs&cb=dd268e674ff585f030ba16f2288c268a:204 Error: [$compile:tpload] http://errors.angularjs.org/1.2.28/$compile/tpload?p0=plugins%2FMultiSites%…shboard%2Fdashboard.directive.html%3Fcb%3Ddd268e674ff585f030ba16f2288c268a
    at Error (native)
    at http://snagfin.sg/index.php?module=Proxy&action=getCoreJs&cb=dd268e674ff585f030ba16f2288c268a:118:450
    at http://snagfin.sg/index.php?module=Proxy&action=getCoreJs&cb=dd268e674ff585f030ba16f2288c268a:173:148
    at http://snagfin.sg/index.php?module=Proxy&action=getCoreJs&cb=dd268e674ff585f030ba16f2288c268a:184:286
    at w (http://snagfin.sg/index.php?module=Proxy&action=getCoreJs&cb=dd268e674ff585f030ba16f2288c268a:213:167)
    at w (http://snagfin.sg/index.php?module=Proxy&action=getCoreJs&cb=dd268e674ff585f030ba16f2288c268a:213:167)
    at http://snagfin.sg/index.php?module=Proxy&action=getCoreJs&cb=dd268e674ff585f030ba16f2288c268a:214:428
    at h.$eval (http://snagfin.sg/index.php?module=Proxy&action=getCoreJs&cb=dd268e674ff585f030ba16f2288c268a:225:32)
    at h.$digest (http://snagfin.sg/index.php?module=Proxy&action=getCoreJs&cb=dd268e674ff585f030ba16f2288c268a:222:117)
    at h.$apply (http://snagfin.sg/index.php?module=Proxy&action=getCoreJs&cb=dd268e674ff585f030ba16f2288c268a:225:362)(anonymous function) @ index.php?module=Proxy&action=getCoreJs&cb=dd268e674ff585f030ba16f2288c268a:204

**Comment by tsteur** [comment] 2015-11-26 20:15
Ad blocker or something similar maybe?

**Comment by andrewfam** [comment] 2015-11-26 23:45
Hey nope I've tried it in firefox and chrome. I can give you access to the site to take a look if you pass me your email

**Comment by tsteur** [comment] 2015-11-27 01:07
Actually I checked out http://snagfin.sg/ and could reproduce it but I have no clue why they are blocked. This seems to be a server configuration problem. Check out maybe  http://www.tomshardware.com/forum/4370-73-error-err_empty_response or other sites. If you can't solve it I'd suggest to ask in the forum if someone can help: http://forum.piwik.org/

I'm closing it for now as it seems to be not a generic Piwik problem. Would be nice to comment here if you find a solution for it so it will help other people

**Closed by tsteur** 2015-11-27 01:07 UTC

**Comment by andrewfam** [comment] 2015-11-27 11:08
The above didn't seem to work.

Got someone to debug and he came up with this.

/etc/nginx/apps/piwik/piwik.conf 
valid_referers none blocked *.snagfin.sg snagfin.sg;

**Comment by tsteur** [comment] 2015-11-29 18:37
Thx for letting us know. @mattab is there maybe a FAQ where this could be useful as a possible solution to add? Maybe something like http://piwik.org/faq/troubleshooting/faq_18485/ ?

**Comment by mattab** [comment] 2015-12-21 01:26
@andrewfam what was the issue exactly, do you mind re-explaining?

@tsteur if you understood, maybe you can suggest a new bullet point to add to the FAQ http://piwik.org/faq/troubleshooting/faq_18485/ ?

**Comment by tsteur** [comment] 2015-12-21 19:23
Yes that FAQ was what I was thinking about

**Comment by andrewfam** [comment] 2015-12-21 23:24
Hey its the below
https://github.com/perusio/piwik-nginx/blob/master/apps/piwik/piwik.conf

Line 9
valid_referers none blocked *.mysite.com othersite.com;
Changing all to your site.

**Comment by mattab** [comment] 2015-12-22 00:21
I noticed there is already a mention of this in the FAQ! 

> * if you are using Nginx, check out the <a href='https://github.com/perusio/piwik-nginx/'>Piwik-Nginx configuration</a>. Note: make sure you replace the corresponding line in the piwik-nginx configuration with your own domain(s): `valid_referers none blocked *.mysite.com othersite.com;`  (if that is too much of a hassle for you then just comment out the `valid_referers` block.)
