### ISSUE TITLE
When selecting a segment with a date range on a goal, then 0 conversions are shown but data shows when selecting the same range as a week

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#18915] opened 2022-03-09 19:42 UTC
I couldn't reproduce this on demo or any other segment or any other data range that covers a week. It only happens for this specific date range and segment combination.

To recreate, please follow the steps below in our analytics for site 12:

* Date range (2022-02-21 to 2022-02-27)
* Segment ([visited matomo cloud via menu](https://demo-web.matomo.org/index.php?module=CoreHome&action=index&idSite=12&period=day&date=yesterday#?period=range&date=2022-02-21,2022-02-27&segment=pageUrl%3D%3Dhttps%25253A%25252F%25252Fmatomo.org%25252Fmatomo-cloud%25252F%25253Fmenu&idSite=12&category=Goals_Goals&subcategory=9))
* Go to goal (Cloud - signed up for free trial)

It shows 0 conversions
<img width="1520" alt="image" src="https://user-images.githubusercontent.com/273120/157520323-ac233446-1ce0-476f-a2a5-9a9fc265467b.png">

When selecting the same range as a week, then the data shows.

Site Timezone: France
Matomo: 4.7.1 (but the data could have been archived under 4.6.2)
PHP 8

**Comment by Chardonneaur** [comment] 2022-04-05 13:58
Hi Tomas, one of my client reproduces it, it happens on a weekly comparison basis with conversions.
To reproduce it, please select a weekly range period and compare it to the previous period and look through the goal report per channel types.

**Comment by mattab** [comment] 2023-12-11 04:28
Thanks for contributing to this issue. As it has been a few months since the last activity and we believe this is likely not an issue anymore, we will now close this. If that's not the case, please do feel free to either reopen this issue or [open a new one](https://developer.matomo.org/guides/core-team-workflow#submitting-a-bug-report). We will gladly take a look again!

**Closed as not planned by mattab** 2023-12-11 04:28 UTC
Labels: Bug, not-in-changelog
