### ISSUE TITLE
Optional display of Revenue field

### ISSUE THREAD

**Issue by raj45** [piwik/piwik#9029] opened 2015-10-16 08:50 UTC
It should be possible to turn off the Revenue field completely, if you don't use it anyway.

![selection_001](https://cloud.githubusercontent.com/assets/7046001/10537661/9c38ba36-73f3-11e5-8805-d434813aee9e.png)

**Comment by tsteur** [comment] 2015-10-16 17:59
Thx for reporting this issue. I'll close it as a duplicate of #2390 . Please follow that issue (there are also a couple of similar issues referenced)

**Closed by tsteur** 2015-10-16 17:59 UTC
Labels: duplicate

**Comment by raj45** [comment] 2015-10-19 07:37
Thanks, I'll follow it over there.
