### ISSUE TITLE
Log Analytics: Monitor Bandwidth for each page, download, and measure overall traffic in bytes

### ISSUE THREAD

**Issue by anonymous-piwik-user** [piwik/piwik#5248] opened 2014-05-27 12:54 UTC
As a user, when [importing my server logs in analytics](http://piwik.org/log-analytics/), I want to measure the Bandwidth that was used by each page view.

How would it work?

* The bandwidth information is commonly available in the server access log files. It is measured in Bytes.
* Log analytics script would detect the numeric bandwidth value
* Log analytics forwards this value to the [Tracking API](http://developer.piwik.org/api-reference/tracking-api) and this value will be stored in the action.
* This value can be attached to downloads and pageviews
* The Reporting UI:
  * for each page: display the total bandwidth for each page view
  * for each directory (groups of pages): display the aggregated bandwidth value (the sum) of all pages within the directory

Proposed implementation:

 * New column in log_link_visit_action: `bandwidth`
 * Tracking API add new parameter: file size in bytes` bw_bytes `
* Log Analytics parses filesize, and sets &bw_bytes to tracking api requests
  * first log format we need to support is Apache common log format.
* Tracker stores bandwidth in the new column `log_link_visit_action.bandwidth`
* Actions/Archiver will aggregate the filesize in the Action report blobs. 
  * This is similar to Average generation time.
  * The metric is processed for Pages, Page titles, and Download files.
* User interface: the new metric "Bytes" will be displayed in the Actions tables
  * It is displayed in the existing Actions reports (Pages, Page titles, Downloads): this is not a new report.
  * If a user is not using Log Analytics, or if he is using Log Analytics but the logs don't have the file size bandwidth, then Actions reports will not have the "Bytes" column. 

Other steps: 
 * Add new overall metric (and sparkline) in Visitors > Overview report:```
 Total Bandwidth ``` 
  * eg. Total Bandwidth for piwik.org website = 155 Gb
* Update [Tracking API reference](http://developer.piwik.org/api-reference/tracking-api) to document new parameter
 * Add new FAQ```
 How do I measure traffic bandwidth used by a page, and/or overall bandwidth? ```
* Update [feature page](http://piwik.org/features/) and [Log Analytics](http://piwik.org/log-analytics/) page to mention this new feature

To be confirmed / optional:
* Besides Apache common log format, maybe other log formats contain the bandwidth information
* New custom segment "Bandwidth" to let users segment traffic based on the file size in bytes
  * for example "Show me reports only for file requests of files over 500,000"
* We could even measure in Javascript the current page size, which would be useful, but unfortunately it can only be done with approximate value. This counts the number of bytes in DOM tree:```
 document.documentElement.innerHTML.length ```.  
  * This is an approximation only. if there's lots of page content created on the fly from script, that content will count in innerHTML despite not being present in the original source, which could throw your calculation out [source](http://stackoverflow.com/a/4402107/120988)

**Comment by tsteur** [comment] 2015-01-04 22:39
Maybe a plugin on the marketplace? Especially since we do not directly need something in piwik.js. Could be a nice plugin example for how to do such things. Later we could also at some point work on how to make piwik.js for plugins extensible but that's another issue

**Comment by mattab** [comment] 2015-01-05 00:43
> Maybe a plugin on the marketplace?

this would be ideal!

**Comment by tsteur** [comment] 2015-01-11 06:46
what would be the plugin name for this?

**Comment by mattab** [comment] 2015-01-12 00:04
Good question... Maybe
 * `FileSize`
 * or `Bandwidth` 
 * or `ActionFilesize`
 * or better?

**Comment by tsteur** [comment] 2015-01-20 23:01
I won't measure the current page size with JavaScript in Piwik JS Tracker. It is not accurate at all, especially in modern websites/applications and one would maybe expect to include traffic that was caused by CSS / Images / JavaScript files. Tracking only the HTML content is most likely not that interesting. Also it is not yet possible to extend the Piwik JS Tracker with a plugin I think but that's not really a problem.

The name will be `Bandwidth` as the traffic is not necessarily caused by a file and `ActionFilesize` / `ActionBandwidth` is too technical and too coupled to Actions.

**Comment by tsteur** [comment] 2015-01-20 23:26
This part is not as easy and it is kinda wrong as it can be also used via the Tracking API and not only log analytics:

> If a user is not using Log Analytics, or if he is using Log Analytics but the logs don't have the file size bandwidth, then Actions reports will not have the "Bytes" column.

It is complicated as there are subtables and we would maybe end up showing the columns in the first level but not in a lower level.

I might have to send another API request to get the top level report when configuring the ViewDataTable which columns to show. I'd then have to check if any of those has a bandwidth metric or not. I'd also have to request stats for period=month as it would be not as nice to show the columns on some days where there is a bandwidth recorded and on other days not for the same site. It would maybe not happen as often but can still happen, especially around midnight. Re performance this could be cached but makes everything complicated. Might have to archive more numeric records for this which would be easiest probably.

**Comment by tsteur** [comment] 2015-01-21 04:14
@diosmosis would you mind having a look at the plugin if there's something strange or missing or so? https://github.com/piwik/plugin-Bandwidth I could use maybe more Metric classes eg for OverallTotalBandwidth, PageviewTotalBandwidth and DownloadTotalBandwidth metrics. Otherwise it seems to work with latest master

**Comment by diosmosis** [comment] 2015-01-21 21:07
@tsteur The total metrics are aggregated and there's currently no way to express those as metadata classes, so they shouldn't be metrics (yet). One issue is that some aggregated metrics like min/max bandwidth have processed metrics classes, however, it's not a big deal. If/when aggregated metrics classes are supported this can be changed (or not, it will likely still work regardless).

**Comment by tsteur** [comment] 2015-01-22 00:35
Ok thx. Closing it for now and waiting for feedback from client.

**Closed by tsteur** 2015-01-22 00:35 UTC
Labels: c: Log Analytics (import_logs.py), Enhancement, Major

**Comment by mattab** [comment] 2015-02-07 02:50
The plugin Bandwidth will be released on the Marketplace! See issue https://github.com/piwik/plugin-Bandwidth/issues/1

**Comment by mattab** [comment] 2015-02-18 04:11
The plugin Bandwidth has been released on the Marketplace: http://plugins.piwik.org/Bandwidth :+1:
