### ISSUE TITLE
New bold red message about ad blockers at the top of each page

### ISSUE THREAD

**Issue by CyrilBrulebois** [piwik/piwik#19097] opened 2022-04-14 00:55 UTC
Since upgrading to 4.9.0, a big fat red message appears at the top of each page, warning me against the use of ad blockers:

> Dans le cas où vous utiliseriez un bloqueur de publicités, veuillez le désactiver pour ce site afin de vous assurer que Matomo fonctionne correctement.

Screenshot:

![Screenshot from 2022-04-14 02-50-33](https://user-images.githubusercontent.com/8861145/163292804-d4e9a565-9bc7-4600-b7fe-3dddb0e4b014.png)

## Expected Behavior

Back to pre-4.9.0 behaviour: no such messages.

## Current Behavior

The message hideous and non-dismissable. Whether I'm using an ad blocker is absolutely none of Matomo's business.

## Context

Happily upgraded from the previous release to 4.9.0, and wow! Quite a change from the usually seamless upgrade path!

## Your Environment

* Matomo Version: 4.9.0

**Comment by justinvelluppillai** [comment] 2022-04-14 08:53
This warning already existed for a long time with no changes in Matomo 4.9.0.

**Comment by sgiehl** [comment] 2022-04-14 09:39
@CyrilBrulebois You should check if your browser blocks any requests to Matomo. That message is automatically hidden by CSS/JS. If it's visible that means the requests failed.

**Comment by CyrilBrulebois** [comment] 2022-04-14 09:52
@sgiehl Thanks, I had been checking this since the previous reply: I'm indeed seeing an item getting blocked (`bottomAd`); I've looked around and didn't see anything obvious that could have changed in this release (as stated by @justinvelluppillai). That message was definitely not showing up before the upgrade though (I've got Matomo in a pinned tab, I would have noticed).

I'm not sure why that's happening all of a sudden then. Since you folks seem to consider this is not a bug, I suppose I'll patch out the twig include in my installation, and call it a day.

**Comment by cadeyrn** [comment] 2022-04-14 09:55
> This warning already existed for a long time with no changes in Matomo 4.9.0.

For me the message definitely appears only since the update to Matomo 4.9.0.

**Comment by sgiehl** [comment] 2022-04-14 10:01
That's interesting. The code of that template hadn't changed since 2018. Wondering why it should suddenly start blocking it, unless there was an update in the adblocker maybe. 
In general disabling the adblocker for Matomo only should fix any such issues.

**Comment by CyrilBrulebois** [comment] 2022-04-14 10:15
I was trying to check https://github.com/easylist/easylist's history (that's the trigger according to uBlock Origins), but got tired of waiting for deltas to be resolved on that ~ 3G repository…

Sure, disabling the adblocker for Matomo might work as a general solution might work.

I don't understand why I would have to do that.

Going back in the twig file's history, I'm seeing https://github.com/matomo-org/matomo/pull/12493 mentioned. It seems the intent was use within the installer. I'm on the front page of my instance. Why should I turn my adblocker off?

**Comment by cadeyrn** [comment] 2022-04-14 10:43
While disabling the easylist filter in Adblock Plus works for me I want to note that I did the Matomo update ~ 1 hour ago. The last filter list update was done a few hours earlier on my system. It would also have been a very big coincidence if the filter list would have been updated in exactly the same moment as Matomo.

**Comment by Findus23** [comment] 2022-04-14 11:56
@CyrilBrulebois #12493 was not just intended for the installer, but also all other pages in Matomo. And this check has been there indeed since 2018.

Everyone, do you by chance have your Matomo instance installed on a subdomain called matomo.yoursite.example?
Then it might be caused by this rule in the easyprivacy filter list:

https://github.com/easylist/easylist/commit/ece9fd83f4e9c0bcb9fde348c1e6a1d7486944db#commitcomment-56844920

[Update: No, it seems like this is another unrelated issue]

**Comment by cadeyrn** [comment] 2022-04-14 12:03
> Everyone, do you by chance have your Matomo instance installed on a subdomain called matomo.yoursite.example?

In my case it's analytics.yoursite.example. And the linked change was commited in September 2021, so it would not explain why it suddenly happens after the Matomo 4.9.0 update.

**Comment by Findus23** [comment] 2022-04-14 12:05
> Whether I'm using an ad blocker is absolutely none of Matomo's business.

That's of course fully true (and I assume most Matomo users use ad-blockers).
The reason for this is just that ad-blockers often block the core JS package of Matomo with overly broad rules. And as this breaks Matomo in unexpected ways, it's very helpful if a message is displayed at the same time.


That said, maybe the check could be improved. At the moment it seems to check if a `bottomAd` element gets modified. But maybe instead it should check if the Matomo core JS is loaded (by putting the code that hides the message there).
Then again this might make the message flash for a short amount of time on every page load until the JS has been loaded, which also isn't ideal.

**Comment by Findus23** [comment] 2022-04-14 12:14
@cadeyrn That's true, that is probably unrelated. 

I think I can reproduce this issue now that I added an exception rule (`@@://matomo.$domain=~matomo.org` ) for the rule above and enabled ublock origin again for my site.
Weirdly enough it still doesn't appear on demo.matomo.cloud even though the `bottomAd` is also hidden there.
I think there might be some timing issue in the JS of _adblockDetect.twig.

**Comment by CyrilBrulebois** [comment] 2022-04-14 12:17
I'm using `numbers.` as a subdomain here, not `matomo.`.

**Comment by CyrilBrulebois** [comment] 2022-04-14 12:23
The easylist update seems like a red herring too, finally retried a `git clone` on a machine with more cores, and `git blame` suggests that rule has been here since forever or so:

```
commit 8058e2f5866d67094d5782d4f52abf9252f0a135
Author: Ares2 <ares2mail@gmail.com>
Date:   Mon Nov 30 00:54:14 2009 +0100
```

**Comment by sgiehl** [comment] 2022-04-14 12:30
@Findus23 I'm not able to reproduce that with my installed adblocker. If you find a way to fix / improve that feel free to create a PR against `next_release` so we can include that in Matomo 4.9.1

**Comment by CyrilBrulebois** [comment] 2022-04-14 12:47
The timing issue hypothesis (or something similar) seems possible to my rather inexperienced web debugger eyes: once the demo page is loaded, using Firefox's debugger to run parts of the detection function correctly gets `wasMostLikelyCausedByAdblock = true`.

**Comment by diosmosis** [comment] 2022-04-14 15:19
@CyrilBrulebois this looks like it's related to the Vue migration as some code is no longer loaded in a blocking manner. Can you check if this change fixes the issue for you: https://github.com/matomo-org/matomo/pull/19106 ?

**Comment by CyrilBrulebois** [comment] 2022-04-14 15:40
@diosmosis Sure thing: wrapping the code inside that `DOMContentLoaded` listener makes the issue disappear, thanks!

(Tested by hitting Refresh a few times with that change applied, all good; undoing the change makes the issue come back immediately.)

**Comment by ghost** [comment] 2022-04-15 15:28
I just joined, to report that I am seeing this horrible message about the adblocker.

Obviously I am not going to disable my ad blocker for anyone :D

Is there a manual way to remove it entirely?

Thank you.

**Comment by sgiehl** [comment] 2022-04-15 19:20
@LauraTaylorUK you can apply the changes from this PR: https://github.com/matomo-org/matomo/pull/19106/files
Otherwise a fix will be included in 4.9.1, which should be released soonish.

**Comment by ghost** [comment] 2022-04-15 19:40
Thank you for the prompt fix and support.

Maybe now is a good time to ask, why there is a adblock detection script included in the admin interface?

**Comment by Findus23** [comment] 2022-04-15 20:13
> Maybe now is a good time to ask, why there is a adblock detection script included in the admin interface?

Mainly for the reason I explained here: https://github.com/matomo-org/matomo/issues/19097#issuecomment-1099116238

There are too many ill-configured ad-blockers and overly broad blocking rules that break Matomo and when it does it often does in ways that makes Matomo look broken. And the adblocker is often not the first thing people think of when debugging.

**Comment by MatomoForumNotifications** [comment] 2022-04-16 11:48
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/fur-den-fall-dass-sie-einen-ad-blocker-verwenden-deaktivieren-sie-diesen-bitte-fur-diese-seite-um-sicherzustellen-dass-matomo-problemlos-lauft/45558/2

**Closed as completed** 2022-04-18 21:53 UTC
Labels: not-in-changelog, Regression
