### ISSUE TITLE
All websites dashboard don't save period parameter

### ISSUE THREAD

**Issue by semafork** [piwik/piwik#7831] opened 2015-05-04 20:18 UTC
Hi,

On the All websites dashboard, though I set the parameter "Load dashboard for the current month", the period is still set by default to "current day".

I tried to change the parameter, save, and put it again on "Current month", it does nothing.

Thanks

**Comment by tsteur** [comment] 2015-05-04 22:06
I think this is a duplicate of #7795. Please reopen if not.

**Closed by tsteur** 2015-05-04 22:06 UTC
Labels: duplicate

**Comment by semafork** [comment] 2015-05-05 06:44
You're right. It's a duplicate. Sorry.

Thanks
