### ISSUE TITLE
Comparing segments – no data for conversions

### ISSUE THREAD

**Issue by niklasternstedt** [piwik/piwik#18869] opened 2022-03-02 07:44 UTC
## Expected Behavior
I would be able to compare two segments regarding conversions and see if search, direct traffic, web pages etc are converting.

## Current Behavior
When I choose to compare two segments like computer vs mobile and go to the report goals everything seems fine. But when I scroll down to see how search, direct traffic, web pages etc perform regarding conversions there are no data for conversions, only for visits. It works fine if I only choose one segment.

I succeeded to replicate the bug in your demo environment.

## Steps to Reproduce (for Bugs)
1. Choose a segment and then choose a another one to compare it with.
2. Go to the report goals.
3. Scroll down to channel type.
4. You will see there is no data for conversions, only for visits

## Context
I'm trying to compare different segments with each other to try to gain more insights in how one of our clients web is performing.

## Your Environment
* Matomo Version: 4.7.1
* PHP Version: 7.4.28
* Additionally installed plugins: custom reports and search engine keywords performance
* Browser: Brave
* Operating System: MacOS
<img width="660" alt="Skärmavbild 2022-03-02 kl  08 31 18" src="https://user-images.githubusercontent.com/47598905/156316952-2956f8c1-be81-4de5-aed0-52486208f81f.png">

**Comment by sgiehl** [comment] 2022-03-02 08:17
Thanks for creating the issue. I am able to reproduce that on our demo:
https://demo.matomo.cloud/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?idSite=1&period=month&date=2022-02-17&segment=&category=Goals_Goals&subcategory=General_Overview&compareSegments%5B%5D=countryCode%3D%3Dnz
This seems to be a bug in compare mode, as both segments that are compared have conversions when viewed without comparing.
@tsteur that is something we should investigate. Not sure if that is a regression, or maybe never worked correctly.

**Comment by niklasternstedt** [comment] 2022-03-02 14:47
I think it has worked before.

**Comment by tsteur** [comment] 2022-03-02 19:11
This might be a duplicate of https://github.com/matomo-org/matomo/issues/15849 ? My understanding was it never worked in the first place (and at least seems to have been broken since April 2020 unless it's a different issue)

**Comment by sgiehl** [comment] 2022-03-03 12:55
That seems to be the same issue, indeed.

**Comment by sgiehl** [comment] 2022-03-03 13:26
I think I found the problem. will prepare a PR to fix that.

**Closed as completed** 2022-03-04 09:48 UTC
Labels: Bug, not-in-changelog, Regression
