### ISSUE TITLE
Enhancement: Add a percentages option instead of raw counts / totals.  In all diagrams and tables.

### ISSUE THREAD

**Issue by atom-box** [piwik/piwik#18855] opened 2022-02-26 23:37 UTC
A user writes:

Question: What is the feature you are missing the most in Matomo and why?
Answer:
percentages instead of total values in all diagrams!!!!!

**Comment by tsteur** [comment] 2022-02-28 00:03
Thanks @atom-box I'll close this one as a duplicate of https://github.com/matomo-org/matomo/issues/15515

**Closed as completed by tsteur** 2022-02-28 00:03 UTC
Labels: duplicate
