### ISSUE TITLE
Issue with Graph in PDF Email Report

### ISSUE THREAD

**Issue by jagdish-nasit** [piwik/piwik#8419] opened 2015-07-24 05:04 UTC
Hi,

We have observed one issue in PDF Report which is getting delivered as Email Report option. We have setup Piwik recently and we have data only from 15-Jul. However, graph under Page Titles & Downloads section its showing data in Jun month dates and no data on 15-Jul onwards.

Other graphs are showing it correct. I have attached screenshot of both Page Title, Downloads which has issue and also Visit Summary which is showing graph correct.
![pdf_report](https://cloud.githubusercontent.com/assets/2486967/8867995/66344694-31ef-11e5-9517-b74e73433ef9.png)

**Comment by mattab** [comment] 2015-07-28 09:24
Thanks for the report @jagdish-nasit - this is duplicate of #7948

**Closed by mattab** 2015-07-28 09:24 UTC

**Comment by jagdish-nasit** [comment] 2015-08-04 03:34
Thanks @mattab, I checked and that bug and seems its tagged with short-term milestone. Do we have tentative date for this milestone ?
