### ISSUE TITLE
Backspace eats extra characters

### ISSUE THREAD

**Issue by mskala** [piwik/piwik#12143] opened 2017-10-03 15:37 UTC
In several places in Piwik's Web interface, pressing the backspace key will delete two characters instead of one, if by doing so it can delete a space at the end of the input.

Steps to reproduce:
- Go to "manage" a Goal, either by creating a new one or clicking the edit icon for an existing goal in the "manage" menu.
- Click at the end of the Description field
- enter some non-space characters, one space, and then one more non-space character.  For example, "abc d"
- press backspace once.  It will delete two characters (the space, and the final non-space character)
- it ought to delete only one character, leaving the space intact.

I'm running Piwik 3.1.1, server is Linux, Apache, PHP 5.6.31; client is Linux, Pale Moon.  It happens to me in every text field in the interface that has fancy fade-in and similar features, throughout the settings and configuration screens, but not in the "search" box and a few other places.

**Comment by Findus23** [comment] 2017-10-03 16:26
I can reproduce this in Firefox 56.

I feel like this is kind of intended by some library, but I agree with you that it is annoying as the user doesn't expect it.

**Comment by Morerice** [comment] 2017-10-15 09:13
Sorry for the first commit which was not branched from **3.x-dev**

**Comment by sgiehl** [comment] 2017-10-15 18:20
Fixed with #12197

**Closed by sgiehl** 2017-10-15 18:20 UTC
Labels: Hacktoberfest
