### ISSUE TITLE
Google Analytics import plugin not compatible with Matomo 4.9.1

### ISSUE THREAD

**Issue by niklasternstedt** [piwik/piwik#19147] opened 2022-04-27 11:00 UTC
## Expected Behavior
It should not appear a error message inside Matomo with the info:
"The plugin GoogleAnalyticsImporter could not be loaded as it has missing dependencies: GoogleAnalyticsImporter requires Matomo >=4.10.0-b1. Please contact your Matomo administrator."

## Current Behavior
Same as above

## Possible Solution
Update the plugin Google Analytics import so it is compatible with the latest version of Matomo

## Context
The plugin do not work

## Your Environment
* Matomo Version: 4.9.1
* PHP Version: 7.4.27
* Browser: Brave
* Operating System: iOS

**Comment by Findus23** [comment] 2022-04-27 11:33
Hi,

How did you install the plugin?

From the Marketplace or did you manually download and extract it?

**Comment by Findus23** [comment] 2022-04-27 11:33
> Update the plugin Google Analytics import so it is compatible with the latest version of Matomo

The issue is more the other way around: The latest version of GA-import requires the next version of Matomo (which will be released in weeks). But this means it also should not be recommended to anyone to be installed.

**Comment by sgiehl** [comment] 2022-04-28 12:03
I'll close this one. It should be automatically fixed with the upcoming release. It actually slipped through that the new version of the plugin will only be compatible with a not yet released version of Matomo. Normally this shouldn't happen and we will try to prevent that this happens again.

**Closed as completed by sgiehl** 2022-04-28 12:03 UTC
Labels: answered

**Comment by niklasternstedt** [comment] 2022-05-02 12:31
Thanks for the answers 👍

**Comment by MatomoForumNotifications** [comment] 2022-05-11 07:31
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/googleanalyticsimporter-required-executables-nohup/37982/4

**Comment by MatomoForumNotifications** [comment] 2022-05-18 07:43
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/incompability-problem-with-googleanalyticsimporter-on-matomo-4-6-2/45974/2
