### ISSUE TITLE
Error excluded referrers

### ISSUE THREAD

**Issue by mindbreaker** [piwik/piwik#19848] opened 2022-10-12 09:14 UTC
I wanted to use the new referrers exclude option, but i got an error while adding some Domains

![image](https://user-images.githubusercontent.com/225204/195302306-b412572f-5fb5-42df-a2de-5b2d17772c7a.png)

Now it is not longer possible to save it:

![image](https://user-images.githubusercontent.com/225204/195302397-3de8a250-8172-4e0f-8a75-620c43f6e39d.png)

**Comment by MatomoForumNotifications** [comment] 2022-10-12 09:20
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/error-excluded-referrers/47798/1

**Comment by Findus23** [comment] 2022-10-12 09:34
This might be related to https://github.com/matomo-org/matomo/issues/19833 
@peterhashair can you please take a look at this too?

**Comment by peterhashair** [comment] 2022-10-12 11:02
@Findus23 sure thing

**Comment by MatomoForumNotifications** [comment] 2022-10-12 12:43
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/the-address-is-not-a-valid-url/47725/5

**Comment by heurteph-ei** [comment] 2022-10-12 16:19
Is it linked to https://forum.matomo.org/t/error-500-after-update/47774/4 ❓

**Comment by MatomoForumNotifications** [comment] 2022-10-12 16:19
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/error-500-after-update/47774/6

**Comment by MatomoForumNotifications** [comment] 2022-10-13 08:27
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/mise-a-jour-4-12-message-pour-info-pas-bloquant/47700/5

**Comment by justinvelluppillai** [comment] 2022-10-18 03:37
@peterhashair what is the status of this? It doesn't look like it's been progressed or triaged fully yet. Can you please check what should happen next?

**Comment by peterhashair** [comment] 2022-10-18 10:29
@justinvelluppillai I believe this has been resolved, I can't reproduce this on my local anymore. I will close this tickets for now.

**Closed as completed by peterhashair** 2022-10-18 10:29 UTC
Labels: answered

**Comment by mindbreaker** [comment] 2022-11-03 17:59
Jep seems to be fixed
