### ISSUE TITLE
Goals->Overview, after clicking on sparkline of a goal's metrics (conversions or conversion rate), the top evolution graph doesn't show metrics of the goal

### ISSUE THREAD

**Issue by weixuezhang** [piwik/piwik#18764] opened 2022-02-09 05:29 UTC
On https://demo.matomo.cloud/, can reproduce this issue.

## Steps to Reproduce (for Bugs)

1.
2.

## Your Environment

* Matomo Version:
* PHP Version:
* Server Operating System:
* Additionally installed plugins:

* Browser:
* Operating System:

**Comment by bx80** [comment] 2022-02-09 20:36
Duplicate of #18766

**Closed as completed by bx80** 2022-02-09 20:36 UTC
Labels: duplicate
