### ISSUE TITLE
"Unique Visitor" label for KPI widget only visible for Day periods

### ISSUE THREAD

**Issue by 9joshua** [piwik/piwik#21068] opened 2023-07-26 22:16 UTC
The label for the Unique Visitor KPI widget is missing when the calandar is set to a Week or Month period.
Day period:
![Screenshot from 2023-07-27 10-12-08](https://github.com/matomo-org/matomo/assets/20234985/53294e50-9567-420d-894b-34ae8f80d078)

Week period:
![Screenshot from 2023-07-27 10-10-16](https://github.com/matomo-org/matomo/assets/20234985/f3fb8c95-d3ee-42dc-b472-d4cf41d8ffad)

Steps to reproduce:
Add a KPI widget and select "Unique Visitors"
Change the calebndar period to aWeek or Month period

Tested on both Cloud and On-premise, Matomo version 4.15

**Comment by michalkleiner** [comment] 2023-07-27 15:41
Same happens e.g. with the Users metric. It seems some metrics are not defined for date ranges longer than a day. There could be a reason for this but I don't have the history/context for this.
Would you know, @sgiehl, whether it's intentional or it's a legitimate bug?

**Comment by sgiehl** [comment] 2023-07-27 16:17
Some "unique" metrics might not be processed at all, depending on the configuration. But default should be that the metric is only unavailable for year and range

**Comment by michalkleiner** [comment] 2023-07-27 20:11
I guess the problem isn't as much that the metric is not available, but rather how it is/is not presented to the user.

**Comment by michalkleiner** [comment] 2023-07-27 20:13
Closing as a duplicate of #20216.

**Closed as not planned by michalkleiner** 2023-07-27 20:13 UTC
Labels: duplicate, not-in-changelog
