### ISSUE TITLE
Core:archive scheduled tasks Call to undefined method in Tasks.php

### ISSUE THREAD

**Issue by mahdi1234** [piwik/piwik#10884] opened 2016-11-20 14:02 UTC
Piwik 2.17.1

```
php5 /var/www/site/piwik/console core:archive --url=http://piwik.site
...
INFO [2016-11-14 22:04:25] SCHEDULED TASKS
PHP Fatal error: Call to undefined method Piwik\Plugins\CorePluginsAdmin\CorePluginsAdmin::isMarketplaceEnabled() in /var/www/site/piwik/plugins/CorePluginsAdmin/Tasks.php on line 17
```

I commented out problematic part in piwik/plugins/CorePluginsAdmin/Tasks.php

 ```
   /**
    if (CorePluginsAdmin::isMarketplaceEnabled()) {
    $this->daily('sendNotificationIfUpdatesAvailable', null, self::LOWEST_PRIORITY);
    }
    */
```

and it works again.

**Comment by tsteur** [comment] 2016-11-20 18:10
It looks like some files were not updated during the last update. Can you follow these steps to update the files manually: http://piwik.org/docs/update/#the-manual-three-step-update

You could maybe also try to only update that file `piwik/plugins/CorePluginsAdmin/Tasks.php` first to check if it works but maybe other files weren't updated either.

Important: If you update all your files make sure to backup the file `config/config.ini.php` first as explained in the guide

**Comment by tsteur** [comment] 2016-11-20 18:12
Actually, you can fix it by just deleting that file `piwik/plugins/CorePluginsAdmin/Tasks.php`.

**Comment by tsteur** [comment] 2016-11-20 18:13
Duplicate of https://github.com/piwik/piwik/issues/10805

**Closed by tsteur** 2016-11-20 18:13 UTC
Labels: answered
