### ISSUE TITLE
Access Denied to Users 

### ISSUE THREAD

**Issue by MattiaLamma** [piwik/piwik#20920] opened 2023-06-22 14:46 UTC
Good Afternoon. Yesterday I add a new user to my Matomo and i gave him the "Only wiev" role. Today he tried to Access but Matomo denies it. So i login to Matomo site, because i have the administrator role, and we found out that Matomo automatically changed his role from "only wiev" to "no access". This is the second time that happened when i tried to add new Users. I always have to assigned the role twice, because the first time Matomo didn't save it. I use the last Version of Matomo, 4.14.2, on Windows 11. Thanks for your Help.

Mattia Lamma

**Comment by michalkleiner** [comment] 2023-06-23 02:02
Hi @MattiaLamma,
thanks for opening the issue.
I just tried locally, invited a new user, selected the "View" permission for All websites and it worked as expected, the user was able to accept the invite and view the dashboard.

Can you test, in the list of users, when you invite a new user, copy their invitation link and try to accept the invitation in a new browser window, if the issue occurs again?
Do you have any plugins installed that could be interfering with this perhaps?

**Comment by MattiaLamma** [comment] 2023-06-23 08:45
Hi @michalkleiner 
Thank you for the support.
Unfortunately tthe issue occurs again.
I don't think we have plugins that could be interfering.
Have a nice day.

**Comment by michalkleiner** [comment] 2023-06-23 09:21
Sorry to hear that @MattiaLamma. Unfortunately  I can't reproduce the issue, so I can't be of any more help. Do you have multiple websites perhaps and looking at the correct one in the list of users? There's a "Role for" dropdown above the users table, and if a different website is selected to the one you gave permissions for then it will show no access, but will show the correct access when you switch to the correct website.

<img width="460" alt="role for website - users list" src="https://github.com/matomo-org/matomo/assets/233342/045cd4fe-c450-44e7-a5ac-1f1536b06917">

If you still consider this being an issue with Matomo we would need further steps on how to reliably replicate the issue.

**Comment by sgiehl** [comment] 2023-08-24 12:38
Closing this one as there hadn't been any feedback in the last months. 
@MattiaLamma If you still have problems around that, maybe try to find some help on our forums or create a new issue with a detailed list of steps how the problem can be reproduced.
Cheers,

**Closed as completed by sgiehl** 2023-08-24 12:38 UTC
Labels: worksforme
