### ISSUE TITLE
Page URLs hostnames are not set correctly when importing logs with cs-host field

### ISSUE THREAD

**Issue by Brutonix** [piwik/piwik#7341] opened 2015-03-03 11:59 UTC
Scenario:
1 website installed on Windows 2008 r2 IIS 7.5. The website is configured with several bindings. eg. http://www.mysite1.com, http://www.mysite2.com, http://www.mysite3.com
![image](https://cloud.githubusercontent.com/assets/11292522/6461533/89b3e0f6-c198-11e4-89a5-b76c8a7e1ab4.png)

The IIS logs are configured with the default settings and I have added cs-host to be recorded.
![image](https://cloud.githubusercontent.com/assets/11292522/6461516/73f530c6-c198-11e4-8535-b63b1cf5746d.png)

I have installed Piwik 2.11.1 on a linux server and configured a site with ID:16, Name:MySite, URLs:http://www.mysite1.com, http://www.mysite2.com, http://www.mysite3.com and left everything else as default.
![image](https://cloud.githubusercontent.com/assets/11292522/6461560/c7adb9a4-c198-11e4-9522-bb72fd2ce001.png)

I then run the import_logs.py that was supplied with the Piwik installation.
Within Piwik, the Vistor Log displays the default website address http://www.mysite1.com and not the correct URL that was hit.
![image](https://cloud.githubusercontent.com/assets/11292522/6461716/6739a5b8-c19a-11e4-8bcd-a014a338994d.png)

The IIS logs report the correct URL / cs-host
![image](https://cloud.githubusercontent.com/assets/11292522/6461733/9c4a83b2-c19a-11e4-841a-6b19661fa01e.png)

If you amend some lines in import_logs.py, the correct information is displayed within Piwik.
From line 1468, make the following changes:

#only prepend main url if it's a path 
#url = (main_url if path.startswith('/') else '') + path[:1024] 

try: 
url = 'http://' + hit.host + path 
except AttributeError: 
url = (main_url if path.startswith('/') else '') + path[:1024]

And now my Visitor Logs report the correct URL

**Comment by mattab** [comment] 2015-03-03 21:00
Hi @Brutonix thanks for the report. Can you please paste here a short log file (maybe 10-20 lines) so we can try reproduce the issue?

**Comment by Brutonix** [comment] 2015-03-03 21:05
Mattab,
You've lost me on the request for a short log file, as I have given the repo steps in the above scenario with a solution.

**Comment by mattab** [comment] 2015-03-03 21:12
Thanks for the instructions above, they are really great :+1: but to reproduce, since none of us use IIS, it would help to get the log file. Could you send it, even privately to hello@piwik.org ?

**Comment by Brutonix** [comment] 2015-03-03 21:13
Ah, I see, will do when I'm at work tomorrow.

**Comment by mattab** [comment] 2015-04-08 03:19
@Brutonix any update maybe about this short log file we could use to reproduce?

**Comment by mattab** [comment] 2015-04-08 06:50
Maybe it's similar or duplicate of  #7396

**Comment by Brutonix** [comment] 2015-04-08 20:17
Matthieu,

An email was sent on the 4th March. Do you need me to send it again ?

Regards

**Comment by mattab** [comment] 2015-04-13 02:37
Thanks @Brutonix - it would be great if you could send your log again to hello@piwik.org as I didn't get it the last time. Also I've created an issue for this bug in log-analytics project: https://github.com/piwik/piwik-log-analytics/issues/67

**Closed by mattab** 2015-04-13 02:37 UTC
Labels: Bug
