### ISSUE TITLE
Do not use eval function in piwik.js (for CSP)

### ISSUE THREAD

**Issue by ondrejmirtes** [piwik/piwik#5960] opened 2014-08-09 19:27 UTC
In order to implement CSP on my website, I disallowed `'unsafe-eval'` in `script-src` directive. But I cannot track visitors with Piwik, because piwik.js tracking code contains call to `eval` function twice.

Can you consider rewriting the code so it does not use `eval`? (Which is a bad idea nevertheless.)

**Comment by tsteur** [comment] 2015-02-17 20:11
I wonder why this issue is closed as it is not fixed? For example we could use https://bestiejs.github.io/json3/ which does not use eval

**Comment by tsteur** [comment] 2015-02-17 23:29
FYI: I tried to replace JSON2 with JSON3 but I can't get JSON3 to work with [JSLint](http://www.jslint.com/) . Meaning no matter which options I set JSLint always fails and it seems to be not possible to ignore one block of code for JSLint. We should replace JSLint at some point with [JSHint](http://jshint.com/) which would exactly solve this.

**Comment by tsteur** [comment] 2015-02-17 23:55
If someone manages to make Piwik.js work with JSHint we could replace JSON2 with JSON3 and remove all evals. See #7232

**Comment by mattab** [comment] 2015-04-09 04:36
since the goal of this issue is really to add CSP support to piwik.js I suggest we mark as duplicate of:  #1542

next step: #7232

**Comment by tsteur** [comment] 2015-10-02 09:08
Reopen this one since `eval` !== CSP

**Closed** 2015-10-04 21:09 UTC
Labels: Enhancement
