### ISSUE TITLE
piwik.js broken in 2.15.0 [JSON2.stringify is not a function]

### ISSUE THREAD

**Issue by thommyhh** [piwik/piwik#9130] opened 2015-10-30 08:54 UTC
Hi,

after an update to Piwik 2.15.0 the number of tracked visitors dropped to nearly zero. After investigating I found out, that there is a js error in "piwik.js". It's about this website: http://www.statistik-nord.de/

I tried it with Chrome 46 and Firefox 41 and Safari 9 on Mac OS 10.10. and IE11 and Firefox 41 on Windows 7.

Can you give me some feedback here?

**Comment by tsteur** [comment] 2015-10-30 20:25
It looks like your website is defining a `JSON2` as well that defines eg following methods: `JSON2.decode`, `JSON2.encode`, `JSON2.replaceChars`, ...

Did you maybe also make any changes to your website recently?

I quickly tried to reproduce but couldn't. I presume Piwik is defining `JSON2` correctly, then it gets changed by the website (I tested setting `var JSON2 = {}` first and then letting Piwik add methods). This would mean there were changes in your website though which is probably not the case. Need to have a look again

**Comment by tsteur** [comment] 2015-11-01 21:58
I prepared a patch. It should be fixed by overwriting your `piwik.js` in the Piwik directory with this: https://raw.githubusercontent.com/piwik/piwik/9130/piwik.js 

With the next release it should be fixed automatically

**Closed** 2015-11-02 00:35 UTC
Labels: Bug

**Comment by thommyhh** [comment] 2015-11-03 08:35
The patch works. Thank you very much.
