### ISSUE TITLE
In Scheduled reports, graphs display icons too big in the graph labels (for country, browser and OS)

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#11558] opened 2017-03-29 12:25 UTC
When creating a scheduled report, one can choose to include Graphs. The option is called "Display report tables and graphs". When adding reports like "Country", "Browsers". The generated report looks like below.

* Expected: to see icons in the standard icon size (about 16 or 20 pixels)
* Got: icons displayed much bigger

### Countries + Region + City
![countries](https://cloud.githubusercontent.com/assets/466765/24454240/6f1b590c-148b-11e7-816a-01035db92d7d.png)

### Operating systems

![os](https://cloud.githubusercontent.com/assets/466765/24454241/6f222868-148b-11e7-923d-a5bef98d72d6.png)

### Browsers

![browsers](https://cloud.githubusercontent.com/assets/466765/24454242/6f2a3a12-148b-11e7-96ef-d14a32948387.png)

**Comment by Findus23** [comment] 2017-03-29 12:44
@mattab, are you talking about the pdf or the html report?
 I thought I have tested it.

**Comment by mattab** [comment] 2017-03-29 12:49
Both have this problem as they both use the same ImageGraph API to generate those PNG graph

**Comment by Findus23** [comment] 2017-03-29 13:00
Ah, I have only tested the images in tables.
The problem is that the images are 48x48px large, but should be only displayed 16x16px large.

How are these images generated? They are inlined as `data:image`.

**Comment by sgiehl** [comment] 2017-03-29 13:06
Guess somewhere in the ImageGraph plugin

**Comment by Findus23** [comment] 2017-03-29 15:11
Seems like there is no easy fix. Hardcoding `getMaxLogoSize` or `getLogoSize` only changes the spacing but not the image size. Seems like pChart always prints images in original size.

The documentation isn't extremely helpful ether:
http://wiki.pchart.net/doc.dataset.setseriepicture.html

**Comment by sgiehl** [comment] 2017-04-18 15:11
Could we create resized duplicates of the images in tmp directory and use them?
Or we could try to adjust cPchart to make it possible to resize those images. Maybe it would get merged upstream if we propose a nice pull request...

**Closed** 2017-05-08 08:58 UTC
Labels: Regression
