### ISSUE TITLE
Accessibility: radio buttons read the label 3 times

### ISSUE THREAD

**Issue by mnapoli** [piwik/piwik#7008] opened 2015-01-14 01:29 UTC
refs #4167

The screen reader has trouble with our custom radio buttons: the label was read 3 times (e.g. "No, No, radio button, No" or something like that).

**Comment by TheCrowsJoker** [comment] 2015-01-15 01:49
We didnt find an easy fix for this issue and it also happened on other sites when tested indicating it could be a bug with the screen reader as opposed to the website. It does however wok with a simple html page containing only 2 radio buttons.

**Comment by tsteur** [comment] 2015-01-15 01:50
As it is a very minor issue we will close it for now. Fixing it would most likely take a lot of time. If you see this issue and know what it causes and maybe even have a fix for it let us know.

**Closed by tsteur** 2015-01-15 01:50 UTC
Labels: c: Usability, Easy pick

**Comment by tassoman** [comment] 2015-02-25 10:55
Can't reproduce this issue inside Settings Page inside admin UI using NVDA screen reader. Labels are correctly spelled.
