### ISSUE TITLE
Error about getenv function

### ISSUE THREAD

**Issue by loukasstoltz** [piwik/piwik#19173] opened 2022-05-04 15:31 UTC
## Expected Behavior
Try to connect to my matomo instance and get 
Fatal error: Uncaught Error: Call to undefined function Piwik\Plugin\getenv() in analytics.serveur.digital/core/Plugin/Manager.php:345 Stack trace: #15849 
analytics.serveur.digital/core/bootstrap.php(48): Piwik\Plugin\Manager::initPluginDirectories() #1 analytics.serveur.digital/index.php(19): require_once('...') #2 {main} thrown in 
analytics.serveur.digital/core/Plugin/Manager.php on line 345

## Current Behavior
Just update to latest version 

## Possible Solution
I have try to reinstall with command line, 
I have try to reinstall by downloading zip script 
I have fix permission

## Steps to Reproduce (for Bugs)

1. Installation 
2. go to the URL 

## Context

I can't go to my analytics

https://analytics.serveur.digital/

## Your Environment

* Matomo Version: Latest
* PHP Version: 8.1
* Server Operating System: Ubuntu
* Additionally installed plugins:No
* Browser: Google Chrome
* Operating System: iOs

**Comment by sgiehl** [comment] 2022-05-05 13:28
Hm.... `getenv()` is actually a php functions and no method in that namespace. Normally PHP should automatically use the php function if it is not defined in the namespace (when being used unqualified).
Was Matomo working before on that server or weren't you able to install it? Just wondering if anything changed on your server or within Matomo.

**Comment by loukasstoltz** [comment] 2022-05-05 13:34
Hi Stefan, 

It look I solve the issue by downgrading my PHP version from 8.0 to 7.4 
Right now I can re-access it nicely (lucky I’m :-) ) 
Thank you ! 


Le 5 mai 2022 à 15:29:06, Stefan Giehl ***@***.***) a écrit:

Hm.... getenv() is actually a php functions and no method in that namespace. Normally PHP should automatically use the php function if it is not defined in the namespace (when being used unqualified).
Was Matomo working before on that server or weren't you able to install it? Just wondering if anything changed on your server or within Matomo.

**Comment by sgiehl** [comment] 2022-05-05 14:26
Ok. I'll close this issue for now, as I'm not able to reproduce that. If you decide to update PHP later and run into the same problem, feel free to reopen/create an issue. Thanks.

**Closed as completed by sgiehl** 2022-05-05 14:26 UTC
Labels: worksforme
