### ISSUE TITLE
pageUrl segment does not work with =@ contains operator for the Site Search Keyword Panel

### ISSUE THREAD

**Issue by andrewbrown12** [piwik/piwik#9189] opened 2015-11-09 13:47 UTC
pageUrl segment does not work with =@ contains operator for the Site Search Keyword Panel

Issue #2727 is a similar issue that has fixed this problem in other areas, but it is still present ont he Site Search Keyword Panel.

If I add a segment based on the URL containing one of our base URLs no results are show, however the Pages Following a Search panel correctly segments the data. To prove this issue I have swapped to doesn't contain operator and still get no results in the Site Search Keyword panel

**Comment by mattab** [comment] 2015-11-25 23:52
Could you please paste one or two screenshots showing the problem? (ie. segment editor + site search results segmented and un-segmented?)

**Comment by andrewbrown12** [comment] 2015-11-26 15:23
Hi Matt,

Here is the Site Search Keyword with no Segment
![piwik1](https://cloud.githubusercontent.com/assets/15730419/11426037/137fd1ba-9451-11e5-83a1-af14981b6304.png)

The config for contains mydomain segment

![piwik2](https://cloud.githubusercontent.com/assets/15730419/11426057/4223807a-9451-11e5-8b57-ca9203a7ea72.png)

This results in no entries in the panel even though most of the searches are from this domain
![piwik3](https://cloud.githubusercontent.com/assets/15730419/11426074/5b1b8384-9451-11e5-8c22-629695de7815.png)

Trying the inverse doesn't contain mydomain segment
![piwik4](https://cloud.githubusercontent.com/assets/15730419/11426081/6abfb7ec-9451-11e5-9bc6-6bbaf863ecf2.png)

Still returns no results, which indicates to me that the Segmentation by Page URL isn't working.
![piwik5](https://cloud.githubusercontent.com/assets/15730419/11426094/7b55eed2-9451-11e5-8d22-952c4b17fcdc.png)

Andy

**Comment by mattab** [comment] 2015-11-27 03:14
can you try to remove `https` from the segment, does it work better?

**Comment by andrewbrown12** [comment] 2015-11-27 08:29
I've just tried without https and still doesn't work.

Andy

**Comment by mattab** [comment] 2015-12-23 03:51
Maybe this issue i  srelated to #8878  and #8972

**Comment by mattab** [comment] 2016-07-01 04:07
This was also [reported in the forums:](https://forum.piwik.org/t/segment-visitors-visits-that-include-a-certain-page-url-doesnt-work/19921)

> I've tried doing so by building a segment where 'Page URL' 'equals' << page URL name >>. I think I have segmented visitors that have visited this page, among other pages and expect the other pages to also show in the pages overview. However, I can only see this specific page in the Actions > Pages overview. 

The issue lies in how Piwik implements segmentation when one is segmenting based on actions dimensions. We will likely fix this issue in a next version. this PR will help us: https://github.com/piwik/piwik/pull/10264 cc @tsteur

**Comment by mattab** [comment] 2017-09-22 21:08
Marking as duplicate of https://github.com/piwik/piwik/issues/11900

**Closed by mattab** 2017-09-22 21:08 UTC
Labels: Bug, Major

**Comment by mattab** [comment] 2019-10-27 20:32
This should be fixed in Matomo 3.12.0 which will be released tomorrow - if you still experience this issue then, let us know.
