### ISSUE TITLE
Customizable columns in All Websites Dashboard

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#5150] opened 2014-05-13 00:47 UTC
There were at least two user feedbacks which were interested in customizable columns in the all websites dashboard. For instance one user wanted to hide the revenue column (in this case system wide) as they are a non profit organization and another user wanted to see the number of unique visitors as this a key metric for their company.

**Comment by mattab** [comment] 2015-01-07 20:48
Requirements:

 * allow display more than 3 columns, eg. N columns
 * all existing metrics should be selectable including:
```
    Page views
    Page views per session
    Percentage new session
    Sessions
    Avg. pages per session
    Avg time on site
    Bounce rate
    Depth of visit (1, 2, 3 and more pages) 
    Avg. Length of visit
```

**Comment by mattab** [comment] 2015-03-26 01:10
I think this is duplicate of -> #2390

**Comment by mattab** [comment] 2015-07-15 16:56
duplicates #2390

**Closed by mattab** 2015-07-15 16:56 UTC
Labels: Enhancement
