### ISSUE TITLE
PDF in Scheduled reports' attachments may include  " â€“ characters

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#9631] opened 2016-01-26 06:05 UTC
As reported on the forum: http://forum.piwik.org/t/weekly-mail-report-is-empty-it-has-different-wrong-mime-format-since-version-2-15-0/17643

Sometimes, email attachments names can show up as: `December 21 â€“ 27, 2015.pdf` - for example the long hyphen (called `em-dash`) can cause this issue in email attachments, in at least some email client.

Goal of this issue would be to sanitise the Subject and attachment name to prevent these weird characters display issues.

**Comment by tsteur** [comment] 2016-01-26 19:46
This is a duplicate of https://github.com/piwik/piwik/issues/9580

**Comment by tsteur** [comment] 2016-01-26 20:33
Actually I reopen this one as it is different and only about `-` and `’` whereas #9580 is about other characters in general.

**Closed** 2016-01-26 20:34 UTC
Labels: Bug
