### ISSUE TITLE
cannot open "view visitor profile" when I add a segment whose condition contains ">"

### ISSUE THREAD

**Issue by phith0n** [piwik/piwik#9036] opened 2015-10-16 17:09 UTC
I just want to see the visitors who have visited my website more than 3 times.
so I add a segment
<img width="1207" alt="web_analytics_reports" src="https://cloud.githubusercontent.com/assets/5711185/10547873/9210868a-7469-11e5-8430-89edddad15f2.png">
then click the "view visitor profile"
<img width="626" alt="15_10_17_ 12_59" src="https://cloud.githubusercontent.com/assets/5711185/10548020/74e43862-746a-11e5-8919-ddd955c9830c.png">

but nothing happens
click "view visitor profile" again, I got an error:
<img width="637" alt="_-_piwik_ _web_analytics_reports" src="https://cloud.githubusercontent.com/assets/5711185/10547951/1348e40e-746a-11e5-8fab-c2cc0f358c91.png">

reload this error page,I got a bigger error:
<img width="1249" alt="_-_piwik_ _web_analytics_reports" src="https://cloud.githubusercontent.com/assets/5711185/10548047/b3b6661e-746a-11e5-9119-f1f2ed219dd6.png">

I think it is a bug about url encode.

**Comment by sgiehl** [comment] 2015-10-17 18:19
Which version are you using. That might already be fixed in latest beta with #8805.
Might be a duplicate of #8323

**Comment by tsteur** [comment] 2015-10-19 06:46
Hi @phith0n I tried to reproduce using latest Piwik beta version and could not reproduce it. Please update to 2.15.0 once it's available and feel free to reopen in case it still does not work for you. 

If you're having a Piwik installation on a test server you could also enable beta updates and get a possible fix already now: http://piwik.org/faq/how-to-update/#faq_159  We recommend to not install beta versions on production Piwik installations

**Closed by tsteur** 2015-10-19 06:46 UTC
