### ISSUE TITLE
PHP 8.1 incompatibility - Deprecated - preg_split(): Passing null to parameter #2 ($subject) of type string is deprecated in Draw.php (2451)

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#20656] opened 2023-05-03 00:28 UTC
> vendor/szymach/c-pchart/src/Draw.php(2451): Deprecated - preg_split(): Passing null to parameter #2 ($subject) of type string is deprecated - Matomo 4.14.3-b1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) [internal function]: Piwik\ErrorHandler::errorHandler(),#1/vendor/szymach/c-pchart/src/Draw.php(2451),#2/plugins/ImageGraph/StaticGraph/GridGraph.php(312),#3/plugins/ImageGraph/StaticGraph/Evolution.php(24),#4/plugins/ImageGraph/API.php(506),[internal function]: Piwik\Plugins\ImageGraph\API->get(),#6/core/API/Proxy.php(244),#7/core/Context.php(28),#8/core/API/Proxy.php(335),#9/core/API/Request.php(267)

After upgrading to PHP 8.1 above warning is showing up in the logs. This is all the information we have.

**Comment by michalkleiner** [comment] 2023-05-04 03:14
Duplicate of #20655

**Closed as not planned** 2023-05-15 21:42 UTC
Labels: wontfix, duplicate
