### ISSUE TITLE
Secured Tracking API ?!

### ISSUE THREAD

**Issue by albilu** [piwik/piwik#22056] opened 2024-03-27 19:22 UTC
Can't find a way to secure the POST request to the Tracking HTTP API using token_auth.

Not sure if this is normal as calls to the Tracking HTTP API are unsecure and anyone can craft the http://{matomo.server}/matomo.php?action_name... request and flood my server with fake events from any Rest client such as Postman.

I understand it would still be unsecure using a token from the Javascript code snippet as the token will be available for all users of my website.

But we should be able to secure the API using the Java Tracker.

In that case the http://{matomo.server}/matomo.php endpoint is restricted to only request coming from My app server using the appropriate token.

Am i missing something as this seems very unsecure. I will appreciate any clarification

**Comment by sgiehl** [comment] 2024-04-03 08:32
@albilu There is currently no (official) way to secure the tracking endpoint.
What in theory could work is to set the config flag `tracking_requests_require_authentication_when_custom_timestamp_newer_than` to zero. That should cause every tracking request to require a valid (admin) token_auth with the request.
But that for sure only works in a context where that token_auth in the request can't be revealed by anyone, otherwise they could use that token_auth to access the Matomo API.

**Comment by sgiehl** [comment] 2024-04-03 08:34
Closing this as duplicate of https://github.com/matomo-org/matomo/issues/20801

**Closed as not planned by sgiehl** 2024-04-03 08:34 UTC
Labels: Enhancement, duplicate

**Comment by albilu** [comment] 2024-05-05 17:03
@sgiehl thanks for your reply it is clear although tracking_requests_require_authentication_when_custom_timestamp_newer_than doesnt seems to works with my docker installation.

I think this is a case that worth considering. Especially when one running their own Matomo server.
It should be possible to secure the remote server and then call the report Api With the Java API client for example. That way the token is not expose to any public users as i am handling the tracking of events from my backend

Please consider this usecase
