### ISSUE TITLE
100 sites is the max when giving access rights

### ISSUE THREAD

**Issue by Bedouille69** [piwik/piwik#19168] opened 2022-05-03 07:01 UTC
Hello,

When I want to give access rights for all sites to an account, It’s seems limited to 100 sites.
Is it a bug ?

![image](https://user-images.githubusercontent.com/8983084/166415389-bc2de849-4757-4787-9564-fafadee5ffda.png)

Thanks.

**Comment by MatomoForumNotifications** [comment] 2022-05-03 09:48
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/100-sites-is-the-max-when-giving-access-rights/45778/4

**Comment by sgiehl** [comment] 2022-05-03 09:58
Hi @Bedouille69. Thanks for creating this issue. Isn't the a possibility to select all sites working for more than 100 sites. I don't have that much site created, but I'm able to select all like here:
![image](https://user-images.githubusercontent.com/1579355/166434915-9cceecb2-b345-4c43-92ec-30e7114db2c5.png)

**Comment by Bedouille69** [comment] 2022-05-03 10:05
Hi @sgiehl ,

Yes you can select like that but no change. If I look the request with Firefox debugger, there is a parameter with an array of 100 values and never more :(

**Comment by sgiehl** [comment] 2022-05-03 11:39
I'm actually not able to reproduce that. Just generated 105 sites and a bulk request to set view permission to all of them included all 105 site ids.

@Bedouille69 which version of Matomo are you using and which browser?

**Comment by Bedouille69** [comment] 2022-05-03 11:52
Matomo 4.9.1 and Firefox last version.

**Comment by sgiehl** [comment] 2022-05-03 12:30
Sorry, I'm also not able to reproduce that with Matomo 4.9.1 and Firefox. Are you sure the request does not contain all sites, or does your server drop everything after 100 post params maybe?

**Comment by Bedouille69** [comment] 2022-05-03 12:45
My request is like this in network, I have 103 sites but much more in production soon : 

force_api_session | "1"
-- | --
userLogin | "test"
access | "view"
idSites[] | […]
0 | "1"
1 | "2"
2 | "3"
3 | "4"
4 | "5"
5 | "6"
6 | "7"
7 | "8"
8 | "9"
9 | "10"
10 | "11"
11 | "12"
12 | "13"
13 | "14"
14 | "15"
15 | "16"
16 | "17"
17 | "18"
18 | "19"
19 | "20"
20 | "21"
21 | "22"
22 | "23"
23 | "24"
24 | "25"
25 | "26"
26 | "27"
27 | "28"
28 | "29"
29 | "30"
30 | "31"
31 | "32"
32 | "33"
33 | "34"
34 | "35"
35 | "36"
36 | "37"
37 | "38"
38 | "39"
39 | "40"
40 | "41"
41 | "42"
42 | "43"
43 | "44"
44 | "45"
45 | "68"
46 | "70"
47 | "76"
48 | "79"
49 | "80"
50 | "81"
51 | "82"
52 | "83"
53 | "92"
54 | "93"
55 | "94"
56 | "95"
57 | "96"
58 | "97"
59 | "98"
60 | "99"
61 | "100"
62 | "101"
63 | "102"
64 | "103"
65 | "104"
66 | "105"
67 | "106"
68 | "107"
69 | "108"
70 | "109"
71 | "110"
72 | "111"
73 | "112"
74 | "113"
75 | "114"
76 | "115"
77 | "116"
78 | "117"
79 | "118"
80 | "119"
81 | "120"
82 | "121"
83 | "122"
84 | "123"
85 | "124"
86 | "133"
87 | "134"
88 | "135"
89 | "136"
90 | "137"
91 | "138"
92 | "139"
93 | "140"
94 | "141"
95 | "142"
96 | "143"
97 | "144"
98 | "145"
99 | "146"

I don't know if the server limits something :(

**Comment by sgiehl** [comment] 2022-05-03 12:56
Might it be possible that the output in the dev tools is showing that limited? could you maybe check the raw data sent with the request? Maybe it contains more.

**Comment by Bedouille69** [comment] 2022-05-03 12:58
In bulk : token_auth=bde9168b6659317c65f71fb1d8af40a1&force_api_session=1&userLogin=test&access=view&idSites%5B%5D=1&idSites%5B%5D=2&idSites%5B%5D=3&idSites%5B%5D=4&idSites%5B%5D=5&idSites%5B%5D=6&idSites%5B%5D=7&idSites%5B%5D=8&idSites%5B%5D=9&idSites%5B%5D=10&idSites%5B%5D=11&idSites%5B%5D=12&idSites%5B%5D=13&idSites%5B%5D=14&idSites%5B%5D=15&idSites%5B%5D=16&idSites%5B%5D=17&idSites%5B%5D=18&idSites%5B%5D=19&idSites%5B%5D=20&idSites%5B%5D=21&idSites%5B%5D=22&idSites%5B%5D=23&idSites%5B%5D=24&idSites%5B%5D=25&idSites%5B%5D=26&idSites%5B%5D=27&idSites%5B%5D=28&idSites%5B%5D=29&idSites%5B%5D=30&idSites%5B%5D=31&idSites%5B%5D=32&idSites%5B%5D=33&idSites%5B%5D=34&idSites%5B%5D=35&idSites%5B%5D=36&idSites%5B%5D=37&idSites%5B%5D=38&idSites%5B%5D=39&idSites%5B%5D=40&idSites%5B%5D=41&idSites%5B%5D=42&idSites%5B%5D=43&idSites%5B%5D=44&idSites%5B%5D=45&idSites%5B%5D=68&idSites%5B%5D=70&idSites%5B%5D=76&idSites%5B%5D=79&idSites%5B%5D=80&idSites%5B%5D=81&idSites%5B%5D=82&idSites%5B%5D=83&idSites%5B%5D=92&idSites%5B%5D=93&idSites%5B%5D=94&idSites%5B%5D=95&idSites%5B%5D=96&idSites%5B%5D=97&idSites%5B%5D=98&idSites%5B%5D=99&idSites%5B%5D=100&idSites%5B%5D=101&idSites%5B%5D=102&idSites%5B%5D=103&idSites%5B%5D=104&idSites%5B%5D=105&idSites%5B%5D=106&idSites%5B%5D=107&idSites%5B%5D=108&idSites%5B%5D=109&idSites%5B%5D=110&idSites%5B%5D=111&idSites%5B%5D=112&idSites%5B%5D=113&idSites%5B%5D=114&idSites%5B%5D=115&idSites%5B%5D=116&idSites%5B%5D=117&idSites%5B%5D=118&idSites%5B%5D=119&idSites%5B%5D=120&idSites%5B%5D=121&idSites%5B%5D=122&idSites%5B%5D=123&idSites%5B%5D=124&idSites%5B%5D=133&idSites%5B%5D=134&idSites%5B%5D=135&idSites%5B%5D=136&idSites%5B%5D=137&idSites%5B%5D=138&idSites%5B%5D=139&idSites%5B%5D=140&idSites%5B%5D=141&idSites%5B%5D=142&idSites%5B%5D=143&idSites%5B%5D=144&idSites%5B%5D=145&idSites%5B%5D=146

**Comment by sgiehl** [comment] 2022-05-03 13:06
Does the confirmation box ask you if you want to give the access to `103` sites, or does that one already only mentions 100?

**Comment by Bedouille69** [comment] 2022-05-03 13:08
No count : 
![image](https://user-images.githubusercontent.com/8983084/166458547-c6dddf2f-d5d1-4328-9397-e7f20b6b9109.png)

The "forgotten" sites are always the same (The 3 last created)

**Comment by sgiehl** [comment] 2022-05-03 13:30
Ah sorry. I thought you were talking about giving access when selecting websites in the lower area. There it is possible to select more than 100 sites. When using the part in the top it seems it first fetches the available sites and then sets access for all sites received. Guess the first request is silently limited to 100. Will quickly check that and provide a fix if possible

**Comment by Bedouille69** [comment] 2022-05-03 13:33
It would be great because I will have between 350 and 400 sites in production.(I work for the university of Liège in Belgium)

Thanks :)

**Comment by sgiehl** [comment] 2022-05-03 13:34
It will take till Matomo 4.11.0 until this will be included. But as a workaround you can simply use the bulk edit in the lower part. That should allow to set permission for all sites.

**Comment by Bedouille69** [comment] 2022-05-03 13:38
Thanks. I didn't see that the bulk edit was permitting other things than filtering so it's a great workaround 👍

**Closed as completed** 2022-05-04 00:42 UTC
Labels: Bug
