### ISSUE TITLE
Evolution graph in acquisitions overview not showing data

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#21051] opened 2023-07-22 04:41 UTC
See below screenshot on latest 4.X beta where it shows no data and metric names contain a `%20`.

<img width="1697" alt="image" src="https://github.com/matomo-org/matomo/assets/273120/24cc3cd7-a003-4a9b-939e-ffb237d1adfd">

The metrics to plot looks like this:

<img width="408" alt="image" src="https://github.com/matomo-org/matomo/assets/273120/6f7790e7-8522-4325-9cc0-ef521e35999b">

Once I click on one of the sparklines, it does show data and also shows the metric names correctly. 
<img width="299" alt="image" src="https://github.com/matomo-org/matomo/assets/273120/6f2cce02-d50d-4b29-a2bc-3903e9b4d1d0">

I can't reproduce it on the demo. Not sure if there was maybe any change around the saved datatable parameters or so.

**Comment by sgiehl** [comment] 2023-07-24 08:36
I'm able to reproduce that locally and on the demo as well. We run a `encodeURIComponent` on all rows before they are stored as data table params (See https://github.com/matomo-org/matomo/blob/5.x-dev/plugins/CoreVisualizations/javascripts/seriesPicker.js#L108). Guess that maybe isn't reverted before it's used. 
Not sure if simply removing that `encodeURIComponent` might cause other implications.

**Comment by michalkleiner** [comment] 2023-07-24 13:17
Related to or a duplicate of #20635.

**Comment by tsteur** [comment] 2023-07-25 14:56
Isn't this a regression maybe? I'm pretty sure this used to work

**Comment by sgiehl** [comment] 2023-07-28 12:06
Yes. This might be a regression of the migration to vue.js

**Comment by sgiehl** [comment] 2023-08-22 12:50
While checking this one again it turned out, that there actually also is another i18n related issue around evolution charts. If I e.g. configure that chart to show "Search Engines" and "Websites" and then change my language to German, the chart won't show any data was well. As for German there are no records "Search Engines" or "Websites". They are localized to "Suchmaschinen" and "Webseiten". So we might also need to think about storing the internal name and only showing the translation or something similar.

**Closed as completed** 2023-09-04 18:02 UTC
Labels: Bug, Regression
