### ISSUE TITLE
System Check says to delete vendor/szymach/c-pchart/app; doing so breaks Piwik

### ISSUE THREAD

**Issue by GreenReaper** [piwik/piwik#11978] opened 2017-08-27 15:45 UTC
The System Check reported:
```
Directories were found in your Piwik but we didn't expect them.
--> Please delete these directories to prevent errors. <--

Directory to delete: vendor/szymach/c-pchart/app


To delete all these directories at once, you can run this command:
rm -Rf /home/harmony-prod/html/piwik/vendor/szymach/c-pchart/app
```

However, I did so, and then it started warning me about missing files inside this directory.
After an Apache restart, Piwik failed to load completely:
```
PHP Warning: require([censored]/piwik/vendor/composer/../szymach/c-pchart/src/Resources/data/constants.php): failed to open stream: No such file or directory in [censored]/piwik/vendor/composer/autoload_real.php on line 70
PHP Fatal error:  require(): Failed opening required '[censored]/piwik/vendor/composer/../szymach/c-pchart/src/Resources/data/constants.php' (include_path='[censored]/piwik/vendor/pear/pear_exception:[censored]/html/piwik/vendor/pear/console_getopt:[censored]/piwik/vendor/pear/pear-core-minimal/src:[censored]/piwik/vendor/pear/archive_tar:.:/usr/share/php:/usr/share/pear') in [censored]/piwik/vendor/composer/autoload_real.php on line 70
```
Reinstalling from the build's tar.gz resulted in a resumption of the initial System Check warning.

I am on Piwik 3.0.5-b2 on Debian jessie with PHP 5.6.30-0+deb8u1 and a backport of Apache 2.4.25.

**Comment by Findus23** [comment] 2017-08-27 16:12
Seems like a false alarm.

The folder `vendor/szymach/c-pchart/app` is included in the latest build.zip (even though it seems to only include a cache file)
```
app
└── cache
    ├── cache.db
    └── index.db
```

**Comment by sgiehl** [comment] 2017-08-30 18:11
The problem is, that those files aren't listed in the `manifest.inc.php`. Will check why this is the case

**Comment by sgiehl** [comment] 2017-08-30 18:18
Ok. Those files aren't included in the build zip, but seems that they might be created under some circumstances. Guess we should exclude them from integrity check.

**Comment by s1awa** [comment] 2017-09-12 02:08
@mattab @sgiehl 

I just upgraded two server to Piwik 3.1.0

And this comes up in System Check

```
Directories were found in your Piwik but we didn't expect them.
--> Please delete these directories to prevent errors. <--

Directory to delete: vendor/szymach/c-pchart/app


To delete all these directories at once, you can run this command:
rm -Rf /var/www/example.com/vendor/szymach/c-pchart/app
```

**Comment by goodspeedal** [comment] 2017-09-12 02:33
Same here, @s1awa , update to Piwik 3.1.0 (I am using bitnami AWS build).
Got the same message in system check.

**Comment by mmilano** [comment] 2017-09-15 07:23
if one has gone and deleted these directories (following what the app says),
and there is no backup to restore from,
what can be done to manually restore the files from the piwik install?

**Comment by mattab** [comment] 2017-09-18 01:00
@mmilano it should be safe to delete this directory `vendor/szymach/c-pchart/app` and don't think you'd need to restore it from backup, or did you experience some problem after deleting it? 

Otherwise you can simply re-download Piwik and reupload those files from the piwik ZIP

**Comment by mattab** [comment] 2017-09-18 01:08
Should be fixed in https://github.com/piwik/piwik/pull/12060

Could you try upgrading to 3.1.1-b2 and you shouldn't see this integrity message anymore?

**Closed** 2017-09-18 01:08 UTC
Labels: Bug, duplicate, Task
