### ISSUE TITLE
Javascript error "Cannot read property 'left' of undefined" in Piwik 2.13.1

### ISSUE THREAD

**Issue by splinter89** [piwik/piwik#8063] opened 2015-06-08 13:32 UTC
Hi!
The mentioned error occurs on [this line](https://github.com/piwik/piwik/blob/2.13.1/plugins/Annotations/javascripts/annotations.js#L579):
```
canvas.position().left
```
I wasn't able to trace conditions which lead to this error though, because breakpoints on minified JS are not very useful.

Maybe someone can fix it?

**Comment by mattab** [comment] 2015-06-10 03:32
Hi @splinter89 

thanks for the report. we'll take a look

**Comment by mattab** [comment] 2015-06-10 03:33
@splinter89 can you reproduce this issue on the demo.piwik.org as well? which browser do you use?

**Comment by splinter89** [comment] 2015-06-11 08:14
I get this error in Chrome 43.0.2357.124 m.
Also Firefox 38.0.5 shows "TypeError: canvas.position(...) is undefined"

Ok, I have found that my simple custom plugin is the reason.
But graph is rendered automatically by Piwik, so I don't see how this plugin could cause that. However, if it's the case, I am sorry for taking your time.

Anyway, maybe this would help:

```php
class OurCompany extends Plugin
{
    public function postLoad()
    {
        WidgetsList::add('OurCompany widgets', 'Banners', 'OurCompany', 'bannersGraph');
    }
}

class Controller extends \Piwik\Plugin\Controller
{
    public function bannersGraph()
    {
        $view = new View('@OurCompany/banners');
        $this->setPeriodVariablesView($view);
        $view->bannersGraph = $this->getBannersGraph(['page1', 'page2']);
        return $view->render();
    }

    public function getBannersGraph(array $defaultColumns = [])
    {
        $columns = Common::getRequestVar('columns', false);
        if (false !== $columns) {
            $columns = Piwik::getArrayFromApiParameter($columns);
        }

        $view = $this->getLastUnitGraphAcrossPlugins(
            $this->pluginName,
            __FUNCTION__,
            $columns,
            $defaultColumns,
            false,
            'OurCompany.getBannersEvolution'
        );
        $view->requestConfig->disable_generic_filters = true; // do not sort

        if (empty($view->config->columns_to_display) && !empty($defaultColumns)) {
            $view->config->columns_to_display = $defaultColumns;
        }

        return $this->renderView($view);
    }
}

class API extends \Piwik\Plugin\API
{
    public function getBannersEvolution($idSite, $period, $date, $segment = false)
    {
        $data = [/*...*/]; // sorted manually
        return DataTable::makeFromIndexedArray($data);
    }
}
```

and simple "banners.twig"
```html
{{ bannersGraph|raw }}
```

**Comment by mattab** [comment] 2015-07-15 07:41
> Ok, I have found that my simple custom plugin is the reason.

Since it's not a bug in Piwik core, i'm closing. We plan to improve the Platform  & APIs around displaying reports, graphs, in the future, so hopefully such issue would be fixed. if this bug is blocking you or breaking your Piwik we could maybe re-open the issue

**Closed** 2015-07-15 07:46 UTC
Labels: answered, Bug
