### ISSUE TITLE
@CoreUpdater/runUpdaterAndExit_welcome.twig" at line 8.

### ISSUE THREAD

**Issue by thE-iNviNciblE** [piwik/piwik#11051] opened 2016-12-20 05:06 UTC
Hello, 
after Update -> runs to Server Error 500, after refresh piwik system said: 

"An exception has been thrown during the rendering of a template (".native-select is undefined: failed at `.native-select();` line: 3924") in "@CoreUpdater/runUpdaterAndExit_welcome.twig" at line 8."

How to fix this bug.

**Comment by lesaff** [comment] 2016-12-20 23:49
I am getting similar error after upgrade attempt

```
An exception has been thrown during the rendering of a template (".form-description is undefined: failed at `.form-description;` line: 6302") in "@CoreUpdater/runUpdaterAndExit_welcome.twig" at line 8.
```

**Comment by lesaff** [comment] 2016-12-21 00:09
Solved my issue by doing the following
- run `composer update`
- remove InterSites plugin

**Comment by mattab** [comment] 2016-12-26 02:35
Closing as this issue is caused by third party plugins.

Note: In the next Piwik version when such errors will occur, the safe mode will be displayed which will make it easier for you to deactivate plugins: https://github.com/piwik/piwik/pull/11083

**Closed by mattab** 2016-12-26 02:35 UTC

**Comment by thE-iNviNciblE** [comment] 2016-12-27 14:29
i can't find the "InterSites" Plugin, i had deleted the whole folder without "/config". 
Reupload it from *.zip and update piwik to 3.0.0 it works :-)

**Comment by brandtOSS** [comment] 2016-12-27 15:48
Had the issue as well.
Went to [piwik]/plugins and renamed the folder "InterSites" to "Old_InterSites", then proceeded with the update.

All good as it seems!
