### ISSUE TITLE
Some periods may not be archived at all

### ISSUE THREAD

**Issue by quba** [piwik/piwik#9468] opened 2016-01-04 16:10 UTC
In one of recent Piwik versions, a feature was introduced that checks if there are visits for given site ID between now and last archiving time, e.g. 
`- tracking data found for website id 52 (between 2016-01-04 00:36:23 and 2016-01-04 02:35:47)`

But in case a site tracked visits only for a short period of time, it's possible that archiving won't run for a period bigger than day and this will lead to empty archives after those temporary are deleted. 

I remember that in the past there was also a check that forced archiving for sites that reached midnight in their timezone. Currently it seems like this check is missing.

**Comment by mattab** [comment] 2016-01-15 01:15
Hi @quba thanks for the report. Do you maybe have an idea how to reproduce this issue?

**Comment by quba** [comment] 2016-01-15 10:08
E.g. track a few visit today some time, e.g. 4 p.m. and then stop tracking. There temporary archives will be purged tomorrow and no archiving will start tomorrow as there won't be new visits between last archiving and tomorrow.

**Comment by quba** [comment] 2016-03-14 18:10
Reoccured today. The workaround is to add `--force-all-websites` parameter to the archiving script.

**Comment by tsteur** [comment] 2016-04-07 20:54
Do you maybe have the log output of that archiving?

**Comment by tsteur** [comment] 2016-04-07 20:58
Also are there multiple archiver running at the same time?

**Comment by tsteur** [comment] 2016-04-07 21:00
Can you also post all options that are used to run the archiver?

**Comment by quba** [comment] 2016-04-07 21:05
>I remember that in the past there was also a check that forced archiving for sites that reached midnight in their timezone. Currently, it seems like this check is missing.

Everything's fine with this archiving. Data is there, but only temporary archives (deleted after some period of time). If after midnight there are no new visits, there's no possibility to run archiving and to create valid archives.

**Comment by tsteur** [comment] 2016-04-07 21:20
Can you answer the other question? There are still checks whether a website has been processed since midnight but thinking it could be eg related to having multiple archives running at the same time.

**Comment by tsteur** [comment] 2016-04-07 22:12
I couldn't really reproduce it so far I would say but it's hard to reproduce in general. I basically set the time when what ran etc hard in the code to reproduce it a bit more easily. 

The only thing I noticed is that https://github.com/piwik/piwik/blame/2.16.0/core/CronArchive.php#L1219 here the `array_diff` should be maybe an `array_intersect`. `$websiteDayHasFinishedSinceLastRun` returns a list of all websites that have finished since last run. In my example all websites were finished since last run so `$websiteDayHasFinishedSinceLastRun = array(1,2,3, ..., 100);`. I wanted to archive all websites so `$websiteIds = array(1,2,3,..., 100);`. The diff was an empty array and it resulted in `$this->websiteDayHasFinishedSinceLastRun = array()` but I believe it should have been `$this->websiteDayHasFinishedSinceLastRun = array(1,2,3,..., 100);`. Not sure if the current behaviour is expected or not. I will try to make this change and see what the tests say. If this is buggy, quite a lot should actually change in terms of what will be reprocessed when...

**Comment by mattab** [comment] 2016-04-08 00:55
> The only thing I noticed is that https://github.com/piwik/piwik/blame/2.16.0/core/CronArchive.php#L1219 here the array_diff should be maybe an array_intersect

Great find Thomas. Bug was here since the beginning 4+ years ago https://github.com/piwik/piwik/commit/0508f2c54f9609135927d6ac8f4e9f1032040c1e

**Comment by tsteur** [comment] 2016-04-08 01:59
I issued a PR. Possible that it fixes the issue but not 100% sure

**Comment by quba** [comment] 2016-04-08 07:35
> Can you answer the other question?
Which one? I don't have access to archiving logs. There's only one archiving process. Minimum set of options.

Just to make sure, I'll try to write down the use case (to confirm that this bug fix will cover this one).

- (archiving) no visits for siteID 1 - archiving skipped
- new visit for siteID 1
- (archiving) new visits for siteID 1 - archiving done, visits visible on graphs, archives marked as temporary (not closed period)
- (archiving) no visits for siteID 1 - archiving skipped
- (archiving) no visits for siteID 1 - archiving skipped
- midnight
- (archiving) no visits for siteID 1 - archiving skipped, scheduled task removes temporary archives
- no visits on graphs for the previous day

**Comment by tsteur** [comment] 2016-04-08 08:54
I was especially wondering whether there are multiple archivers running at the same time. The description sounds like the fix in #10022 might help

**Comment by quba** [comment] 2016-04-11 07:42
> Great find Thomas. Bug was here since the beginning 4+ years ago 0508f2c

I can see that it's merged now. If it was there since the beginning, maybe it's worth adding a test to not regress?

**Comment by quba** [comment] 2016-04-11 07:45
Additionally, change was merged, not added to the changelog, available in 2.16.1. I think I don't get it really..

**Comment by mattab** [comment] 2016-04-11 07:55
@quba sorry we simply forgot to close this issue which should now be fixed! 

Yes we should add a test. we discussed it on friday and decided the CronArchiver should be refactored to allow easier testing. In general, this code needs some love and a set of tests. I'll create an issue and ref this one.

**Closed by mattab** 2016-04-11 07:55 UTC
Labels: Bug

**Comment by mattab** [comment] 2016-04-11 07:57
just added `#9468 Some periods may not be archived at all [by @tsteur]` to the changelog, thanks for the feedback!
