### ISSUE TITLE
Marketplace: Add possibility to FAQ tab (and other tabs) directly

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#9391] opened 2015-12-15 05:49 UTC
I had it quite a few times that I want to link to the FAQ page of a plugin like http://plugins.piwik.org/QueuedTracking#faq 

but it is not possible since the FAQ and other information is hidden behind a tab. It would be great if we could add eg `#faq` or `#support` and it would open the respective tab directly. So far I did not use a link or I linked to the GitHub Readme page instead which is not ideal. Eg in changelogs, in guides, etc it would be useful.

**Comment by mattab** [comment] 2015-12-22 02:58
Also had this need a few times, it would help :+1:

**Comment by mattab** [comment] 2016-08-16 23:54
The FAQ tab is now supported as you can see on the CustomDimensions plugin page: https://plugins.piwik.org/CustomDimensions

It was documented in: http://developer.piwik.org/guides/distributing-your-plugin#your-plugins-page

**Comment by mattab** [comment] 2016-08-16 23:54
Umh i misread. This issue is about adding #hashtag to tabs in plugin pages. Marking as duplicate of our internal issue

**Closed by mattab** 2016-08-16 23:54 UTC
Labels: c: Marketplace, Enhancement
