### ISSUE TITLE
Visits Log incorrectly represents external link containing apostrophe

### ISSUE THREAD

**Issue by rlizzi** [piwik/piwik#18190] opened 2021-10-20 14:03 UTC
Below is the Visits Log showing my visit to this page:  https://www.gooutsidebook.com/articles/east-rock-soldiers-and-sailors-monument-moon.html

![Visits Log Bug](https://user-images.githubusercontent.com/14956603/138108691-501b314c-905c-4bab-ab71-524b724f2c02.png)

The external link to the Wikipedia page is incorrect, and following the link leads to the wrong page.

The correct link is:  https://en.wikipedia.org/wiki/Soldiers'_and_Sailors'_Monument_(New_Haven)

The apostrophes in the link are mishandled.

**Comment by bx80** [comment] 2021-10-20 20:09
Hi @rlizzi, thanks for creating this issue. I've managed to recreate the problem, it looks like an encoding bug with the way external links are displayed.

**Comment by tsteur** [comment] 2021-10-20 20:13
Hi @rlizzi thanks for reporting this. I'll close this as a duplicate of https://github.com/matomo-org/matomo/issues/14695 . We're actually already working on a fix.

**Closed as completed by tsteur** 2021-10-20 20:13 UTC
Labels: duplicate
