### ISSUE TITLE
[Bug] MySQL Update to 5.0.0: The storage engine for the table doesn't support descending indexes

### ISSUE THREAD

**Issue by Suplanus** [piwik/piwik#21729] opened 2023-12-21 06:20 UTC
### What happened?

Updates failes with error.

### What should happen?

Update to 5.0.0

### How can this be reproduced?

- MySQL: 8.0.35-0ubuntu0.22.04.1
- Update to Matomo 5.0.0

### Matomo version

4.16.0

### Relevant log output

```shell
Executing ALTER TABLE `piwik_log_visit` ADD INDEX `index_idsite_idvisitor_time` (`idsite`, `idvisitor`, `visit_last_action_time` DESC);...
    [X] Critical Error during the update process:

    * /var/www/html/matomo-01/core/Updates/5.0.0-b1.php:
    Error trying to execute the migration 'ALTER TABLE `piwik_log_visit` ADD INDEX `index_idsite_idvisitor_time` (`idsite`, `idvisitor`, `visit_last_action_time` DESC);'.
    The error was: SQLSTATE[42000]: Syntax error or access violation: 1178 The storage engine for the table doesn't support descending indexes
```
```


### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by michalkleiner** [comment] 2023-12-21 10:15
Hi @Suplanus, it looks like you might be using MyISAM engine for your database, can you confirm that's the case? The descending index is only supported by the InnoDB storage engine from MySQL 8 (and the `DESC` in an index definition was ignored on older versions).

**Comment by Suplanus** [comment] 2023-12-21 12:28
> it looks like you might be using MyISAM engine for your database, can you confirm that's the case?

Yes. Its an very very old PIWIK instance which was converted several times into the new world.

---

**Fix for the issue**
I fixed it selecting all tables which have MyISAM:
https://stackoverflow.com/a/30648414/3559353

Then I converted each table (line by line of the output).

Double checked if all tables are converted.

Then I have done the update in the Web-GUI and executed:
```
php /var/www/html/matomo-01/console core:update
```
Without any errors this time.

---

All looks good. Thank you for the hint!
Should this fix perhaps in the upgrade process of Matomo? I leave this issue open for clearing this :)

**Comment by michalkleiner** [comment] 2023-12-21 12:53
I don't have a strong preference here, but I don't think we could/should automatically change db engine during an upgrade.
Perhaps we can add a note to https://matomo.org/faq/on-premise/matomo-requirements/.

What do you think, @sgiehl? If there are no extra thoughts, we can close this as resolved.

**Comment by sgiehl** [comment] 2023-12-21 13:40
Automatically converting the tables could cause problems for bigger instances maybe. Innodb is default since #4611 and thus Matomo 2.1, which is around 9 years old.
In theory I guess we still support MyISAM, as it's still possible to configure that. So maybe we would need to change the update script, so it doesn't try to use a desc index if it's not supported.
@tsteur What do you think on that one? Should we "drop" support for MyISAM and force people to change to InnoDB?

**Comment by tsteur** [comment] 2023-12-21 19:15
Do we have any data on usage of MyISAM? 

If the only issue is the "Desc" and everything works well otherwise, I would add a quick check to see if it's MyISAM and then not define the "DESC". Like @sgiehl mentions.

The effort is extremely low, but the impact can be quite big for users. I would assume there's quite a number of MyISAM users out there and in some cases it may be working faster for them.

Like @sgiehl  mentions changing DB engine during an upgrade wouldn't be recommended as in worst case it may take days to upgrade and such upgrades need to be planned carefully. There may be also odd setups where InnoDB is not available or are other issues.

Maybe some "non-log tables" we could migrate automatically if we break support for MyISAM for a specific table in the future. 

We could consider declaring MyISAM as deprecated and recommend changing to InnoDB saying the support will be removed in the future and we recommend migrating to InnoDB ASAP. This could be put in a blog or FAQ with some instructions on how to do it. As part of this doc we may also want to recommend updating the above changed index (to get the performance improvement of the `DESC`).

For people to become more aware of this deprecation we could eg show a warning in https://github.com/matomo-org/matomo/blob/5.x-dev/plugins/CoreUpdater/tests/UI/expected-screenshots/CoreUpdaterDb_main.png or https://github.com/matomo-org/matomo/blob/5.x-dev/plugins/CoreUpdater/tests/UI/expected-screenshots/CoreUpdaterDb_updated.png but this gets easily lost in the amount of content there. Or similar to outdated PHP warning we could show a deprecation notice to super users in the admin. Or there may be other things.

Before declaring it as deprecated, I highly recommend reaching out to our Enterprise support team to see if they are aware of MyISAM users and learn more about it just to make sure we're not missing anything important. This way we could get some data maybe.

In the meantime we could make the upgrade work smoothly by removing the `DESC`

**Comment by seraphyn** [comment] 2023-12-21 22:48
1. Make a dump of your Database
mysqldump -h HOST  -u USER -p --databases DATABASE > transformation.sql
2. Change the type
sed -e 's/ENGINE=MyISAM/ENGINE=InnoDB/g' transformation.sql > newsqlfile.sql
3. Import SQL-File
mysql -h HOST  -u USER -p --databases DATABASE < newsqlfile.sql

Upgrade

Keep a Backup of your file and DB

Merry Christmase

**Comment by sgiehl** [comment] 2023-12-22 16:10
This could actually be a problem with MySQL 8 and MyISAM tables only. Using such a command with e.g. MySQL 5.7 and a MyISAM table works without problems.. Before MySQL 8, the descending order was simply ignored, as no engine supported it. Now only InnoDB supports it. Don't have a MySQL 8 set up atm, but might be possible that error only occurs there...

**Closed as completed** 2024-01-02 09:23 UTC
Labels: not-in-changelog, Regression

**Comment by MatomoForumNotifications** [comment] 2024-01-04 10:56
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/cannot-upgrade-from-4-16-0-to-5-0-0-the-storage-engine-for-the-table-doesn-t-support-descending-indexes/54498/7

**Comment by atom-box** [comment] 2024-04-18 15:37
Possible regression in 5.0.3? On April 15, 2024, a user reported this same error. Their details:
- updating from 4.16 to 5.0.3
- using **InnoDB**
- failure of core:update*
- success when they tried it again, with the DESC removed from the SQL statement

*Here is the query that failed:
`ALTER TABLE `matomo_log_visit` ADD INDEX `index_idsite_idvisitor_time` (`idsite`, `idvisitor`, `visit_last_action_time` DESC);`

Here is the query that succeeded: 
ALTER TABLE `matomo_log_visit` ADD INDEX `index_idsite_idvisitor_time` (`idsite`, `idvisitor`, `visit_last_action_time`);
