### ISSUE TITLE
segment filter with 2 action types (and) not working

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#9709] opened 2016-02-04 15:08 UTC
Just wanted to find (filter) visits with two types of actions ("download" and "event") included.
No visits were found.

When segmenting only action type "download"
there were results
and within these results were lots of visits with events

same when segmenting only action type "event"
there were results
and within these results were lots of visits with downloads

Between the results of them are definitively some of the same visits shown => so also combined filter should find them.

![2016-02-04_16h02_28](https://cloud.githubusercontent.com/assets/5681880/12819003/7a868fcc-cb59-11e5-9aed-9866d493ecfb.png)

![2016-02-04_16h01_54](https://cloud.githubusercontent.com/assets/5681880/12819009/85a976ee-cb59-11e5-9c69-c5ed1aa24280.png)

**Comment by tsteur** [comment] 2016-02-04 19:33
I'll mark this one as a duplicate of https://github.com/piwik/piwik/issues/7533 (and https://github.com/piwik/piwik/issues/7177)

**Closed by tsteur** 2016-02-04 19:33 UTC
