### ISSUE TITLE
Campaign metrics are in some widgets too low

### ISSUE THREAD

**Issue by davidplewa** [piwik/piwik#16939] opened 2020-12-11 21:04 UTC
In "acquisition" > "all channels" metrics show up correctly. I.e. "facette2020beitrag" sums up to 2.688 visits from Dec 1st - Dec 10th.

BUT:  In "acquisition" > "campaigns" all metrics show up too low. I.e. "facette2020beitrag" sums up to 36 visits from Dec 1st - Dec 10th.
If you click here on the green icon (translation from german you be s.th. like "open line development"), then the values in the lightbox are shown up correctly.

Please see attached screens.
![2020-12-11_14-52-09](https://user-images.githubusercontent.com/75847226/101954692-d2d67700-3bfc-11eb-8a94-49408e819588.jpg)
![2020-12-11_14-52-18](https://user-images.githubusercontent.com/75847226/101954697-d669fe00-3bfc-11eb-8b70-7e7f96f72883.jpg)
![2020-12-11_21-56-25](https://user-images.githubusercontent.com/75847226/101954703-d964ee80-3bfc-11eb-93b4-eb17120b04aa.jpg)

**Comment by Chardonneaur** [comment] 2021-03-19 17:35
Hi @davidplewa 
I am facing exactly the same issue for a client of mine.
What I noticed is this, for the all channels report, when I click on the campaign visit segmented log, the campaign name is absent for some of them.
So it is like it was there... and then it has been deleted.
![Screenshot from 2021-03-19 18-32-56](https://user-images.githubusercontent.com/28002238/111820422-c475b680-88e1-11eb-9f32-4be12a8a113f.png)

**Comment by diosmosis** [comment] 2021-03-21 21:09
Hi @Chardonneaur, can't reproduce this myself (and it sounds like it could be unrelated to the original issue)... would you be able to check in the normal visitor log whether some of the visits that don't have the campaign in the segmented visitor log look like that as well? I'm wondering if the segmented visitor log is selecting the wrong data in this case or if there's something wrong w/ the visits themselves.

**Comment by Chardonneaur** [comment] 2021-03-22 17:45
Hi @diosmosis 
thank you very much for your answer, it feels good to be supported.
Here are the figures:
For a given day,
Within the Visit log:
7 visits which have a campaign name
Within the channel type for campaign:
7 visits but when I click on the segmented visit log only 3 of them have a campaign name (so they lost the campaign name for some reasons but are still considered as campaign)
Within the campaign report:
3 visits

**Comment by diosmosis** [comment] 2021-03-23 00:02
@Chardonneaur is this user using the MarketingCampaignReporting plugin? Can you provide a screenshot of the campaign report where it has 3 visits? And would it be possible to get access to the matomo instance to further see what's wrong? (If so, email dizzy@innocraft.com)

**Comment by Chardonneaur** [comment] 2021-04-22 14:02
I saw another case today on a different client of mine, for which the traffic is listed in campaign name, but when you click on the visit log associated to the campaign name, all the visits have the campaign name stripped out. As a result segments are not working.

**Comment by mattab** [comment] 2023-05-15 10:48
Thanks for contributing to this issue. As it has been a few months since the last activity and we believe this is likely not an issue anymore, we will now close this. If that's not the case, please do feel free to either reopen this issue or [open a new one](https://developer.matomo.org/guides/core-team-workflow#submitting-a-bug-report). We will gladly take a look again!

**Closed as not planned by mattab** 2023-05-15 10:48 UTC
Labels: wontfix
