### ISSUE TITLE
/misc/cron/archive.php crontab is regressed  Class 'Piwik\Common' not found

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#7900] opened 2015-05-13 22:56 UTC
Demo2 has regressed, running the cron via misc/cron/archive.php is erroring:

```
$ php /home/piwik-demo2/www/misc/cron/archive.php --url=http://demo2.piwik.org

-------------------------------------------------------
Using this 'archive.php' script is no longer recommended.
Please use '/path/to/php /home/piwik-demo2/www/console core:archive --url=http://demo2.piwik.org' instead.
To get help use '/path/to/php /home/piwik-demo2/www/console core:archive --help'
See also: http://piwik.org/docs/setup-auto-archiving/

If you cannot use the console because it requires CLI
try 'php archive.php --url=http://your.piwik/path'
-------------------------------------------------------

Fatal error: Class 'Piwik\Common' not found in /home/piwik-demo2/www/misc/cron/archive.php on line 44
```

we added tests earlier to prevent the regression, we need to check why those tests didn't work to catch this regression

cc  @diosmosis

**Comment by diosmosis** [comment] 2015-05-14 01:35
This bug wasn't caught because ArchiveWebTest uses the proxy archive.php script, which includes the autoloader before the actual archive.php script. I might be able to fix this in my DI branch.

**Comment by mattab** [comment] 2015-05-14 07:09
it makes sense, feel free to close the issue as it looks fixed

**Comment by diosmosis** [comment] 2015-05-14 07:39
The issue is fixed, but tests won't catch it yet, I'll close after they detect it. Which will be after my other DI branch is done.

**Comment by mattab** [comment] 2015-06-16 02:45
> The issue is fixed, but tests won't catch it yet, I'll close after they detect it. Which will be after my other DI branch is done.

@diosmosis what is status, now that DI branch was merged, maybe this could be closed?

**Comment by diosmosis** [comment] 2015-06-16 03:58
Actually found an easier way to test for this, will close this soon.

**Closed** 2015-06-16 04:12 UTC
Labels: Bug, not-in-changelog

**Comment by mattab** [comment] 2015-06-16 07:33
:+1:
