### ISSUE TITLE
[Bug] Total Revenue chart empty when using date comparison 

### ISSUE THREAD

**Issue by goochj03** [piwik/piwik#21921] opened 2024-02-12 21:47 UTC
### What happened?

When using the comparison option from the date picker, the Total Revenue metric displays no data for the eCommerce > Overview graph. The other metrics display fine.

### What should happen?

The chart should show the Total Revenue data as the other metrics do when comparing dates.

### How can this be reproduced?

Change the date picker to a date to compare for the eCommerce > Overview chart. This can be any date comparison week, month etc This can also be reproduced on the demo version of Matomo.
![image](https://github.com/matomo-org/matomo/assets/118518962/61c0c8c6-a085-483c-874f-ca1216fa87f4)

### Matomo version

Matomo Cloud

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment] 2024-02-13 09:29
most likely a duplicate of #19933 or #15349

**Comment by michalkleiner** [comment] 2024-02-21 10:25
Thanks for the report @goochj03. I'll close this as duplicate of #19933 but if you feel strongly it's a different issue then let us know and we'll consider reopening it.

**Closed as completed by michalkleiner** 2024-02-21 10:25 UTC
Labels: duplicate
