### ISSUE TITLE
matomo robots.txt

### ISSUE THREAD

**Issue by matomoto** [piwik/piwik#20403] opened 2023-02-28 10:22 UTC
There is a trouble with the robots.txt

The current robots.txt
```
User-agent: Googlebot
User-agent: AdsBot-Google
User-agent: AdsBot-Google-Mobile
User-agent: AdsBot-Google-Mobile-Apps
User-agent: Google Favicon
User-agent: Googlebot-News
User-agent: Googlebot-Image
User-agent: Googlebot-Video
User-agent: Mediapartners-Google
User-agent: APIs-Google
User-agent: DuplexWeb-Google
User-agent: Bingbot
User-agent: Slurp
User-agent: DuckDuckBot
User-agent: Baiduspider
User-agent: AhrefsBot
User-agent: rogerbot
User-agent: YandexBot
User-agent: DotBot
User-agent: Twitterbot
User-agent: BingPreview
User-agent: LinkedInBot
User-agent: Yandexbot
User-agent: facebot
User-agent: facebookexternalhit
User-agent: MSNBot
User-agent: MSNBot-Media
Disallow: /
Allow: /matomo.php
Allow: /piwik.php
Allow: /matomo.js
Allow: /piwik.js
Allow: /js/
```

The FAQ
**How do I make sure Search engines robots do not index Matomo server?**
```
User-agent: *
Disallow: /
```
Googles documentation for this:

> Note: This does not match the various AdsBot crawlers, which must be named explicitly.

https://developers.google.com/search/docs/crawling-indexing/robots/create-robots-txt

**The questions:**

- why are all other bots and crawler and spiders not disallowed in the current robots.txt?
- why are files allowed in the current robots.txt?

Please answer.

Suggestion:
- add `User-agent: *`
- remove `Allow`.
```
User-agent: *
User-agent: Googlebot
User-agent: AdsBot-Google
User-agent: AdsBot-Google-Mobile
User-agent: AdsBot-Google-Mobile-Apps
User-agent: Google Favicon
User-agent: Googlebot-News
User-agent: Googlebot-Image
User-agent: Googlebot-Video
User-agent: Mediapartners-Google
User-agent: APIs-Google
User-agent: DuplexWeb-Google
User-agent: Bingbot
User-agent: Slurp
User-agent: DuckDuckBot
User-agent: Baiduspider
User-agent: AhrefsBot
User-agent: rogerbot
User-agent: YandexBot
User-agent: DotBot
User-agent: Twitterbot
User-agent: BingPreview
User-agent: LinkedInBot
User-agent: Yandexbot
User-agent: facebot
User-agent: facebookexternalhit
User-agent: MSNBot
User-agent: MSNBot-Media
Disallow: /
```

**Comment by sgiehl** [comment] 2023-03-09 13:25
Hi @matomoto 
Allowing the tracker files was added on purpose, as some users are tracking bots on purpose.
Therefor we can't disallow all bots accessing the tracker endpoints. Nevertheless tracking requests from bots will be ignored by default.
Why we are using a named list of bots and don't use a wildcard is out of my knowledge. This might be something we could consider changing maybe.

**Comment by matomoto** [comment] 2023-03-10 12:30
OK about the files allowed.

By the using of an asterix "*" see the Link and the 

> Note: This does not match the various AdsBot crawlers, which must be named explicitly.

It is also OK, that the user agents are listed, but its maybe not OK why without asterix "*". Thats the question. The knowledge on my side is equally non-existent about this matter.

The other thing is the matomo documentation about this: 
https://matomo.org/faq/troubleshooting/faq_20966/
This information is not OK in reference to the **Note** above.

**Comment by MatomoForumNotifications** [comment] 2023-03-12 11:57
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/0-sekunden-aufenthaltsdauer-pro-url/49486/15

**Comment by matomoto** [comment] 2023-07-28 16:14
Hi @sgiehl 
> Allowing the tracker files was added on purpose, as some users are tracking bots on purpose.
Therefor we can't disallow all bots accessing the tracker endpoints. Nevertheless tracking requests from bots will be ignored by default.

I think, that is a big mistake.  An `Allow` or `Disallow` in the `robots.txt` don't forbidden bots the access / request of this files. In the `robots.txt` only a hint is given whether folders / files should be indexed by search engine robots. Bots can ignore that. So why should the files / pages specified under `Allow` be indexed by searchbots?
```
Allow: /matomo.php
Allow: /piwik.php
Allow: /matomo.js
Allow: /piwik.js
Allow: /js/
```
This files / pages have no relevant content for search engines.

Also a tracking of the accesses / requests of this files / pages is untouched by the specifications in the `robots.txt`, because in the `robots.txt` not accesses / requests are regulated (it's not the `htaccess`), but only the indexing.

**Comment by sgiehl** [comment] 2023-08-03 08:25
closing this one as duplicate of #21067, as being able to provide a custom robots.txt would solve the problem.

**Closed as completed by sgiehl** 2023-08-03 08:25 UTC
Labels: duplicate
