### ISSUE TITLE
[Enhancement] Apply segment / custom report to a custom group of sites

### ISSUE THREAD

**Issue by SW-Vincent** [piwik/piwik#20513] opened 2023-03-23 11:36 UTC
Apply segment / custom report to a custom group of sites instead of "this website" or "all websites".

## Summary

Currently, when defining a segment or a custom report it can be defined for a specific website or "all websites".
Applying a segment (or custom report) to all websites makes its management easier, but also makes it very quota-consuming.

As a reminder, matomo cloud plans usually contains 100 segments and 100 custom reports, and defining 1 segment for 10 websites counting as 10 segments.

Therefore, being able to manage segments and custom reports through custom groups would be really usefull for cloud users that are tracking several websites.
It would be nice to be able to chose between : 
 - apply to all website except custom selection
 - apply to custom selection

## Your Environment

* Matomo Version: Cloud

**Comment by sgiehl** [comment] 2023-03-23 16:18
Hi @SW-Vincent 
Thanks for your suggestion. It might indeed make sense to allow assigning multiple specific sites when creating segments or custom reports. But this actually might require some bigger changes to the UI (as the site selector currently doesn't allow to select multiple sites) and to the backend (as the siteid is stored directly in the database, allowing multiple sites might need another relation table or similar).
Anyway, our product team will consider this for future improvements.

**Comment by mattab** [comment] 2023-04-17 00:43
Thanks for your feedback! Marking as duplicate of https://github.com/matomo-org/matomo/issues/20972

**Closed as not planned by mattab** 2023-04-17 00:43 UTC
Labels: Enhancement, duplicate, c: Usability
