### ISSUE TITLE
Error on processing a date range on actions/pages on high traffic site (2.16.0)

### ISSUE THREAD

**Issue by patriiiiiiiiiick** [piwik/piwik#9851] opened 2016-02-25 15:37 UTC
When loading the following page with a high traffic site:

/piwik/index.php?module=CoreHome&action=index&idSite=37&period=range&date=2015-09-01,2016-02-24#?module=Actions&action=menuGetPageUrls&idSite=37&period=range&date=2015-09-01,2016-02-24

I get an error in the form "Oops… there was a problem during the request.".

I will enquire if there is an error in the log files.

**Comment by gaumondp** [comment] 2016-02-25 18:51
Define "High traffic".

One of my user got such "Oops" when using date range but I never got them myself, even with his account so in my case it looks suspiciously related to the client computer sometimes.

BTW, 3 millions pageviews/month is my "high traffic" Piwik installation.

**Comment by tsteur** [comment] 2016-02-25 19:53
> I will enquire if there is an error in the log files.

That would be good. Most likely it's due to not having enough memory. Increasing the memory will likely help.

**Comment by gaumondp** [comment] 2016-02-25 20:05
@tsteur , which memory are you asking ? PHP ? MySQL ?

I'm at roughly 1GB/4GB used for my Apache/PHP/Piwik server. And on my MySQL Server it's currently 6GB used over 12 GB.

I'm interfering in the discussion because I've seen the error only on few "normal" users computers (querying same server of course) but I never as Super Admin and with a different computer got such "Oops".

I'm still wondering why such bizarre difference would happen...Ajax related? Network related ? Virus-free computer? ;) Win 8.1 versus Windows 7 ?

**Comment by tsteur** [comment] 2016-02-25 20:27
I asked re PHP memory. 

There shouldn't be a difference between users I'd say. Maybe on other computers a different kind of segment was used or a larger date range? Or maybe it's just "by accident" in case it has only happened a few times that it happens on other computers but not on yours. There should be no difference between operating systems etc. It is hard to reproduce it as you would need to send the same request from two different computers. Problem is: Likely when the error occurred the first  time on a computer some data got maybe already archived and when you try it on another computer the problem is not there anymore since some data was already archived meanwhile (if browser archiving is enabled)

**Comment by patriiiiiiiiiick** [comment] 2016-02-26 13:24
It is on a site with about a million visits and page views.

I didn't spot any memory capacity issue.

I had the report that there was a "Maximum execution time of 30 seconds exceeded" and that it was extended to 90s and that it now works. Indeed it now works but I believe it’s something else (DB restart?) that made it work. It was most probably a temporary load issue. As far as I am concerned, I would just close the issue.

**Comment by tsteur** [comment] 2016-02-26 19:37
Thanks for letting us know. I will close the issue.

**Closed by tsteur** 2016-02-26 19:37 UTC
