### ISSUE TITLE
Visitors > Locations produces 500 error on POST for idSite=2

### ISSUE THREAD

**Issue by courtens** [piwik/piwik#19955] opened 2022-11-06 15:10 UTC
I have 5 sites in Matomo, but site ID 2 is always producing a 500 POST error on the page **_Visitors > Locations_**. 

![image](https://user-images.githubusercontent.com/27327453/200178313-a04cd2de-d3c0-4f67-87e5-07af8405b44e.png)

And, also, for almost always, on **_Dashboard > Visits in real-time_**

![image](https://user-images.githubusercontent.com/27327453/200177825-7ea33c73-c449-4d9b-b60d-7ad328e8abc5.png)

> Warning: the module=Live&action=widget&widget=1&disableLink=0&idSite=2&period=range request failed!

> Uncaught (in promise) 
Object { readyState: 4, getResponseHeader: getResponseHeader(a), getAllResponseHeaders: getAllResponseHeaders(), setRequestHeader: setRequestHeader(a, b), overrideMimeType: overrideMimeType(a), statusCode: statusCode(a), abort: abort(a), state: state(), always: always(), then: then(), … }

I did notice that  if I reduce the date range to fewer days: 
![image](https://user-images.githubusercontent.com/27327453/200178410-a5d6f94d-f453-4aaa-a7ba-e73dbc0be4da.png)

The error goes away on **_Visitors > Locations_**; but it is back, with a normal range; such as:

![image](https://user-images.githubusercontent.com/27327453/200178385-6fb3b679-6ed9-496f-aa05-ba272ef38b9f.png)

Please note that I am not getting this error with any of the other sites!

This link provides further information https://forum.matomo.org/t/oops-there-was-a-problem-during-the-request-failed-to-write-cache-file/47390/21

**Comment by peterhashair** [comment] 2022-11-06 20:43
@courtens I read the original forum, and it seems like this is caused by a tracking URL containing special/broken characters. It may be the same issue https://github.com/matomo-org/matomo/issues/18763

**Comment by MatomoForumNotifications** [comment] 2022-11-07 13:40
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/oops-there-was-a-problem-during-the-request-failed-to-write-cache-file/47390/22

**Comment by peterhashair** [comment] 2022-11-09 02:19
ping @sgiehl any suggestion on that one?

**Comment by sgiehl** [comment] 2022-11-10 10:54
I haven't read the forum post in detail. Might be helpful to get the exact response content of the failing request (if any) or maybe a error message from the error log. Otherwise it's hard making a guess where the problem is.

**Comment by courtens** [comment] 2022-11-21 23:44
Without chasing after error-logs I just ran across the use of a [Zero-width-space](https://en.wikipedia.org/wiki/Zero-width_space) (&amp;&#35;8203;) in the code. Maybe using such a character in the title is what is tripping out matomo.

**Comment by sgiehl** [comment] 2022-11-22 14:10
@courtens I've tested tracking a zero width space locally, and for me that works without issues. Visits log is showing the visit correctly.

**Comment by courtens** [comment] 2022-12-16 22:51
I found this in my error logs (not sure if it is related)

> [12-Dec-2022 16:26:24 UTC] [www.site.ch] Error in Matomo (tracker): Error query: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xC3' for column `piwik`.`piwik_log_link_visit_action`.`idpageview` at row 1 In query: INSERT INTO piwik_log_link_visit_action (idvisit, idsite, idvisitor, idaction_url, idaction_url_ref, idaction_name_ref, server_time, idpageview, pageview_position, time_spent_ref_action, time_dom_processing, time_network, time_server, time_transfer, idaction_name) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) Parameters: array (   0 => 303944,   1 => 2,   2 => '¿򰰡
> ÷',   3 => 85556,   4 => 85556,   5 => 52019,   6 => '2022-12-12 16:26:24',   7 => '1À§ç,   8 => 340,   9 => 1,   10 => 458,   11 => 0,   12 => 23,   13 => 1,   14 => 52019, )

and I am getting a lot of these:
>
[12-Dec-2022 17:09:23 UTC] [www.site.ch] Error in Matomo (tracker): Invalid idSite: '0'

Opening Visits Log I get
> Warning: the module=Live&format=html&forceView=1&viewDataTable=VisitorLog&action=getLastVisitsDetails&small=1&idSite=2&period=range&segment=&widget=&showtitle=1&random=9776 request failed!

**Comment by sgiehl** [comment] 2022-12-19 11:07
Hm. The first messages don't seem to be related to the visits log and the last message is not quite helpful.
Did you have a look at the global php / system error log or at the matomo error log (should be located in matomo/tmp/logs/matomo.log)? Maybe any log contains some additional information on the problem.

**Comment by courtens** [comment] 2022-12-19 20:36
it from matomo.log
> ERROR Piwik\FrontController[2022-12-19 20:34:26 UTC] [23e8e] Uncaught exception: F:\www\matomo\plugins\Live\templates\_actionCommon.twig(25): The string to escape is not a valid UTF-8 string. [Query: ?date=previous30&module=Live&format=html&forceView=1&viewDataTable=VisitorLog&action=getLastVisitsDetails&small=1&idSite=2&period=range&segment=&widget=&showtitle=1&random=1242, CLI mode: 0]

and also
> .... Live\templates\getLastVisitsStart.twig(76): The string to escape is not a valid UTF-8 string. [Query: ?date=2022-11-19,2022-12-18&module=Live&action=widget&widget=1&disableLink=0&idSite=2&period=range, CLI mode: 0]

**Comment by sgiehl** [comment] 2022-12-21 16:58
Ok. So it seems indeed to be the same problem as #18763. I will close this one as duplicate.
I'm actually not able to reproduce that issue locally. Even when trying to log unsupported characters.
Feel free to comment the other issue with some more details on your set up, maybe it only happens with a certain database or database version.

**Closed as not planned by sgiehl** 2022-12-21 16:58 UTC
Labels: answered, Waiting for user feedback
