### ISSUE TITLE
[Bug] Date range not avaliable for Scheduled Report downloads

### ISSUE THREAD

**Issue by goochj03** [piwik/piwik#21945] opened 2024-02-14 20:39 UTC
### What happened?

Setting a custom date range and trying to "download" an email report fails with the following message:

"Date format must be: YYYY-MM-DD, or 'today' or 'yesterday' or any keyword supported by the strtotime function (see http://php.net/strtotime for more information): '2024-02-01,2024-02-11'"

### What should happen?

The report should download based on the defined date range.

### How can this be reproduced?

Within any Cloud subscription create a scheduled report from Administration > Personal > Email Reports and set the date range from the date picker to a custom date. Attempt to download the report and the message will display.

Testing this on On-Premise the email report has downloaded for the date period correctly.

### Matomo version

Matomo Cloud

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by danavarmahmoodi** [comment] 2024-02-15 22:07
Our team's reporting is being affected by this bug for all of our clients' website reports that we deliver weekly. We are looking forward to this bug being fixed, thank you for working on this!

**Comment by atleduc** [comment] 2024-02-20 16:18
Same as https://github.com/matomo-org/matomo/issues/21903

**Comment by goochj03** [comment] 2024-02-21 07:28
Another customer today affected by this, wanting to use custom date ranges. “Attempting an immediate send results in the following error message: "Report period must be one of the following: day, week, month, year (got range)."“

**Comment by michalkleiner** [comment] 2024-02-21 09:57
I've tested this both on-premise and in cloud and the issue is in both places. It's likely there's a missing logic to split the range into two dates that would then get passed to the strtotime method for conversion to actual date/times.

**Comment by danavarmahmoodi** [comment] 2024-03-05 21:38
Hello everyone,

I'm reaching out to inquire about any recent updates or milestones achieved in resolving this bug? Your attention to this matter is greatly appreciated - thank you for your ongoing efforts!

**Comment by clintguy74** [comment] 2024-03-08 16:06
This is affecting, me as well, but not custom reports, for the simple monthly reports

**Comment by goochj03** [comment] 2024-03-20 19:47
Another customer affected by this issue today, asking for a fix.

**Comment by atom-box** [comment] 2024-03-21 13:56
Another customer today is being blocked in a major project for their client by this.

**Closed as completed** 2024-03-25 15:57 UTC
Labels: Bug, Regression, c: Dates & Calendar

**Comment by atom-box** [comment] 2024-03-26 01:01
I don't know if there is any way the following screenshot could be related but the same error message, popped up in a single table, even though it was a page where the other tables were all okay:

![image](https://github.com/matomo-org/matomo/assets/22874146/9fd77af8-2c49-488f-a11c-62d3862e9fc1)

Customer:

> _most of the tables were filtered as expected but I have an error message on the source-medium table within campaign reporting._

**Comment by paul-buttimore** [comment] 2024-04-24 00:27
another customer today has noticed this bug with custom date ranges

**Comment by utrautmann** [comment] 2025-01-20 12:13
@paul-buttimore why is the issue closed? the problem happens currently in Version 5.2.1 on premise
