### ISSUE TITLE
Add Custom Dimension Command doesn't work as expected

### ISSUE THREAD

**Issue by mickaelandrieu** [piwik/piwik#20563] opened 2023-04-05 13:13 UTC
## Context

I want to add custom dimensions using the Console

## Expected Behavior

It should work as documented.

## Current Behavior
It does not, probably because the condition on message confirmation doesn't work as expected

![NOK](https://user-images.githubusercontent.com/1247388/230090103-60f7bc2f-ad87-4690-b187-01c4fb143aad.JPG)

And the program stay this way for hours (waiting for a confirmation message not displayed IMHO ? IDK)

## Possible Solution
This suggestion is backed up by the fact it's still possible to add custom dimensions without interacting with the console:

![OK](https://user-images.githubusercontent.com/1247388/230090723-2c408e3e-420a-48c6-add9-b2277fcccdb9.JPG)

## Steps to Reproduce (for Bugs)
1. docker-compose exec app /usr/local/bin/php /var/www/html/console customdimensions:add-custom-dimension --scope=action --count=1
2. docker-compose exec app /usr/local/bin/php /var/www/html/console customdimensions:add-custom-dimension --scope=action --count=1 --no-interaction

## Your Environment

* Matomo Version: the most recent 4.X
* PHP Version: 8.1
* Server Operating System: Ubuntu server
* Additionally installed plugins: I'm not allowed to list them
* Browser: Irrelevant
* Operating System: Irrelevant

**Comment by sgiehl** [comment] 2023-04-05 14:34
Hi @mickaelandrieu. Thanks for taking the time to report this issue.
I've tried reproducing it, but for me it actually worked without problems. Did you try typing an `y` and pressing enter? There should actually be a confirmation question displayed, but seems that doesn't work for you for any reason:

![image](https://user-images.githubusercontent.com/1579355/230113848-35e2ca9b-21bd-4e83-8039-2e5736688311.png)

Anyway, there had been some changes around commands due to updating the symfony console dependency in our upcoming major release. So I assume this will be fixed with Matomo 5. If you still see this problem after Matomo 5 was released, feel free to create another report.

**Closed as not planned by sgiehl** 2023-04-05 14:34 UTC
Labels: wontfix

**Comment by mickaelandrieu** [comment] 2023-04-05 14:47
Please tag it as "wont fix",  so people won't add issues on 4.X again :)

> Did you try typing an y and pressing enter?

Yes, it doesn't execute the creation of custom dimensions.

> So I assume this will be fixed with Matomo 5.

Yes, probably. I'll upgrade Matomo by July or August, I'll let you know atm.

**Comment by MatomoForumNotifications** [comment] 2024-08-13 18:58
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/unable-to-increase-custom-dimension-count/54323/2

**Comment by atom-box** [comment] 2024-08-13 19:05
_For one user, the_
`customdimensions:add-custom-dimension`
_command blew up their server. Their message follows:_


> Today I attempted to run script to add to the max action custom dimensions. This was the command I ran from 
`./console customdimensions:add-custom-dimension --scope=action --count=5`


> Since initiating, our matomo site has been returning a 503 Service Unavailable message. I see the following in the apache error_log:

`server reached MaxRequestWorkers setting, consider raising the MaxRequestWorkers setting`

`server is within MinSpareThreads of MaxRequestWorkers, consider raising the MaxRequestWorkers setting`

**What solved it**
> I updated mpm_event_module apache config to get past the maxrequestworker limitation and allowed us to get to the point where it exposed a MySQL error of too many connections. Our DBAs killed the connection and we are back in business.
