### ISSUE TITLE
Report period is always selected as "day"

### ISSUE THREAD

**Issue by santoshbmath** [piwik/piwik#21162] opened 2023-08-21 11:06 UTC
Irrespective of report period selected "Weekly" or "Monthly", it is always selected as "day".

## Context

Not able to generate the reports.

## Expected Behavior

Period should reflect based on selection,

https://HOSTNAME/analytics/index.php?module=ScheduledReports&action=index&idSite=1&**period=day**&date=today&idContainer=JJBLtNTh&activated=&mode=admin&type=&show=#

## Steps to Reproduce (for Bugs)

1.
2.

## Your Environment

* Matomo Version: 4.15.1
* PHP Version: 8.1.16
* Server Operating System: Windows
* Additionally installed plugins:

* Browser:
* Operating System:

**Comment by michalkleiner** [comment] 2023-08-21 11:27
Hi @santoshbmath, thank you for raising the issue. I'm not sure I understand what the exact issue is, what part of Matomo you're trying to use and what is expected vs what is actually happening.
Can you please provide exact replication steps from the time you log in to the dashboard to the end where you see the issue? A screenshot might also help with marked area where the issue is etc. Anything that would allow us better understand the issue and evaluate whether it's a bug or not.
Thank you!

**Comment by santoshbmath** [comment] 2023-08-21 12:01
In the below image, report is scheduled weekly, but when we either click on "Download" or "Send Report now", the "period" will be set to "day" instead of "week/weekly".

![image](https://github.com/matomo-org/matomo/assets/3702899/a0073efa-583d-4c1a-8315-3b4c7ff97983)


https://HOSTNAME/analytics/index.php?module=ScheduledReports&action=index&idSite=1&**period=day**&date=today&idContainer=JJBLtNTh&activated=&mode=admin&type=&show=

**Comment by sgiehl** [comment] 2023-08-21 13:16
@santoshbmath The `send report now` will always use the period that is currently selected in the period selector. This was actually meant as kind of feature, as it allows you to send the report for any period (and not only the configure one).
We lately received a couple of reports, as users aren't expecting that. So guess we need to improve the UI or change that so it's less confusing.
I'll close this one if favor of https://github.com/matomo-org/matomo/issues/19674, as there already was some discussion around that topic.
Thanks anyway for creating the issue.

**Closed as not planned by sgiehl** 2023-08-21 13:16 UTC
Labels: duplicate
