### ISSUE TITLE
Report date to load by default doesn't work

### ISSUE THREAD

**Issue by ohaucke** [piwik/piwik#7795] opened 2015-04-30 08:35 UTC
If i set "Report date to load by default" to "Current Month" and go back to the dashboard it shows me the report for today.

Reproduce:
1. $User->Settings: Report date to load by default: Current Month
2. Open a new Tab/Browserwindow with the domain (e.g. http://piwik.domain.com)

Version: 2.13.0.

**Comment by mattab** [comment] 2015-04-30 10:13
Hi @ohaucke 
Thanks for the report! 
Unfortunately the feature is indeed broken....
We will fix it in the next release (in few days or weeks)

**Comment by mnapoli** [comment] 2015-04-30 21:57
Works for me. There's one thing that has changed regarding that so may be related: #7623

**Comment by diosmosis** [comment] 2015-04-30 21:58
I can reproduce, you have to visit the page in a new tab.

**Comment by diosmosis** [comment] 2015-04-30 23:03
The cause of the bug is here: https://github.com/piwik/piwik/blob/master/plugins/UsersManager/UserPreferences.php#L107

getDefaultDateWithoutValidation() sets the default value for the user preference to `'today'`. It is then passed to getDefaultPeriodWithoutValidation(), which will set the period to 'day' w/o ever looking at the user preference. The quick fix would be to move the getDefaultPeriodWithoutValidation() call to before the getDefaultDateWithoutValidation(), however the code is confusing and there is no complete specification about how this feature is meant to behave, so I can't be sure it won't have side effects.

@mnapoli You've recently worked w/ this code, do you have any insights?

**Comment by mattab** [comment] 2015-05-01 02:30
How to reproduce:
 * Set date by default to "Current month"
 * Click on Piwik icon: 
 * Got: it loads current day period=day
 * Expected: it loads current month period=month

Also 
 * check all other combinations of dates to load by default, in the UI, are working too
 * let's write a test for this feature so it won't regress in the future (and I feel sorry
 for having written this messy code months ago and not having written tests for it!)

**Comment by mnapoli** [comment] 2015-05-01 02:46
@benaka sorry I don't have an idea on the top of my head (can't look in details right now), I agree the code is really confusing and when I worked on that I didn't improve it much (probably not even at all) as the better solution we identified had a too high refactoring cost.

**Comment by diosmosis** [comment] 2015-05-01 14:42
@mnapoli Do you remember what the better solution was?

**Comment by mnapoli** [comment] 2015-05-01 22:35
@diosmosis not in details right now, we discussed it with @mattab. It involved handling period + date as a single entity (e.g. wrap them in a single concept/object), allowing for example to validate them both (e.g. [this change](https://github.com/piwik/piwik/pull/7623/files#diff-75cfa1b19ed2a0001a465a5c2c0eb02cR107) is kinda in that spirit). Because some dates only make sense for some ranges, and some ranges only make sense for some dates, they are highly coupled.

**Comment by diosmosis** [comment] 2015-05-01 23:06
Centralizing the query parameter logic in classes sounds like a good idea. Will be simple w/ DI.

**Comment by mnapoli** [comment] 2015-05-03 04:40
PR: #7814

**Comment by diosmosis** [comment] 2015-05-04 22:22
Fixed by #7814

**Closed by diosmosis** 2015-05-04 22:22 UTC
Labels: Bug
