### ISSUE TITLE
Selectable Metrics on the Dashboard of all Websites

### ISSUE THREAD

**Issue by Nine-1982** [piwik/piwik#20434] opened 2023-03-08 13:09 UTC
As a user in public services, I would like to choose, which metrics I want to be shown on the Dashboard of all Websites, to see the statistics that are most relevant for me. For example we do not need any sales metrics, the bounce rate e.g. would be much more interesting. It could look like this:
![image](https://user-images.githubusercontent.com/127313991/223720841-5e4cf659-9ee9-47e5-a491-55f9175449d2.png)

**Comment by bx80** [comment] 2023-03-09 00:06
Thanks for the suggestion @Nine-1982, that would be a nice enhancement :+1: 

I've assigned this for prioritization in a future release.

**Comment by Nine-1982** [comment] 2023-03-09 08:48
That’s great. I‘ looking forward to it ☺

Von: Ben Burgess ***@***.***>
Gesendet: Donnerstag, 9. März 2023 01:07
An: matomo-org/matomo ***@***.***>
Cc: Ostritsch, Christine (IBBW Stuttgart) ***@***.***>; Mention ***@***.***>
Betreff: EXTERN: Re: [matomo-org/matomo] Selectable Metrics on the Dashboard of all Websites (Issue #20434)


Thanks for the suggestion @Nine-1982<https://github.com/Nine-1982>, that would be a nice enhancement 👍

I've assigned this for prioritization in a future release.

**Comment by mattab** [comment] 2023-03-12 04:50
Thanks for creating this issue. Closing as duplicate of https://github.com/matomo-org/matomo/issues/2390

**Closed as not planned by mattab** 2023-03-12 04:50 UTC
Labels: Enhancement, not-in-changelog
