### ISSUE TITLE
use leaving signals to meassure time on last page of visit

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#9475] opened 2016-01-05 15:35 UTC
It's not possible to directly measure time on last page visited.
To solve this a heartbeat signal was introduced which pings to piwik as long as site is visited " I'm still there!" see https://github.com/piwik/piwik/issues/8225
This produces additional server-load.
The more exact the time on page has to be measured (high resolution), the higher needed ping frequency and wit this the higher server-load.
Since not during complete visit a a high resolution is always necessary, one can work with growing intervals of pings see https://github.com/piwik/piwik/issues/9423
But of course even this produces permanent server-load.

An other way to help to measure time on last page is to use available "leaving signals" to send a signal "I'm leaving" and stop time recording when receiving this signal.
( instead of "I'm still there" heartbeat procedure)

possible leaving signal maybe:
- use outgoing link (in same tab)
- move fast mouse to top left (same as used to show advertisements an some sites)
- possibly some other...

**Comment by mattab** [comment] 2016-01-18 04:35
Marking as duplicate of: https://github.com/piwik/piwik/issues/9539 - also it will be improved in https://github.com/piwik/piwik/issues/9540

**Closed by mattab** 2016-01-18 04:35 UTC
