### ISSUE TITLE
Visitor map NaN error in browser console

### ISSUE THREAD

**Issue by andrzejewsky** [piwik/piwik#8243] opened 2015-06-29 15:17 UTC
Hi, I found problem with visitor map, take a look on the screenshot:

![zrzut ekranu 2015-06-29 o 17 10 00](https://cloud.githubusercontent.com/assets/7943292/8411141/a06e887c-1e82-11e5-81c4-20f35a7af9d3.png)

Look at the console, we can see a lot of "NaN" errors. I think, this problem occur only if we will select Canada

**Comment by tsteur** [comment] 2015-06-29 22:01
Can you let us know what your browser + operating system is and steps to reproduce? Also what's your Piwik version?

**Comment by quba** [comment] 2015-06-29 22:07
demo.piwik.org on Mac OS X using latest Chrome.

**Comment by mattab** [comment] 2015-07-01 13:47
Since we recently fixed some problems with the map, i'm wondering that maybe it will be fixed in RC2 (coming soon). Let's check bug is still here in RC2 once it will be on the demo.

**Comment by quba** [comment] 2015-07-06 10:39
I can still reproduce it using demo.piwik.org (after update)

**Comment by barbushin** [comment] 2015-07-06 20:52
Problem was in Kartograph centroid calculation function, it was a popular bug fixed in Kartograph v 0.8.2 (see https://github.com/kartograph/kartograph.js/blob/master/CHANGELOG.md#082). 

There was some backward compatibility with Kartograph 0.8.6 and 0.8.7, so I just used 0.8.2 release with trivial migration refactoring. Now it works.

**Comment by mattab** [comment] 2015-07-07 12:00
Assigning to 2.14.1 to have bit more time to test it

**Comment by mattab** [comment] 2015-07-12 16:39
PR was reverted in #8335

**Closed** 2015-07-14 14:53 UTC
Labels: Bug
