### ISSUE TITLE
Segment --> Visitor Location --> Country --> United States is missing; by Country Code --> US is present

### ISSUE THREAD

**Issue by pranavmishra90** [piwik/piwik#17020] opened 2020-12-24 22:28 UTC
# Platform:
Matomo 4.1.0
Ubuntu Server 18.04 Minimal

## Issue
Cannot create a "segment" of visitors on Matomo dashboard, restricted to United States visitors, by "Country"

## Segment creation by country
![United](https://user-images.githubusercontent.com/62562712/103107489-6a2bc900-4604-11eb-9fdc-3921bb3ba369.png)
Trying "United" for "United States" or "United States of America"
![US](https://user-images.githubusercontent.com/62562712/103107490-6ac45f80-4604-11eb-9976-9d3be37144bd.png)
Trying abbreviated form "US" for "US" or "USA"
![America](https://user-images.githubusercontent.com/62562712/103107491-6ac45f80-4604-11eb-9793-3f21c7390b8f.png)
Trying America

## What is working - segment creation by country code
Using the country code US

![Country Code](https://user-images.githubusercontent.com/62562712/103107518-aa8b4700-4604-11eb-8b82-dfc54c1385cb.png)

Because a workaround is possible and this is not security related, I do not believe this is a high priority bug. However, I do want to document both the bug and the temporary solution for other end-users.

**Comment by tsteur** [comment] 2020-12-27 19:21
Thanks for creating this issue @pranavmishra90 I'll close this issue as a duplicate of https://github.com/matomo-org/matomo/issues/15620

**Closed as completed by tsteur** 2020-12-27 19:21 UTC
Labels: duplicate
