### ISSUE TITLE
Custom dimensions at the action level are not assigned to goals

### ISSUE THREAD

**Issue by Chardonneaur** [piwik/piwik#20642] opened 2023-04-27 17:54 UTC
Hi team,
I found a nice bug. Goals are normally actions. But if you define a custom dimension and assign it to a goal, then it is not working. Seems like custom dimensions can only be assigned to pages, events...

**Comment by michalkleiner** [comment] 2023-05-15 19:41
Hi @Chardonneaur,
thank you for opening the issue. Could you please provide further replication steps, some screenshots or perhaps a screen recording of the issue you're experiencing? When you say it is not working, is there perhaps an error message?

**Comment by Chardonneaur** [comment] 2023-05-17 06:50
Hi @michalkleiner 
In order to reproduce it.
Create a manual goal within Matomo.
Create a custom dimension at the action level.
Then set this manual goal as a tag within Matomo Tag Manager.
Assign it a configuration variable which include a custom dimension with the corresponding slot you created before.
Trigger the goal.
Then you will see within the visit log that this goal has no custom dimension assigned... which is not correct because a goal is an action.

**Comment by sgiehl** [comment] 2024-05-27 14:36
Closing as duplicate of #16147

**Closed as not planned by sgiehl** 2024-05-27 14:36 UTC
Labels: duplicate
