### ISSUE TITLE
[Bug] PagePerformance Graphs per-page are blank always on all pages on all sites (when drilling down)

### ISSUE THREAD

**Issue by BloodyIron** [piwik/piwik#21811] opened 2024-01-15 19:11 UTC
### What happened?

Parts of the PagePerformance aspect work seemingly rather well, like Dashboard Widgets. However when I try to get the PagePerformance Metrics and Graph for individual URLs (via the in-line pop-up link) they are 100% of the time blank. See screenshot:

![image](https://github.com/matomo-org/matomo/assets/12439391/e2726147-5aed-47da-868f-621a642e21f6)

### What should happen?

I expect a graph generated per-URL that is relevant metrics to that URL when doing the in-line pop-up graphing.

### How can this be reproduced?

Anywhere in Matomo hover over a specific URL for the relevant links to show visible (normally hidden) and click "Open page performance report" link.

### Matomo version

4.16.0

### PHP version

7.4.33

### Server operating system

Ubuntu 22.04

### What browsers are you seeing the problem on?

Not applicable (e.g. an API call etc.)

### Computer operating system

Ubuntu 22.04

### Relevant log output

```shell
I see zero log info on this topic, despite digging for it in documentation or even reports from other users. I cannot find any insights as to why this is failing anywhere.
```

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment] 2024-01-16 09:26
@BloodyIron Are you maybe viewing the pages reports flattened? There is a known bug, that page performance report doesn't work correctly in this case. See https://github.com/matomo-org/matomo/issues/17807

**Comment by BloodyIron** [comment] 2024-01-16 16:56
@sgiehl I read through the linked issue and don't see really how flattening is set/unset. I don't recall touching a setting, but I'm a fragile human, and I'll gladly check such a setting... but I don't know where that would be :) Where would I find it?

**Comment by sgiehl** [comment] 2024-01-17 12:16
@BloodyIron Does the report show a hierarchical view, where you can extend subtables or is it flattened where each row show a full url?

**Comment by BloodyIron** [comment] 2024-01-17 21:14
Um, the screenshot I already posted above doesn't answer that question? I am not yet following you on this, sorry.

**Comment by sgiehl** [comment] 2024-01-17 21:27
Could you post a screenshot of the report you are opening the page performance overlay from?

**Comment by BloodyIron** [comment] 2024-01-17 21:36
I can't without posting sensitive information, but I can describe an example that may be helpful.

So, on the dashboard, I have a widget "Entry Pages". And it shows the pages people enter the site at (which I suspect you already know lol). When I hover over one of the URLs in the list and click on "Open page performance report", this is one of the many cases where the graphs are blank (for all URLs in this list). I get the same experience generally for other lists of URLs in other sections of Matomo (like if I'm going into Behaviour -> Entry Pages/Exit Pages, etc)

Hope that helps! Also, thanks for your engagement here, really appreciated :)

**Comment by michalkleiner** [comment] 2024-01-18 02:43
@sgiehl I tried in demo and it looks like the performance metrics are all zero there for all pages as well, the performance report doesn't show anything, regardless of whether the widget is using flattened or hierarchical data.

https://demo.matomo.cloud/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?period=week&date=2023-09-12&idSite=1&category=General_Actions&subcategory=PagePerformance_Performance

**Comment by sgiehl** [comment] 2024-01-18 08:52
@michalkleiner We are not tracking any performance metrics on demo, so there isn't anything that could be shown.

**Comment by sgiehl** [comment] 2024-01-18 08:58
@BloodyIron Does the pages report look like this:
![image](https://github.com/matomo-org/matomo/assets/1579355/187ac3b9-3c57-4558-98de-7e3be6126323)

Or like this:
![image](https://github.com/matomo-org/matomo/assets/1579355/ec86253b-6103-4e48-b90d-7278e3108dcf)

**Comment by michalkleiner** [comment] 2024-01-18 09:40
> @michalkleiner We are not tracking any performance metrics on demo, so there isn't anything that could be shown.

Ah, ok, didn't realise it needed to be specifically enabled/added/configured. Apologies.

**Comment by BloodyIron** [comment] 2024-01-18 19:02
@sgiehl for the "Entry Pages" widget on the Dashboard each line is the URL (below the FQDN of course), so the second picture, except that all of them are hyperlinks (your example has one that isn't hyperlinked, unsure if relevant).

So... does that help? :)

Also, thanks @michalkleiner for chiming in! Really do appreciate the help here :D

**Comment by michalkleiner** [comment] 2024-01-18 22:33
@BloodyIron so you have the flattened report if each line is a URL.
At the bottom of the report, there's a cog wheel where you can change the report to be hierarchical. Can you test if changing it to hierarchical and then seeing the performance metrics work?
![report settings](https://github.com/matomo-org/matomo/assets/233342/c6a8958b-ea6d-4239-b5b0-d155d6289407)
![report settings dropdown open](https://github.com/matomo-org/matomo/assets/233342/ec51dbce-204b-4d02-a246-a595f3567040)

**Comment by BloodyIron** [comment] 2024-01-18 23:11
@michalkleiner switching to hierarchical, I now get graphs on specific URLs, and it seems to be showing up for every one of them now. Any chance we can get this working for flat? I like flat a lot more, and it's really odd this breaks with flat.

**Comment by michalkleiner** [comment] 2024-01-18 23:26
Ok, thanks for the confirmation, @BloodyIron.

We've fixed this for the flattened reports in https://github.com/matomo-org/matomo/pull/21786 and it will be released in Matomo 5.0.2 when that is released. You will need to upgrade to Matomo 5, too, as I don't think there will be a fix for this for Matomo 4.

**Comment by michalkleiner** [comment] 2024-01-18 23:26
We can now mark this as duplicate of https://github.com/matomo-org/matomo/issues/17807.

**Comment by BloodyIron** [comment] 2024-01-19 19:19
@michalkleiner a whole bunch of plugins aren't yet v5 compatible, which really is the only reason I haven't upgraded. Is the fix not feasible for the v4 codebase? I do want to go to v5, but the plugins not yet ready are important on my end, which is really my end of motivation on that topic.

Either way, yay! Thanks for your help and working through this! \o/ Oh and your help too @sgiehl !

**Comment by Stan-vw** [comment] 2024-01-22 07:56
@BloodyIron can you let me know which plugins aren't matomo 5 compatible yet that prevent you from upgrading? We upgraded all Matomo plugins, and the most popular community plugins have new versions too. If there's still some outstanding that we missed to contact, perhaps we can give it another try with a kind message :)

**Comment by BloodyIron** [comment] 2024-01-22 17:18
Bandwidth
BotTracker
CustomVariables
DarkTheme
DeviceDetectorCache
IPReports
LogViewer
Provider
ShortcodeTracker

**Comment by snake14** [comment] 2024-01-22 20:46
@BloodyIron I'm curious why you say that those plugins are preventing you from upgrading? I just checked [the marketplace](https://plugins.matomo.org/) and all of them show as being compatible. Although, ShortcodeTracker wasn't until about 2 days ago.

**Closed as not planned** 2024-01-22 20:53 UTC
Labels: duplicate

**Comment by BloodyIron** [comment] 2024-01-23 17:29
@snake14 because the upgrade interface in Matomoto says they are incompatible... 

![image](https://github.com/matomo-org/matomo/assets/12439391/842d1d82-2115-4365-9bfc-e01a3c6e87ab)

And there are no updates visible to make them compatible...

**Comment by Stan-vw** [comment] 2024-01-24 00:28
Conversation around that message is continuining in https://github.com/matomo-org/matomo/issues/21842
