### ISSUE TITLE
The pragma "disableCookies" does not work in some browers

### ISSUE THREAD

**Issue by AgnesWhy** [piwik/piwik#7494] opened 2015-03-20 08:49 UTC
I have tested the piece of code hereafter including the "diableCookies" pragma respectively in Firefox 36.0 and in Chrome 41.0.2272.89 m
In Firefox, no cookie is installed, while in Chrome, the visitor cookies are installed (i.e.: ses; id, cvar....)

You can reproduce the issue using the site:  ShemaleAgnes.com . The pages index.html and tst_dis.html have cookies diabled, the page tst_end has cookies enabled. In Firefox, cookies are only installed when opening the page tst_enb.hml. In Chrome, opening any page will install the cookies. Cookies are also installed when the pragma "diableCookies" is used on all pages for all trackers.

The piece of code used :
QUOTE 
<script type="text/javascript">

</script>
UNQUOTE

**Comment by svenlewerentz** [comment] 2015-03-23 08:53
I can confirm this issue. More details here: http://forum.piwik.org/read.php?2,123722

**Comment by mattab** [comment] 2015-04-08 04:19
Hi guys, thanks for the report.

Increasing priority as it's an important feature to make sure that `disableCookies` works correctly, this Privacy feature is loved by many Piwik users.

**Comment by AgnesWhy** [comment] 2015-05-14 09:17
Could some pick up this problem? It's open for 8 weeks now and it's a quite annoying issue.

**Comment by AgnesWhy** [comment] 2015-05-14 09:43
Apparently, problem has been fixed on version 2.12.0 as I can no longer reproduce it in Google Chrome 42.0.2311.135 m. Could someone else, test it again? Thanks

**Comment by mattab** [comment] 2015-05-20 22:42
Hi @svenlewerentz can you confirm the issue is also fixed for you in 2.13.1 ?

**Comment by svenlewerentz** [comment] 2015-05-21 08:09
I can NOT confirm, that the issue is fixed. I tested with Piwik 2.13.1 and Chrome 43.0.2357.65 m / Windows.
You can check it here: http://www.sven-lewerentz.de

**Comment by carbureted** [comment] 2015-06-01 19:05
It would be great if this could get fixed ASAP - this bug is really obnoxious when combined with EU cookie law.

**Comment by AgnesWhy** [comment] 2015-06-02 03:47
IMHO the problem is fixed, at least in version 2.12, I have tested it again ysterday in Firefox and Chrome with the instruction "disable cookies" and no "visitor cookie" was installed.

Hello Carbureted, could you please elaborate on on your problem: which version of Piwik, which version of the browser ? 

If you want to test it, just visit one of my sites (e.g.:  https://ShemaleAgnesEscort.com  )  Piwik is called from each and every page and visitor cookies are disabled. Navigate through the site and check whether vistor cookies are installed in any of the browsers you used.

Have a nice day

Agnès

**Comment by svenlewerentz** [comment] 2015-06-02 06:19
@AgnesWhy Could you please check the link, I posted in my last post and report, if there are any piwik-cookies set by my page?
If I visit your site, there are multiple cookies set in chrome. Please check the screenshot:
![cookies](https://cloud.githubusercontent.com/assets/351596/7929585/fc42036a-08ff-11e5-8af1-8f6f8facbb95.png)

Thanks! Sven

**Comment by AgnesWhy** [comment] 2015-06-02 11:35
Hi Sven,

I have just checked in Chrome Version 43.0.2357.81 m  for differetn pages of your site http://www.sven-lewerentz.de/  and no cookie was stored by Piwik. And the same for my site, I have re-checked once more and no cookie was stored by Piwik.
I also checked in the venrable IE 8 with your site and my site and there was no cookie stored by Piwik.
Could it be the problem is linked to some settings of you Chrome version ? But I cannot figure out which ones.

A.

**Comment by carbureted** [comment] 2015-06-03 08:07
I saw cookies on the disconnect.me site (piwik is now disabled) with the no-cookies option selected as of last Friday on the latest version of Chrome. Weirdly, no cookies reported in Firefox. Additionally, the cookies were empty, which is strange.

![messages image 1184827456](https://cloud.githubusercontent.com/assets/597441/7955349/8bee5ba8-098c-11e5-84f6-aecb1400636e.png)

**Comment by tsteur** [comment] 2015-06-07 22:39
@AgnesWhy please contact "hello at piwik.org" via email and leave a comment here once you did so we can have a look in the spam folder just in case it goes there

**Comment by tsteur** [comment] 2015-06-07 23:01
FYI: I've identified 2 issues so far:

1. Eg `setSiteId()` might be executed before `disableCookies()` causing it to set a cookie initially which *should* be removed later as soon as a tracking request is performed. This can be fixed "easily" by making sure to execute `_paq('disableCookies')` very first.

2. Before any `disableCookies` is executed we do set a visitorIdCookie already in the constructor. This requires some refactoring and we need to stay BC see https://github.com/piwik/piwik/blob/2.14.0-b1/js/piwik.js#L4095 . Need to investigate about possible options.

**Comment by tsteur** [comment] 2015-06-08 00:58
I couldn't reproduce it but found some possible edge cases how this can happen.

Can you give this updated `piwik.js` https://raw.githubusercontent.com/piwik/piwik/7494/piwik.js a try and replace the existing file with the content of the new one?

**Comment by svenlewerentz** [comment] 2015-06-08 08:26
@tsteur 
I replaced the piwik.js here: http://www.sven-lewerentz.de 
Cookies are still saved in Chrome.

**Comment by tsteur** [comment] 2015-06-08 09:24
Can you maybe delete all cookies and test again in case you didn't delete them before? It's weird when I open that site with Chrome Version 43.0.2357.81 (64-bit) + Mac OS there are no cookies. Maybe I'm doing something wrong?

**Comment by tsteur** [comment] 2015-06-08 21:02
@svenlewerentz I just had a look again under Windows + Chrome and during this I noticed it is still using the "old" `piwik.js`. While testing with the old `piwik.js` I could reproduce and see cookies once. Here's the link to the "new" `piwik.js`: https://raw.githubusercontent.com/piwik/piwik/c6985edb229abf4a5328fe27d371bd4d01b617f7/piwik.js Do you mind updating?

**Comment by svenlewerentz** [comment] 2015-06-09 13:17
@tsteur 
Sorry, I made a mistake and replaced the wrong piwik.js in the js-subfolder. Now the correct file should be replaced with yours. 
And it seems it works well with your file. No cookies are set.

**Comment by tsteur** [comment] 2015-06-09 20:39
Sweet. Thanks a lot! Closing the issue.

**Closed by tsteur** 2015-06-09 20:39 UTC
Labels: Bug, c: Privacy, Major
