### ISSUE TITLE
Call to undefined method Piwik\Menu\MenuTop::add()

### ISSUE THREAD

**Issue by Firesphere** [piwik/piwik#10876] opened 2016-11-16 04:19 UTC
After updating to beta 3, I get this error message. Nothing more.

**Comment by sgiehl** [comment] 2016-11-16 07:53
Where, in which file and line?

**Comment by ehajo** [comment] 2016-11-16 09:30
Same here after update from 3.0.0-b2 to 3.0.0-b3:
Call to undefined method Piwik\Menu\MenuAdmin::add()

[Link to screenshot](http://imgur.com/m69u6b7)

That screen appears after installing it with auto-update.
Downgrade to b2 is not possible because the screen than say something like "update in process, b3 already installed, ..."

**Comment by Firesphere** [comment] 2016-11-16 09:36
Stack trace is empty in my server logs :(

**Comment by sgiehl** [comment] 2016-11-16 09:38
Any third party plugins installed?

**Comment by Firesphere** [comment] 2016-11-16 09:45
Found it, took me some `grep` magic, but it's in PerformanceMonitor and BotTracker module indeed.

Sorry for not getting back sooner, didn't have time.
If you use a third party plugin, run the following grep command to find the usages of the old add method and either comment out the lines, or update them, until the makers of the plugin fix it.
`grep -rnw '.' -e "menu->add"`

**Comment by ehajo** [comment] 2016-11-16 09:48
Thank you very much. Was also the BotTracker-Module here on my server.
Changed add to addItem and now it is working again :)

**Comment by sgiehl** [comment] 2016-11-16 09:52
Maybe it would be useful for the plugin developer to know that. Could you create issues in their repos?
e.g. https://github.com/Thomas--F/BotTracker

**Comment by Firesphere** [comment] 2016-11-16 09:55
Bottracker is already updated for Piwik 3, but somehow not showing up as an update.

**Comment by huye** [comment] 2016-11-16 11:35
I added the following content to the file:

`    public function add($menuName, $subMenuName, $url, $order = 50, $tooltip = false)
    {
		return parent::addItem($menuName, $subMenuName, $url, $tooltip, $order);
    }`

**Comment by Firesphere** [comment] 2016-11-20 03:22
@huye That kinda defies the whole idea of deprecating and removing the method, doesn't it?

**Comment by tsteur** [comment] 2016-11-20 18:25
FYI: The plugin BotTracker doesn't show up for Piwik 3 because it currently requires a fixed PHP version of "5.3.10". I will send a PR to fix this

**Comment by mattab** [comment] 2016-12-06 04:46
I'm leaving this issue opened as maybe our Safe mode should have been displayed to let user disable easily plugin. Haven't tried to reproduce but I suspect Safe mode wasn't displayed for you?

Safe mode looks like this: https://media.githubusercontent.com/media/piwik/piwik/3.x-dev/tests/UI/expected-screenshots/UIIntegrationTest_fatal_error_safemode.png

**Comment by unixfox** [comment] 2016-12-19 23:03
@mattab Safe mode isn't displayed for me too.

**Comment by mattab** [comment] 2016-12-26 03:28
in the next Piwik version, the safe mode will be displayed for such errors (done in #11082 ). Closing as it's caused by a third party plugin

**Closed by mattab** 2016-12-26 03:28 UTC
