### ISSUE TITLE
[Bug]: Matomo Times out if it cannot reach 199.232.170.132 

### ISSUE THREAD

**Issue by AnnoyingTechnology** [piwik/piwik#21450] opened 2023-10-27 07:01 UTC
### What happened?

We have an IDPS that dynamically drops suspicious connexion attempts. 
Matomo seems to try to reach 199.232.170.132 on port 80. If this get's dropped, Matomo's web GUI will timeout for any request.
I wasn't able to pinpoint the original domain that Matomo attempts to reach, but the IP would be different depending on how the that domain resolves at any given time.

### What should happen?

Matomo should not assume that 
* internet is available, 
* any specific IP is available

It should work properly if after a few seconds it cannot reach an external service/domain. 

### How can this be reproduced?

drop traffic to 199.232.170.132 or whatever IP matomo is trying to reach

### Matomo Version

Matomo 4

### Matomo Patch or Minor Version

4.15.1

### PHP Version

8.2

### Server Operating System

Debian 12.2

### What browsers are you seeing the problem on?

Not applicable (e.g. an API call etc.)

### Computer Operating System

Not relevant

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [ ] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by AnnoyingTechnology** [comment] 2023-10-27 07:03
Likely duplicate of https://github.com/matomo-org/matomo/issues/19735

**Comment by bx80** [comment] 2023-10-29 20:02
Hi @AnnoyingTechnology,

Thanks for reporting this, it is a duplicate of #19735 but additional supporting information is always helpful :+1:

Matomo 5 will use `https://` for marketplace requests by default which should resolve this issue. 
You can disable any attempt by Matomo to check for updates by adding the `config/config.ini.php` setting: 
```
[General]
enable_internet_features = 0
```

**Closed as not planned by bx80** 2023-10-29 20:02 UTC
Labels: duplicate
