### ISSUE TITLE
Report Graphs break up

### ISSUE THREAD

**Issue by strowi** [piwik/piwik#7948] opened 2015-05-20 09:39 UTC
Hi,

i seem to have a weird problem with the graphs in Email-reports.

For a couple of websites the graphs for entry-/exitsites stop a couple of days ago. 

E.g. from the top5 entrysites 1 graph is up2date, 1 stops 10 days ago and another one 14 days ago... 
I already tried dropping the archives and regenerating the reports, but the graph doesn't change.. 
This is the current stable-version of piwik. 

If needed i can provide more detailed info and screenshots. 

![image006](https://cloud.githubusercontent.com/assets/589662/7722912/b39c21f6-fee4-11e4-917e-69175039d266.jpg)
You can see the graphs stopping before and after "Di 28 Apr" at various dates.

regards,
strowi

**Comment by mattab** [comment] 2015-05-21 03:27
Hi @strowi thanks for the bug report. Maybe it would fixed when #6434  is fixed?

**Comment by strowi** [comment] 2015-05-21 09:08
@mattab thx for the info... will keep an eye on that.

**Comment by twpol** [comment] 2015-06-01 09:02
I've noticed the same thing with graphs in my email reports too. It looks to me like some of the graphs are not back-filling zeros to the start date - which means the line starts at the left edge of the graph instead of somewhere in the middle.

Here's a good example with referrer type:

![referrer type - week 25 may - 31 may 2015 - 5 - report 1](https://cloud.githubusercontent.com/assets/1017843/7909467/53edcbe2-0844-11e5-8381-5dd318ce5c63.png)

The campaigns started in the middle of the date range, in Feb 2015, but the graph draws the line from the left edge. All the other lines start slightly early too as the Piwik data only goes back to Dec 2014 but the graph starts from Nov 2014.

The graphs I have seen this problem on are:
- Page titles
- Referrer Type
- Websites
- Search Engines
- Campaigns
- Social Networks
- Country
- Device type
- Visitor Browser
- Operating System families
- Operating System versions
- Browser engines

It seems to not be a problem on:
- Visits Summary
- Goals
- Returning Visits

Hopefully that'll help someone figure out where the problem is and get it fixed. :)

**Comment by mattab** [comment] 2015-07-15 06:05
> which means the line starts at the left edge of the graph instead of somewhere in the middle.

Thanks for the tip, this looks like it could be the issue. cc @JulienMoumne

**Comment by mattab** [comment] 2015-08-13 16:41
Hi guys, can you please try to upgrade to 2.15.0-b1 which may fix this issue?

**Comment by mattab** [comment] 2015-08-17 09:24
This should be fixed, please reopen if you still have the issue with the latest Piwik beta release (see instructions: http://piwik.org/faq/how-to-update/faq_159/)

**Closed by mattab** 2015-08-17 09:24 UTC
Labels: Bug

**Comment by twpol** [comment] 2015-08-18 10:17
I've upgraded to 2.15.0-b1 and it's looking much better. Thanks!

**Comment by jagdish-nasit** [comment] 2015-08-26 09:41
@mattab I have upgraded to 2.15.0-b1 and issue seems resolved. However, one of plugin (IntranetGeoIP) stopped working. After checking PHP log, its giving below error.

[26-Aug-2015 09:35:34 UTC] PHP Warning:  Parameter 1 to Piwik\Plugins\IntranetGeoIP\IntranetGeoIP::logIntranetSubNetworkInfo() expected to be a reference, value given in C:\piwik\core\EventDispatcher.php on line 141
[26-Aug-2015 09:35:34 UTC] PHP Stack trace:
[26-Aug-2015 09:35:34 UTC] PHP   1. {main}() C:\piwik\piwik.php:0
[26-Aug-2015 09:35:34 UTC] PHP   2. Piwik\Tracker->main() C:\piwik\piwik.php:67
[26-Aug-2015 09:35:34 UTC] PHP   3. Piwik\Tracker->track() C:\piwik\core\Tracker.php:98
[26-Aug-2015 09:35:34 UTC] PHP   4. Piwik\Tracker\Handler->process() C:\piwik\core\Tracker.php:121
[26-Aug-2015 09:35:34 UTC] PHP   5. Piwik\Tracker->trackRequest() C:\piwik\core\Tracker\Handler.php:49
[26-Aug-2015 09:35:34 UTC] PHP   6. Piwik\Tracker\Visit->handle() C:\piwik\core\Tracker.php:139
[26-Aug-2015 09:35:34 UTC] PHP   7. Piwik\Tracker\Visit->handleNewVisit() C:\piwik\core\Tracker\Visit.php:160
[26-Aug-2015 09:35:34 UTC] PHP   8. Piwik\Piwik::postEvent() C:\piwik\core\Tracker\Visit.php:274
[26-Aug-2015 09:35:34 UTC] PHP   9. Piwik\EventDispatcher->postEvent() C:\piwik\core\Piwik.php:694
[26-Aug-2015 09:35:34 UTC] PHP  10. call_user_func_array:{C:\piwik\core\EventDispatcher.php:141}() C:\piwik\core\EventDispatcher.php:141

**Comment by MagicFab** [comment] 2015-10-09 09:26
@jagdish-nasit please file it in the Intranet-GeoIP project - https://github.com/ThaDafinser/https://github.com/ThaDafinser/Piwik-IntranetGeoIPPiwik-IntranetGeoIP.

**Comment by jagdish-nasit** [comment] 2015-10-09 09:29
Hi @MagicFab , I had filed under that as well, however this was fixed at Piwik level in subsequent Beta release.
