### ISSUE TITLE
Generation time display

### ISSUE THREAD

**Issue by marechalseb** [piwik/piwik#10158] opened 2016-05-17 10:11 UTC
Hello!

I am getting weird display of génération times as you can see on the pic. Any clue?

![image](https://cloud.githubusercontent.com/assets/16413071/15318817/2ec1d6bc-1c28-11e6-9c0b-c8b7340f3397.png)

**Comment by tsteur** [comment] 2016-05-22 21:32
This looks like a bug, however I cannot reproduce it on demo.piwik.org with french language: http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=day&date=yesterday#?module=Actions&action=menuGetPageUrls&idSite=7&period=day&date=yesterday

Is it broken for all time generation labels?

**Comment by mattab** [comment] 2016-07-14 10:40
Salut @marechalseb  - as tu ce probleme avec Piwik, et d'autres problemes similaires ? Screenshots are welcome. we haven't been able to reproduce in 2.16.1

**Comment by mattab** [comment] 2016-08-23 03:52
As we have not heard from you, closing the issue. Feel free to comment and re-open if you still experience the issue and have more info.

**Closed by mattab** 2016-08-23 03:52 UTC
Labels: Waiting for user feedback / Cannot reproduce yet
