### ISSUE TITLE
no displaying tracking code after update

### ISSUE THREAD

**Issue by maw2be** [piwik/piwik#11758] opened 2017-06-01 11:03 UTC
I have update Piwik to 3.0.4. After update on settings/tracking code I see only grey box with no tracking code. I add another website and still the same. Is this some bug or something wrong with my installation?

**Comment by Findus23** [comment] 2017-06-01 11:26
Is there an error in the javascript console? Maybe an adblocker is interfering.

**Comment by maw2be** [comment] 2017-06-01 14:15
In console I get
/analytics/index.php?date=yesterday&format=json&idSite=1&method=SitesManager.getJavascriptTag&module=API&period=day Failed to load resource: the server responded with a status of 500 ()

I'm not using adblocker at this computer, also I have check another computer and the same.

**Comment by Findus23** [comment] 2017-06-01 14:43
Hm, 500 means the error is on the server, so can you please also check your php error log?

**Comment by maw2be** [comment] 2017-06-01 15:04
This is my log, for me looks ok (hmm)
[rminfo.arleseytownfc.co.uk-ssl_log-Jun-2017.txt](https://github.com/piwik/piwik/files/1045180/rminfo.arleseytownfc.co.uk-ssl_log-Jun-2017.txt)

**Comment by Findus23** [comment] 2017-06-01 15:13
This looks like the access.log of your webserver. As the error (probably) occurs in piwik, we'll need the php errors, which are either in the error.log of your webserver or in a seperate php log file

**Comment by mattab** [comment] 2017-06-21 07:22
@maw2be Do you have an error in your error log?

**Comment by sgiehl** [comment] 2017-09-27 20:22
@maw2be  We are not able to reproduce this. If you still can reproduce that problem and you are able to provide some details on the error that is shown in the php error log, please provide us this information and we will try to help fixing it. Otherwise we will close this issue soon.

**Comment by sgiehl** [comment] 2017-10-31 22:33
Closing now. If anyone experiences a similar problem please open a new issue

**Closed by sgiehl** 2017-10-31 22:33 UTC
Labels: Waiting for user feedback / Cannot reproduce yet, worksforme
