### ISSUE TITLE
UserCountryMap plugin did broken

### ISSUE THREAD

**Issue by simpleuser99** [piwik/piwik#8239] opened 2015-06-29 09:06 UTC
Hello everybody!
I have a trouble. The UserCountryMap plugin do not work. I see a white frame instead the map.
I have a next errors in my Firebag.
![usercountrymap](https://cloud.githubusercontent.com/assets/11714750/8404654/47e19922-1e57-11e5-8898-84a6f5bcb5b6.PNG)
How can i fix it?

**Comment by tsteur** [comment] 2015-06-29 22:02
Can you let us know what your browser + operating system is and steps to reproduce? Also what's your Piwik version?

**Comment by simpleuser99** [comment] 2015-06-30 09:38
My browser is google chrome 43.0.2357.81 m and firefox 38.0.1
Operation system windows 7. My Piwik version is 2.13.1.
I have russian version of piwik, and i don`t know how it named in english version, but i try to explain with screenshot.
You may click 1 and 2 as well as in the attach screenshot.
![piwik_explain](https://cloud.githubusercontent.com/assets/11714750/8428050/78ff8f1e-1f24-11e5-8826-e481136bc630.PNG)

**Comment by simpleuser99** [comment] 2015-07-03 09:10
anybody help me?

**Comment by Globulopolis** [comment] 2015-07-03 09:30
@simpleuser99 try to setup force_ssl = 1 under the [General] section in config.ini.php. And you're using a self-signed certificate?

**Comment by simpleuser99** [comment] 2015-07-03 09:53
@Globulopolis  i don't use ssl sertificate. I have rewrite http to https

**Comment by Globulopolis** [comment] 2015-07-03 10:12
@simpleuser99 don't do that, or you will get an errors about mixed content.

**Comment by simpleuser99** [comment] 2015-07-03 10:15
@Globulopolis . i`m sorry. I wrote wrong information in last message. I use thawte-signed sertificate.

**Comment by diosmosis** [comment] 2015-07-03 16:27
@simpleuser99 Could you translate the error messages, maybe?

Also, if you try to load the page w/ the following INI config, you will get clearer stack traces:

```
[Development]
disable_merged_assets = 1
```

If you use it, be sure to undo your changes after you're done checking.

**Comment by simpleuser99** [comment] 2015-07-06 07:57
@diosmosis 
i try to translate line 4. "Blocked active content of mixed loading" or "activ mixed content loading is bloked"
I don`t understand when the mistakes. Piwik plugin code has the mistakes or my install/settings has the mistakes. I use piwik during four months, and i didn`t have trouble with UserCountryMap.  I don`t know when UserCountryMap did broken, but i can suppose that happend when i install last update piwik (2.13.1) but i`m not sure

**Comment by simpleuser99** [comment] 2015-07-06 08:33
@mnapoli @mattab Could you help me with my problem?
I think that problem in code.

**Comment by tsteur** [comment] 2015-07-06 21:04
Do you mind sending us login credentials to your Piwik to "hello at piwik.org"? If so, please comment here after you sent it so we can check the spam folder just in case. A user having view access should be enough. Otherwise it will be hard for us to investigate further.

Also try to maybe deactivate all browser extensions in case you have any installed (eg adblocker) just in case.

**Comment by simpleuser99** [comment] 2015-07-07 06:56
@tsteur I trying to use Piwik in IE11 without extensions and i view the issue.
I send login/pass to your email ( thomas@piwik.org)

**Comment by tsteur** [comment] 2015-07-08 03:43
I get the following error:

> Mixed Content: The page at 'https://example.org/index.php?module=CoreHome&action=index&i…=UserCountryMap&action=realtimeWorldMap&idSite=4&period=day&date=yesterday' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://example.org/plugins/UserCountryMap/svg/world.svg'. This request has been blocked; the content must be served over HTTPS.

It looks like svg maps are loaded via HTTP in your case (I can also see svgBase url is set to HTTP). This means most likely that this method returns a HTTP url for you: https://github.com/piwik/piwik/blob/2.14.0-rc3/core/SettingsPiwik.php#L166

This method *should* return a https url as I'm requesting the page with https. Somewhere there seems to be a bug. Maybe someone has an idea why this method would return not HTTPS when requested with HTTPS?

**Comment by simpleuser99** [comment] 2015-07-08 07:43
@tsteur I don`t understand this "It is very slow and seems to regenerate the merged JavaScript quite often etc which takes always over a minute etc."  sentence, Can you explain me more simple?

I use standart plugins and the following plugins from piwik.org marketplace:
AdvancedCampaignReporting 
ComparisonDashboard 
InterSites 
LiveTab 
LoginLdap 
PerformanceMonitor 
TasksTimetable

**Comment by mattab** [comment] 2015-07-09 16:47
> Maybe someone has an idea why this method would return not HTTPS when requested with HTTPS?

Could it be (yet another) occurrence of #6880

**Comment by tsteur** [comment] 2015-07-13 12:53
This is actually a duplicate of https://github.com/piwik/piwik/issues/6703

> I don`t understand this "It is very slow and seems to regenerate the merged JavaScript quite often etc which takes always over a minute etc."

Is Piwik fast for you? If not, you might want to create a question regarding this in the forum: http://forum.piwik.org/list.php?2

**Closed by tsteur** 2015-07-13 12:53 UTC
Labels: duplicate

**Comment by simpleuser99** [comment] 2015-10-16 11:37
I want to know when this issue will be resolved ?

**Comment by mattab** [comment] 2015-10-16 11:43
@simpleuser99 follow this ticket: https://github.com/piwik/piwik/issues/6703
