### ISSUE TITLE
Visitor map visualization issues

### ISSUE THREAD

**Issue by quba** [piwik/piwik#8060] opened 2015-06-08 06:58 UTC
Please see:

![nvzhh4u7gxbgqmj5nrvgopxiwzrqp7aoianijcvte5s](https://cloud.githubusercontent.com/assets/647328/8029302/ccd79318-0dbb-11e5-9d39-a8bac05d5d09.png)

I can see here several issues:
- [ ] incorrect legend for the bounce rate metric (only 0 and 1 displayed instead of percentages),
- [ ] legend not visible after changing view (e.g. switching countries),
- [x] map title not fully visible as well after changing visualization (on the attached image it's being overlapped by Finland).

I'm using the latest version of Chrome browser. It's possible to reproduce this issue using demo.piwik.org

**Comment by mattab** [comment] 2015-06-10 01:16
Thanks for report, moved to 2.14.0

**Comment by mnapoli** [comment] 2015-06-10 16:58
The legend/map overlapping has been fixed in #8082.

**Comment by mnapoli** [comment] 2015-06-10 17:00
>  legend not visible after changing view (e.g. switching countries),

- I load the home page -> I see the world map
- I zoom to France -> it has visits, I see the legend
- I switch to Span -> it has visits, I still see the legend

I cannot reproduce this bugs, could you list steps to reproduce it? Are you sure you didn't switch to a country that didn't have any visit? (in that case the legend is hidden)

**Comment by quba** [comment] 2015-06-10 17:08
You have to switch countries several times. It's a little bit random but looks like an issue with z-index.

**Comment by andrzejewsky** [comment] 2015-06-19 15:33
> incorrect legend for the bounce rate metric (only 0 and 1 displayed instead of percentages)

What is the current status of this case ? @piwik/core-team Could you prepare patch for this issue ?

**Comment by tsteur** [comment] 2015-06-21 22:26
I cannot reproduce it either. Even switching countries very often. Tried for 5 minutes. If you can reproduce it, maybe someone of you can have a look at it? Useful would be maybe also detailed operating system and browser information and which Piwik version.

**Comment by quba** [comment] 2015-06-22 07:40
I think that points 2 and 3 have been fixed already after changing the z-index. There's one more issue with bounce rate legend.

**Comment by mattab** [comment] 2015-06-24 00:04
It's working on demo.piwik.org after beta8 upgrade :+1:

**Closed by mattab** 2015-06-24 00:04 UTC
Labels: Bug
