### ISSUE TITLE
Numeric value out of range: 1264 Out of range value for column 'visit_total_actions' at row 1 In query

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#6834] opened 2014-12-09 23:18 UTC
This was reported in the [forums](http://forum.piwik.org/read.php?2,122601):

> Following my upgrade to the latest version, I am getting the following problem when importing logs.

```
2014/12/06 11:28:11 [error] 2848#0: *29 FastCGI sent in stderr: "PHP message: Error in Piwik (tracker): 
Error query: SQLSTATE[22003]: Numeric value out of range: 
1264 Out of range value for column 'visit_total_actions' at row 1 In query: 
UPDATE piwik_log_visit SET idvisitor = ?, visit_total_time = ?, visit_last_action_time = ?, visit_exit_idaction_url = ?, visit_total_actions = visit_total_actions + 1 , custom_var_k1 = ?, custom_var_v1 = ? WHERE idsite = ? AND idvisit = ? Parameters: array ( 0 => '&▒▒▒▒E▒', 1 => 4852, 2 => '2014-11-30 19:18:36', 3 => 277470, 4 => 'Not-Bot', 5 => 'Mozilla/5.0 (Windows NT 6.3; WOW64; rv:33.0) Gecko/20100101 Firefox/33.0', 6 => 72, 7 => 21276112, )
```

**Comment by mattab** [comment] 2015-01-08 07:00
let's make this change only if there is another "Major DB schema change". There's no point making an upgrade "heavy schema change upgrade" just for fixing this bug

**Comment by mattab** [comment] 2015-02-23 21:29
Moving to next milestone because we are still waiting for resolution of #6953

**Comment by mnapoli** [comment] 2015-03-25 22:05
#6953 is assigned to 2.13.0 so this issue should be moved to the next milestone.

**Comment by mattab** [comment] 2015-09-11 09:41
moving to 3.0.0 where will apply big schema changes

**Comment by tsteur** [comment] 2016-09-13 00:59
I think this was resolved in https://github.com/piwik/piwik/pull/10002 and seems to be a duplicate of https://github.com/piwik/piwik/issues/9565 . Please reopen if not.

**Closed by tsteur** 2016-09-13 00:59 UTC
Labels: Bug, Major
