### ISSUE TITLE
2.16.2 : Since upgrade mobile version usability drops

### ISSUE THREAD

**Issue by Glisse1** [piwik/piwik#10376] opened 2016-08-04 15:47 UTC
Since upgrade from version 2.16.1 to 2.16.2 checking piwik from my phone became a hassle due to two reason:
- scrolling is a hit-miss situation, often the widget are moved.. this is not good usability, in order to move a widget there should be something like long-press for 2 seconds, or i dont know.. but not the normal scrolling down.
- widgets buttons (close, refresh, etc) are almost impossible to invoke.. there are widgets which i want to manually refresh.. right now this became impossible, i need to refresh the whole piwik in browser in order to get new data.. either make the buttons always visible (best solution, this is not a desktop that would maybe appreciate a fancy fade-in buttons on-mouse-over, just make the buttons always visible)..  or make them appear on-click upon widget`s top bar, like it used to be in version 2.16.1.. now, the new move "feature" i believe disabled that

PS: No, the dedicated piwik app is not a solution for me because i want the customized install loaded on my phone, with all my modifications.. from the modified definition of last "24 hours" (i preffer google s way of resetting stats at midnight unlike piwik continuum) to all colors and icons for each site`s page, etc, etc..

**Comment by tsteur** [comment] 2016-08-07 19:47
I mentioned similar here: https://github.com/piwik/piwik/pull/10045#issuecomment-211659413 and I think it's due to that PR as otherwise not much has changed. Maybe it's worth reverting that patch again

**Comment by dev-101** [comment] 2016-08-15 07:13
I have the same problem with scroll since the last update (Chrome, Android), and looking at the changelog TouchPunch lib introduction is the cause of the accidental widgets movements.

I see 2 ways to fix this issue:

1) Increase the minimum initial touch&hold event duration (for example , to 1,5 ~ 2 seconds), which should eliminate false or unintentional drags.

2) As Piwik knows I am on mobile, we could add an option in settings to disable this lib.

Thanks

**Comment by mattab** [comment] 2016-08-16 04:29
it should be good enough to fix this issue in Piwik 3.0.0 only as it is not critical

**Comment by tsteur** [comment] 2016-08-16 05:55
It may be critical for some power users but reverting the other patch would mean creating segments doesn't work on mobile which may not be too bad

**Comment by dev-101** [comment] 2016-08-16 08:03
Quick & Dirty fix for users who wish to revert to the old way before the official solution in the update becomes available:

**METHOD 1:**

1.1 go to dir

> /.../piwik/plugins/CoreHome/CoreHome.php

locate line 99 and add two slashes // in front of the line:

> //$jsFiles[] = "libs/bower_components/jqueryui-touch-punch/jquery.ui.touch-punch.min.js";

1.2 go to dir

> /.../piwik/tmp/

and remove all dirs (except .htaccess file)

-------------------------------------------------------------------------

**METHOD 2:**

2.1 go to dir

> /.../piwik/libs/bower_components/jqueryui-touch-punch/jquery.ui.touch-punch.min.js

open **jquery.ui.touch-punch.min.js** file with Notepad/code editor and remove the entire content from it, then re-save

2.2 go to dir

> /.../piwik/tmp/

and remove all dirs (except .htaccess file)

**Comment by dev-101** [comment] 2016-11-14 19:53
Hi, are there any plans to also fix this in 2.x branch? We're at 2.17.1 currently and this issue is still unresolved.

Also, instead of removing the lib, we can define touch delay, offset an distance values that should prevent from accidental firing, but still work for those when/if need it.

Thanks

**Comment by mattab** [comment] 2016-12-06 03:13
@dev-101 no it won't be fixed in 2.x

**Comment by mattab** [comment] 2016-12-18 21:45
Hello if you still experience the issue in Piwik 3 please re-open or create a new issue :+1:

**Closed by mattab** 2016-12-18 21:45 UTC
Labels: Bug, Regression
