### ISSUE TITLE
Widget mispagination in Views » Times

### ISSUE THREAD

**Issue by tassoman** [piwik/piwik#10219] opened 2016-06-07 10:25 UTC
Hello there,
when you click table view of the metrics in a data-table that occupies entire the screen width, widget on its right doesn't scale vertically inside the screen but stills there «absolutely» positioned.

I'm posting a screenshot taken with Firefox on Xubuntu, IE11+win7 behavior is the same.

![screenshot-demo piwik org 2016-06-07 12-08-32](https://cloud.githubusercontent.com/assets/92727/15854613/0e149a92-2cab-11e6-9521-6cb1275380b5.png)

**Steps to reproduce**

1. visit Visitors » Times
1. go fullscreen
1. in the first widget click the second view (as a table)

**Comment by tsteur** [comment] 2016-06-10 17:40
Isn't this a duplicate of https://github.com/piwik/piwik/issues/6121 ? Does maybe your comment https://github.com/piwik/piwik/issues/6121#issuecomment-90500891 help? I will close it as a duplicate. I'm assigned to the other issue and it'll be fixed in Piwik 3 but likely we won't fix it in Piwik 2.

**Closed by tsteur** 2016-06-10 17:40 UTC

**Comment by tassoman** [comment] 2016-06-12 06:56
Whoops! Sorry for duped issue :disappointed:

**Comment by tsteur** [comment] 2016-06-13 21:33
All good :) better creating one issue too much than not at all 👍
