### ISSUE TITLE
[Enhancement] Create API keys with parametrable access rights

### ISSUE THREAD

**Issue by SW-Vincent** [piwik/piwik#20533] opened 2023-03-30 08:59 UTC
Api keys currently have the same rights as their owners.
It would be a nice feature to be able to chose what an API key can (and can't) do, just as an administrator can define a user's rights.

## Summary

For a lot of users, API keys can represent a security breach : is your API key as well guarded as your passwords ? 
For exemple it can be used within scripts for scheduled Google Sheets data exports, and it would be wonderful to reduce the access level of these API keys to read only.

## Your Environment

* Matomo Version: Cloud

**Comment by sgiehl** [comment] 2023-03-30 09:32
Matomo in general lacks a more granular access model. But having the possibility to assign certain access right to newly created token_auths already sounds like a big improvements. That would at least allow to reduce the access of a token from e.g. an admin user to view access and similar.

**Comment by sgiehl** [comment] 2023-08-24 12:40
closing as duplicate of https://github.com/matomo-org/matomo/issues/15368

**Closed as not planned by sgiehl** 2023-08-24 12:40 UTC
Labels: Enhancement, duplicate
