### ISSUE TITLE
Event list inside Behaviour section is not showing all events.

### ISSUE THREAD

**Issue by modiboa** [piwik/piwik#17232] opened 2021-02-18 17:20 UTC
## Issue
For some reason, the events are not showing in the Event list inside Behaviour section, but I can see them on the Visitors Log

Here you can see the list of actions with 6 actions
![Screenshot from 2021-02-18 17-15-49](https://user-images.githubusercontent.com/6961049/108394800-06410d80-720d-11eb-9a17-d4f3b03fa73d.png)

Here you can see the events has only 3 entries
![Screenshot from 2021-02-18 17-17-10](https://user-images.githubusercontent.com/6961049/108394997-3be5f680-720d-11eb-94ba-b385255f1a3f.png)

## Your Environment

* Matomo Version: 4.1.1
* Matomo Tracker Java Library: 1.5
* PHP Version:  7.4.15
* Operating System: Ubuntu

**Comment by diosmosis** [comment] 2021-02-18 22:42
Hi @thiagofabre, do the other event reports have the same issue? If you invalidate the day and re-archive does it fix the problem for you?

**Comment by modiboa** [comment] 2021-02-22 15:10
My Matomo server has only events now, we are in testing phase. How Can I invalidate the day to test if it will fix the problem?

**Comment by sgiehl** [comment] 2021-02-22 15:14
@thiagofabre you can find the possibilities to do that here: https://matomo.org/faq/how-to/faq_155/

**Comment by modiboa** [comment] 2021-02-22 15:30
I just try to invalidate the day, but it's still not showing on the **Behaviour** section.

**Comment by modiboa** [comment] 2021-02-23 14:17
I just want to mention that I am using the java tracker library to do that

**Comment by diosmosis** [comment] 2021-02-23 17:15
@thiagofabre would you be able to provide access to your matomo and/or database to help diagnose? (if so, email dizzy@innocraft.com)

**Comment by 84adam** [comment] 2021-06-18 21:45
I was also having this problem while using the javascript tracker library. I could see all the events listed correctly within the Visitor Logs, but not in the Behavior > Events logs (for 1 of 2 sites). This was the case for an external site, but for one internal site. The tagged events did show up in the Event Log section for the internal site. When I switched sites (from the Event Logs page, site dropdown menu) back to the Internal Site, and then back to the External Site again, ALL the events showed up properly.

This seems to be an intermittent bug with a workaround as I described (switching between sites a few times).

**Comment by diosmosis** [comment] 2021-06-27 20:06
Hi @84adam, do you still experience this issue? Would you be able to provide screenshots before and after switching sites? And would you also be able to provide the exported report data before/after switching sites to workaround the issue?

**Comment by sgiehl** [comment] 2024-06-03 12:31
Closing as there hadn't been any further activity on this issue. We assume the issue is meanwhile solved or not a problem anymore. If this isn't the case, feel free to create a new issue. Thanks.

**Closed as not planned by sgiehl** 2024-06-03 12:31 UTC
Labels: Waiting for user feedback
