### ISSUE TITLE
Image export is scaled wrong 

### ISSUE THREAD

**Issue by DaSchTour** [piwik/piwik#7303] opened 2015-02-26 09:36 UTC
I hope there isn't a lot more to say, the picture should be enough to show how the problem looks like
![2015-02-26 at 10 38](https://cloud.githubusercontent.com/assets/1907266/6389351/a7ce99a8-bda3-11e4-8235-2eaae251300a.png)

**Comment by mattab** [comment] 2015-04-08 03:10
Hi @DaSchTour, thanks for reporting the issue.

**Comment by mattab** [comment] 2015-09-11 09:44
@DaSchTour can you reproduce this on the http://demo.piwik.org/ ? which browser/ OS are you using? so far it seems to work for me in FF, Chromium on ubuntu.

**Comment by sgiehl** [comment] 2015-12-19 20:58
Not able to reproduce that on Windows  IE11 / Chrome or Firefox

**Comment by mattab** [comment] 2015-12-20 23:14
@sgiehl FYI added `Waiting for user feedback / Cannot reproduce yet` new label

**Comment by sgiehl** [comment] 2017-10-31 22:41
This one was already fixed with #11557.

**Closed by sgiehl** 2017-10-31 22:41 UTC
Labels: Bug, c: Usability, Waiting for user feedback / Cannot reproduce yet
