### ISSUE TITLE
[Bug] double metric _paq.push(['trackSiteSearch', false, false])

### ISSUE THREAD

**Issue by KevinTessier** [piwik/piwik#22150] opened 2024-04-22 16:39 UTC
### What happened?

Hello, 

I integrated this for a search form that offers article suggestions.

but I noticed that the data is counted twice.

Here is the integration of the code in the head:

```
  <script>
    var _paq = window._paq = window._paq || [];
    /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
    _paq.push(["setExcludedQueryParams", ["sp_con"]]);
    _paq.push(['enableLinkTracking']);
    (function() {
      var u="mywebsite";
      _paq.push(['setTrackerUrl', u+'matomo.php']);
      _paq.push(['setSiteId', 'VarSiteID']);
      var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
    })();
  </script>

  <script>
    var _mtm = window._mtm = window._mtm || [];
    _mtm.push({'mtm.startTime': (new Date().getTime()), 'event': 'mtm.Start'});
    (function() {
      var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
      g.async=true; g.src='mywebsite/js/container_999999999.js'; s.parentNode.insertBefore(g,s);
    })();
  </script>
```

and here  my network : 

![Screenshot_20240422_183639](https://github.com/matomo-org/matomo/assets/29430975/a7915ee7-e3b4-405e-bfbc-43d6bbdcfd01)

I suppose it's because of the two scripts in my head but I seem to need both for the ex siteID config etc..

and the second for the container.

I'm lost, if anyone has an explanation.

Best.

### What should happen?

I would like to receive my research data only once.

### How can this be reproduced?

i don't know

### Matomo version

5.0.2

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by michalkleiner** [comment] 2024-04-22 22:59
Hi @KevinTessier,
unfortunately we can't provide support within GitHub issues. We only handle bug reports and feature requests here.

At a quick glance, if you're including the JS tracking snippet as well as MTM snippet in your page head, you will get the tracking twice. If you need to use Matomo Tag Manager, the best bet would be to configure the tracking via MTM and remove the standard JS snippet from your page head.

As this is not a bug in Matomo core, I will close the issue now. For further questions on the topic you may try to post on our forums at https://forum.matomo.org/ or if you're a Matomo Cloud customer you may reach out to our support.

Thanks for your understanding.

**Closed as not planned by michalkleiner** 2024-04-22 22:59 UTC
Labels: answered

**Comment by KevinTessier** [comment] 2024-04-23 07:32
thank you for your reply,
have a nice day.
