### ISSUE TITLE
Custom Variable values does not allow Page Size change

### ISSUE THREAD

**Issue by bcumberledge** [piwik/piwik#10434] opened 2016-08-23 17:31 UTC
https://forum.piwik.org/t/custom-variables-paging-page-size-export/19270

When using Custom Variables (Paging/Page Size/Export),

There is not a way to set the page size or see all data for the Custom Variables when the number of rows are beyond 10. Also, exporting only exports the Page Size which I believe is always 20 rows.

1-10 of 340 NEXT › So you can see this is a big issue when you have a lot of rows.

The Page Size only works for the Custom Variables not the details (Values) within a Custom Variable.

This has existed in every version including latest.

**Comment by mattab** [comment] 2016-09-27 04:44
> There is not a way to set the page size or see all data for the Custom Variables when the number of rows are beyond 10. Also, exporting only exports the Page Size which I believe is always 20 rows.

Hi @bcumberledge 
Currently there is a "Row limit selector" in the custom variable report, so you can display eg. 10 or 100 or 500 rows. 

What is the problem actually?

**Comment by bcumberledge** [comment] 2016-09-27 13:27
You can't change row size or export Custom Variable values.   Not custom variables but their actual values.

**Comment by mattab** [comment] 2016-09-27 20:07
Are some custom variable values not displayed? it should display them all, although truncated during report processing (as per: http://piwik.org/faq/how-to/faq_54/ )

**Comment by bcumberledge** [comment] 2016-09-27 21:16
Only 10 or 20 show, I forget the config default.   If you have hundreds, they don't show. Unless you click next 10 times.   You also have no page count for values you only have them for Variables names     You get next link but no option for page size.  Exporting actually I can't ever get export to have custom variable values at all.  Export gives you custom variable names only.  

So there are multiple issues.

**Comment by RMastop** [comment] 2016-10-02 21:06
Hi @bcumberledge a workaround would be to use the '&flat=1' in the URL, or use make it flat from the cog icon.
![image](https://cloud.githubusercontent.com/assets/7987117/19023651/d5c966e0-88f3-11e6-9a20-bec2e71bf420.png)

@mattab The issue is that when you have multiple values (more than 10) per Variable name, one is not able to change the amount of visible values other than the default 10, one has to navigate using next or previous to see the other values.
![image](https://cloud.githubusercontent.com/assets/7987117/19023697/c090ed56-88f4-11e6-8c78-5c159e41b564.png)

**Comment by mattab** [comment] 2016-10-03 23:59
Hello, this is fixed in Piwik 3

**Closed by mattab** 2016-10-03 23:59 UTC
Labels: Bug
