### ISSUE TITLE
Incorrect label

### ISSUE THREAD

**Issue by kongsted** [piwik/piwik#9847] opened 2016-02-25 07:43 UTC
Hi,

I found some labels there's not showed correct.
When opening Action - Pages, select "Open Transitions" and hovering the percentage next to the from and to pages, it shows:
%1$s (out of %2$s) from internal pages
The problem is also when hovering the pageviews.

//Anders

**Comment by tsteur** [comment] 2016-02-25 20:04
Thank you for creating the issue! We fixed this here https://github.com/piwik/piwik/pull/9800 and the fix will be available with the next update. It's a duplicate of https://github.com/piwik/piwik/issues/9799

**Closed by tsteur** 2016-02-25 20:04 UTC
