### ISSUE TITLE
the real time log are mixed up

### ISSUE THREAD

**Issue by mattmary** [piwik/piwik#19034] opened 2022-03-31 06:06 UTC
in the real time log, the log are not well ordered.

## Expected Behavior
the logs should be ordered by date

## Current Behavior
the logs are not ordered by date

## Your Environment

* Matomo Version: 4.6.2
* PHP Version:7.4.27
* Server Operating System: Linux
* Browser:(Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36)
![2022-03-30 12_09_23-Computer Dimensions - From 2022-03-24 to 2022-03-30 - Web Analytics Reports - Ma](https://user-images.githubusercontent.com/86216084/160987387-d44e94db-3376-490f-ac65-be593b49be1c.jpg)

**Comment by sgiehl** [comment] 2022-03-31 12:46
@mattmary are you able to see a javascript error in the browser console? If so this could be a duplicate of #18916

**Comment by mattmary** [comment] 2022-04-01 06:32
HI @sgiehl 

the user has:
`DevTools failed to load source map: Could not load content for chrome-extension://ddoijapfgfbaaehaegnddlbnmcbngkpi/context-menu.js.map: System error: net::ERR_BLOCKED_BY_CLIENT`

**Comment by Starker3** [comment] 2022-04-07 04:48
@sgiehl We've had a few more reports about this same bug from several different users. I've managed to get this to happen as well on the cloud instance (web). It looks almost like the older visits in the real time visits log aren't getting removed correctly when new ones load in.

I opened a second browser window on the same report and both are not showing the same visits for the same widget.
![image](https://user-images.githubusercontent.com/20905821/162121775-24a3a7e5-f6ff-487d-b8f3-182263323e70.png)
The screenshot just shows one out of order, but it happened several times for different ones as well.

In this one where the issue is has the following error in the browser console:
![image](https://user-images.githubusercontent.com/20905821/162121853-9d56395e-e28e-47de-b741-f1593563703e.png)

Not sure why it only happened in the one tab and not in the other one I had open on the same page. I'm using Firefox on Ubuntu.

**Comment by MatomoForumNotifications** [comment] 2022-04-11 09:21
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/live-visitor-log-widget-is-often-ordered-incorrectly-and-stops-updating/45469/2

**Comment by sgiehl** [comment] 2022-04-25 14:17
@mattmary are you able to say if that still occurs with Matomo 4.9.0 ?

**Comment by JustJoe21** [comment] 2022-04-25 14:21
I had the same issue and from I can say it does not appear any more in version 4.9.0; seems to be fixed.

**Comment by sgiehl** [comment] 2022-04-25 15:48
Hi @JustJoe21. Thanks for the feedback!
@mattmary  If the error still occurs with Matomo 4.9.0 or later, feel free to reopen the issue.

**Closed as completed by sgiehl** 2022-04-25 15:48 UTC
Labels: duplicate
