### ISSUE TITLE
system check complains about lack of UTF8mb4 support when using mysqli adapter

### ISSUE THREAD

**Issue by dominikborkowski** [piwik/piwik#18049] opened 2021-09-22 16:18 UTC
After installing brand new 4.4.1 instance with MYSQLI adapter the system check widget complains about lack of UTF8mb4 support. There is no such warning when PDO adapter is used.

## Expected Behavior

No warnings. Presumably MYSQLI is equally supported.

## Current Behavior

MYSQL

## Steps to Reproduce (for Bugs)

1. Perform a fresh new install of 4.4.
2. select MYSQL adapter
3. continue through interactive setup
4. Observe the following warning

![image](https://user-images.githubusercontent.com/3235494/134382221-34cd5ec2-8c6f-4845-88fb-4f5583d00a5b.png)

## Your Environment

Using official docker approach:

* Matomo version: 4.4.1
* MySQL version: 10.6.4-MariaDB-1:10.6.4+maria~focal
* PHP version: 7.4.23

I also repeated the same clean install with RDS Aurora (mysql 5.7 compatibility), and observed the same problem.

**Comment by sgiehl** [comment] 2021-09-23 10:01
@dominikborkowski  Did you maybe have a look at the full system check and not only the widget. The widget tooltips might sometimes be misleading - see https://github.com/matomo-org/matomo/issues/18006

**Comment by dominikborkowski** [comment] 2021-09-23 11:30
You're right, the tooltip is misleading, the full system check indicates the same exact problem as seen in the issue you linked:

![image](https://user-images.githubusercontent.com/3235494/134499415-39ce11a3-cc2f-43e2-938b-08ac72ac126e.png)

Can we merge this issue with the one you linked?  EDIT: On a second thought, I think there is an important distinction. The problem I describe here manifests itself right away after a simple install, not by changing an existing database afterwards. 

Cheers!

**Comment by sgiehl** [comment] 2021-09-23 13:05
@dominikborkowski I will close this one as duplicate of #18006. It doesn't make a difference if it's a fresh setup or changed database settings.

**Closed as completed by sgiehl** 2021-09-23 13:05 UTC
Labels: duplicate
