### ISSUE TITLE
Incorrect server time being displayed

### ISSUE THREAD

**Issue by CanuckNick** [piwik/piwik#7291] opened 2015-02-24 18:13 UTC
Below is a copy from a forum post. Matt asked for a bug report to be filed. When I made the original forum post I was using 2.10.0 but I updated to 2.11.1 this morning and this still applies.

Source: http://forum.piwik.org/read.php?2,124425
I'm trying to figure out if this is a bug in Piwik, a configuration issue or normal operation. 

Our server is set for the Eastern time zone. The current time on the server is 10:07 AM. When I go to the Scheduled Tasks screen for the TasksTimetable plugin it reports this: 
The following tasks are scheduled to be executed based on the current server time Friday 20 February 2015 15:07:53. 

It looks like this is reporting the time in UTC and not following the server time. Likewise, it looks like it is intending to schedule/run the tasks at midnight. However, these end up running at 7 PM Eastern (which would be midnight UTC). 
```
Piwik\Plugins\CorePluginsAdmin\Tasks.clearAllCacheEntries	Saturday 21 February 2015 00:00:04
(in 8 hours 53 min)
Piwik\Plugins\CoreAdminHome\Tasks.optimizeArchiveTable	Saturday 21 February 2015 00:00:04
(in 8 hours 53 min)
Piwik\Plugins\PrivacyManager\Tasks.deleteReportData	Saturday 21 February 2015 00:00:04
(in 8 hours 53 min)
Piwik\Plugins\PrivacyManager\Tasks.deleteLogData	Saturday 21 February 2015 00:00:04
(in 8 hours 53 min)
Piwik\Plugins\CoreAdminHome\Tasks.purgeInvalidatedArchives	Saturday 21 February 2015 00:00:08
(in 8 hours 53 min)
Piwik\Plugins\CoreUpdater\Tasks.sendNotificationIfUpdateAvailable	Saturday 21 February 2015 00:00:12
(in 8 hours 53 min)
Piwik\Plugins\CoreAdminHome\Tasks.purgeOutdatedArchives	Saturday 21 February 2015 00:00:41
(in 8 hours 53 min)
```

I've also noticed that in any log files that Piwik generates, the time reported on each line is again in UTC and not the server time. In the Piwik dashboard, the Visits by Server Time report appears to be using the correct server time. 

So, my question: 
Is the intention for Piwik to run the scheduled tasks at midnight server time (and not midnight UTC)? Midnight server time would make sense because this would be a lower traffic period for most web sites.

**Comment by gaumondp** [comment] 2015-02-24 18:34
Not a bug, an unwanted feature for some...

See #3029 

Another Canuck

**Comment by tsteur** [comment] 2015-02-24 20:42
Probably the naming "Server time" is a bit confusing as one would actually expect to see the server time there in the server's timezone which it is not (which is good by default). Maybe there is a better name for this? Then we could have a second column "Server time" that actually logs in the server's timezone or alternatively a config setting.

FYI: Server Time won't be easy for us to rename and/or change the behaviour as it will most likely break many systems

**Comment by CanuckNick** [comment] 2015-02-24 20:42
OK - let's assume that the timestamp logging is intended to be in UTC. That's fine, I can live with that. There's still a couple outstanding questions/issues from my original post:

1. The Scheduled Tasks screen still displays the text "based on the current server time Friday 20 February 2015 15:07:53". This is not really the current server time (10:07 AM EST), but technically is the server time adjusted for UTC. That's not clear here with the wording and possibly what Matt meant in his reply in the forum.

2. Based on my previous assumption that the above should actually be the current server time, the scheduled tasks are intended to run at midnight. They appear to be scheduled for midnight UTC. This does not make sense, as they should be running at midnight in the timezone of the server IMO. Maybe this needs to turn into a feature request to allow the administrator to specify what time these daily tasks are run. They end up running at 7 PM for us which is still in our peak traffic period. It would be more ideal from a performance perspective if they ran at midnight (or even at 1 or 2 AM).

**Comment by mnapoli** [comment] 2015-02-24 22:00
> 1. The Scheduled Tasks screen still displays the text "based on the current server time…

That's an error in the message. On the scheduled tasks screen everything is shown in UTC, but the wording is incorrect. -> needs to be fixed.

> 2. […] They appear to be scheduled for midnight UTC

Scheduled tasks are run in the **time of the website they belong to**. So it can be extra confusing if your server time is e.g. EST, and you track a website in PST:

- the schedule task's time will be in PST (e.g. if you set "midnight", it will be midnight PST)
- the scheduled tasks screen will show time in UTC
- yet that screen says it's in "server time" (i.e. PST)

Yay :)

So all this should be made clearer (via the wording on the screen). But the current logic makes sense: you want to wait for the end of the website's day before generating the daily report (i.e. you need to do it at midnight in the website's timezone).

**Comment by mnapoli** [comment] 2015-02-25 01:47
I first changed the confusing wording in the timetable in https://github.com/piwik/plugin-TasksTimetable/commit/fa68b4f5832f3dfe42f8f363b1c78dc522821da2: now it will say "based on the current UTC time".

**Comment by CanuckNick** [comment] 2015-02-25 11:54
That's great! One thing taken care of. For the record, my server time is EST and all my sites are set to America/Toronto. Now, focusing on these tasks that run:
```
Piwik\Plugins\CoreAdminHome\Tasks.purgeOutdatedArchives	
Piwik\Plugins\CoreAdminHome\Tasks.purgeInvalidatedArchives	
Piwik\Plugins\CorePluginsAdmin\Tasks.clearAllCacheEntries	
Piwik\Plugins\CoreAdminHome\Tasks.optimizeArchiveTable	
Piwik\Plugins\PrivacyManager\Tasks.deleteReportData	
Piwik\Plugins\PrivacyManager\Tasks.deleteLogData	
Piwik\Plugins\CoreUpdater\Tasks.sendNotificationIfUpdateAvailable
```
On the Scheduled Tasks screen they are listed as running at midnight UTC (and this seems to be intended based on what I'm learning about the preference for UTC). I have not researched what all of these tasks do, but given they run once a day I would assume that they could be fairly intensive on larger systems. As I noted above, my server and sites all run under EST. The above noted tasks are all running at 7 PM EST for me, when we are still in our high traffic period for the day. It would be nice if there was an option to adjust the time that these tasks run. 

Lastly (and I think this is important), when the archive cron runs at 7 PM, 9 PM, 11 PM and 1 AM (all EST - it only runs every two hours during that window because it seems to take much longer), the log file is showing that Piwik is invalidating the archives for a number of sites. I have a feeling this is because Piwik thinks it's the next day, but it is not yet for all my sites.
7 PM EST/midnight UTC (ran for 58 minutes)
```
INFO CoreConsole[2015-02-25 00:00:02] Will invalidate archived reports for 2015-02-24 for following siteIds: 41,6,9
INFO CoreConsole[2015-02-25 00:11:06] - Will process 35 websites with new visits since 43 min 9s , IDs: 2, 6, 7, 8, 9, 13, 15, 18, 20, 24, 28, 30, 34, 38, 40, 41, 46, 50, 54, 56, 57, 58, 59, 60, 64, 65, 66, 69, 70, 73, 89, 99, 108, 136, 147
INFO CoreConsole[2015-02-25 00:11:06] - Will process 3 other websites because some old data reports have been invalidated (eg. using the Log Import script) , IDs: 41, 6, 9
```
Also worth noting - this is when the daily tasks run:
```
INFO CoreConsole[2015-02-25 00:57:05] SCHEDULED TASKS
INFO CoreConsole[2015-02-25 00:57:05] Starting Scheduled tasks... 
INFO CoreConsole[2015-02-25 00:58:54] task,output
Piwik\Plugins\CoreAdminHome\Tasks.purgeOutdatedArchives,Time elapsed: 22.444s
Piwik\Plugins\CoreAdminHome\Tasks.purgeInvalidatedArchives,Time elapsed: 76.296s
Piwik\Plugins\PrivacyManager\Tasks.deleteReportData,Time elapsed: 0.013s
Piwik\Plugins\PrivacyManager\Tasks.deleteLogData,Time elapsed: 0.001s
Piwik\Plugins\CorePluginsAdmin\Tasks.clearAllCacheEntries,Time elapsed: 0.008s
Piwik\Plugins\CoreAdminHome\Tasks.optimizeArchiveTable,Time elapsed: 9.678s
Piwik\Plugins\CoreUpdater\Tasks.sendNotificationIfUpdateAvailable,Time elapsed: 0.002s
```
9 PM EST/2 AM UTC (ran for 61 minutes)
```
INFO CoreConsole[2015-02-25 02:00:02] Will invalidate archived reports for 2015-02-24 for following siteIds: 104,108,136,137,13,14,15,22,24,28,2,30,34,38,40,41,46,47,50,53,54,55,56,57,58,64,65,67,68,69,6,73,7,8,92,99,9
INFO CoreConsole[2015-02-25 02:13:05] - Will process 34 websites with new visits since 1 hours 1 min , IDs: 2, 6, 7, 8, 9, 13, 14, 15, 24, 28, 30, 34, 38, 40, 41, 46, 50, 53, 54, 56, 57, 58, 64, 65, 67, 68, 69, 73, 92, 99, 104, 108, 136, 137
INFO CoreConsole[2015-02-25 02:13:05] - Will process 40 other websites because some old data reports have been invalidated (eg. using the Log Import script) , IDs: 2, 6, 7, 8, 9, 13, 15, 18, 20, 24, 28, 30, 34, 38, 40, 41, 46, 50, 54, 56, 57, 58, 59, 64, 65, 69, 73, 99, 108, 104, 136, 137, 14, 22, 47, 53, 55, 67, 68, 92
```
11 PM EST/4 AM UTC (ran for 48 minutes)
```
INFO CoreConsole[2015-02-25 04:00:02] Will invalidate archived reports for 2015-02-24 for following siteIds: 108,13,15,20,24,28,2,30,34,38,40,41,46,48,50,53,54,56,57,58,60,61,64,65,66,68,69,6,70,73,7,8,9
INFO CoreConsole[2015-02-25 04:08:54] - Will process 30 websites with new visits since 58 min 14s , IDs: 2, 6, 7, 8, 9, 13, 15, 20, 24, 28, 30, 34, 38, 40, 41, 46, 50, 53, 54, 56, 57, 58, 61, 64, 65, 66, 68, 69, 73, 108
INFO CoreConsole[2015-02-25 04:08:54] - Will process 37 other websites because some old data reports have been invalidated (eg. using the Log Import script) , IDs: 2, 6, 7, 8, 9, 13, 14, 15, 24, 28, 30, 34, 38, 40, 41, 46, 53, 54, 56, 57, 58, 64, 65, 67, 68, 69, 73, 92, 108, 20, 59, 48, 50, 60, 61, 66, 70
```
1 AM EST/6 AM UTC (ran for 53 minutes)
```
INFO CoreConsole[2015-02-25 06:00:02] Will invalidate archived reports for 2015-02-24 for following siteIds: 13,15,22,24,2,30,34,38,40,41,46,54,56,57,64,65,6,73,8,9
INFO CoreConsole[2015-02-25 06:11:28] - Will process 28 websites with new visits since 1 hours 11 min , IDs: 6, 7, 8, 9, 13, 14, 15, 24, 28, 30, 34, 38, 40, 41, 46, 50, 53, 54, 56, 57, 58, 59, 64, 65, 68, 69, 70, 73
INFO CoreConsole[2015-02-25 06:11:28] - Will process 28 other websites because some old data reports have been invalidated (eg. using the Log Import script) , IDs: 2, 6, 7, 8, 9, 13, 15, 24, 30, 34, 38, 40, 41, 46, 50, 53, 54, 56, 57, 58, 64, 65, 66, 68, 69, 73, 14, 22
INFO CoreConsole[2015-02-25 06:11:28] - Will process 166 other websites because the last time they were archived was on a different day (in the website's timezone) , IDs: 3, 10, 11, 12, 16, 17, 18, 19, 20, 21, 23, 25, 26, 27, 29, 31, 32, 33, 35, 36, 37, 39, 42, 43, 44, 45, 47, 48, 49, 51, 52, 55, 60, 61, 62, 63, 67, 71, 72, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201
```

I realize this issue is titled for incorrect server time being displayed so let me know if you want this copied into a new issue.

**Comment by mnapoli** [comment] 2015-02-25 20:56
> The above noted tasks are all running at 7 PM EST for me, when we are still in our high traffic period for the day. It would be nice if there was an option to adjust the time that these tasks run.

Just FYI running at midnight in the server's timezone wouldn't be a bulletproof solution because the traffic peak depends actually on the timezone of websites being tracked. So if your server in EST tracks website in PST (or even New Zealand time) then running tasks at midnight EST could as well end up in one of your site's traffic peak.

An option to adjust the time could help with that, but that would be pretty advanced for users to understand that I guess. But why not.

Regarding the second issue:

> Piwik is invalidating the archives for a number of sites. I have a feeling this is because Piwik thinks it's the next day, but it is not yet for all my sites.

I think it's invalidating the *current* day because new visits have happened in the current day (so the reports need to be updated). I don't think the time of the archiving will change anything here because archiving is done based on the website's timezone, so it's unrelated to the server timezone.

But I'm not an expert about archiving, @mattab maybe you have a better answer?

**Comment by mattab** [comment] 2015-02-26 02:16
>  Piwik is invalidating the archives for a number of sites. I have a feeling this is because Piwik thinks it's the next day, but it is not yet for all my sites.

if you refer to this log line `INFO CoreConsole[2015-02-25 06:11:28] - Will process 28 other websites because some old data reports have been invalidated (eg. using the Log Import script) , IDs: 2, 6, 7, 8, 9, 13, 15, 24, 30, 34, 38, 40, 41, 46, 50, 53, 54, 56, 57, 58, 64, 65, 66, 68, 69, 73, 14, 22` then these websites are the ones that have been invalidated which means that new data was imported in older days that were already archived when the new data was tracked. typically it would occur I think only when you import logs in the past (or use the Tracking API with parameter `cdt` set in the past)

**Comment by CanuckNick** [comment] 2015-02-26 15:21
>  typically it would occur I think only when you import logs in the past (or use the Tracking API with parameter cdt set in the past)

We have not done any log file importing and we are only using the standard JavaScript tracking. This invalidation only starts appearing in the log files at the 7 PM EST/midnight UTC execution of the archiving process and remains until the day rolls over in EST. My gut tells me Piwik is doing something a little funny here but you would know better. If you think that Piwik is behaving properly (given the internal use/preference of UTC) we can close this and move on! :)

**Comment by RMastop** [comment] 2015-03-10 10:54
would it be an option to have an API call that serves the servertime at time of requesting it?
Something like API.getServerTime that would need the parameter of idSite. It would help in cases where data requested from the API does not result in the expected data. For instance an API call to get data for yesterday at 0:05 would be expected to provide the data for the day before. if for some reason you get data for the day before yesterday, you could debug by requesting the serverTime via API.

**Comment by mnapoli** [comment] 2015-03-10 20:26
@RMastop that wouldn't be the server time but the website time. I'm not sure it's really useful because you can take the timezone of the site and just look up the time of that timezone.

**Comment by RMastop** [comment] 2015-03-10 20:44
The purpose of the API call would indeed be to request the website time, should have written it like that. However one would not need to recalculate it. I have a hard time explaining this, but if I could point the user to the API call, that would be useful.

**Comment by mattab** [comment] 2015-04-08 03:40
The original issue "incorrect server time being displayed" looks done - if there is another issue please open a new one :+1: 

@RMastop feel free to create new issue to request a new API to display server datetime for given website

**Closed by mattab** 2015-04-08 03:40 UTC
