### ISSUE TITLE
Garbled text of translation

### ISSUE THREAD

**Issue by brownsugar** [piwik/piwik#11130] opened 2017-01-02 16:18 UTC
There's a garbled text at segment editor when using language zh-TW and even zh-CN.

zh-TW (Should be 指標)
![qq 20170103001523](https://cloud.githubusercontent.com/assets/2935980/21592641/1ecb594a-d14a-11e6-8a2f-bbe6433f63bd.png)

zh-CN (Should be 指标)
![qq 20170103001701](https://cloud.githubusercontent.com/assets/2935980/21592640/1ea82902-d14a-11e6-9d41-fad6ff09da6c.png)

But I've checked the translated strings, there was nothing wrong with them, so I think it's a bug.

**Comment by sgiehl** [comment] 2017-01-02 21:07
Without having a closer look I would assume that is caused by a `strtolower` or similar...

**Comment by sgiehl** [comment] 2017-01-05 10:40
Related to https://github.com/piwik/piwik/pull/10921

**Comment by vibbow** [comment] 2017-01-22 14:28
I'm not sure if #10921 is the fix for this issue, since ucfirst should only break the first char of the string, and all chinese string, not some of them and middle of the string.

**Comment by mattab** [comment] 2017-02-20 15:57
It occurs at this line https://github.com/piwik/piwik/blob/3.0.1/plugins/SegmentEditor/SegmentSelectorControl.php#L58-58 but I can't figure out what's the problem here... technically it's supposed to work

**Comment by brownsugar** [comment] 2017-02-20 16:01
Chinese words does not support '$metricsLabel[0]' like this split them to single characters.
This method should works: https://github.com/piwik/piwik/pull/10921/commits/ef0f9e2d6519332721add22fcb795857207b2711

**Comment by mattab** [comment] 2017-02-20 16:22
Thanks for that, i'll open a PR now

**Closed** 2017-02-21 10:24 UTC
Labels: c: Design / UI, c: i18n
