### ISSUE TITLE
show incoming data which could not be processed

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#8732] opened 2015-09-08 06:13 UTC
If you are working with with lots of actions e.g. events on your site it could happen that you setup something wrong e.g. a needed parameter is missing or...
To find these problems, it would be great, to have a list (log file) were all "not processable" incoming "messages" are stored (logged)

second step: having this list accessible from piwik backend, each user could report this problem to his site admin..

Maybe there is already a way how to get that kind of information, but always when searching for it one simply get informations about using the web-server logs in piwik...

**Comment by tsteur** [comment] 2015-09-08 06:27
I think this is a duplicate of https://github.com/piwik/piwik/issues/7550 Can you confirm @hpvd ?

**Comment by hpvd** [comment] 2015-09-08 06:36
interesting, hmm maybe it could fit within this. But it should not only work in a special "safe mode" but always.
Reason: there could be some faulty actions/events which are only triggered e.g. twice per month.
Having to have safe mode on on could easily miss them.
Or other way around it must be possible to use this safe mode permanent in live
- without any problems (e.g. performance) in "live"

**Comment by hpvd** [comment] 2015-09-08 06:40
I will move these notes to the mentioned tickets...

**Comment by tsteur** [comment] 2015-09-08 06:41
Yes the solution should work always, in production and fast (not affecting performance)

BTW: There is also https://github.com/piwik/piwik/issues/6209

**Comment by tsteur** [comment] 2015-09-08 06:41
Sweet, I'll close it then for now

**Closed by tsteur** 2015-09-08 06:41 UTC
