### ISSUE TITLE
after update on version 2.15.0 there is much less visitors recorded

### ISSUE THREAD

**Issue by adminkpr** [piwik/piwik#9097] opened 2015-10-26 21:57 UTC
After update on version 2.15.0 there is much less visitors recorded.
Before 300 visitors per day, after update up to 16 visitors per day.
Number of visitors according Google analytics is still the same - over 300 people per day.

**Comment by quba** [comment] 2015-10-26 22:01
Please check your error log files.

**Comment by adminkpr** [comment] 2015-10-26 22:04
No record since the update

**Comment by tsteur** [comment] 2015-10-26 22:10
Are the same amount of actions / pageviews recorded?

**Comment by adminkpr** [comment] 2015-10-26 22:16
No. See image. There is just 10 recorded visitors with 100 actions during last 24 hours. 
Before 22th October (when I do the update)  there was around 300 visitors per 24 hours. 
Statistics from Google Analaytics shows still around 300 visitors per day. But Piwik record only few of them (11-35)

![visitors](https://cloud.githubusercontent.com/assets/15332445/10744014/3710981c-7c37-11e5-8f0b-48010dcf98cf.png)

**Comment by tsteur** [comment] 2015-10-26 22:55
Can you try to debug the tracker? I reckon there will be some kind of error during the tracking requests. Here is an article re how to enable logging: http://developer.piwik.org/api-reference/tracking-api#debugging-the-tracker . You will most likely also have to do the second step and enable logging to file or database as described here: http://piwik.org/faq/troubleshooting/faq_115/

I'd recommend to enable tracker logging until you see an error in the logs and then disable it again to prevent from exposing any logging data to your users.

**Comment by adminkpr** [comment] 2015-10-27 07:03
I have done it.
In tmp/logs/piwik.log I see only few visitor from few sites.
However, I can not see there much more visitors, including those visits made by me.

**Comment by ThaDafinser** [comment] 2015-10-27 08:39
@adminkpr how did you upgraded piwik? Did you downloaded it from here? https://github.com/piwik/piwik/releases

**Comment by adminkpr** [comment] 2015-10-27 09:17
I have upgraded piwik online through the admin on my server.

**Comment by ThaDafinser** [comment] 2015-10-27 09:57
Hmm. I had such an error one of time also. The counter visitors were returning, which had the `piwik.js` already cached. Because new visitors couldnt load the `piwik.js` it didnt worked anymore

**Comment by tsteur** [comment] 2015-10-27 19:30
If there are only a few visitors in the log and no errors it sounds like the requests are not making it to your server somehow. Can you maybe check your apache or webserver log and PHP error log? If you cannot see your visits there, can you maybe open the developer tools in the browser (in case you are familiar with it) and see if it actually sends a tracking request to your Piwik? Maybe you have an ad/privacy blocker enabled or Do Not Track?

**Comment by adminkpr** [comment] 2015-10-28 17:19
There is no error records in the PHP error logs. I have even downloaded https://github.com/piwik/piwik/releases and upload it again. I really do not why, but at least 4 website has extreme decline of visitors (nearly zero) when compared before and after upgrade. The rest websites has less or more the same amount of visitors.

@tsteur Can you email me at admin(at)kpr.eu. I will give you password to access my piwik and you can look on it.

**Comment by tsteur** [comment] 2015-10-28 19:46
Email is hello at piwik.org. 

BTW: The downloads in releases should not be used, instead please use http://piwik.org/download for stable releases and http://builds.piwik.org/ for betas and RC releases.

@mattab re the GitHub releases: Can we attach the built zip there where tests etc are removed or alternatively disable downloads there?

**Comment by ThaDafinser** [comment] 2015-10-29 10:21
It's possible to add files to the release: https://help.github.com/articles/creating-releases/

> If you'd like to include binary files along with your release, such as compiled programs, drag and drop or select files manually in the binaries box.

**Comment by tsteur** [comment] 2015-10-29 19:49
I think the releases are created with a script, but I'm sure there's also an API for that. I will create an issue for it

**Comment by tsteur** [comment] 2015-11-02 19:44
This issue is fixed by https://github.com/piwik/piwik/pull/9142 and a duplicate of https://github.com/piwik/piwik/pull/9130

@adminkpr It should be fixed by overwriting your piwik.js in the Piwik directory with this: https://raw.githubusercontent.com/piwik/piwik/9130/piwik.js

The website overwrites `JSON` caused by http://mootools.net/core/docs/1.5.2/Utilities/JSON

**Closed by tsteur** 2015-11-02 19:44 UTC
Labels: duplicate

**Comment by tsteur** [comment] 2015-11-02 19:45
@adminkpr thx for providing us access to your instance. You can remove our account again from your Piwik. 

BTW: There's another unrelated JavaScript error on your actual website of idSite 10

**Comment by adminkpr** [comment] 2015-11-02 20:04
There is nothing on this link https://raw.githubusercontent.com/piwik/piwik/9130/piwik.js

**Comment by sgiehl** [comment] 2015-11-02 20:07
that was already merged to master. so use https://raw.githubusercontent.com/piwik/piwik/master/piwik.js
