### ISSUE TITLE
Add new metrics to Custom Report (Premium Plugin)

### ISSUE THREAD

**Issue by jr-ewing** [piwik/piwik#21032] opened 2023-07-19 07:35 UTC
I am using the Custom Report Plugin. The filters in the segments have been changed since Matomo 3.12. This plugin is actively recommended here to segment pages. Now I keep having the problem that I want to replicate a page report 1:1 like under Pages. 
But I am missing some fields like:

- Time spent on page
- Exits
- Entrances

See also:
#15438
#17046 

https://forum.matomo.org/t/costum-reports-metrics/33245
https://forum.matomo.org/t/durchschnittliche-verweildauer-fur-custom-reports/46346/3
...

![image](https://github.com/matomo-org/matomo/assets/192153/68412ddf-47c3-4230-b685-8a6fb3c77caf)

The Matomo support refers me here to the tickets from above. However, I believe that some of the users also have this problem and that's why they might not buy the Custom Report Plugin. In 80% of my projects this is desired.

**Comment by michalkleiner** [comment] 2023-07-24 13:23
Partial duplicate of #20694 but asks for the average time spent as well. @Stan-vw I'll leave it up to you if you want to merge them and close one or keep both, but it's becoming apparent that there are dimensions we could enable/add to core to enable their use in the Custom Reports plugin.

**Comment by Stan-vw** [comment] 2023-07-27 04:11
Just checking if I'm missing something, to me this seems like a full duplicate (when comparing to the separate tickets for 1) time spent and 2) entries/exits). Is there anything in this ticket that is not mentioned in the separate tickets?

Mainly asking since it's easier to keep separate items in separate tickets, so we can schedule them separately in our sprints. Large tickets with multiple items in them are less likely to make it into the upcoming/current sprints, as they always take more time to figure out exactly what needs to happen, and they get higher storypoints which makes them more difficult to plan with.

Closing for now, but feel free to reopen if there's anything that's specifically only mentioned in this ticket.

**Closed as completed by Stan-vw** 2023-07-27 04:11 UTC
Labels: Enhancement, duplicate
