### ISSUE TITLE
Scheduled Reports not sending

### ISSUE THREAD

**Issue by rmoesbergen** [piwik/piwik#8320] opened 2015-07-10 08:15 UTC
I'm experiencing an issue with scheduled e-mail reports not being sent by piwik. We have several users who receive e-mail reports on a daily basis, so e-mail settings etc. are OK. However, other users (myself included) have created reports, but never receive them. Manually sending the report (clicking 'send report now') works just fine. I've created a separate cronjob to run all scheduled tasks every hour with debugging enabled (-vvv). The output is as follows:

DEBUG [2015-06-30 23:05:01] Loaded plugins: CorePluginsAdmin, CoreAdminHome, CoreHome, CoreVisualizations, Proxy, API, Widgetize, Transitions, LanguagesManager, Actions, Dashboard, MultiSites, Referrers, UserSettings, UserLanguage, DevicesDetection, SEO, Events, UserCountry, VisitsSummary, VisitFrequency, VisitTime, VisitorInterest, Provider, Monolog, Login, UsersManager, SitesManager, Installation, CoreUpdater, CoreConsole, ScheduledReports, UserCountryMap, Live, CustomVariables, PrivacyManager, ImageGraph, Annotations, MobileMessaging, Overlay, SegmentEditor, Insights, ZenMode, LeftMenu, Morpheus, Contents, BulkTracking, Resolution, DevicePlugins, Bandwidth, BotTracker
DEBUG [2015-06-30 23:05:01] 22 scheduled tasks loaded
INFO [2015-06-30 23:05:01] Starting Scheduled tasks...
DEBUG [2015-06-30 23:05:01] Executing tasks with priority 0:
DEBUG [2015-06-30 23:05:01] Executing tasks with priority 1:
DEBUG [2015-06-30 23:05:01] Executing tasks with priority 2:
DEBUG [2015-06-30 23:05:01] Executing tasks with priority 3:
DEBUG [2015-06-30 23:05:01] Executing tasks with priority 4:
DEBUG [2015-06-30 23:05:01] Executing tasks with priority 5:
DEBUG [2015-06-30 23:05:01] Executing tasks with priority 6:
DEBUG [2015-06-30 23:05:01] Task Piwik\Plugins\ScheduledReports\API.sendReport_3 is scheduled to run again for 2015-07-01.
INFO [2015-06-30 23:05:01] Scheduler: executing task Piwik\Plugins\ScheduledReports\API.sendReport_3...
DEBUG [2015-06-30 23:05:01] Running task Piwik\Plugins\ScheduledReports\API.sendReport_3
INFO [2015-06-30 23:05:02] Scheduler: finished. Time elapsed: 0.441s
DEBUG [2015-06-30 23:05:02] Task Piwik\Plugins\ScheduledReports\API.sendReport_4 is scheduled to run again for 2015-07-01.
INFO [2015-06-30 23:05:02] Scheduler: executing task Piwik\Plugins\ScheduledReports\API.sendReport_4...
DEBUG [2015-06-30 23:05:02] Running task Piwik\Plugins\ScheduledReports\API.sendReport_4
INFO [2015-06-30 23:05:02] Scheduler: finished. Time elapsed: 0.001s
DEBUG [2015-06-30 23:05:02] Task Piwik\Plugins\ScheduledReports\API.sendReport_10 is scheduled to run again for 2015-07-01.
INFO [2015-06-30 23:05:02] Scheduler: executing task Piwik\Plugins\ScheduledReports\API.sendReport_10...
DEBUG [2015-06-30 23:05:02] Running task Piwik\Plugins\ScheduledReports\API.sendReport_10
WARNING [2015-06-30 23:05:08] Preventing the same scheduled report from being sent again (report #10 for period "2015, Mei"winking smiley
INFO [2015-06-30 23:05:08] Scheduler: finished. Time elapsed: 5.946s
DEBUG [2015-06-30 23:05:08] Task Piwik\Plugins\ScheduledReports\API.sendReport_11 is scheduled to run again for 2015-07-01.
INFO [2015-06-30 23:05:08] Scheduler: executing task Piwik\Plugins\ScheduledReports\API.sendReport_11...
DEBUG [2015-06-30 23:05:08] Running task Piwik\Plugins\ScheduledReports\API.sendReport_11
INFO [2015-06-30 23:05:08] Scheduler: finished. Time elapsed: 0.002s
DEBUG [2015-06-30 23:05:08] Task Piwik\Plugins\ScheduledReports\API.sendReport_13 is scheduled to run again for 2015-07-01.
INFO [2015-06-30 23:05:08] Scheduler: executing task Piwik\Plugins\ScheduledReports\API.sendReport_13...
DEBUG [2015-06-30 23:05:08] Running task Piwik\Plugins\ScheduledReports\API.sendReport_13
WARNING [2015-06-30 23:05:10] /export/www/piwik/html/libs/Zend/Validate/Hostname.php(549): Deprecated - iconv_set_encoding(): Use of iconv.internal_encoding is deprecated - Piwik 2.13.1 - Please report this message in the Piwik forums: [forum.piwik.org] (please do a search first as it might have been reported already)
WARNING [2015-06-30 23:05:10] /export/www/piwik/html/libs/Zend/Validate/Hostname.php(645): Deprecated - iconv_set_encoding(): Use of iconv.internal_encoding is deprecated - Piwik 2.13.1 - Please report this message in the Piwik forums: [forum.piwik.org] (please do a search first as it might have been reported already)
INFO [2015-06-30 23:05:10] Scheduler: finished. Time elapsed: 2.256s
DEBUG [2015-06-30 23:05:10] Task Piwik\Plugins\ScheduledReports\API.sendReport_14 is scheduled to run again for 2015-07-01.
INFO [2015-06-30 23:05:10] Scheduler: executing task Piwik\Plugins\ScheduledReports\API.sendReport_14...
DEBUG [2015-06-30 23:05:10] Running task Piwik\Plugins\ScheduledReports\API.sendReport_14
WARNING [2015-06-30 23:05:12] /export/www/piwik/html/libs/Zend/Validate/Hostname.php(549): Deprecated - iconv_set_encoding(): Use of iconv.internal_encoding is deprecated - Piwik 2.13.1 - Please report this message in the Piwik forums: [forum.piwik.org] (please do a search first as it might have been reported already)
WARNING [2015-06-30 23:05:12] /export/www/piwik/html/libs/Zend/Validate/Hostname.php(645): Deprecated - iconv_set_encoding(): Use of iconv.internal_encoding is deprecated - Piwik 2.13.1 - Please report this message in the Piwik forums: [forum.piwik.org] (please do a search first as it might have been reported already)
INFO [2015-06-30 23:05:12] Scheduler: finished. Time elapsed: 1.866s
DEBUG [2015-06-30 23:05:12] Task Piwik\Plugins\ScheduledReports\API.sendReport_15 is scheduled to run again for 2015-07-01.
INFO [2015-06-30 23:05:12] Scheduler: executing task Piwik\Plugins\ScheduledReports\API.sendReport_15...
DEBUG [2015-06-30 23:05:12] Running task Piwik\Plugins\ScheduledReports\API.sendReport_15
WARNING [2015-06-30 23:05:14] /export/www/piwik/html/libs/Zend/Validate/Hostname.php(549): Deprecated - iconv_set_encoding(): Use of iconv.internal_encoding is deprecated - Piwik 2.13.1 - Please report this message in the Piwik forums: [forum.piwik.org] (please do a search first as it might have been reported already)
WARNING [2015-06-30 23:05:14] /export/www/piwik/html/libs/Zend/Validate/Hostname.php(645): Deprecated - iconv_set_encoding(): Use of iconv.internal_encoding is deprecated - Piwik 2.13.1 - Please report this message in the Piwik forums: [forum.piwik.org] (please do a search first as it might have been reported already)
INFO [2015-06-30 23:05:14] Scheduler: finished. Time elapsed: 1.965s
DEBUG [2015-06-30 23:05:14] Executing tasks with priority 7:
DEBUG [2015-06-30 23:05:14] Executing tasks with priority 8:
DEBUG [2015-06-30 23:05:14] Executing tasks with priority 9:
DEBUG [2015-06-30 23:05:14] Executing tasks with priority 10:
DEBUG [2015-06-30 23:05:14] Executing tasks with priority 11:
DEBUG [2015-06-30 23:05:14] Executing tasks with priority 12:
INFO [2015-06-30 23:05:14] done

So there are no errors reported. Are the Id's mentioned in the logs the same id's as the 'idreport' column in the piwik_report table? If so, 'my' report has report-id 11. The report is scheduled to run daily and 'sent to me' is enabled. How can I debug this issue?

**Comment by mattab** [comment] 2015-07-15 16:26
Hi @rmoesbergen 

thx for the report. Can you please post your information in the other ticket that is duplicate of your issue: #8092 - cheers

**Closed by mattab** 2015-07-15 16:26 UTC
