### ISSUE TITLE
Show "content interactions" in vistor log

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#10052] opened 2016-04-14 13:03 UTC
Content tracking is a good thing! (For details see: https://piwik.org/docs/content-tracking/)
To get even more informations from this implementation, it would be good to **show "content interactions" in visitor log** similar to events (maybe only using another symbol)

This would give the **possibility to understand** which **way** the visitor has taken to go from one site to an other:
- does he use the mega-drop-down menu in head of page?
- does he use the "related article links" located at the end of the article?
- does he use the "next article" link?
- does he use the news box on the right side?
- does he use the links within the text of the article?

**Comment by hpvd** [comment] 2016-04-14 16:30
in addition to understand which way a user uses, **it gives an inside about his motivation:**
Just an example:
if he uses "related article links" which shows name and image of an related article, he is much more focused and intersted in the content of the related article
than if he uses "next article" link which brings him to an unpreknown type of artikle...

**Comment by tsteur** [comment] 2016-04-14 21:18
Thanks @hpvd I'll mark this one as a duplicate of https://github.com/piwik/piwik/issues/6416

We'll have a look at this one again when working on #6416

**Closed by tsteur** 2016-04-14 21:18 UTC

**Comment by hpvd** [comment] 2016-04-18 06:10
an idea how this can look:
![2016-04-18_08h00_18](https://cloud.githubusercontent.com/assets/5681880/14595128/0e8a4138-053d-11e6-8413-dff5739e30f1.png)
