### ISSUE TITLE
Not able to create annotations since one of the recent updates

### ISSUE THREAD

**Issue by zigojacko** [piwik/piwik#20647] opened 2023-04-30 11:16 UTC
When trying to create a new annotation, nothing happens when you click the 'Save' button (it just disappears and does not add).

No errors in console.

I was adding them in March so this has stopped working recently.

I have tested in multiple browsers as well to make sure not browser specific and unable to add them in Edge neither as well as Chromium based browsers.

**Comment by Stan-vw** [comment] 2023-04-30 23:37
I tried reproducing this, but it seems to be working fine for me on Cloud in Chrome.
Can you tell us more about your Matomo environment?

**Comment by zigojacko** [comment] 2023-05-01 08:30
> I tried reproducing this, but it seems to be working fine for me on Cloud in Chrome. Can you tell us more about your Matomo environment?

This is really strange but I have checked this again today and all of the annotations I tried adding yesterday now appear in the list yet I just tried adding one again now and it doesn't show - even after refreshing the page. But clearly they are getting added and seemingly take a while to show up. Bit odd. 🤔

Matomo 4.14.2 on a CentOs (7.9) Linux server running Plesk with PHP 8.2 if of any use.

Not really an issue if they are going to eventually show up but just a bit strange. It's been several minutes since I tried adding one and still no show.

**Comment by Stan-vw** [comment] 2023-05-01 23:12
Will close this for now, as it seems to be working (albeit not in realtime for everyone). Feel free to reopen in case they haven't come along 24 hours later.
Alternatively, you could change the ticket to something like "Annotations don't show up immediately" so it's clear that it's working but not as quickly as it should.

**Closed as completed by Stan-vw** 2023-05-01 23:12 UTC
Labels: answered
