### ISSUE TITLE
Trouble with "check system": Entry Piwik\Plugins\Diagnostics\DiagnosticService cannot be resolved:

### ISSUE THREAD

**Issue by simpleuser99** [piwik/piwik#8014] opened 2015-05-28 07:06 UTC
Hello!
 When I click on "check system" I see next messages:

Entry Piwik\Plugins\Diagnostics\DiagnosticService cannot be resolved: The parameter 'mandatoryDiagnostics' of Piwik\Plugins\Diagnostics\DiagnosticService::__construct has no value defined or guessableFull definition:Object ( class = Piwik\Plugins\Diagnostics\DiagnosticService scope = singleton lazy = false __construct( $mandatoryDiagnostics = #UNDEFINED# $optionalDiagnostics = #UNDEFINED# $disabledDiagnostics = #UNDEFINED# ))

Please,help me. How can I fix it?
P.S. I use piwik version 2.13.1

**Comment by mnapoli** [comment] 2015-05-28 14:47
Is it during the installation or in the admin section? In any case this looks like a classic error of files that were not all uploaded, could you try uploading the latest Piwik version manually?

**Comment by mnapoli** [comment] 2015-05-28 14:52
Closing preemptively, we'll reopen if there is indeed a bug.

**Comment by simpleuser99** [comment] 2015-05-29 09:56
Is it happen in the admin section. I uploaded the latest Piwik version manually by the http://piwik.org/docs/update/ instruction "The Manual Three-Step Update" and I have the same problem.

**Comment by mnapoli** [comment] 2015-05-29 09:59
Could you check that the `Diagnostics` plugin is activated in the administration? Maybe the upgrade to 2.13.1 (which should have activated this plugin) failed somehow. You can activate the plugin manually with the following command: `./console plugin:activate Diagnostics` (or manually in your config.ini.php)

**Comment by simpleuser99** [comment] 2015-06-08 08:21
Thank you! Diagnostics plugin was deactivated. I activate it and i don't have problem already

**Comment by mattab** [comment] 2015-06-08 09:42
Maybe we can make Piwik core work when the Diagnostics plugin is disabled?

**Comment by simpleuser99** [comment] 2015-06-08 10:01
I use Piwik without problem, except "check system" on admin panel

**Comment by mnapoli** [comment] 2015-06-08 11:12
@mattab the system check is the first step of the installation

**Comment by mattab** [comment] 2015-06-08 11:25
maybe user had the warning message in the other place: Administration > System check?

**Comment by mnapoli** [comment] 2015-06-08 11:37
I think we are discussing about different things. The diagnostics plugin provide the system check feature. That plugin is mandatory and enabled by default.

What was most probably experienced here (see the comments above) is that the upgrade to Piwik 2.13 was done but somehow the upgrade script didn't run correctly and didn't active the diagnostics plugin, leaving Piwik in a corrupted state.

**Comment by mattab** [comment] 2015-06-08 11:45
>  That plugin is mandatory and enabled by default.

Ok, if Piwik breaks when this plugin is deactivated, we can enforce it being always activated by adding it to: `$pluginToAlwaysActivate` array in Plugin\Manager. likely we missed this in the review?

**Comment by mnapoli** [comment] 2015-06-08 12:06
OK I thought that adding it to `global.ini.php` was enough. I'm adding it to `$pluginToAlwaysActivate` then.

**Closed** 2015-06-08 12:07 UTC
Labels: answered

**Comment by jmaupetit** [comment] 2015-07-20 10:32
Hi there. This problem still occurs during installation phase with 2.14.1 How can I help you to debug this?

**Comment by mnapoli** [comment] 2015-07-20 10:42
@jmaupetit could you check that everything was uploaded correctly? If you are installing Piwik from scratch, the "system check" should show a warning if some files were not uploaded correctly (if you have no warning there, it's good).

If you are updating Piwik, it sometimes fails to overwrite all files. What you can do is reupload Piwik manually.

If after that you still have the problem let me know

**Comment by jmaupetit** [comment] 2015-07-20 13:18
Thank you for the reply. I was upgrading Piwik inside a Docker container and the container cache trapped me! Sorry for the noise.

**Comment by larsen0815** [comment] 2015-07-30 14:04
I am experiencing this error with 2.14.2 (manually updated via SSH using latest.zip) when I go to "Administration > Diagnostic > System Check".

The console command tells me "The plugin is already activated."
In "config/config.ini.php" 'there is "PluginsInstalled[] = "Diagnostics"'.

**Comment by mnapoli** [comment] 2015-07-30 15:36
@larsen0815 Could you trying reuploading the latest version of Piwik manually? (there are often issues with the updater). If the issue is still there, could you create a separate issue? (and try to run the command `diagnostics:run` and tell us what happen?)

**Comment by larsen0815** [comment] 2015-08-03 09:20
Created ticket https://github.com/piwik/piwik/issues/8479
