### ISSUE TITLE
Report for a single website mismatches the "Sent from" website with another

### ISSUE THREAD

**Issue by ghost** [piwik/piwik#19301] opened 2022-06-01 12:39 UTC
On single matomo 4.10.1 instance we track ~10 websites, each from its specific url like https://track.dns1.tld

In the automated monthly report, all data are coherent except the "sent from" website that shows another one.

## Expected Behavior
The report should show the tracker from the website it tracks

## Current Behavior
1. report one sent for dns1.tld with "sent from" dns45.tld + noreply@dns45.tld
2. report two sent for dns2.tld with "sent from" dns13.tld + noreply@dns45.tld
3. etc.

## Steps to Reproduce (for Bugs)
1. just setup a monthly report for a website to one ore more recipients

## Context
Matomo used in french in Firefox nightly, UI currently broken, saying:
"The string General_Description was not loaded in javascript. Make sure it is added in the Translate.getClientSideTranslationKeys hook."

## Your Environment
Matomo: 4.10.1
MySQL: 5.7.30-log
PHP: 7.4.28

**Comment by Findus23** [comment] 2022-06-01 14:02
This is caused by the same issue as https://github.com/matomo-org/matomo/issues/14583 

@justinvelluppillai maybe this could be added to the schedule for the next releases as it makes URLs in Matomo completly random if one uses multiple `matomo.sitename.example` urls that point at the same Matomo instance.

**Comment by ghost** [comment] 2022-06-01 14:38
Indeed, sorry I did not look for such an old issue as #14583 but it's the same, that appeared with the upgrade to 4.10 in my case.

**Comment by Findus23** [comment] 2022-06-02 20:07
No problem, it also took me quite a while to find it again.

**Comment by justinvelluppillai** [comment] 2022-06-03 01:13
Thanks for the report @laurentelgard , I will add it to the queue for Product Team to prioritize soon.

**Comment by ghost** [comment] 2022-06-03 01:17
> Thanks for the report @laurentelgard , I will add it to the queue for Product Team to prioritize soon.

Thank you @justinvelluppillai, it's a real problem when different clients receive their report with another website "from", but you know it.
Hope this will come soon, can not use the report module right now.

**Comment by michalkleiner** [comment] 2024-05-05 06:57
Closing this as it's been already identified it'll be resolved when https://github.com/matomo-org/matomo/issues/14583 is resolved.

**Closed as not planned by michalkleiner** 2024-05-05 06:57 UTC
Labels: duplicate
