### ISSUE TITLE
receiving a sqlstate[42s22] column not found error upon trying to create a measurable

### ISSUE THREAD

**Issue by aloyr** [piwik/piwik#20808] opened 2023-05-30 22:04 UTC
upon trying to create a new measurable website, i receive the following error message:

sqlstate[42s22]: Column not found: 1054 unknown column 'description' in 'field list'

i've contacted matomo support and they instructed me to create a ticket here.

![Picture1](https://github.com/matomo-org/matomo/assets/231727/7d705700-5944-4a40-8956-9495bbbe16b0)

**Comment by heurteph-ei** [comment] 2023-05-31 09:22
Hi @aloyr 
Which Matomo version do you run?
When was the last update? Did you try to install or remove some plugin recently?
Did the measurable creation worked before?

Can you try the following command:
```
$ ./path/to/matomo/console core:update --yes
```

**Comment by sgiehl** [comment] 2023-05-31 13:20
This sounds like a duplicate of https://github.com/matomo-org/matomo/issues/19886
That should be meanwhile fixed and we even added some changes lately to prevent that better.
The linked issue should contain some details how to fix that.

**Closed as not planned by sgiehl** 2023-05-31 13:20 UTC
Labels: duplicate
