### ISSUE TITLE
Administration's Users tab new UI suggestion for better UX

### ISSUE THREAD

**Issue by shahar3012** [piwik/piwik#8514] opened 2015-08-07 19:49 UTC
Hi,

I'm using Piwik (currently 2.14.3) and one of the biggest UX failure I found is the Administration's Users tab, it designed as 3 lists without considering that a Piwik instance could have a lot of users.

I have about 100 users on the test evniroment in my organization and it's very annoying to go through the long list.

I'm working closely with the UX team in my organization. They suggested to change how Piwik displays the users lists, which include:
* Website permission list
* Users list (for management purposes)
* Super user permission list. 

All of above are currently displayed as a vertical list, multiple by 3 lists, each one below the other, cause the height of the page to be enormous.

**They suggested to add an option to collapse each list or to add 3 tabs inside the page in order to show one list at a time, with the option to switch between the tabs and change the list that is currently shown.**

Please consider this change in the future versions of Piwik.
How it's displayed right, isn't a good user experience.

**Comment by tsteur** [comment] 2015-08-10 08:25
I will close this as a duplicate of #6187. Please comment or reopen in case it is not a duplicate. Thx!

**Closed by tsteur** 2015-08-10 08:25 UTC
Labels: duplicate

**Comment by shahar3012** [comment] 2015-08-18 17:31
It a suggestion, so please take one more time and go over it.
I see it different from the issue you've mentioned.
Yet, the other issue wasn't implemented, although it was opened a year ago..
So I believe there is a place for reconsidering my suggestion.

**Comment by tsteur** [comment] 2015-08-19 06:56
I took one more time and went over it re the tabs. It is a good idea and less work than the other suggestion but somehow also a bit more work since we're usually not using tabs so far. The idea is to make it even more usable by kinda merging the 3 into one thing. I will mention your suggestion and link to this issue in the other suggestion
