### ISSUE TITLE
Feature request: Quarterly reports

### ISSUE THREAD

**Issue by Birkaransingh94** [piwik/piwik#20981] opened 2023-07-07 05:10 UTC
Feature request: It will be nice to have an option for quarterly reports.

**Comment by michalkleiner** [comment] 2023-07-08 01:38
Thanks for the suggestion @Birkaransingh94. I'll move this to PO for prioritisation but if there's more info, more context etc, please feel to add it here or internally.

**Comment by Stan-vw** [comment] 2023-07-09 22:35
This seems like a duplicate of https://github.com/matomo-org/matomo/issues/20418 so I'll close this ticket.
Feel free to reopen if it's a different request.

**Closed as completed by Stan-vw** 2023-07-09 22:35 UTC
Labels: duplicate
