### ISSUE TITLE
Add an option to make events not counted as an interaction

### ISSUE THREAD

**Issue by Chardonneaur** [piwik/piwik#17717] opened 2021-06-28 15:22 UTC
In Google Analytics, there is an option (a binary one, 0 true, 1 false) in order to say if the event has to be counted as an interaction or not.
The typical use case is the following one, the visitor lands on a page, do nothing, a pop-up came out automatically and is measured as an event... why would it be an interaction as this is not coming from the visitor?
So the idea would be to have something like in GA with,
ga('send', 'event', 'Videos', 'play', 'Fall Campaign', {
  nonInteraction: true
});
hope that helps.

**Comment by tsteur** [comment] 2021-06-28 20:08
Hi @Chardonneaur thanks for creating this issue. I'll close this as a duplicate of https://github.com/matomo-org/matomo/issues/9199

**Closed as completed by tsteur** 2021-06-28 20:08 UTC
Labels: duplicate
