### ISSUE TITLE
Documention for Google Shopping & Adwords tracking

### ISSUE THREAD

**Issue by websnail** [piwik/piwik#10151] opened 2016-05-15 08:23 UTC
As per this forum topic.
https://forum.piwik.org/t/adwords-google-shopping-tracking-guide-for-idiots-ie-me/18037

I'm finding it difficult to transfer the information provided for general adwords campaign tracking and applying it to Google Merchant/Froogle/Shopping campaigns.

I'm unsure if this is because the current documentation is out of date, doesn't cover the topic or if I'm simply missing something but, as per the forum thread, I was advised to create an issue here so it can be addressed or an answer provided.

Thanks in advance for any info/response.

**Comment by tsteur** [comment] 2016-05-16 19:00
I think so far the only documentation we have about this are the ones linked in the forum post eg http://piwik.org/docs/tracking-campaigns/ and https://piwik.pro/2015/05/piwik-url-tagging-best-practices/?pk_source=Piwik.org&pk_medium=Banner_link&pk_campaign=PO_Explore_Piwik_Pro . I will close this issue as a duplicate of https://github.com/piwik/piwik/issues/8348 . Feel free to comment there.

**Closed by tsteur** 2016-05-16 19:00 UTC
