### ISSUE TITLE
Have a message in the UI after install saying this plugin does not track to Cloud

### ISSUE THREAD

**Issue by jmumby** [piwik/piwik#19028] opened 2022-03-15 04:16 UTC
There is a bit of confusion for customers when it comes to trialling cloud and Matomo for Wordpress. Users will for example install Matomo for WordPress and then mention there is no tracking in the cloud.

It would be good to have an admin notice congratulating the user on installing Matomo and that it does not track to the Cloud for example. 

![image](https://user-images.githubusercontent.com/4339071/158305228-36608394-8e88-4f95-908d-1cd4e78cadaf.png)

**Comment by tsteur** [comment] 2022-03-16 22:05
@jmumby I've updated the WordPress plugin description so it'll become slightly more clear. 

I've also thought about your suggestion for a while as I'm not 100% sure where to display it, for how long it should be displayed, and whether it would really help. I wouldn't do it for now but instead do a likely more effective solution:

* Update the guide (done this already)
* Update the product (details see below)

In the "No Data" screen, when we detect a WordPress site is configured as URL, then we currently show below:

<img width="984" alt="image" src="https://user-images.githubusercontent.com/273120/158698403-daac70eb-cb4c-41e6-bda5-885df67228c7.png">

* On above screenshot make it more clear to follow the instructions from the guide and that it will require the "WP-Matomo" plugin (we could even link to it). For example `Simply [follow the instructions from this guide](https://matomo.org/faq/new-to-piwik/how-do-i-install-the-matomo-tracking-code-on-wordpress/#wpmatomo) to install the [WP-Matomo plugin](https://wordpress.org/plugins/wp-piwik/)  `. This has two critical changes. 1. Linking to `#wpmatomo` directly to the right content. 2. Mentioning WP-Matomo plugin is needed so people can skip the guide and directly go to the right plugin. We could also mention that "Matomo Analytics – Ethical Stats. Powerful Insights.` plugin, not sure if it makes sense.
* As we can detect WordPress sites, and no data has been tracked, we could show in the "No Data" page another sentence saying something like "Set up the WordPress plugin already and not seeing any data?". And then in the content or in an FAQ mention it might be because the wrong plugin is installed and mention the correct plugin.
* Above behaviour needs to be configurable as in Matomo for WordPress we would not want to mention "WP-Matomo" as they shouldn't use that plugin and they wouldn't use the wrong plugin accidentally.

Those would be some easy changes that will confuse people less. I reckon that this will help more than the changes in Matomo for WordPress that can be missed easily.

**Comment by tsteur** [comment] 2022-03-30 23:16
Note: we're getting issue multiple times per week in support which is why we'd like to improve this so people won't install the wrong plugin anymore and so they will keep using Matomo

**Comment by sgiehl** [comment] 2022-07-25 13:13
@tsteur I've implemented some changes for this in #19401. The instruction page for a wordpress site now looks like this:

![image](https://user-images.githubusercontent.com/1579355/180784694-fd7d5b49-fd93-4209-ba36-436542b2df44.png)

The `our FAQs for help` link currently points to `https://matomo.org/guide/installation-maintenance/matomo-for-wordpress/`.

Let me know if that should be changed / improved any further. The requirements above are a bit unspecific.

**Comment by tsteur** [comment] 2022-07-25 14:04
@sgiehl for `our FAQs for help` we would need to create a new FAQ explaining that they may have installed the wrong plugin.  We could mention that if they have installed [Matomo for WordPress](https://wordpress.org/plugins/matomo/) then they installed the wrong plugin and need to instead install the other one. We could advise them to uninstall Matomo for WordPress, then follow the steps to set up WP-Matomo. Eventually we could mention even more steps why it might not be tracking like "They might have a filter enabled to not track logged in users or certain roles" etc.

We would also need to implement this part:

> Above behaviour needs to be configurable as in Matomo for WordPress we would not want to mention "WP-Matomo" as they shouldn't use that plugin and they wouldn't use the wrong plugin accidentally.

Or better would be: adjust the logic if `SettingsServer::isMatomoForWordPress()===true then not mention WP-Matomo and show it as it was previosuly`  because then they don't need `WP-Matomo` plugin as Matomo for WordPress can fully track data by itself and we would show how it was previously.

Does this help?

**Comment by sgiehl** [comment] 2022-07-25 16:05
@tsteur I'm happy to adjust the text if anyone provides the text I should add. I'm not very deep into the Matomo for Wordpress stuff, so I'm not aware of the possible problems or solutions, so I think it's better if someone else provides a useful text for that.
Same applies for the FAQ. If anyone creates one, I'm happy to adjust the link accordingly.

> Or better would be: adjust the logic if SettingsServer::isMatomoForWordPress()===true then not mention WP-Matomo and show it as it was previosuly because then they don't need WP-Matomo plugin as Matomo for WordPress can fully track data by itself and we would show how it was previously.

will do that.

**Comment by tsteur** [comment] 2022-07-26 07:43
@sgiehl we wouldn't need to be into Matomo for WordPress. The problem is that you can't use [Matomo for WordPress](https://wordpress.org/plugins/matomo/) when using On-Premise or the Cloud. In that case they would need to make sure to use [WP-Matomo](https://wordpress.org/plugins/wp-piwik/).

What @jmumby mentions is that people sometimes install the wrong WordPress plugin and are then wondering why no data appears.

**Comment by sgiehl** [comment] 2022-07-26 07:50
I understood that. I'm happy to adjust the wording and the link. But I'm pretty sure that it is easier for someone, who better knows what people are asking or have a feeling for their needs, to pick a good text to place in that case. Also I won't create a FAQ for that for similar reasons.

So once anyone provides the text we should place into Matomo and a link to an existing FAQ, I will adjust the PR accordingly. (ping @justinvelluppillai)

**Comment by justinvelluppillai** [comment] 2022-07-27 00:29
@jmumby has good insight into the user issues we're trying to solve here and is happy to create the supporting FAQ and text changes. @jmumby if you can please let @sgiehl know if anything needs clarification here or otherwise a link to the FAQ and text to include in app we can close this out.

**Comment by justinvelluppillai** [comment] 2022-08-09 02:21
Hi @jmumby just checking in for an update when you think you might have time to action this?

**Comment by justinvelluppillai** [comment] 2022-08-12 01:41
@sgiehl here is the new FAQ: https://matomo.org/faq/how-to-install/which-plugin-should-i-use-with-wordpress/

**Comment by sgiehl** [comment] 2022-08-12 08:06
Ok. I've adjusted the link. So if we detect a wordpress site we would now show:

- in case Matomo for Wordpress is being used:
![screen](https://user-images.githubusercontent.com/1579355/184311706-2a392066-e3ec-475c-b7f7-3d737a21b61d.png)

- If normal Matomo is used:
![screen](https://user-images.githubusercontent.com/1579355/184312020-69d2c8e5-b9f7-45e8-9737-8d9823f7a8bf.png)

Let me know if anything should be changed. If not I'll put the PR into review, so we get this merged for 4.12.

**Comment by justinvelluppillai** [comment] 2022-08-12 08:10
Looks good @sgiehl. Let's proceed and see what impact it has. @jmumby can reopen the issue or create a new one if needed later for further improvements here

**Closed as completed** 2022-08-16 11:36 UTC
Labels: Enhancement, c: Onboarding
