### ISSUE TITLE
PDF reports showing wrongly 

### ISSUE THREAD

**Issue by seemsneat** [piwik/piwik#9464] opened 2016-01-03 21:12 UTC
Generated reports shows disorderly including big logo, charts on multiple pages and so on. I'm attaching current PDF and PDF which I want to see.
[piwik.export.currently.pdf](https://github.com/piwik/piwik/files/76750/piwik.export.currently.pdf)
[piwik.export.target.pdf](https://github.com/piwik/piwik/files/76751/piwik.export.target.pdf)

**Comment by sgiehl** [comment] 2016-01-03 21:22
Thanks for your suggestions. Maybe a first start to make such "custom" reports possible, would be to work with kind of pdf templates. Otherwise it won't be possible to insert a nice looking custom header and/or footer on every page.
I'm not sure if the library we are using to create the pdf allows using templates. Guess we need to have a closer look to check if that is possible...

**Comment by seemsneat** [comment] 2016-01-04 09:36
Hi, when you think you will look at this?

**Comment by tsteur** [comment] 2016-01-10 20:53
This might be kinda a duplicate of https://github.com/piwik/piwik/issues/9351 ?

#9351 kinda focuses on one time export but it should be also possible to have similar features for automated, regular exports

**Comment by mattab** [comment] 2016-01-12 01:50
thanks for the suggestion, please post your suggestions in https://github.com/piwik/piwik/issues/9191

**Closed by mattab** 2016-01-12 01:50 UTC
