### ISSUE TITLE
Visits Over Time widget bug when clicking on current day twice

### ISSUE THREAD

**Issue by minos314** [piwik/piwik#10735] opened 2016-10-13 15:07 UTC
The Visits Over Time widget causes an error when a user tries to navigate to the current day by clicking to the rightmost datapoint in the graph.

![piwik_visits_over_time_bug](https://cloud.githubusercontent.com/assets/21129886/19354404/dece24f8-9166-11e6-968e-5c0a815966ab.png)

When I click that point once it work (site reloades, url changes slightly), but when i click that butten the second time an error occurs.

To reproduce simply visit http://demo.piwik.org and click the rightmost datapoint in the graph more than once.

**Comment by sgiehl** [comment] 2016-10-13 21:06
I'm able to reproduce that. the hash in the url seems to get broken in that case. the `#?module=` gets replaced with `#/module=`.

**Comment by sgiehl** [comment] 2016-10-13 21:08
Side note: This issue seems to be already fixed in 3.x

**Comment by mattab** [comment] 2016-11-11 04:48
> Side note: This issue seems to be already fixed in 3.x

Thanks for checking @sgiehl - marking as fixed!

**Closed by mattab** 2016-11-11 04:48 UTC
Labels: Bug
