### ISSUE TITLE
Huge query on Matomo hundreds of thousands of rows on repeat

### ISSUE THREAD

**Issue by StevieKay90** [piwik/piwik#17376] opened 2021-03-22 20:34 UTC
We have an issue where the following query, seemingly on repeat is pushing our db requirements for Matamo through the roof;

SELECT `visit_last_action_time` , `visit_first_action_time` , `idvisitor` , `idvisit` , `user_id` , `visit_exit_idaction_url` , `visit_exit_idaction_name` , `visitor_returning` , `visitor_seconds_since_first` , `visitor_seconds_since_order` , `visitor_count_visits` , `visit_goal_buyer` , `location_country` , `location_region` , `location_city` , `location_latitude` , `location_longitude` , `referer_name` , `referer_keyword` , `referer_type` , `idsite` , `profilable` , `visit_entry_idaction_url` 

we have disabled all plugins and this query still runs ad nauesum

## Expected Behavior

Massive query should not be on repeat

## Current Behavior

At present we required a lot of extra resource to run our Matomo instance. On RDS we notice a vast query which was seemingly on repeat over and over;

<img width="960" alt="image (2)" src="https://user-images.githubusercontent.com/80366750/112052692-50d6e200-8b4b-11eb-8e0b-2b2aecc43217.png">

<img width="960" alt="image (4)" src="https://user-images.githubusercontent.com/80366750/112054309-503f4b00-8b4d-11eb-8753-aa402dced21b.png">

## Possible Solution

The issue does not lie with plugins, we removed all non essential plugins and the query is still appearing
We are going to try and cache this query on a proxy in front of the db's

## Steps to Reproduce (for Bugs)

Regular setup, it happens continually on our system

## Context

Not sure what else to put, other than we don't know why this is happening!
We are trying to pinpoint it but its not plugins, maybe its on the tracker.php ?

## Your Environment

[matomo_system_check (2).txt](https://github.com/matomo-org/matomo/files/6185121/matomo_system_check.2.txt)

**Comment by tsteur** [comment] 2021-03-22 20:59
Hi @StevieKay90 could you have a look at https://github.com/matomo-org/matomo/issues/16904 and see if that's maybe the same problem?

**Comment by StevieKay90** [comment] 2021-03-22 21:08
Thanks for the quick reply @tsteur !   

That looks interesting, over the last year i've noticed this;
a lot of user_ids share the same visitorid (i have no idea why), is there another way to solve this?

![image](https://user-images.githubusercontent.com/80366750/112058574-a82c8080-8b52-11eb-8be8-7eecb399fe42.png)

This might have been the issue i was having with redis a few weeks ago

**Comment by tsteur** [comment] 2021-03-22 21:16
Are you using Matomo 4? There by default this should not be the case unless you changed `enable_userid_overwrites_visitorid` config option. If you aren't on Matomo 4, then I would recommend upgrading and this might fix the issue already.

https://github.com/matomo-org/matomo/issues/16904#issuecomment-789273870 could help too

**Comment by StevieKay90** [comment] 2021-03-22 21:21
@tsteur  that screenshot was from matomo 3 (i took it about 5 months ago when i noticed) - i've actually just checked and we don't get this anymore (multi visitor_id per user_id) . We've recently upgraded to matomo 4 and that is where we found this issue we are running into with the big query.

We've added in the enable_userid_overwrites_visitorid=1 now but it doesn't seem to do much. What can we do?

we track lots of client websites and they all use set user_id. is it someway our clients have implemented the tags that could be tripping us up?

**Comment by tsteur** [comment] 2021-03-22 21:29
If you didn't have the problem before, then `enable_userid_overwrites_visitorid =0` would actually help you in that case likely. It might be worth a try at least temporary to see if it fixes something (might need to run it for an hour or so).

Regarding the implementation it's really hard to say without knowing details etc unfortunately.

**Comment by StevieKay90** [comment] 2021-03-22 21:46
> If you didn't have the problem before, then `enable_userid_overwrites_visitorid =0` would actually help you in that case likely. It might be worth a try at least temporary to see if it fixes something (might need to run it for an hour or so).

@tsteur  Wow, ok after this the number of reads on the DB has dropped to 1000s instead of 1M. so its done something!!

What might be the knock on effect of this, in terms of data?

**Comment by StevieKay90** [comment] 2021-03-23 13:21
hi @tsteur `enable_userid_overwrites_visitorid =0` seems to have done the trick, a massive thanks :)

It was either that or we also noticed the following at the bottom of the config so we removed it. 

```
[QueuedTracking]
notify_queue_threshold_single_queue = 250000
```

We seem to be on an even keel now!

**Comment by tsteur** [comment] 2021-03-24 02:00
Glad to know this helped. I'll close this for now as a duplicate of https://github.com/matomo-org/matomo/issues/16904 :) 

It should definitely not have improved by `notify_queue_threshold_single_queue`.

**Closed as completed by tsteur** 2021-03-24 02:00 UTC
Labels: duplicate
