### ISSUE TITLE
Visits Overview widget - Sparkline not displayed

### ISSUE THREAD

**Issue by SujalXplores** [piwik/piwik#19596] opened 2022-08-04 05:02 UTC
## Expected Behavior

Sparkline should be displayed
![image](https://user-images.githubusercontent.com/56556259/182771651-005711fb-93ca-4d92-af56-fe2aa4671aa7.png)

## Current Behavior

Image is broken/blank
![image](https://user-images.githubusercontent.com/56556259/182766795-211230ff-0627-469f-b63d-4892144458ce.png)

## Possible Solution

Path to image is not correct

## Steps to Reproduce (for Bugs)

1. Navigate to matomo dashboard
2. Add **Visits Overview** widget to the dashboard
3. You can see broken images in widget

## Context

This widget has affect the whole beautiful UI of matomo dashboard.

## Your Environment

* Matomo Version: 4.11.0
* PHP Version: 8.0.20
* Server Operating System: Linux
* Additionally installed plugins: All Core plugins only

* Browser: Chrome (v103.0.5060) (No ad-blocker plugin installed)
* Operating System: Windows 11

**Comment by sgiehl** [comment] 2022-08-04 07:02
Hi @SujalShah3234 
Thanks for creating this issue. I'm unfortunately unable to reproduce that. For me the sparklines are loading correctly.
In the screenshot above the urls actually look correct.
Maybe there is another reason why the image can't be displayed for you. 
- Are the sparklines working in other places of Matomo?
- Are you seeing the failing requests in the network tab of the dev tools? If so, is the URL incorrect there, like a missing path or similar?
- Are there maybe some errors logged?

**Comment by SujalXplores** [comment] 2022-08-04 09:43
Hi @sgiehl 

> Are the sparklines working in other places of Matomo?

Yes, in every tab where sparkline is used
![image](https://user-images.githubusercontent.com/56556259/182815021-6fb9faa8-5dcd-414f-a999-a7fa3bbca20c.png)
![image](https://user-images.githubusercontent.com/56556259/182815209-6e6e5de9-c362-45e5-94fa-5c70cf9e795f.png)
![image](https://user-images.githubusercontent.com/56556259/182815320-d7b047bc-9dba-4416-965c-bdd2825bce05.png)
![image](https://user-images.githubusercontent.com/56556259/182815444-fe745c46-92f9-4378-b58c-dba78e1ff6a5.png)

> Are you seeing the failing requests in the network tab of the dev tools? If so, is the URL incorrect there, like a missing path or similar?

No, request is not failing but in response blank body is came
[image dev tool url](https://dev-analytics.zurutech.online/index.php?date=2022-07-05,2022-08-03&module=Referrers&format=html&forceView=1&viewDataTable=sparkline&action=get&idSite=1&period=day&segment=&widget=&showtitle=1&random=1164&columns=Referrers_visitorsFromSocialNetworks%2CReferrers_visitorsFromSocialNetworks_percent&colors=%7B%22backgroundColor%22%3A%22%23ffffff%22%2C%22lineColor%22%3A%22%23162c4a%22%2C%22minPointColor%22%3A%22%23ff7f7f%22%2C%22maxPointColor%22%3A%22%2375bf7c%22%2C%22lastPointColor%22%3A%22%2355aaff%22%2C%22fillColor%22%3A%22%23ffffff%22%7D)

> Are there maybe some errors logged?

No errors, dev-tool console is clean.

**Comment by sgiehl** [comment] 2022-08-05 07:17
Ok. As they aren't working anywhere for you, this is more likely a server configuration issue.
I'll close this issue here, as we only handle bug reports or feature requests on GitHub.

Nevertheless some notes that might help you to solve the problem:
* Check if the GD extension for PHP is installed / activated on the server. Running the system check of Matomo should tell you if it working. (See https://matomo.org/faq/troubleshooting/faq_34/)
* Might otherwise also be worth to check for errors in the PHP error log or the Matomo error log file (tmp/logs/matomo.log/)

If this doesn't help you to solve this on your own, please try to get some help on our forum (https://forum.matomo.org)

**Closed as not planned by sgiehl** 2022-08-05 07:17 UTC
Labels: answered
