### ISSUE TITLE
Website selector has only current site plus "all websites".

### ISSUE THREAD

**Issue by instance** [piwik/piwik#9829] opened 2016-02-23 05:35 UTC
Running 2.16.0. Pretty sure this is a local issue since this install has been running for 8 years and something is likely wonky. Checked #5102 and it looks like I can see HTML files.

Dashboard is working fine but the website dropdown is only showing the current site and "all websites" on the dashboard. Elsewhere the list is empty. Logged in as super admin.

Same behaviour in PHP 5.3 and 5.5. It's been happening through several updates.. I was hoping it would just disappear in a bug fix.

If someone can point me to where the list is populated I can probably debug from there.

**Comment by tsteur** [comment] 2016-02-23 08:06
Do you maybe have access to the log files of your webserver? Can you see any errors there?

The websites should be fetched from this API method: https://github.com/piwik/piwik/blob/2.16.0/plugins/SitesManager/API.php#L1540

**Comment by instance** [comment] 2016-02-24 01:59
No PHP there for a few months. I just split our Piwik subdomain into a separate account so I'll check the Apache logs as well.

I suspected it was an access issue, so I made a test account super-admin and got the same thing. I think I'll try creating a brand new user and if the problem still persists I'll dig in and start tracing it. I still think this will be a data issue.Thanks for the pointer.

**Comment by tsteur** [comment] 2016-02-24 09:06
Let us know how it goes so we can close the issue later. Thanks :)

**Comment by mattab** [comment] 2016-03-31 03:41
We cannot reproduce this issue @instance - please re-open if you know how to reproduce it.

**Closed by mattab** 2016-03-31 03:42 UTC
