### ISSUE TITLE
Duplicate a Segement

### ISSUE THREAD

**Issue by mkarg67** [piwik/piwik#17140] opened 2021-01-25 08:36 UTC
In addition to edit a segment a duplicate function would be nice. Often one creating a segment with a lot of conditions. In such cases it is likely that there have to be many of those segments with similar conditions. Duplication would make this process faster.

**Comment by tsteur** [comment] 2021-01-25 18:53
Thanks for creating this issue @mkarg67 I'll close this for now as a duplicate of https://github.com/matomo-org/matomo/issues/7246

**Comment by tsteur** [comment] 2021-01-25 18:53
Thanks for creating this issue @mkarg67 I'll close this for now as a duplicate of https://github.com/matomo-org/matomo/issues/7246

**Closed as completed by tsteur** 2021-01-25 18:53 UTC
Labels: duplicate
