### ISSUE TITLE
Search field above each table

### ISSUE THREAD

**Issue by varunKothare** [piwik/piwik#19355] opened 2022-06-14 22:14 UTC
Search field above each table (e.g. in Behavior -> Pages) with which users can filter all pages of the current tabular overview by keywords. Opposed to the search field at the bottom.

**Comment by atom-box** [comment] 2022-10-06 19:54
A user wrote to Matomo: 

"Feature: (Search filter)
Like: No
Feedback: Needs clear search bar"

(The positioning was anti-intuitive:)
"I did not see the search bar feature at the bottom -- after a few dozen pages are being tracked, the view disappears below the fold. Having the search bar at the top (beside the PAGE URL would be great!) would be helpful for discovery."

**Comment by ronak-innocraft** [comment] 2024-08-05 23:05
This is a duplicate of https://github.com/matomo-org/matomo/issues/19669 and will be tackled as part of that ticket. Closing this issue now but if it differs in requirements to what's outlined in other issue for search bar then feel free to reopen and let us know.

**Closed as not planned** 2024-08-05 23:05 UTC
Labels: Enhancement, c: Design / UI
