### ISSUE TITLE
[Bug] on php 8.1, sparklines visualization does not remove 0% evolution when 0 visits

### ISSUE THREAD

**Issue by diosmosis** [piwik/piwik#21746] opened 2024-01-01 06:54 UTC
### What happened?

When viewing the sparklines visualization on php 8.1 vs. php 7.2, there is a discrepancy. With php 8.1, when there are 0 visits on the current period and the previous period, you will see a 0% evolution next to sparklines in the `sparklines` visualization:

![image](https://github.com/matomo-org/matomo/assets/68335276/5b6e1958-8163-46af-be81-52c8d286fc5b)

This does not appear if using php 7.4. The code that excludes it at https://github.com/matomo-org/matomo/blob/5.x-dev/plugins/CoreVisualizations/Visualizations/Sparklines/Config.php#L309-L312 will not work on php 8.1, because it compares a string percent (`0%`) with `0`.

### What should happen?

The behavior should be consistent across PHP versions.

### How can this be reproduced?

1. Use PHP 8.1
2. Select a day with no visits, and no visits the previous day
3. View the visitors overview
4. See the percent that says 0%
5. Switch to PHP 7.4 and load the same page
6. See the percent is missing

### Matomo version

5.0

### PHP version

8.1

### Server operating system

Linux

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by michalkleiner** [comment] 2024-01-01 10:36
Closing as a quick search for "0%" within the open issues shows that this is a duplicate of #21595.

**Closed as not planned by michalkleiner** 2024-01-01 10:36 UTC
Labels: duplicate, not-in-changelog

**Comment by diosmosis** [comment] 2024-01-01 19:28
@michalkleiner :+1: nice catch!
