### ISSUE TITLE
Piwik installation issue : 1146 Table 'piwik.option' doesn't exist".  Go back to Piwik.

### ISSUE THREAD

**Issue by peeyar** [piwik/piwik#11595] opened 2017-04-05 19:34 UTC
I am trying to run piwik installation using puppet. When I add a config.ini.php file, I get the following error.
Error: Piwik is already installed. 
Original error was "SQLSTATE[42S02]: Base table or view not found: 1146 Table 'piwik.option' doesn't exist".
Go back to Piwik.

If I don't have a config.ini.php file, everything is fine and it displays the page where we can setup DB.

any idea what is going on and how can I trick the piwik to create this table by itself.

thanks
Raj

**Comment by tsteur** [comment] 2017-04-05 19:40
Duplicate of https://github.com/piwik/piwik/issues/10257 . There is not really a way to do this but I recommend to have a look at the linked issue eg https://github.com/piwik/piwik/issues/10257#issuecomment-252109277

**Closed by tsteur** 2017-04-05 19:40 UTC
