### ISSUE TITLE
Creating visitor segment in mobile phone fails

### ISSUE THREAD

**Issue by openbrian** [piwik/piwik#9196] opened 2015-11-11 12:15 UTC
The popup will popunder.  Drag and drop doesn't work at all.

**Comment by tsteur** [comment] 2015-11-11 19:19
Thanks for reporting. This issue is related to https://github.com/piwik/piwik/issues/9100 and is a duplicate of https://github.com/piwik/piwik/issues/9179

**Comment by tsteur** [comment] 2015-11-24 20:25
It's actually not a duplicate, it's about drag & drop

**Comment by mattab** [comment] 2015-11-25 23:39
It counts as a Major bug, as one expects to be able to create segments on Mobile. Adding to 2.15.1.

**Comment by mattab** [comment] 2016-07-12 05:26
This should be fixed in git, let's confirm when it will be deployed on demo

**Comment by mattab** [comment] 2016-07-14 04:27
Fixed in #10045 and verified on demo.piwik.org running latest beta. Kuddos @wronan

**Closed by mattab** 2016-07-14 04:27 UTC
Labels: Bug
