### ISSUE TITLE
[Bug]: Segment vs All Visits Discrepancy with Search Engine attributed sales

### ISSUE THREAD

**Issue by 9joshua** [piwik/piwik#21422] opened 2023-10-20 06:15 UTC
### What happened?

A simple segment was created with the condition `Channel type is Search` (Organic)

For a specific week, the Sales by bu Referer -> Channel Type report shows 13 orders for the All Visits segment and 10 for the Organic segment...
![image](https://github.com/matomo-org/matomo/assets/20234985/34db3a7a-6c52-414e-ab0c-fa65dc55fe8b)
![image](https://github.com/matomo-org/matomo/assets/20234985/71dee001-bd12-410e-b3f9-1736e7378d74)

However, the segmented visitor log for these two reports both show 11 orders. One visit in this log indicates there was an ecommerce order, but there is no entry for the order, so 10 is likely the correct number. This makes me believe the All Visits segment is showing additional orders that may not exist in the Sales by Referrer -> Channel Type table.

The Multi Channel Conversion Attribution report shows 10 orders for both segments...
![image](https://github.com/matomo-org/matomo/assets/20234985/35b174b1-103e-452e-b1d6-bbbcbb77f9e3)
![image](https://github.com/matomo-org/matomo/assets/20234985/3e9ae3ba-7a45-4692-8259-926c015f036c)

### What should happen?

The both the All Visits segment and the Organic segment should show the same number of Search Engine orders because they both draw from visits where the last non-direct referrer is a search engine. 

### How can this be reproduced?

The occurred on a Cloud instance. Unfortunately I don't have another instance to test this where there are:

1. Conversion from Search Engine traffic
2. An Organic segment set up

### Matomo Version

Matomo 4

### Matomo Patch or Minor Version

4.15

### PHP Version

8.1

### Server Operating System

NA

### What browsers are you seeing the problem on?

Chrome

### Computer Operating System

NA

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by bx80** [comment] 2023-10-23 20:30
Thanks for reporting this @9joshua, it may be difficult to recreate as it seems be related to a specific combination of data. I'll assign it to the product team for prioritization.

**Comment by Stan-vw** [comment] 2023-10-24 21:20
Just trying to understand what the issue here is, because in the first screenshot I see 14 orders (not 13) and every other screenshot I see 10 (never 11) orders. In other words, when looking at All Visits I see 14, and within the Organic segment I consistently see 10.

Can you help me understand the problem?

Also having no steps to reproduce means this is unlikely to be picked up anytime soon, because it might be a data issue rather than a platform issue. Let us know if you've been able to reproduce it consistently, so we can have a look at what's happening 👍

**Comment by Stan-vw** [comment] 2024-12-04 03:47
As our QA team wasn't able to reproduce this anymore I'm closing this for now. If someone still runs into this problem, feel free to reopen it

**Closed as completed by Stan-vw** 2024-12-04 03:47 UTC
Labels: Potential Bug
