### ISSUE TITLE
HKG.svg  file lost

### ISSUE THREAD

**Issue by oliguo** [piwik/piwik#8383] opened 2015-07-20 11:01 UTC
I'm in the HK, I test visit map function but I cannot find place,
it is empty,so I figure out something wrong here by developer tool 
![screen shot 2015-07-20 at 6 52 46 pm](https://cloud.githubusercontent.com/assets/8209221/8774484/63ab1d8e-2f11-11e5-91c9-c82a6df4b2ee.png)

The file HKG.svg is miss from the v2.14.1 source 
![screen shot 2015-07-20 at 6 53 12 pm](https://cloud.githubusercontent.com/assets/8209221/8774505/9108b7f0-2f11-11e5-8303-1b64c2099f2d.png)

Please check it and appreciate it if attach svg file, thanks.

**Comment by sgiehl** [comment] 2015-07-20 11:39
That is kind of duplicate of #321
There are some more small country maps missing.

**Closed by sgiehl** 2015-07-20 11:39 UTC
