### ISSUE TITLE
HTTP response should be 401 instead of 200 when accessing reporting API with wrong AUTH TOKEN

### ISSUE THREAD

**Issue by heurteph-ei** [piwik/piwik#17310] opened 2021-03-05 16:52 UTC
## Step to reproduce on the online demo server
Call https://demo.matomo.cloud/index.php?module=API&method=API.getMatomoVersion&token_auth=TOKEN_AUTH (yes, the authentication token is wrong, this is wanted)

## Expected Behavior
If an error occurs, the HTTP response code should not be `2xx`, but `4xx` (in case of request error, in my case I am not authenticated so the HTTP error code should be `404`) or `5xx` (in case of server error or misconfiguration)

## Current Behavior
![image](https://user-images.githubusercontent.com/79993552/110146081-6bcef580-7dda-11eb-95cf-5442a82c2f99.png)
I am not authenticated, I receive an error message, but the HTTP response is `200: OK` "everything seems good"

## Possible Solution
In case of error message (error result), never use HTTP `200`, but at least HTTP `400` or HTTP `500`

**Comment by diosmosis** [comment] 2021-03-07 03:33
Hi @heurteph-ei, you're right, thanks for the bug report!

**Comment by tsteur** [comment] 2021-03-07 19:17
Just fyi this might affect various monitors and could break BC. So I'm putting this for now into Matomo 5 where we can consider doing this.

**Comment by justinvelluppillai** [comment] 2022-06-13 20:45
Closing as duplicate of #18055

**Closed as completed by justinvelluppillai** 2022-06-13 20:45 UTC
Labels: Bug, duplicate
