### ISSUE TITLE
MySQL >= 5.7.5 breaks Piwik <= 2.15.0

### ISSUE THREAD

**Issue by otheus** [piwik/piwik#9131] opened 2015-10-30 11:21 UTC
A friendly write-up is [here](http://forum.piwik.org/read.php?2,130254).

From the [MySQL Documentation](http://dev.mysql.com/doc/refman/5.7/en/miscellaneous-functions.html#function_get-lock):
>   MySQL 5.7.5 and later enforces a maximum length on lock names of 64 characters. Previously, no limit was enforced

The typical string generated by Piwik for this purposes is 65 characters in length. It typically looks like this:

> deletePreviousArchiveStatus.piwik_archive_numeric_2015_10.1267863

The `get_lock()` function is invoked from two functions within `core/db.php`. The two functions are `getDbLock` and `releaseDbLock`. For purposes of expediency on our systems, I wrapped the string used by these functions into a call to `md5()`, guaranteeing 32 characters at most, and almost ensuring uniqueness. I hope the devs come up with something better.

          if ($db->fetchOne($sql, array(md5($lockName))) == '1') {

These two functions are in turn invoked via `acquireArchiveTableLock` and `releaseArchiveTableLock`, both in `DataAccess/Model.php`.

**Comment by tsteur** [comment] 2015-10-30 20:27
Thx for the report!

**Comment by mattab** [comment] 2015-10-30 22:33
We need to add Mysql 5.7 support in our Long Term Support release, added to 2.15.1: https://github.com/piwik/piwik/issues/6642

**Comment by otheus** [comment] 2015-11-03 19:22
Presumably, the generated label is usable for debugging, especially in those edge cases where a lock blocks for a long time, then the server goes away, and some dba needs to clean it up. (At least, it might work on innodb tables.) My md5() workaround clobbers the utility of such code. That code is here: `core/Model.php:284`.

            $dbLockName = "deletePreviousArchiveStatus.$numericTable.$archiveId";

The problem is this: the code is completely MySQL-specific. Acquiring a "named" table lock is MySQL specific, (as is the need for table locks, in general), so to abstract from the db-engine, you'd need to push the name-generation down a level, into the Db-handler code itself. I'm not here today to preach the glorious benefits of using postgresql over mysql, so let's assume it will remain mysql-specific for the near future.

So while we're still talking MySQL-specific code, and since it's MySQL that forces us now to restrict this call to 64 characters, let's shorten it in a reasonable but mysql-specific way.  Let me suggest: (1) use hex-encoded archiveID, (2) abbreviate the module prefix name.

The archiveID for that table type (see `Db/Schema/Mysql.php`) is an `unsigned integer`, or 4-bytes, or 8-hex chars. We explicate the length of the other fields, leaving up to 40 characters for the name of the table.

        // Ensure compat with 5.7.5+ : max 64-char get_lock() label
        $dbLockName = sprintf("%.14s.%.40s.%08x",
                "delPrvArcvStat", # 14 chars
                $numericTable,
                intval($archiveId)
        );

Is this enough to expedite progress, or should I generate an actual patch?

**Comment by otheus** [comment] 2015-11-03 21:19
My PHP isn't that great, but maybe instead of relying on sprintf's precision, it makes more sense to do something like: 
    substr($numericTable, -40, 40),
in order to make sure the lock identifies the most distinctive part of the table name.

**Comment by mattab** [comment] 2015-11-24 20:44
Marked as duplicate of https://github.com/piwik/piwik/issues/9131

**Closed** 2015-12-13 23:29 UTC
Labels: Bug

**Comment by otheus** [comment] 2015-12-21 14:36
@tsteur  thank you for addressing this.   Your patch does appear to solve the problem very thoroughly.

I don't want to sound presumptuous in addressing the following point on _coding style_: The fix in ```core/DataAccess/Model.php``` has a hard-coded constant of `23` without explanation whatsoever. I'm sure string interpolation in PHP is fast enough, but for clarity, might I suggest using `sprintf` with constants, ala https://github.com/piwik/piwik/issues/9131#issuecomment-153460895 ?

**Comment by tsteur** [comment] 2015-12-21 19:11
See https://github.com/piwik/piwik/commit/bc4013ebfa65d85bd92c1eb24e72ab8f4143b998#diff-f0dc4d4d133f84005fcebc1e10f155c0

**Comment by tsteur** [comment] 2015-12-21 19:12
and also see https://github.com/piwik/piwik/issues/9395

**Comment by otheus** [comment] 2015-12-23 14:57
tyvm
