### ISSUE TITLE
PHPMailer Connection to the SMTP server failed when resetting password in 4.0.5

### ISSUE THREAD

**Issue by Starker3** [piwik/piwik#17057] opened 2021-01-07 03:04 UTC
We received the following report:

Matomo 4.0.5: When i change my password i'll get an error page:

````An error occurred
Verbindung zum SMTP-Server fehlgeschlagen. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
````
Translation: Connection to the SMTP server failed

The password is changed successfully, but the error still occurs

A test using:
`./console core:test-email test@example.com`
has been successful.

It is not appear to be a problem with PHP mailer.

On their system 6.1.8 is installed and the following test worked fine:
```
<?php
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
date_default_timezone_set('Etc/UTC');
require '../autoload.php';
$mail = new PHPMailer();
$mail->isSMTP();
$mail->SMTPDebug = SMTP::DEBUG_SERVER;
$mail->Host = 'localhost';
$mail->Port = 25;
$mail->setFrom('test@example.com', 'Matomo');
$mail->addReplyTo('test@example.com', 'Matomo');
$mail->addAddress('test@example.com', 'Uwe Wenglewski');
$mail->Subject = 'PHPMailer SMTP without auth test';
$mail->msgHTML("Hallo");
$mail->AltBody = 'This is a plain-text message body';
if (!$mail->send()) {
echo 'Mailer Error: ' . $mail->ErrorInfo;
} else {
echo 'Message sent!';
}
```

**Comment by sgiehl** [comment] 2021-01-07 10:45
Might it be possible that their SMTP server rejects mails that are not having a correctly set `From` header maybe?
Seems we are not setting a from header for the password changed notification.

They could check if adding this
```php
$mail->setFrom(Config::getInstance()->General['noreply_email_address'], Config::getInstance()->General['noreply_email_name']);
```

to this method helps:
https://github.com/matomo-org/matomo/blob/679e73f1236969db0c2d767655cb84456a727d24/plugins/UsersManager/API.php#L1450-L1473

**Comment by Starker3** [comment] 2021-01-08 00:36
Additional note after further feedback from user:
They received the email notifying them of a new update available.

So it seems the PHPMailer is only failing to send the password reset emails.

**Comment by tsteur** [comment] 2021-01-10 19:28
@Starker3 I'll close this for now as a duplicate of https://github.com/matomo-org/matomo/issues/17026

Maybe they can set `login_password_recovery_email_address` and `login_password_recovery_replyto_email_address` to `noreply@{DOMAIN}` (same config value as `noreply_email_address`) and see if it works then.

**Closed as completed by tsteur** 2021-01-10 19:28 UTC
Labels: duplicate
