### ISSUE TITLE
Piwik segmented search with archived data (cron) doesn't show some periods

### ISSUE THREAD

**Issue by akrus** [piwik/piwik#8436] opened 2015-07-27 06:28 UTC
Hi,

I have Piwik running (latest stable version) and real-time segmented search is quite slow. I've changed this to use archived data (cron) and executed full re-archive using 'piwik/console core:archive --url=http://piwik -vv -
-force-all-periods=315576000 --force-all-websites --force-date-last-n=10000'. This took one day to complete, but as I can see on the graphs, e.g. Visits over Time, in one segmented search there is no data between Apr 2014 and Jun 2015 (so I have Mar 2014 and Jul 2015), in another - Jan-Jun 2015 is missing and so on. Why this could happen? Executing console core:archive again doesn't change anything. New days are appearing fine though.

See screenshots attached.
![piwik_daily](https://cloud.githubusercontent.com/assets/36325/8899811/d804d1a4-3441-11e5-94c3-85117e001ffb.png)
![piwik_monthly](https://cloud.githubusercontent.com/assets/36325/8899812/d82ec68a-3441-11e5-84f0-3e20d11e5e93.png)
![piwik_segment_settings](https://cloud.githubusercontent.com/assets/36325/8899813/d83043e8-3441-11e5-95d3-11a59d92aa74.png)

**Comment by tsteur** [comment] 2015-07-27 07:05
> but as I can see on the graphs, e.g. Visits over Time, in one segmented search there is no data between Apr 2014 and Jun 2015 (so I have Mar 2014 and Jul 2015), in another - Jan-Jun 2015 is missing and so on

I'm not sure if I understand the issue right. It is normal that two different segmented searches result in different data. It depends on the query and data whether it is normal that there is no data or not. Or do you mean when executing the same segmented search multiple times you get a different result?

**Comment by akrus** [comment] 2015-07-27 07:07
Same segmented search with "segmented reports are processed in real time (default)" has all the information available, see graph below:
![piwik_realtime_daily](https://cloud.githubusercontent.com/assets/36325/8900295/3c6c66ca-3447-11e5-8ec1-9c5fe2112f8c.png)
When I change this to use archives - the data is missing and I can't find out why as no errors appear during archiving.

**Comment by bodomic** [comment] 2015-07-30 07:18
That's a good question, I experience the same issue too. Realtime works fine, archived one is patially lacking data.

**Comment by tsteur** [comment] 2015-07-30 08:39
I have no clue how this can happen right now. Maybe someone else does? It would be probably beneficial to get access to a database or to get a dump of a database to debug this issue - if possible. If that's possible for someone, please email us at "hello at piwik.org" and leave a comment here (in case it goes into spam folder)

**Comment by quba** [comment] 2015-07-30 09:06
Do you monitor archiving logs? 

Such situation may happen if there were archiving errors in the past (e.g. memory limit and others). It's possible that there are incomplete archives marked as done. 

There are 2 solutions to confirm:
- you can either invalidate the data and then run re-archiving - http://piwik.org/faq/how-to/#faq_155
- or just drop numeric and blob tables for given month and re-archive.

Hope that helps.

**Comment by akrus** [comment] 2015-07-30 09:12
Okay, tried to increase memory_limit to 2G, dropped data for 2015_02 and launched archiving again, let's see...

**Comment by akrus** [comment] 2015-07-30 11:19
Now it archived fine, how to deal with this situation without reading logs all the time?

**Comment by quba** [comment] 2015-07-30 12:19
Make sure that you have memory_limit set properly (2G should be fine but it depends on your traffic).

You can also set a basic monitoring (even cron job) that will grep the log file searching for errors and send an e-mail if needed.

**Comment by akrus** [comment] 2015-09-03 09:06
Alright, I dropped all tables in MySQL related to archives, re-indexed everything and now the data is there, but I have another problem - whenever I add any new segmented search (e.g. new region) and switch it to use 'pre-processed data' it shows nothing and re-indexing doesn't help, the only solution is to again clear everything and initialize it from scratch.
Doesn't look like correct behavior...

**Comment by RMastop** [comment] 2015-09-03 09:38
I have the same issue here, 
The default value of process_new_segments_from = "beginning_of_time" is still in place.
However I see data not being archived.

One solution is to delete the tables, but for large sites this is not really an option.
You don't want to delete a month of archived data for 50+ sites because of one segment failing. 
Invalidate the data is not the easiest solution, because you have to create a URL with comma separated dates or a bash file that calls the URL for every date you would like to invalidate. (It would help to be able to invalidate per range, and segment)

**Comment by mattab** [comment] 2015-09-18 07:45
>whenever I add any new segmented search (e.g. new region) and switch it to use 'pre-processed data' it shows nothing and re-indexing doesn't help, the only solution is to again clear everything and initialize it from scratch.

@akrus  Can you explain exactly the step to reproduce? it seems to work fine for us

> I have the same issue here,  The default value of process_new_segments_from = "beginning_of_time" is still in place. However I see data not being archived.

@RMastop do you still have this issue? how can we reproduce this?

**Comment by RMastop** [comment] 2015-12-09 08:52
Hi @mattab,
We reproduced the issue. Will write the details about it to Piwik.pro support.

**Comment by mattab** [comment] 2016-04-11 08:08
Hi @RMastop @akrus Could you please try again with 2.16.1 stable? we fixed a related issue recently in https://github.com/piwik/piwik/issues/9468 https://github.com/piwik/piwik/issues/10022 which may have fixed this issue. let us know please if you are still affected or if it's fixed using 2.16.1...

**Comment by akrus** [comment] 2016-04-11 08:14
Upgraded now, should I execute full re-index or usual cron job should fix this?

**Comment by mattab** [comment] 2016-04-11 08:26
Maybe wait 24 hours and see if it fixed itself already. If some old data is still not processed, you can re-process it all with the command in: https://piwik.org/faq/log-analytics-tool/faq_17994/

If you are still seeing the issue we'll investigate more and get to the bottom of it... 

(added `Major` tag since when data doesn't show or is not tracked properly in Piwik, we consider it a major issue.)

**Comment by RMastop** [comment] 2016-04-11 08:31
Hi @mattab,

I'm sorry, I'm not allowed to connect to the instance where it happened.
I'll try to contact someone to validate.

Cheers,
Richard

**Comment by mattab** [comment] 2016-07-18 03:25
> whenever I add any new segmented search (e.g. new region) and switch it to use 'pre-processed data' it shows nothing and re-indexing doesn't help, the only solution is to again clear everything and initialize it from scratch.

@akrus could you please create a new issue? I will mark this issue as solved for now, but if you still experience this issue in Piwik 2.16.2 or later, please open a new issue and we will investigate!

**Closed by mattab** 2016-07-18 03:25 UTC
Labels: Bug, Major

**Comment by XinfinityoO** [comment] 2016-09-04 21:24
I m having similar issues ..i cant see old records

**Comment by mattab** [comment] 2016-09-27 03:45
@XinfinityoO please create a new issue and write down as many details as possibl

**Comment by voarsh** [comment] 2018-12-03 15:00
I can having a similar issue

**Comment by voarsh** [comment] 2018-12-05 12:51
Solution:
Invalidate plugin + delete all numeric and BLOB tables.

Run: 
The query to process all sites, all periods, segements. Took 3 days to process 9 GBs of data....
