### ISSUE TITLE
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 

### ISSUE THREAD

**Issue by L3on1d** [piwik/piwik#18951] opened 2022-03-16 18:57 UTC
Hi!

After upgrade to Matomo 4.8.0 my system started sending such error messages: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '_NUMBER_' for key 'PRIMARY'.

Any help would be appreciated.

Thank you!

**Comment by EreMaijala** [comment] 2022-03-29 06:07
Upgraded yesterday, now seeing this during archiving from console: 

`ERROR [2022-03-29 05:29:34] 5139  Got invalid response from API request: ?module=API&method=CoreAdminHome.archiveReports&idSite=712&period=week&date=2022-03-28&format=json&trigger=archivephp. Response was '{"result":"error","message":"SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '361822039' for key 'PRIMARY' - in plugin VisitFrequency. #0 \/data\/matomo\/core\/ArchiveProcessor\/Loader.php(284): Piwik\\ArchiveProcessor\\PluginsArchiver-&gt;callAggregateAllPlugins() #1 \/data\/matomo\/core\/ArchiveProcessor\/Loader.php(176): Piwik\\ArchiveProcessor\\Loader-&gt;prepareAllPluginsArchive() #2 \/data\/matomo\/core\/ArchiveProcessor\/Loader.php(159): Piwik\\ArchiveProcessor\\Loader-&gt;insertArchiveData() #3 \/data\/matomo\/core\/ArchiveProcessor\/Loader.php(99): Piwik\\ArchiveProcessor\\Loader-&gt;prepareArchiveImpl() #4 \/data\/matomo\/core\/Context.php(75): Piwik\\ArchiveProcessor\\Loader-&gt;Piwik\\ArchiveProcessor\\{closure}() `

Is this maybe the same issue you're seeing, @L3on1d ?

**Comment by L3on1d** [comment] 2022-03-29 10:21
Hi @EreMaijala, yes exactly the same error.

**Comment by EreMaijala** [comment] 2022-03-29 10:25
@L3on1d Thanks for the confirmation. I already opened my own issue at #19015, but perhaps one can be closed if the other gets attention.

**Comment by tsteur** [comment] 2022-03-29 18:47
Hi everyone, I'll close this as a duplicate of https://github.com/matomo-org/matomo/issues/18937 . Please follow this issue to see the progress on it.

**Closed as completed by tsteur** 2022-03-29 18:47 UTC
Labels: duplicate

**Comment by Txt-justified66** [comment] 2025-10-20 20:15
Answer complete https://pain-acl240.github.io/whiff/
