### ISSUE TITLE
Dashboard does not load after disabling Overlay plugin

### ISSUE THREAD

**Issue by quba** [piwik/piwik#9946] opened 2016-03-17 15:59 UTC
Looks like there's some JS code missing after disabling the Overlay plugin. See:
`Uncaught ReferenceError: DataTable_RowActions_Overlay is not defined`

It's a regression because it worked in 2.15.0.

**Comment by sgiehl** [comment] 2016-03-21 13:04
That already seems to be fixed in master. Can't reproduce that on my local instance.

**Comment by tsteur** [comment] 2016-03-29 19:41
Thank you for creating the issue. It was fixed as part of this issue: https://github.com/piwik/piwik/issues/9704

**Closed by tsteur** 2016-03-29 19:41 UTC
