### ISSUE TITLE
Show optional "content impression" in vistorlog

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#10053] opened 2016-04-14 13:19 UTC
Content tracking is a good thing! (For details see: https://piwik.org/docs/content-tracking/)

To get even more informations from this implementation, it would be good to
Show  **"content impression" in vistorlog,**
**to see what a specific visitor could have seen.**

But make it possible to show / hide these pieces of information to not overflow visitor log with informations.

**Comment by tsteur** [comment] 2016-04-14 21:19
Marking this one as a duplicate of #6416 as well

**Closed by tsteur** 2016-04-14 21:19 UTC
