### ISSUE TITLE
Make website manager take 100% of width

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#7747] opened 2015-04-22 22:16 UTC
Site manager currently looks as below, which looks bit wrong on a wide screen.

 * Could we make the table take 100% of the width? then it would be aligned with the search field and generally make better use of space available.

![site manager](https://cloud.githubusercontent.com/assets/466765/7286645/99186ea0-e9a1-11e4-9c4d-f7bf765c3f26.png)

**Comment by mattab** [comment] 2015-04-24 10:22
We removed search field for when there are less than 25 websites in #7758 and in https://github.com/piwik/piwik/commit/48dc43f904235588518aa87c422966123c1295c3 the column for website name was made a bit wider - closing issue as we will make improvements during:
 * Administration design improvements #7587 
 * possibly re-think the website manager to allow it to also manage Mobile Apps #7131

**Comment by mattab** [comment] 2015-04-24 10:22
leaving open and moving to Mid term to remember to check it's fixed

**Comment by tsteur** [comment] 2015-04-24 11:49
Adding easy pick as it does bring a good value and should be still rather easy to do. If we leave it in Mid term we can as well just close it as it should be fixed with the Admin redesign anyway.

**Comment by tsteur** [comment] 2015-04-27 21:45
The problem is currently only hidden for installations having only a few websites. For most users this problem is still very visible.

**Comment by halfdan** [comment] 2015-12-26 23:08
Going to close this as it is fixed with the new design.

**Closed by halfdan** 2015-12-26 23:08 UTC
Labels: c: Design / UI, Easy pick, Task
