### ISSUE TITLE
I cant re-use my existing database because not getting  "Reuse the tables" option 

### ISSUE THREAD

**Issue by inbasekarandev** [piwik/piwik#21841] opened 2024-01-23 13:50 UTC
### What happened?

I am trying to reinstall matomo with my existing database but not getting "Reuse the tables" option , its only giving me to delete the existing table which I can't do because I have last 4 years of data in that.

### What should happen?

It should give option to select existing tables 

### How can this be reproduced?

Installing the matomo again with existing database 

### Matomo version

 5.0.1

### PHP version

 8.2.15

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by bx80** [comment] 2024-01-28 21:17
Hi @inbasekarandev, thanks for reporting this. 

Would it be possible for you to provide a list of the tables you have in the database? (eg. a `SHOW TABLES` output)
According to [this check](https://github.com/matomo-org/matomo/blob/16f8db6d5c6e5cf1e79344877749077ead1361bf/plugins/Installation/Controller.php#L712) there needs to be at least 12 non-archive tables for the reuse database option to be shown.

**Comment by michalkleiner** [comment] 2024-02-21 10:17
Hi @inbasekarandev, could you please check the previous comment and see what db tables you have in your database? Alternatively if you managed to get around this or it's not a problem for you anymore please feel free to close the issue. Thank you!

**Comment by sgiehl** [comment] 2024-03-25 12:46
Closing due to inactivity. @inbasekarandev If you still experience problems around that maybe try to find some help on the forum or if you have details that help to reproduce the problem feel free to open a new issue for that.

**Closed as not planned by sgiehl** 2024-03-25 12:46 UTC
Labels: worksforme
