### ISSUE TITLE
Top navigation in General Settings no longer working

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#18663] opened 2022-01-20 04:04 UTC
This seems to be broken for me on demo2 https://demo2.matomo.org/index.php?module=CoreAdminHome&action=generalSettings&idSite=1&period=day&date=yesterday and locally  but it works on demo.matomo.org 

Looks like a regression in a recent change maybe?

When I click on one of these links then it doesn't jump to the correct settings 
![image](https://user-images.githubusercontent.com/273120/150271221-98c96e1d-6725-4fdf-b896-c7b8dd05262b.png)

**Comment by sgiehl** [comment] 2022-01-20 13:58
I'm not able to reproduce that locally. Also not with disabled developer mode and the same set of plugins. It seems somehow the locationchange doesn't trigger the anchorfix on demo2 as calling `scrollToAnchorInUrl` manually does the scrolling correctly there.
@diosmosis do you have an idea what this could be caused by?

**Comment by diosmosis** [comment] 2022-01-20 23:18
Unfortunately I don't have access to the settings page on demo2. I can try reproducing locally.

**Comment by sgiehl** [comment] 2022-01-21 08:48
@diosmosis let us know if you need access to demo2 to check that there.

**Comment by diosmosis** [comment] 2022-01-21 10:15
Wasn't able to find the cause but I would look at this code:

https://github.com/matomo-org/matomo/blob/4.x-dev/plugins/CoreHome/angularjs/anchorLinkFix.js#L92-L103
or if removing https://github.com/matomo-org/matomo/blob/4.x-dev/plugins/CoreHome/javascripts/broadcast.js#L405 would work

**Comment by sgiehl** [comment] 2022-01-21 11:00
@tsteur Seems neither me, nor @diosmosis are able to reproduce that locally. So might be hard to find the reason.

@diosmosis I can give you super user access on demo2 if that helps. If you need ssh access to check if some changes are helping, guess @tsteur can help. I don't have ssh access to demo2.

**Comment by diosmosis** [comment] 2022-01-21 11:03
I have ssh access to demo2 if I need to change anything.

**Comment by sgiehl** [comment] 2022-01-21 12:12
@diosmosis I just gave you super user access. Feel free to check if you can find the reason...

**Comment by diosmosis** [comment] 2022-01-21 12:34
Looks like the $locationChangeStart event is not even triggered. I'm guessing somewhere in angularjs it's not noticing the update to the hash. I've seen this before but wasn't able to non-intrusively fix it.

**Comment by diosmosis** [comment] 2022-01-21 12:52
Comparing between local and demo2, this event handler appears to be missing on demo2:

![image](https://user-images.githubusercontent.com/125140/150530085-67f6f029-8321-42c9-8075-8ff474f73e6b.png)

Might be related.

**Comment by diosmosis** [comment] 2022-01-21 13:08
Something off w/ the angularjs bootstrap logic.

**Comment by diosmosis** [comment] 2022-01-21 13:14
@sgiehl This line is what fails in demo2 but works locally:

```
  forEach(runBlocks, function(fn) { if (fn) instanceInjector.invoke(fn); });
```

On demo2 `fn` is set to undefined, so nothing is run. Does not at first glance appear to be Vue related.

**Comment by diosmosis** [comment] 2022-01-21 13:18
`loadModules(['ng', ...])` fails, 'ng' resolves to `undefined`

**Comment by diosmosis** [comment] 2022-01-21 13:27
Nevermind, that's not the reason... still looking.

**Comment by diosmosis** [comment] 2022-01-21 13:32
@sgiehl / @tsteur ok, I can reproduce: if you disable GoogleAnalyticsImporter locally (and potentially any other plugin that uses the $location service in a run/config), the behavior is reproducible. `$location` needs to be manually required in a run block so it will be initialized I guess. Or maybe required specifically some other way. (The file that makes it work locally for me is widget-events.run.js.) Do not believe this is Vue related.

**Comment by sgiehl** [comment] 2022-01-21 15:23
@diosmosis good catch. Guess this was caused by migrating some stuff to vue then, as the `$location` might not be used anymore. Would it solve the issue to simply inject `$location` into e.g. `PluginSettings.adapter.ts`?

**Comment by diosmosis** [comment] 2022-01-21 22:37
@sgiehl I think you'd need a run block:

```
angular.module('piwikApp').run(['$location', function () { }]);
```

**Comment by diosmosis** [comment] 2022-01-21 22:38
If sticking it in Vue code would put it in MatomoUrl.adapter.ts since it's to get angularjs initialized properly there.

**Comment by diosmosis** [comment] 2022-01-21 23:44
@sgiehl here you go: https://github.com/matomo-org/matomo/pull/18671 since you didn't find time

**Closed as completed** 2022-01-24 11:17 UTC
Labels: Bug, Regression
