### ISSUE TITLE
3 Column Layout/Dashboard Missing After Update

### ISSUE THREAD

**Issue by Trance-Man** [piwik/piwik#7801] opened 2015-04-30 23:41 UTC
What is going on with the columns for the dashboard? Did this break on the latest Piwik update? I try to set it to three columns and nothing sticks at all.

**Comment by diosmosis** [comment] 2015-04-30 23:49
Duplicates https://github.com/piwik/piwik/issues/7796

Can you try clearing the browser cache and running `./console core:clear-caches` then checking the functionality?

**Comment by Trance-Man** [comment] 2015-05-01 15:21
Is there an instruction manual to 'run' [console], I can't figure out how to do/use this you mentioned "Can you try clearing the browser cache and running ./console core:clear-caches then checking the functionality?"

Thank you

**Comment by diosmosis** [comment] 2015-05-01 15:30
`console` is a PHP file in Piwik's root directory, you can run it on the command line via `php /path/to/piwik/console core:clear-caches`. You can see all available commands by running `php /path/to/piwik/console help`. You will need to access the file remotely, ie, via ssh.

If the console file is executable and there is a php executable on your system's PATH, you can just run `/path/to/piwik/console` directly, w/o the `php` part.

If you can't run the console file, you can delete the files in the `/path/to/piwik/tmp/assets` directory for the same effect.

**Comment by Trance-Man** [comment] 2015-05-01 16:15
- I deleted all in -->  /path/to/piwik/tmp/assets- I cleared cache and cookies
Still have the same problem.
Thanks

Bruce

**Comment by diosmosis** [comment] 2015-05-01 22:09
There is a workaround posted in https://github.com/piwik/piwik/issues/7796 which is to zoom out until the dashboard uses multiple columns. Does this work for you?

**Comment by Trance-Man** [comment] 2015-05-01 23:53
Zoom out?
On browser, on screen resolution, etc?
I tried to zoom in and out on browser options of the screen, then changed layout, still nothing but I have a feeling i am not understanding what you mean by 'zoom'
Thanks!

**Comment by diosmosis** [comment] 2015-05-01 23:59
It's possible the problem you're experiencing is caused by something else. Can you provide access to your Piwik instance? If so, please email credentials to use to hello@piwik.org.

**Comment by Trance-Man** [comment] 2015-05-02 00:01
http://www.brucecullen.com/piwik/index.php
user: cqjb
pass: Spokane007

**Comment by diosmosis** [comment] 2015-05-02 00:09
Please don't post credentials to github. I've removed them and copied them for debugging, you don't need to do anything else.

**Comment by diosmosis** [comment] 2015-05-02 00:10
Ok, I can reproduce this issue, it's not the same as the other one.

**Comment by Trance-Man** [comment] 2015-05-02 00:13
Wow I did that? not sure how.

Should I change my password?

**Comment by Trance-Man** [comment] 2015-05-02 00:14
Ah great, just my luck, so my problem is a rare new one, lol?Any easy fix? Drives me nuts a bit.

**Comment by diosmosis** [comment] 2015-05-02 00:24
It's a common problem, the CSS being served by your web server is incorrect. Removing the /path/to/piwik/tmp/assets/ file should have fixed this. Can you restart your webserver?

If that doesn't work, please archive and send the contents of the /path/to/piwik/tmp/assets folder to hello@piwik.org?

**Comment by Trance-Man** [comment] 2015-05-02 01:10
I just sent it. :)
It's my Godaddy account, only my westhost account I know how to restart. I hate Godaddy.
BC

**Comment by diosmosis** [comment] 2015-05-02 02:38
The files you sent look like they were incorrectly generated. They don't include the new CSS included in 2.13.

Can you check the `/path/to/piwik/plugins/Morpheus/stylesheets/base.less` file for the following text: `@import "bootstrap.css";`? It should be on line 38. If it's not there, the update didn't go as it should have.

If it is there, then my only guess is that the web server is incorrectly caching old PHP files. You'll have to talk to Godaddy about fixing that if you can't restart php-fpm yourself (though `./console core:clear-caches` command described above might fix it).

**Comment by Trance-Man** [comment] 2015-05-02 17:06
OK I caled Godaddy they said they put in the command to refresh, that it might take 30-45 minutes, jees..So I will test it out again in just a bit, hoping this solves the problem.
B

**Comment by Trance-Man** [comment] 2015-05-02 20:18
Ok Godaddy told me they would restart, so that seems to have taken place but still no changes, I still can't change my layout to what it was before.

**Comment by diosmosis** [comment] 2015-05-02 20:34
In this case, it will take further debugging to find the exact cause of the issue. Can you provide ftp or ssh access to your server? If so, please email hello@piwik.org (don't reply to the email you get for this message or the credentials will display on github).

**Comment by diosmosis** [comment] 2015-05-02 22:04
@Trance-Man Your update to Piwik 2.13 didn't properly execute, some files were not correctly overwritten with the new ones. Download Piwik from here: http://builds.piwik.org/piwik.zip and copy the files in the piwik folder over the files in /path/to/piwik.

**Comment by Trance-Man** [comment] 2015-05-03 02:57
I did all of that, I can't win lol, getting errors...
Fatal error: Call to a member function getMetricsRequiredForReport() on a non-object in /home/content/20/8334020/html/piwik/plugins/Goals/API.php on line 406

**Comment by diosmosis** [comment] 2015-05-03 05:03
Check for the /path/to/piwik/plugins/Goals/GetMetrics.php file. If it doesn't exist, you didn't copy/upload the Piwik files correctly. If it does exist, there's a web server problem you will have to contact your web host to resolve (the PHP process doesn't see the GetMetrics.php file).

**Comment by diosmosis** [comment] 2015-05-03 16:52
Sorry, there's a typo in my last comment, the path should be /path/to/piwik/plugins/Goals/Reports/GetMetrics.php.

**Comment by Trance-Man** [comment] 2015-05-03 17:36
I think it is working now, so far. I re-uploaded all files and removed the temp files again, cleared cookies and all the rest at once and refreshed.So far so good, thank you very very much for all your help.

**Comment by diosmosis** [comment] 2015-05-03 17:40
No worries, closing the issue.

**Closed by diosmosis** 2015-05-03 17:40 UTC
Labels: answered

**Comment by Trance-Man** [comment] 2015-07-09 14:37
New problems with latest update as mentioned on thread here: http://forum.piwik.org/read.php?2,127826,127884
I am user "Bruce'
Anything you can do to help me try to solve this?
Bruce
