### ISSUE TITLE
Column Headers Missing

### ISSUE THREAD

**Issue by cfuser** [piwik/piwik#7774] opened 2015-04-27 16:45 UTC
When exporting data using Pages >> Row Evolution >> Export as TSV the column headers now read what appears to be the array position 0, 1, 2, 3, 4, 5, etc. and not the actual column labels. Versions 2.12.0 and 2.12.1

The issue can be reproduced at this URL on demo: [demo.piwik.org](http://demo.piwik.org/index.php?module=API&method=Actions.getPageUrls&format=TSV&idSite=7&period=day&date=2015-04-16,2015-04-22&label=&filter_limit=false&disable_queued_filters=1&format_metrics=1&period=day&expanded=1&translateColumnNames=1&language=en&label=%40%252Findex)

**Comment by tsteur** [comment] 2015-04-28 00:48
I can reproduce it. The link is also broken on all Graph reports. Eg Pie etc. It is caused by https://github.com/piwik/piwik/blob/2.13.0-rc2/plugins/CoreVisualizations/Visualizations/Graph.php#L62

which causes the `disable_queued_filters=1` in the export link. Maybe we could use `$this->requestConfig->disable_queued_filters = 1` instead? This would fix the export link but might break something else, not sure.

Alternatively, we need to apply the metrics column mapping in the CSV renderer but a better fix should be do not disable queued filters as it might break other things as well.

**Comment by mattab** [comment] 2015-04-28 04:33
>  This would fix the export link but might break something else, not sure.

I'm wondering if there's any reason for this line at all, do you remember why we need to disable queued filters?

Moving to 2.14.0

**Closed** 2015-05-13 05:15 UTC
Labels: Bug
