### ISSUE TITLE
Make CustomDimensions available in Segment Editor

### ISSUE THREAD

**Issue by peterbo** [piwik/piwik#19237] opened 2022-05-18 19:44 UTC
Way to reproduce: 
- After updating to 4.10, setup a CustomDimension (doesn't matter, if action or visit scope) 
- open segment editor and try to select your Custom Dimension

-> It's not available in the list of selectable items. This is also the case for the segment filter of the Custom Reports plugin.

**Comment by sgiehl** [comment] 2022-05-18 20:34
Hey @peterbo 
Thanks for the report. I was able to reproduce that. With 4.9.0 the dimensions where visible for segments, but with 4.10.0 and the current development branch they are not visible any longer.
We will try to handle this regression with high priority to fix that as soon as possible

**Comment by sgiehl** [comment] 2022-05-18 20:46
@diosmosis This actually seems to be a regression from vue migration. The request for segments metadata is now sent with idsite=all instead of the specific site. Could you please quickly check that?

**Comment by diosmosis** [comment] 2022-05-18 21:24
Looking now.

**Comment by diosmosis** [comment] 2022-05-18 21:42
@sgiehl fixed by https://github.com/matomo-org/matomo/pull/19240

**Closed as completed** 2022-05-21 06:26 UTC
Labels: not-in-changelog, Regression

**Comment by MatomoForumNotifications** [comment] 2022-05-25 09:47
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/how-to-add-a-new-segment-for-custom-dimension/46063/2
