### ISSUE TITLE
Table layout broken in hierarchy view

### ISSUE THREAD

**Issue by rugk** [piwik/piwik#8506] opened 2015-08-06 14:06 UTC
With Piwik 2.14.3 in Firefox 39 the tables seem to be a bit broken. Basically you can only see numbers, hyphens and a few URLs (I censored them below) - but all of them in one bunch.
But this only happens if I view the table (in the actions part) in the folded (hierarchy) view. If I view it in the unfolded view all looks right.
![piwiktableerrors 2](https://cloud.githubusercontent.com/assets/11966684/9113275/f6d4b56c-3c53-11e5-8c0c-6d9db2567443.png)

This is a 3D view of the table:
![piwiktableerrors](https://cloud.githubusercontent.com/assets/11966684/9113276/f6f76134-3c53-11e5-8a4f-49ba3dd45bfa.PNG)

**Comment by tsteur** [comment] 2015-08-07 06:31
Can you reproduce this on our demo: http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=32&period=day&date=yesterday#/module=Actions&action=menuGetExitPageUrls&idSite=32&period=day&date=yesterday ?

**Comment by rugk** [comment] 2015-08-07 11:48
Well when clicking on your link I got only index-sites.
![piwikonlyindex](https://cloud.githubusercontent.com/assets/11966684/9135047/0df6574e-3d0a-11e5-8eab-b16f77833426.png)
And even if I select the whole week there only one site in each group:
![piwikonlyindex_week](https://cloud.githubusercontent.com/assets/11966684/9135095/63ff2fa8-3d0a-11e5-98f6-eceaab9af1f1.png)

So if I manually go to demo.piwik.org and select a list of sites I can't fold it at all. The option just is not there:
![piwikdemo_nofolding](https://cloud.githubusercontent.com/assets/11966684/9135159/e29ca2a0-3d0a-11e5-8bbe-823ba377ccee.png)

**Comment by rugk** [comment] 2015-08-07 11:52
Okay, finally I got a table with more entries and it works there:
![piwikdemo_correcttable](https://cloud.githubusercontent.com/assets/11966684/9135225/7c941262-3d0b-11e5-9a40-d509cfba8a9f.png)

**Comment by tsteur** [comment] 2015-08-07 12:43
Is it possible that you create an account with view access to your Piwik installation so we can debug? If so, please send us credentials to "hello at piwik.org" and comment here afterwards (just in case it goes to spam folder). You could delete the account directly after we had a look again

**Comment by rugk** [comment] 2015-08-07 12:47
We will discuss this. I will let you know if I know more.

**Comment by rugk** [comment] 2015-08-08 20:13
Mail sent from r\*.k******@outlook.com.

We also had error messages obviously caused my nginx pagespeed, but they does not seem to have anything to do with this issue.

**Comment by rugk** [comment] 2015-08-10 11:01
Any news here? Did you had a look into our installation?

**Comment by tsteur** [comment] 2015-08-10 13:02
I just had a look and it seems to be caused by page-speed probably see eg https://github.com/piwik/piwik/issues/5081#issuecomment-48315406. Can you try to disable it?

For more technical users: Something adds a `<head/>` element to the XHR request but the request should not return a `<head/>` element but start with a `tr` element.

Also possible that this is done by another extension.

**Comment by rugk** [comment] 2015-08-10 13:31
We will look into it again.
I already thought Pagespeed was already deactivated, but probably it was just the CSS-Pagespeed part.

**Comment by rugk** [comment] 2015-08-14 09:14
Okay, so yes, it was Pagespeed.

So we have disabled it and it worked. However we don't want to disable it for the whole site.
As we have Piwik installed in  a subfolder on our domain (and not in subdomain) we tried 'ModPagespeedDisallow' but it did not worked. So does this only work with subdomains or didn't we configured it correctly?

We're using nginx with Plesk 12.

**Comment by rugk** [comment] 2015-08-14 09:20
I mean as we use nginx we tried it with ```pagespeed Disallow "*/piwik/*";``` but that does not work either.

**Comment by tsteur** [comment] 2015-08-14 12:00
Sorry we cannot give pagespeed support here. If someone knows the answer please comment here. Feel free to ask in the forum as well ( http://forum.piwik.org/ ) there might be some more users that can help you. Will close the issue as actual problem is resolved

**Closed by tsteur** 2015-08-14 12:00 UTC
