### ISSUE TITLE
segmentation: add numeric operators for custom dimensions

### ISSUE THREAD

**Issue by voxspox** [piwik/piwik#17219] opened 2021-02-12 17:26 UTC
## Summary

In the segmentation editor the dropdown menu with operators shows only text operators like "contains" "starts with" for custom dimensions. 

I have numeric values in my custom dimensions. I want to see numeric operators for custom dimensions, like "less than", etc.

**Comment by tsteur** [comment] 2021-02-14 19:48
Thanks for creating this issue @voxspox  be great to have this indeed. I will close as as it's a duplicate of https://github.com/matomo-org/matomo/issues/16267 and also refs https://github.com/matomo-org/matomo/issues/5372

**Closed as completed by tsteur** 2021-02-14 19:48 UTC
Labels: duplicate

**Comment by voxspox** [comment] 2021-02-16 15:43
thx :) didn't find the other issues
