### ISSUE TITLE
Install of 2.14.2 blocked by permissions check on piwik/config path

### ISSUE THREAD

**Issue by xavez** [piwik/piwik#8439] opened 2015-07-27 20:19 UTC
On installation, piwik stops at the only error, it says the directory `/path/to/piwik_analyticsconfig/ ` is not writable. This is very possible, since that directory does not exist. It should probably be `/path/to/piwik_analytics/config/ `. Note the extra forward-slash between `piwik_analytics` (root of piwik) and `config`.

Seems like a simple bug, But I wouldn’t know where to start debugging :-).

**Comment by tsteur** [comment] 2015-07-28 05:48
Is this the full error message? It might be this line: https://github.com/piwik/piwik/blob/2.14.2-b1/core/Config.php#L408 there is at least no leading slash. If so, it is only displayed wrong but still tried to write the file correctly (will all needed slashes). Meaning there might be still a problem re permissions to write into this directory.

**Comment by tsteur** [comment] 2015-07-28 08:05
could be also caused by this maybe: https://github.com/piwik/piwik/commit/affd9703293fc748260fe96993d30ef149b34b1a#diff-6385f618444a55b5d6aae8f91574ec51R94

**Comment by mnapoli** [comment] 2015-07-28 09:01
Yes it's caused by affd9703293fc748260fe96993d30ef149b34b1a, that's weird that I wasn't able to install Piwik without this change (the path was wrong). I'll revert the change

**Comment by mnapoli** [comment] 2015-07-28 09:01
And don't know if it deserves a patch release

**Comment by mnapoli** [comment] 2015-07-28 09:04
Done in 08fa53b99fa94ad51112288487c6bcb950474dfa

**Comment by xavez** [comment] 2015-07-28 09:27
Would be nice, because changing the file manually results in a file integrity error.

<img width="868" alt="schermafbeelding 2015-07-28 om 11 21 02" src="https://cloud.githubusercontent.com/assets/400335/8927991/9dca4dd6-351b-11e5-8bf4-ac6c12bf60e5.png">

**Comment by mattab** [comment] 2015-08-05 18:38
Bug was fixed in 2.14.3-b1 and will be released shortly

**Closed by mattab** 2015-08-05 18:38 UTC
Labels: Bug
