### ISSUE TITLE
Dropdown of "Copy dashboard to another user" is incomplete

### ISSUE THREAD

**Issue by Cyver0** [piwik/piwik#18196] opened 2021-10-21 10:58 UTC
We are using Matomo Cloud, so i guess we always have the latest version.
We have 17 user accounts. 

When we want to copy a dashboard to another user, the dropdown with the users is incomplete. I can only see 7 entries. It seems not to be just the first user. I cannot say at which condition a user is in the list.
There is no scrollbar in the dropdown. Same issue on Firefox, Chrome and Safari.

Regards

**Comment by sgiehl** [comment] 2021-10-21 12:58
Hi @Cyver0 
Thanks for creating this issue. Are you using a super user account? In that case all users should be shown. When using an user with admin access only, the dialog will only show those users that have access to the sites you are having admin access to.

**Comment by Cyver0** [comment] 2021-10-21 13:18
Hi, I use a admin account. But I can see users, which doesn't even have access to the site. And I don't see all users which have access tobte site.

**Comment by sgiehl** [comment] 2021-10-21 13:20
Ok. Guess we need to investigate that a bit more in detail to check if there is a bug in our code or if there might be another reason for this.

**Comment by tsteur** [comment] 2021-10-21 19:33
@Cyver0 could you please email our support for this at support@matomo.cloud ? they will be able to check. Generally on my cloud account it works without any issue. I'll close this issue here for now as there's not much we can do but through the support we can investigate and help. Make sure to send them your cloud URL so they know which Matomo the issue is on. 

Thanks @Cyver0

**Closed as completed by tsteur** 2021-10-21 19:33 UTC
Labels: answered

**Comment by Cyver0** [comment] 2021-10-21 19:53
I wrote your support and your support told me to create a GitHub issue...
