### ISSUE TITLE
[Bug] Drop-off do not show for step 1 in Funnels

### ISSUE THREAD

**Issue by niklasternstedt** [piwik/piwik#22340] opened 2024-06-26 08:02 UTC
### What happened?

I've noticed in the new funnel report the drop-off rate don't show in the diagram for step 1 as for step 2, 3 and so forth.

### What should happen?

The drop-off rate should show as light blue as in the other steps

### How can this be reproduced?

Set up a funnel report
![Bugg med funnels gränssnitt](https://github.com/matomo-org/matomo/assets/47598905/1b08eb7d-749d-4b6a-b250-4d41396dbbb6)

### Matomo version

5.1.0

### What browsers are you seeing the problem on?

Chrome

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment] 2024-06-26 09:38
@AltamashShaikh can you answer this one?

**Comment by snake14** [comment] 2024-06-26 20:56
Hi @niklasternstedt . The chart is functioning as designed. The drop-off is reflected in the bar of the next step. This is most evident in the fact that the last bar shows drop-off when the last step cannot have exits because all visits are conversions. If you hover over the bar of step 1, you'll see that drop-off is 0, because all of the visits to step 1 were new entries. They dropped off between step 1 and step 2. Hovering over bar 2, you can see that the drop-off number matches the drop-off number underneath step 1. If you hover over bar 3, the drop-off number matches what is displayed under bar 2.

Does that make sense? We haven't received much feedback about the new chart; what can we do to help avoid this kind of confusion?

@Stan-vw I'm tagging you so that you're aware of this issue.

**Comment by Stan-vw** [comment] 2024-06-26 21:46
Thanks for opening the ticket @niklasternstedt

After considering both internal designs as well as competing products, we landed on the logic:
- show the drop-off visually in the next step, so it's clear how much visits are missing from the previous step (i.e. how many people could've made it to this step if conversion from the step before was perfect)
- show the exits number underneath the step itself, so you can compare visits in the step (top) with how many of them exit*. 
- if we would show the drop-off bar on top of the step itself, it would give a false impression of the total visits in that step.

*As a result of your feedback I noticed that we use the term "drop-off" underneath the chart though, which we will fix to "exits". The idea is that "Exits" is the term we use within the same step, and "Drop-off" will only be used to show the "lost visits" visually. We're soon shipping an improvement to the table underneath, which will align better with the chart and these terms will be more consistent across chart+table.

We're keen to get further feedback on the topic, so feel free to ask further questions, let us know what you think, and/or provide examples of other products that do it differently that you think is more intuitive 👍

**Comment by Stan-vw** [comment] 2024-07-17 00:12
Closing this as the feature is working as-intended (as described above). However, we're happy to receive more feedback 👍

**Closed as not planned by Stan-vw** 2024-07-17 00:12 UTC
Labels: Waiting for user feedback
