### ISSUE TITLE
Codebase: make all API calls customisable by plugins (use Request::processRequest for internal API calls)

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#9116] opened 2015-10-29 00:40 UTC
The Piwik analytics platform aims to be a fully customisable analytics platform that . Our [Developer Guides explain how to build plugins](http://developer.piwik.org/develop) and modify any part of Piwik (eg. [all events](http://developer.piwik.org/api-reference/events) one can hook into).

In this issue we focus on making more of the platform possible to customise. 

Goal is to modify all internal calls `*::getInstance()->` where the instance is an `API`, and change them to `Request::processRequest`. Example: `API::getInstance()->getMetadata(...)` becomes:  `Request::processRequest('API.getMetadata', array(...));`

When passing through `Request::processRequest`, the API call becomes pluggable by any plugin which can modify the request parameters and / or the returned values / output.

**Comment by tsteur** [comment] 2015-10-29 02:13
Duplicate of #7105 ?

**Closed** 2015-10-29 02:53 UTC
Labels: c: Platform
