### ISSUE TITLE
Transitions shows only partial data for URLs when multiple domains tracked to the same site

### ISSUE THREAD

**Issue by diosmosis** [piwik/piwik#17875] opened 2021-08-11 01:37 UTC
NOTE: I looked for a duplicate but couldn't find an open issue.

## Expected Behavior

If URLs with multiple domains are tracked to a single site, for example `piwik1.net/some/path` and `piwik2.net/some/path`, viewing `/some/path` in the Transitions UI should show data for both piwik1.net & piwik2.net URLs.

## Current Behavior

Instead, only data for one URL is used. The URL that is chosen is the URL that ends up as the `url` metadata in the `Actions.getPageUrls` report. The action matching code in `TableLogAction::getIdActionFromSegment` doesn't ignore the host so only some data is selected.

## Possible Solution

Some possible solutions:

- look for idactions where the name ends in the path, rather than just the given URL. (may be a performance hit, especially if patching core logic)
- store every URL host tracked somewhere in the actions report (would require re-archiving for users affected)
- process this data with Actions.getPageUrls archiving (from a quick look, it seems possible to process this data as we aggregate over log_link_visit_action)

## Steps to Reproduce (for Bugs)

1. track a visit to a site with the URL `http://piwik1.net/some/path`
2. track a visit to the same site with the URL `http://piwik2.net/some/path`
3. view the transitions report for `/some/path`. The pageviews count in the dropdown will be correct, the pageviews count in the main visualization will be incorrect.

NOTE: This bug is visible in our Transitions UI tests.

**Comment by diosmosis** [comment] 2021-08-11 01:38
From our UI test:

![image](https://user-images.githubusercontent.com/125140/128956546-ab5e2254-7ccb-4750-8784-73ea9a6b93e4.png)

See 24 vs 14

**Comment by webberian** [comment] 2022-07-01 11:18
Duplicate of #15039?

**Comment by mattab** [comment] 2023-12-10 13:34
Duplicate of https://github.com/matomo-org/matomo/issues/15039 - thanks @webberian @diosmosis for the comments!

**Closed as not planned by mattab** 2023-12-10 13:34 UTC
Labels: Bug, duplicate
