### ISSUE TITLE
Visitor log may be displayed with many columns

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#6928] opened 2015-01-06 03:07 UTC
It was reported [in the forums](http://forum.piwik.org/read.php?2,123190) (and several more posts) that the Visitor Log can appear broken with many columns displayed instead of only 3 columns.

To reproduce the issue you can edit the table preference setting with:
```
UPDATE `piwik`.`piwik_option` SET `option_value` = '{"isFooterExpandedInDashboard":true,"filter_limit":100,"viewDataTable":"table"}' WHERE `piwik_option`.`option_name` = 'viewDataTableParameters_root_Live.getLastVisitsDetails';
```

where `root` is your username. Setting `"viewDataTable":"table"` creates the bug. 

Maybe this is caused because the Visitor Log uses a custom table visualisation with an ID of `'Piwik\Plugins\Live\VisitorLog'` and it expected this `viewDataTable` value?

**Comment by sgiehl** [comment] 2015-01-06 10:51
Maybe could implement to set a "fixed" view type for a report, that can't be changed by settings in db or url.

**Comment by warenhaus** [comment] 2015-01-07 09:01
mattab, are you saying that one could change the preference setting via sql to a setting that "unbreaks" the log? (i.e., displaying only 3 columns)

what setting would that be?

**Comment by dmsz** [comment] 2015-01-15 09:49
i have the same issue with a brand new installation of piwik 2.10.0.
Visitor log is raw data table with text only no images or text formatting..
PHP version is 5.3.27. I will ask them to upgrade it and we'll see what happens then.

**Comment by dmsz** [comment] 2015-01-15 11:50
unortunately the previous fix for view type has not solved the problem for me.

**Comment by sgiehl** [comment] 2015-01-15 11:53
Did you apply the patch? The changes are currently not merged to master

**Comment by dmsz** [comment] 2015-01-15 13:46
i changed the 2 files according to #6987 but the visitor log remains a raw data table with text only. 
tried it twice but no success.

**Comment by sgiehl** [comment] 2015-01-15 14:04
Hm. That's weird. I'm not able to reproduce that on my local machine.

**Comment by dmsz** [comment] 2015-01-15 22:26
it is strange indeed, i tried to install a third time again, the system check passed without a warning, but the visitor log is just the same table with text.

**Comment by sgiehl** [comment] 2015-01-16 20:53
This issue seems to be php related. I've set up a multi php env now to test that.
5.3.27 doesn't display the correct view.
5.5.20 does it with the same install.

**Comment by sgiehl** [comment] 2015-01-16 23:39
I've tried to investigate that a bit more. Besides having an incorrect view set in the options table (which would be fixed by the PR), I'm not able to reproduce that error.
I've also tried that on PHP 5.3.27, 5.4.36 and 5.5.20. All with the same behavior.

**Comment by ToBeFree** [comment] 2015-01-17 22:31
Hey, I just wanted to note that we have been experiencing exactly the same problem and were able to nicely fix it by applying this patch. Thank you so much for your work, and I hope the next version will be released soon for others who might not see this patch. ^.^

**Comment by dmsz** [comment] 2015-01-19 08:21
Thank you guys, the modified fix worked. I am very thankful.

**Closed** 2015-01-20 01:58 UTC
Labels: Bug, Major
