### ISSUE TITLE
Handle 429 HTTP response in the UI

### ISSUE THREAD

**Issue by JasonMortonNZ** [piwik/piwik#19317] opened 2022-06-07 02:02 UTC
We need to adjust the UI to handle a 429 HTTP response happening. At present a generic error message will be displayed when someone encounters this issue. It would be good to implement a custom HTML error page for this response type.

This is required to complete the rate limiting feature (dev-2437) on cloud and will improve uptime, cloud performance and customer experience.

**Comment by sgiehl** [comment] 2022-06-07 13:19
Looks like a duplicate of #19233

**Closed as completed by sgiehl** 2022-06-07 13:19 UTC
Labels: Enhancement, duplicate
