### ISSUE TITLE
'xxxx.piwik_user_language' doesn't exist

### ISSUE THREAD

**Issue by stefan-niedermann** [piwik/piwik#9708] opened 2016-02-04 14:29 UTC
Tried to update to 2.16, getting following error:

/xxx/piwik/plugins/LanguagesManager/Updates/2.15.1-b1.php: Error trying to execute the query 'ALTER TABLE `piwik_user_language` ADD COLUMN `use_12_hour_clock` TINYINT(1) NOT NULL DEFAULT 0 AFTER `language`'. The error was: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'xxxx.piwik_user_language' doesn't exist

now i stuck at update-page - i can not go back, i can not go forward - what to do?

**Comment by tsteur** [comment] 2016-02-04 20:01
Marking this one as a duplicate of https://github.com/piwik/piwik/issues/9666

To solve it execute the SQL query mentioned here: https://github.com/piwik/piwik/issues/9666#issuecomment-177592041

**Comment by Joey3000** [comment] 2016-02-05 05:18
I'm not sure that this is the same issue as #9666. Because the plugins/LanguagesManager/Updates/2.15.1-b1.php script does run here, and the whole `user_language` table appears to not exist here during its run.

I'm wondering where the "xxxx." pre-prefix comes from in 'xxxx.piwik_user_language'. (Unless it's normal for MySQL to prepend something on error reporting.)

@stefan-niedermann If this issue persists, could you please provide the following information:

* How do you update? Could you provide a step-by-step test procedure to reproduce the issue?
* Your PHP and MySQL version

**Comment by tsteur** [comment] 2016-02-07 18:21
Re the `xxx` it's only an assumption: User might have removed "sensitive" information like the path.

From which version did you try to update?

**Comment by tsteur** [comment] 2016-02-07 19:02
See https://github.com/piwik/piwik/issues/9714 user removed real table prefix.

**Closed** 2016-03-31 02:44 UTC
