### ISSUE TITLE
Custom variables all in one graph

### ISSUE THREAD

**Issue by rugk** [piwik/piwik#8507] opened 2015-08-06 14:23 UTC
The [custom variables] (https://developer.piwik.org/guides/tracking-javascript-guide#custom-variables) are all in one graph - no matter what you do. In the table view this may be okay, because you can unfold the name  of the variable and see the results.
But if you select a graph (e.g. a pie chart) at the bottom it at first displays the percentage of the variable names (so the 'category'). E.g. if you have two variable names gender and category (like it's shown on the dev page) both of them will be placed in the pie chart and you will e.g. get: 45% gender, 55% category. That's useless!

However you can make the report 'flat' so you won't have these foldings. After this you can also see the category values, but it's still in one chart. In the example it would be: 30 % gender - male, 30 % gender - female, 15% Category - Europe, 25% Category - Sports.
It even does not matter in what slot/index the variable is saved. It's still all in one graph.

This makes pie charts of specific variables practically useless.

I cannot see a direct relation to these issues, but maybe they are related: https://github.com/piwik/piwik/issues/6762, https://github.com/piwik/piwik/issues/6031

**Comment by mattab** [comment] 2015-09-20 23:24
Thanks @rugk for the feedback. I mark as duplicate of #2786 Allow to plot custom variable values (or any rows) by searching & plotting - JS Graphs 

I post your message as a comment on this issue

**Closed by mattab** 2015-09-20 23:24 UTC
