### ISSUE TITLE
Goal definition using data from "setEcommerceView": category, SKU, price...

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#9756] opened 2016-02-11 14:00 UTC
Piwik has a great feature to track **details of a product page visited**:
- categories,
- SKUs,
- price
- etc

This also works when these informations are **not** within
- pagetitle or
- url

or if the same product is available on different urls*

It's done by using "setEcommerceView" feature
see
https://piwik.org/docs/ecommerce-analytics/#tracking-product-page-views-category-page-views-optional.

**Already tracking these data, it would be awesome to make it also usable - e.g. within goal definition.**

Having this, one could set up **really interesting goals** like:
- products of category X visited/seen (no matter on which url*)
- products visited/seen with a price > 100€
- products visited/see with a SKU containing "1234"

------------------------------------
*In several shop system products are accessible on different urls.
e.g. in Magneto these are:

domain.com/product.html
    domain.com/category1/product.html
    domain.com/catalog/product/view/id/1/
    domain.com/catalog/product/view/id/1/category/1/

**Comment by hpvd** [comment] 2016-02-11 14:40
may look like this (UI):
![2016-02-11_15h32_55](https://cloud.githubusercontent.com/assets/5681880/12979184/d4aa4404-d0d5-11e5-8154-e364a4756bb9.png)

**Comment by mattab** [comment] 2016-03-31 03:23
@hpvd thanks for the suggestion. Marking as duplicate of #4519

**Closed by mattab** 2016-03-31 03:23 UTC
