### ISSUE TITLE
Update to 3.0.0 breaks dashboard if server does not support `Options -Indexes` in ".htaccess" files

### ISSUE THREAD

**Issue by codifex** [piwik/piwik#11146] opened 2017-01-04 13:43 UTC
When updating Piwik using the automatic update process from the last version to the most recent version 3.0.0, the dashboard is broken. This means, that no icons and widgets are shown in the backend.

The problem seems to be caused by the line `Options -Indexes` in the ".htaccess" files in Piwik's "plugins" and "libs" folders, which is not supported by the server. Excerpt from the server's log files:

`Options not allowed here, referer: <URL>`

Piwik is hosted on shared hosting and changing options is disabled by the provider.

The problem can be fixed by commenting out the above-mentioned line (`#Options -Indexes`). However, we are unsure if this fix is safe and what's the recommended solution for this problem.

(Discussion on the forum: https://forum.piwik.org/t/no-more-dashboard-after-upgrade-to3-0/22182)

**Comment by piotr-cz** [comment] 2017-01-05 10:16
I had this problem too, my host doesn't support `Options`  directive.

This Issues is a duplicate of https://github.com/piwik/piwik/issues/11040, fixed in https://github.com/piwik/piwik/commit/f9c20700160610a212ad879e054eff6cd9c91bd6, and available since 3.0.1-b1

**Closed** 2017-01-05 10:49 UTC
Labels: duplicate
