### ISSUE TITLE
Upgrade 3.14.1 to 4.0.3 fails: ALTER TABLE `matomo_log_visit`

### ISSUE THREAD

**Issue by cy2201** [piwik/piwik#16861] opened 2020-12-02 04:39 UTC
Hi,

I tried to upgrade Matomo from 3.14.1 to 4.0.3 and it instantly failed.

Last lines of log:
```
Executing ALTER TABLE `matomo_archive_blob_2020_11` CHANGE `name` `name` VARCHAR(190);... Done. [80 / 115]
  Executing ALTER TABLE `matomo_archive_blob_2020_12` CHANGE `name` `name` VARCHAR(190);... Done. [81 / 115]
  Executing ALTER TABLE `matomo_log_link_visit_action` ;... Done. [82 / 115]
  Executing INSERT IGNORE INTO `matomo_option` (option_name, option_value) VALUES ('version_log_link_visit_action.search_cat', 'VARCHAR(200) NULL')                                                                                          ;... Done. [83 / 115]
  Executing INSERT IGNORE INTO `matomo_option` (option_name, option_value) VALUES ('version_log_link_visit_action.search_count', 'INTEGER(10) UNSIG                                                                                          NED NULL');... Done. [84 / 115]
  Executing INSERT IGNORE INTO `matomo_option` (option_name, option_value) VALUES ('version_log_link_visit_action.time_dom_completion', 'MEDIUMINT(                                                                                          10) UNSIGNED NULL');... Done. [85 / 115]
  Executing INSERT IGNORE INTO `matomo_option` (option_name, option_value) VALUES ('version_log_link_visit_action.time_dom_processing', 'MEDIUMINT(                                                                                          10) UNSIGNED NULL');... Done. [86 / 115]
  Executing INSERT IGNORE INTO `matomo_option` (option_name, option_value) VALUES ('version_log_link_visit_action.time_network', 'MEDIUMINT(10) UNS                                                                                          IGNED NULL');... Done. [87 / 115]
  Executing INSERT IGNORE INTO `matomo_option` (option_name, option_value) VALUES ('version_log_link_visit_action.time_on_load', 'MEDIUMINT(10) UNS                                                                                          IGNED NULL');... Done. [88 / 115]
  Executing INSERT IGNORE INTO `matomo_option` (option_name, option_value) VALUES ('version_log_link_visit_action.time_server', 'MEDIUMINT(10) UNSI                                                                                          GNED NULL');... Done. [89 / 115]
  Executing INSERT IGNORE INTO `matomo_option` (option_name, option_value) VALUES ('version_log_link_visit_action.time_transfer', 'MEDIUMINT(10) UN                                                                                          SIGNED NULL');... Done. [90 / 115]
  Executing ALTER TABLE `matomo_log_visit` ADD COLUMN `visitor_seconds_since_first` INT(11) UNSIGNED NULL, ADD COLUMN `visitor_seconds_since_order`                                                                                           INT(11) UNSIGNED NULL, ADD COLUMN `visitor_seconds_since_last` INT(11) UNSIGNED NULL, ADD COLUMN `profilable` TINYINT(1) NULL;...
    [X] Critical Error during the update process:

    * /var/www/matomo/core/Updates/4.0.0-b1.php:
    Error trying to execute the migration 'ALTER TABLE `matomo_log_visit` ADD COLUMN `visitor_seconds_since_first` INT(11) UNSIGNED NULL, ADD COLUM                                                                                          N `visitor_seconds_since_order` INT(11) UNSIGNED NULL, ADD COLUMN `visitor_seconds_since_last` INT(11) UNSIGNED NULL, ADD COLUMN `profilable` TINYI                                                                                          NT(1) NULL;'.
    The error was: SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not co                                                                                          unting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs

    The above is the core error message. It should help explain the cause, but if you require further help please:

    * Check the [ Matomo FAQ ] which explains most common errors during update.
    * Ask your system administrator - they may be able to help you with the error which is most likely related to your server or MySQL setup.

    If you are an advanced user and encounter an error in the database upgrade:

    * identify and correct the source of the problem (e.g., memory_limit or max_execution_time)
    * execute the remaining queries in the update that failed
    * manually update the `option` table in your Matomo database, setting the value of version_core to the version of the failed update
    * re-run the updater (through the browser or command-line) to continue with the remaining updates
    * report the problem (and solution) so that Matomo can be improved
ERROR [2020-12-02 04:22:38] 22642  Uncaught exception: /var/www/matomo/plugins/CoreUpdater/Commands/Update.php(255): Matomo could not be updated! S                                                                                          ee above for more information.
Matomo could not be updated! See above for more information.



  [RuntimeException]
  Matomo could not be updated! See above for more information.



core:update [--yes]
```

Can you help me? What should I do?

**Comment by cy2201** [comment] 2020-12-02 04:44
![2020-12-02 05_43_45-Window](https://user-images.githubusercontent.com/33823543/100829334-640d5700-3461-11eb-8106-049f768a9ce0.png)

**Comment by tsteur** [comment] 2020-12-02 04:55
Hi @qwertz22 we have an FAQ for this see https://matomo.org/faq/troubleshooting/how-do-i-fix-the-error-1118-row-size-too-large-the-maximum-row-size-for-the-used-table-type-not-counting-blobs-is-8126/ 

Hoping this helps. Let us know if it doesn't.

closing this as a duplicate of https://github.com/matomo-org/matomo/issues/16810

**Closed as completed by tsteur** 2020-12-02 04:55 UTC
Labels: duplicate
