### ISSUE TITLE
Calculate totals row based on search criteria results in reports

### ISSUE THREAD

**Issue by Starker3** [piwik/piwik#18192] opened 2021-10-21 02:09 UTC
Currently when searching/filtering results in a report the totals row is not updated to reflect the totals for the filtered data.

It would be really useful for people to be able to quickly see the summed totals for the data they're looking at.

![image](https://user-images.githubusercontent.com/20905821/138198865-c677ef1f-7ea6-46ed-a81f-42cf9a7b8dae.png)
![image](https://user-images.githubusercontent.com/20905821/138198892-db33b52a-0b48-4d5e-ace5-23beef4dc551.png)

**Comment by tsteur** [comment] 2021-10-21 04:33
@Starker3 I'll close this as a duplicate of https://github.com/matomo-org/matomo/issues/18056 let me know in case it's not the same

**Closed as completed by tsteur** 2021-10-21 04:33 UTC
Labels: duplicate
