### ISSUE TITLE
X-Frame-Options header set to empty value

### ISSUE THREAD

**Issue by powerriegel** [piwik/piwik#10167] opened 2016-05-20 13:12 UTC
Hello,
I'm running Piwik **2.16.1** and use the Custom Opt-Out plugin. I don't know if this bug is related to custom opt-out or not but it also appears if no custom opt-out html is set. 

On the page where my Opt-out is embedded in an IFrame, Chrome reports

> Invalid 'X-Frame-Options' header encountered when loading 'https://mydomain.compiwik/index.php?module=CoreAdminHome&action=optOut&idsite=25&language=de': '' is not a recognized directive. The header will be ignored.

Opening the frame content in a new tab I can see the empty header in chrome dev tools:

```
Server:Apache/2.2.22 (Debian)
Vary:Accept-Encoding
X-Frame-Options:
```

Maybe this is the problem: https://github.com/piwik/piwik/blob/master/core/View.php#L340

Valid values are DENY, SAMEORIGIN, ALLOW-FROM , the latter with very poor browser support. 

Empty values are not allowed. 

Or is this configurable?

**Comment by tsteur** [comment] 2016-05-22 22:06
Thx for reporting the issue 👍  I can reproduce this issue and also get the empty value because of https://github.com/piwik/piwik/commit/00029a887a2d3f7cb123ca548723731aef82dffa#diff-3b04c2fd13299169fa41941cde7074d0R163  

This seems like an easy fix by actually sending "allow". @mattab do you remember why this was needed?

**Comment by blueelvis** [comment] 2016-07-07 20:47
Hey @mattab - A real newbie in OSS here. Do you think this commit is a good fix for this bug? Any way I could improve it?

[https://github.com/blueelvis/piwik/commit/ef9c62868b59c0bd4ff2148a307f409c51456232](url)

**Comment by mattab** [comment] 2016-07-08 04:58
@blueelvis  the link does not work for me, maybe repo is private? feel free to open a pull request and we can discuss in the PR directly :

**Comment by lemonksgithub** [comment] 2016-11-16 14:31
I have the same problem!

**Comment by tuffz** [comment] 2016-11-16 14:36
@mattab https://github.com/piwik/piwik/issues/10167#issuecomment-231202550 the link-href is corrupted but if you copy and paste linked text it works perfectly or you click on following link: https://github.com/blueelvis/piwik/commit/ef9c62868b59c0bd4ff2148a307f409c51456232

**Comment by Braintelligence** [comment] 2017-01-07 12:49
Running on Piwik 3.0.0 I still have this problem, I guess:
`Invalid 'X-Frame-Options' header encountered when loading 'https://subdomain.domain.tld/index.php?module=CoreAdminHome&action=optOut&language=de': '' is not a recognized directive. The header will be ignored.`

What are the necessary steps to fix this?

**Comment by mattab** [comment] 2017-02-18 08:49
> EDIT: Ah nevermind, this fix will make it in 3.0.1 it seems :smile_cat:

@Braintelligence so far we haven't fixed this issue. Please open a pull request if you can

**Comment by GermanKiwi** [comment] 2017-02-19 00:01
Some additional info from me - which I previously posted at #7379:

I'm running WordPress and using the WP Piwik plugin, and I found that this empty X-Frame-Options header, generated by Piwik, is only there when I set "Piwik Mode" to "Self-hosted (PHP API)" in the plugin settings. However, if I change Piwik Mode to "Self Hosted (HTTP API)", then this header is no longer generated. I have no idea why. I'd prefer to keep using the PHP API mode if I can, but obviously without the empty header being generated.

In fact, I would really love the ability to disable Piwik's generation of this header entirely. I'd prefer to manange my HTTP headers myself using my .htaccess file. Could you provide a way to stop Piwik from generating it? Perhaps something in Piwik's options, or something in Piwik's config file that I could add?

**Comment by mattab** [comment] 2017-02-19 10:18
This PR should fix the issue: #11358 - feedback welcome :

**Comment by GermanKiwi** [comment] 2017-02-19 14:34
Hi @mattab, will your patch provide a way to disable the header altogether? Or at least not to add it if it already exists from .htaccess?

**Comment by mattab** [comment] 2017-02-20 08:55
@GermanKiwi No this patch doesn't quite address the case where web server already issues the x-frame-options header. But would you mind testing it and please open new issue if you still have this problem

**Comment by GermanKiwi** [comment] 2017-02-20 23:09
Sure thing @mattab I'll be happy to test it - but can you kindly let me know how exactly I can do that?! In other words, how do I go about installing this patch onto my current Piwik installation? I've never done that before. ;)

**Comment by Findus23** [comment] 2017-02-21 08:55
@GermanKiwi The fastest way would be downloading the patch by appending .patch on the pull request url:
```bash
wget https://github.com/piwik/piwik/pull/11358.patch
```
and then applying the patch (while you are in the root directory of your piwik installation)
```bash
patch -p1 < 11358.patch
```
Of course there is also the manual way:
 - change `core/Plugin/Controller.php` and `core/View.php` as seen in https://github.com/piwik/piwik/pull/11358/files

**Closed** 2017-02-21 10:16 UTC
Labels: Bug, Easy pick

**Comment by mattab** [comment] 2017-02-21 18:52
@GermanKiwi  please try with our latest 3.0.2-b5 which includes this patch: http://piwik.org/faq/how-to-update/faq_159/

**Comment by GermanKiwi** [comment] 2017-02-21 21:25
Hi @mattab, I'm still having some issues with empty headers after I installed 3.0.2-b5, so I've created a new issue with all the details at https://github.com/piwik/piwik/issues/11391.
