### ISSUE TITLE
 anomaly in the Matomo Analytics tool

### ISSUE THREAD

**Issue by Vastruc** [piwik/piwik#21378] opened 2023-10-06 16:25 UTC
While monitoring the group intranet indicators, we identified an anomaly in the Matomo Analytics tool. Indeed, the IP addresses of visitors to eramet|inside (intranet) are unexpectedly geolocated in Israel, as illustrated in the screenshots below. Could you assist us in comprehending this situation? It appears that this issue is related to the database utilized by Matomo to match IP addresses with locations, which seems to be outdated.
We are providing you with the complete list of IP addresses (IP Address column) used, along with their corresponding physical locations, to update in the Matomo tool : 

https://config.zscaler.com/zscalerthree.net/cenr 
![Unknown-2](https://github.com/matomo-org/matomo/assets/147185401/c226b9a1-9172-4fc3-a14a-76f313c8a01c)
![Unknown-3](https://github.com/matomo-org/matomo/assets/147185401/4ccf7d94-6c26-4cac-bf62-132ba0793f32)
![Unknown](https://github.com/matomo-org/matomo/assets/147185401/6c270ce2-c25f-473a-bcfb-152059250598)
![Unknown-1](https://github.com/matomo-org/matomo/assets/147185401/22dec30a-89a1-4183-a633-ded3cdb368c2)

**Comment by michalkleiner** [comment] 2023-10-07 03:52
Closing as a duplicate of #21379.

**Closed as completed** 2023-10-09 09:57 UTC
Labels: duplicate, not-in-changelog
