### ISSUE TITLE
New request for flat view in e-mail report

### ISSUE THREAD

**Issue by dscaravaggi** [piwik/piwik#7746] opened 2015-04-22 16:39 UTC
Hi all,
Is it possible to add an option in the e-mail report wizard in order to add flat=1 in the reporting API ?
I'm aware that it is a secondary feature but It could help final users.

Ciao
Diego

**Comment by gaumondp** [comment] 2015-04-22 16:59
Duplicate of #2137 I think.

**Closed** 2015-04-22 22:05 UTC
