### ISSUE TITLE
Provide non-200 error code when API method does not exist

### ISSUE THREAD

**Issue by diosmosis** [piwik/piwik#21425] opened 2023-10-23 07:33 UTC
## Summary

Currently when sending a request to the Matomo API with a method that does not exist, the HTTP response has a 200 response code but an error message saying the method does not exist. For easier automated detection of this specific error, it would be useful if the response code was a specific error code (like bad request for example).

(Note for prioritisation: should be a quick change, but not needed, would be nice to have.)

**Comment by camicacace** [comment] 2024-04-21 23:17
Hi, is this issue still open?

**Comment by michalkleiner** [comment] 2024-04-22 00:17
Hi @camicacace, yes, the issue is still open and we'd welcome a PR if you wanted to have a go at creating one.

**Comment by jsantos42** [comment] 2024-09-27 14:54
@michalkleiner  I believe this issue has been solved, not sure which PR fixed it but on my local dev copy I seem to be able to elicit the desired behavior. Should we close the issue?

<img width="1286" alt="Screenshot 2024-09-27 at 16 52 40" src="https://github.com/user-attachments/assets/96884c85-290c-46db-aa48-4680aee812b5">

**Comment by michalkleiner** [comment] 2024-09-27 15:20
It indeed had been fixed, @jsantos42, via https://github.com/matomo-org/matomo/pull/22334. Thanks for the follow up, I'll close this issue now.

**Closed as completed by michalkleiner** 2024-09-27 15:20 UTC
Labels: Enhancement, c: APIs
