### ISSUE TITLE
PHP 8.1 incompatibility - imagettfbbox(): Passing null to parameter #4 ($string) of type string is deprecated in Image.php

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#20654] opened 2023-05-03 00:28 UTC
> vendor/szymach/c-pchart/src/Image.php(236): Deprecated - imagettfbbox(): Passing null to parameter #4 ($string) of type string is deprecated - Matomo 4.14.3-b1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) [internal function]: Piwik\ErrorHandler::errorHandler(),#1/vendor/szymach/c-pchart/src/Image.php(236),#2/vendor/szymach/c-pchart/src/Draw.php(2289),#3/plugins/ImageGraph/StaticGraph/GridGraph.php(312),#4/plugins/ImageGraph/StaticGraph/Evolution.php(24),#5/plugins/ImageGraph/API.php(506),[internal function]: Piwik\Plugins\ImageGraph\API->get(),#7/core/API/Proxy.php(244),#8/core/Context.php(28),#9/core/API/Proxy.php(335)

After upgrading to PHP 8.1 above warning is showing up in the logs. This is all the information we have.

**Comment by michalkleiner** [comment] 2023-05-04 03:17
Hi @tsteur,

thank you for reporting this. Looking through the code, this is also the same source of the deprecation when a data series doesn't have a description. I will mark this as a duplicate of #20655 as when that is resolved this issue should also get resolved.

**Closed as not planned by michalkleiner** 2023-05-04 03:17 UTC
Labels: duplicate
