### ISSUE TITLE
“Show more clearly the freshness of reports” not working

### ISSUE THREAD

**Issue by aaragones** [piwik/piwik#18689] opened 2022-01-26 10:28 UTC
Before the update we was able to check the freshness of the reports by doing this:
https://matomo.org/faq/how-to/how-do-i-know-how-long-ago-was-a-given-report-generated/

After the update https://github.com/matomo-org/matomo/issues/14977 we can’t use the old functionality, neither the new one.

## Expected Behavior
These videos: https://github.com/matomo-org/matomo/issues/14977#issuecomment-825221405
Or at least the old behavior: https://user-images.githubusercontent.com/466765/66468671-0bebf680-eae3-11e9-87e1-755313ac9402.png

## Current Behavior
No Freshness showed, even in your demo

**Comment by bx80** [comment] 2022-01-26 23:02
Hi @aaragones, thanks for reporting this, I can confirm that the report generated date is not being shown when hovering over the report header.

Although the report generated date is being added to the report header, the `inlineHelp` div in which it is contained is not being displayed when hovering.

**Comment by peterhashair** [comment] 2022-01-27 02:07
Maybe we can add the date just below the title. @tsteur  @bx80  any suggestion?

![image](https://user-images.githubusercontent.com/3783072/151278873-2d3c3cb1-e855-4693-916c-20078ce32ecf.png)

**Comment by tsteur** [comment] 2022-01-27 02:12
This works for me currently. It shows at least in the latest `4.x-dev` branch, possibly also in the 4.7 release that is upcoming.

![image](https://user-images.githubusercontent.com/273120/151279426-c8f1b970-1590-4df6-b1df-05eac63d973f.png)

Note that this information is only shown when viewing a period that includes today.

Was this fixed by https://github.com/matomo-org/matomo/pull/18498 ?

**Comment by peterhashair** [comment] 2022-01-27 02:29
@tsteur yes, that was fixed by #18498.

**Comment by bx80** [comment] 2022-01-27 21:05
Yes, sorry this does work for me on 4.x-dev.

I noticed the FAQ screenshot shows a question mark help icon, whereas currently an info icon is being shown in the application. It might also be clearer to have two screenshots in the FAQ, first showing the report info hidden and highlighting the info icon and then a second screenshot showing the report info after the icon is clicked.

**Closed as completed** 2022-06-03 13:46 UTC
Labels: duplicate
