### ISSUE TITLE
Add tooltip or help text to "Email Reports" page

### ISSUE THREAD

**Issue by Starker3** [piwik/piwik#17791] opened 2021-07-19 05:30 UTC
Currently when you create a new Email Report (Or for existing reports) you have the option to `Download` the report or the `Send report now`
However, what users may not always realise is that the Email Report will be sent using the both the period and dates selected in the Date Selector.

We should add either a small text box somewhere on the page or add a tooltip to the "Download" and "Send report now" links to indicate that the dates and periods currently in the Date Selector will be used for the report.

For example:
![image](https://user-images.githubusercontent.com/20905821/126107532-ecafb0d5-aeef-450b-85ae-9b2d3d026134.png)

Alternatively help text that is displayed when hovering over the links.

**Comment by Findus23** [comment] 2021-07-19 11:10
related to https://github.com/matomo-org/matomo/issues/11367

**Comment by tsteur** [comment] 2021-07-19 21:33
@Starker3 @Findus23 closing this as a duplicate of https://github.com/matomo-org/matomo/issues/11367

**Closed as completed by tsteur** 2021-07-19 21:33 UTC
Labels: Enhancement, duplicate, c: Usability
