### ISSUE TITLE
Possible regression. When creating segments, "Android" is not offered as an option for Operating System type

### ISSUE THREAD

**Issue by atom-box** [piwik/piwik#19759] opened 2022-09-22 19:44 UTC
**To reproduce:**
In Matomo Cloud, create a new segment with this condition: **(operating system == 'android')**

**Expected:**
One of the suggestions as you type should be 'android'

**Actual:**
Even if you start to type: a-n-d-... nothing comes up in the suggestions.
![image](https://user-images.githubusercontent.com/22874146/191836107-657bbdb7-5a52-4f18-b4c7-0411a0f13f49.png)
The segment can still be created: I typed in 'android', got no assistance from the suggested OS's, and once created, **the segment works fine**.

So this bug is just that the suggestions won't suggest android. This might sound like a small thing, but since the suggestions include weird things like Whale OS and Zenwalk, **it makes it seem to the user that detecting Android OS is one of the few OS's that are unsupported**.

**As a counterexample**, I confirmed that this bug is not present in my on premise Matomo version 4.10.  
So everything is okay on this system:
Matomo version: 4.10.1
MySQL version: 5.7.39-0ubuntu0.18.04.2
PHP version: 7.4.30

**Comment by bx80** [comment] 2022-09-22 23:17
Hi @atom-box, thanks for the detailed write up :+1: I can confirm the issue is present on 4.x-dev, I'll assign it for prioritization.

**Comment by sgiehl** [comment] 2022-10-06 09:20
For me Android is actually in the suggestion list. The list of suggested OS is sorted by their usage. So if there weren't any visits with Android in the last days it might be sorted down the list. As there is a limit how many entries are suggested at all, it can happen that it is removed from the suggestion list I guess. Might be possible that device detector used in Matomo 4.12 is now able to detect more OS, causing more OS being dropped from suggestion list.

**Comment by michalkleiner** [comment] 2024-03-21 10:47
@atom-box is this still an issue (also see Stefan's comment above) or can we close this?

**Comment by michalkleiner** [comment] 2024-05-17 12:53
Closing as it's likely not an issue based on the fact the list is sorted by usage.

**Closed as not planned by michalkleiner** 2024-05-17 12:53 UTC
Labels: Bug
