### ISSUE TITLE
Some static Image graphs are broken

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#8923] opened 2015-10-05 21:43 UTC
See at: http://developer.piwik.org/api-reference/reporting-api-metadata#static-image-graphs

Some of the graphs are broken with error message "Invalid API module and/or action"

This was reported in forums: http://forum.piwik.org/read.php?9,128022

This regressed during 2.15.0 beta cycle. 

Steps 
 * Check why our UI tests for static image graph didn't catch this bug
 * Fix issue

**Comment by diosmosis** [comment] 2015-10-07 17:41
Works for me locally and on demo2, perhaps this is fixed in master?

**Comment by diosmosis** [comment] 2015-10-07 21:56
Ok, I can reproduce now.

**Closed** 2015-10-08 21:41 UTC
Labels: not-in-changelog, Regression
