### ISSUE TITLE
Have been receiving hourly 'GeoIP2AutoUpdater' geolocation errors since the beginning of this month.

### ISSUE THREAD

**Issue by DXXS** [piwik/piwik#22185] opened 2024-05-04 23:53 UTC
ERROR [2024-05-04 23:05:11] 92658  /var/www/matomo/plugins/GeoIp2/GeoIP2AutoUpdater.php(190): GeoIP2AutoUpdater: failed to unzip '/var/www/matomo/tmp/latest/DBIP-City.mmdb.gz.download' after downloading 'https://download.db-ip.com/free/dbip-city-lite-2024-05.mmdb.gz': The downloaded file is not a valid geolocation database. Please re-check the URL or download the file manually. [Query: , CLI mode: 1]
ERROR [2024-05-04 23:05:11] 92658  Scheduler: Error GeoIP2AutoUpdater: failed to unzip '/var/www/matomo/tmp/latest/DBIP-City.mmdb.gz.download' after downloading 'https://download.db-ip.com/free/dbip-city-lite-2024-05.mmdb.gz': The downloaded file is not a valid geolocation database. Please re-check the URL or download the file manually. for task 'Piwik\Plugins\GeoIp2\GeoIP2AutoUpdater.update'

Still using Matomo 4.9.1

If I instead download said file by hand & attempt to unzip it, I get the following errors:

$ unzip ./dbip-city-lite-2024-05.mmdb.gz
Archive:  ./dbip-city-lite-2024-05.mmdb.gz
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of ./dbip-city-lite-2024-05.mmdb.gz or
        ./dbip-city-lite-2024-05.mmdb.gz.zip, and cannot find ./dbip-city-lite-2024-05.mmdb.gz.ZIP, period.

**Comment by michalkleiner** [comment] 2024-05-05 06:54
Closing as a duplicate of #18427.

**Closed as not planned by michalkleiner** 2024-05-05 06:54 UTC
Labels: duplicate

**Comment by DXXS** [comment] 2024-08-24 23:45
I'm not sure it's a duplicate (and I didn't include the unzip messages in the other posts); your 'not planned' status isn't acceptable either, as it keeps cropping up here.  Seems to go away for days sometimes if I simply reboot the server.

**Comment by sgiehl** [comment] 2024-08-26 08:07
@DXXS The underlying problem is the one described in #18427, therefor this issue was marked as duplicate / not planned, as it will be solved by the other one.
