### ISSUE TITLE
Translations: when wrong number of placeholders, error: sprintf() Too few arguments

### ISSUE THREAD

**Issue by dscaravaggi** [piwik/piwik#7546] opened 2015-03-26 15:58 UTC
Hi all,

may you verify sprintf argument usage at:

core/DataTable/Filter/BeautifyTimeRangeLabels.php line 115
	
       {
	if ($lowerBound < 60) {
	return sprintf($this->labelSecondsPlural, $lowerBound);
	} else {
	// since we're using minutes, we use floor so 1801s+ will be 30m+ and not 31m+
	return sprintf($this->labelPlural, "" . floor($lowerBound / 60) . urlencode('+'));
	}
	}

Thanks a lot
Diego

**Comment by mnapoli** [comment] 2015-03-26 21:14
Hi Diego, what is the problem here?

**Comment by dscaravaggi** [comment] 2015-03-27 20:09
*labelSecondsPlural*  sprintf format mask is expected to contain  only 1 argument, but I noticed that in some cases  "%s %s" generate a warning which is logged into piwik.log file: 

    Warning: sprintf() [function.sprintf]: Too few arguments in...

**Comment by mattab** [comment] 2015-04-08 04:48
maybe this is caused by some translations having the wrong number of placeholders in the translation strings? we should have a test that checks and notices when a translation has invalid number of placeholders. 

(fyi @sgiehl  maybe transifex has a mechanism to enforce placeholder count to be the same as in english strings? if not, we continue to remove translations that have wrong number of `%s`)

**Comment by sgiehl** [comment] 2015-04-08 05:30
Transifex is able to check that. Currently I have set that it produces a
warning only. But we could set it to an error aswell. Need to check that
works well before...

**Comment by mattab** [comment] 2015-04-09 00:20
nice to hear! let's try to ensure that all translations when they make it into Piwik git repo, use the same number of placeholders as in the english translation, in our transifex migration (#7567)

**Comment by sgiehl** [comment] 2015-04-12 21:31
we have tests for translation files also checking for the correct parameter count. But they are only marked as "skipped" when failing, so we will not get notice about that.
But updating the translation files using the console command should remove those invalid translations

**Comment by dscaravaggi** [comment] 2015-04-20 12:14
Thanks for your comments,
I understand that this is a secondary issue that could be ignored.

**Comment by sgiehl** [comment] 2015-06-22 14:50
I've rechecked that issue. As long as we ALWAYS run a translation update before building a release, this issue should not appear in any release as an update will filter such translations. Btw. tests will fail aswell if the parameter count for any translation does not match, so I'll close this ticket as we can't do much more to prevent such errors in the furure.

**Closed by sgiehl** 2015-06-22 14:50 UTC
Labels: Bug
