### ISSUE TITLE
Make custom dimension values visible in visitor log

### ISSUE THREAD

**Issue by tmuic** [piwik/piwik#10216] opened 2016-06-06 09:19 UTC
Currently only custom variable values are displayed in live reports and visitor log.

Is there a plan to include custom dimension data in same reports as well?

**Comment by tsteur** [comment] 2016-06-10 17:30
Thanks for the suggestion. I'm marking it as a duplicate of https://github.com/piwik/plugin-CustomDimensions/issues/28

**Closed by tsteur** 2016-06-10 17:30 UTC
