### ISSUE TITLE
[Piwik.js] Refacto code

### ISSUE THREAD

**Issue by dhoko** [piwik/piwik#8642] opened 2015-08-25 14:26 UTC
Hi,

Why don't you split the source into severals files? 5792L in Piwik.js :-1: 
You can then build the source via browserify. 

```js
/* alias frequently used globals for added minification */
documentAlias = document,
navigatorAlias = navigator,
screenAlias = screen,
windowAlias = window,
```

We can remove these using a closure (to create a private scope too):

```js
;(function(docAlias, winAlias, navAlias, screenAlias, undefined) {

// code 
})(document, window, navigator, screen);
```

What do you think ?

I can start to split the source if you want, I think the best way to begin is via [the Query Object](https://github.com/piwik/piwik/blob/master/js/piwik.js#L1241).

**Comment by tsteur** [comment] 2015-08-26 06:06
Heya, closing it as duplicate of #6106 . It's possible to do and would be great to have but doesn't have much priority for us currently.

**Closed by tsteur** 2015-08-26 06:06 UTC
Labels: duplicate
