### ISSUE TITLE
Hide menu on dashboard

### ISSUE THREAD

**Issue by ohreally** [piwik/piwik#9461] opened 2016-01-03 17:24 UTC
The update to Piwik 2.15 moved the menu on my dashboard from top of page to left of page. Since I'm working on a 10-inch screen, this eats up way too much valuable space.
When the menu was at the top of the page, I could just scroll it out of sight, and have optimal working space. But now that the menu is on the left, and I can only scroll vertically, there is no way to get rid of the menu.

Could you please make it configurable or hidable?
Thank you.

**Comment by tsteur** [comment] 2016-01-10 20:50
Thx for the feedback! I'll close it as a duplicate of https://github.com/piwik/piwik/issues/9263

**Closed by tsteur** 2016-01-10 20:50 UTC
Labels: duplicate
