### ISSUE TITLE
Warning when running core:archive with Matomo 4.7.1  WARNING …tcpdf/include/tcpdf_static.php(299)

### ISSUE THREAD

**Issue by atom-box** [piwik/piwik#18879] opened 2022-03-04 00:31 UTC
A user has reported this warning appears during **core:archive**.
Is it possible to make this go away? 
It causes the job to fail, which then causes alerts in the user's job monitoring.

```
INFO [2022-02-28 09:01:18] 1 Starting Scheduled tasks...
INFO [2022-02-28 09:01:18] 1 Scheduler: executing task Piwik\Plugins\ScheduledReports\API.sendReport_1...
WARNING [2022-02-28 09:01:22] 1 ...tcpdf/include/tcpdf_static.php(299): Notice - tempnam(): file created in the system's temporary directory - Matomo 4.7.1
WARNING [2022-02-28 09:01:22] 1 ...tcpdf/tcpdf.php(7375): Warning - imagepng(/var/www/html/tmp/tcpdf/__tcpdf_bf96ba20a3ed8a3621345ce3e1f573ce_imgmask_alpha_7c46a167016c23507b929c97679089b7): failed to open stream: No such file or directory - Matomo 4.7.1  
WARNING [2022-02-28 09:01:22] 1 /var/www/html/vendor/.../tcpdf/tcpdf.php(7380): Warning - imagepng(/var/www/html/tmp/tcpdf/__tcpdf_bf96ba20a3ed8a3621345ce3e1f573ce_imgmask_plain_7c46a167016c23507b929c97679089b7): failed to open stream: No such file or directory - Matomo 4.7.1
```

**Comment by sgiehl** [comment] 2022-03-04 12:59
@atom-box are you able to provide some more details on the system where that happens?
We actually have configured tcpdf to use a custom path, so `tempnam` shouldn't throw a notice.
Did they maybe configure `path.tmp` to the systems tmp directory?

**Comment by MatomoForumNotifications** [comment] 2022-03-04 13:32
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/tcpdf-error-when-running-core-archive-with-version-4-7-1/45003/3

**Comment by Starker3** [comment] 2022-03-07 01:11
FYI the forum post linked here is for the same end user. I'll update this issue once I have further details on this.
For more info though, they are running Matomo on a Multi server setup.

**Comment by sgiehl** [comment] 2024-05-27 09:17
closing as duplicate of https://github.com/matomo-org/matomo/issues/21372

**Closed as not planned by sgiehl** 2024-05-27 09:17 UTC
Labels: duplicate
