### ISSUE TITLE
ecommerce report, Custom variables not displayed

### ISSUE THREAD

**Issue by ryrun** [piwik/piwik#4845] opened 2014-03-12 10:11 UTC
We are currently using user defined variables for customers states of visitors on a store. This should allow use to evaluate what kind of customers did an order. guest vs existing customer vs new customer. This user defined variable will be set on each visit.
It works great for for basic visitor statistics but not for ecommerce. On ecommerce, the visits are count but not the orders. It seems the user defined stats in ecommerce tab is broken.

I'm using piwik 2.1.0, current stable version.

**Comment by mattab** [comment] 2015-04-07 08:13
Thanks  @ryrun for the report - I believe it's duplicate of:  wrong ecommerce conversion calculation in custom variables report #5828 so closing for now - feel free to comment on #5828 as we really want to fix this in next few months

**Closed by mattab** 2015-04-07 08:13 UTC
Labels: Bug
