### ISSUE TITLE
[Bug] Declaration of DI\Container::has($name) must be compatible with Psr\Container\ContainerInterface::has(string $id): bool

### ISSUE THREAD

**Issue by downhiller** [piwik/piwik#21758] opened 2024-01-04 09:21 UTC
### What happened?

I installed matomo with this one-liner, on a PHP 8.3.1 / CentOS Stream release 8 system:

    wget https://builds.matomo.org/matomo.zip && unzip matomo.zip

when I navigate my browser to the relevant folder I get a 500 error, and this line in my logfile:

    FastCGI sent in stderr: "PHP message: PHP Fatal error:  Declaration of DI\Container::has($name)
    must be compatible with Psr\Container\ContainerInterface::has(string $id): bool in
    /var/www/sites/mydomain/http/matomo/vendor/php-di/php-di/src/Container.php on line 210"
    while reading response header from upstream

Any ideas?

### What should happen?

The dashboard should load

### How can this be reproduced?

-

### Matomo version

5.0.0

### PHP version

8.3.1

### Server operating system

CentOS Stream release 8

### What browsers are you seeing the problem on?

Not applicable (e.g. an API call etc.)

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment] 2024-01-04 10:19
I had a look at the dependencies that are triggering this error.
We are currently using `phpd-di/php-di` version `6.3.5`, which defines the method `has($name)` here:
https://github.com/PHP-DI/PHP-DI/blob/6.3.5/src/Container.php#L210
While we are using `psr/container` version ´1.1.1´, which defines the method `has(string $id)` here:
https://github.com/php-fig/container/blob/1.1.1/src/ContainerInterface.php#L35

So basically both definitions don't match and seem to throw an error for your PHP version.

The definition in `php-di` has been fixed with version `7.0.0`. Unfortunately we can't update to that version as it requires PHP 8, while we still support PHP 7.2.
Alternatively we could try downgrading `psr/container` to version `1.0.0`, as that version defined `has($name)` and would be compatible. See
https://github.com/php-fig/container/blob/1.0.0/src/ContainerInterface.php#L35
But downgrading this might not easily work, as the dependency `symfony/service-contracts` requires version `1.1`.

@tsteur any thoughts on this? Creating a patched fork of `php-di` doesn't sound like the smartes solution for me...

**Comment by tsteur** [comment] 2024-01-04 18:23
@downhiller when does this issue happen? 
@sgiehl Is that an issue with PHP 8.3 or also other PHP versions? Is this maybe a regression and not technical debt?

I'm not really seeing another option that to create a patched fork here as we can't increase the PHP version now. Are there any other options?

**Comment by downhiller** [comment] 2024-01-05 11:47
Apologies for wasting your time, it was due to some code in an auto_prepend_file on a legacy project.  I don't understand WHAT code in there was breaking it, but hey ho.  Sorry again :-(

**Comment by sgiehl** [comment] 2024-01-05 13:10
@downhiller Guess your code uses a newer version of `psr/container` and therefor causing the trouble. The problem is that the version you use is defining a return type: `ContainerInterface::has(string $id): bool`, which is incompatible to not defining one.

**Closed as not planned by sgiehl** 2024-01-05 13:10 UTC
Labels: answered
