### ISSUE TITLE
Auto login feature broken in Safari

### ISSUE THREAD

**Issue by timk95** [piwik/piwik#11264] opened 2017-01-23 12:28 UTC
It seems that the auto login feature doesn't work while in a iframe in Safari. It works fine in other browsers I've tested.

I think it's related to a wrong X-Frame-Options header. The headers contains the value ", AA".

We're on Piwik 3.0.1, PHP 7, Ubuntu 16.04, Nginx 1.11.8. the enable_framed_pages option is enabled.

**Comment by mattab** [comment] 2017-02-18 11:32
Thanks for the report. Marking as duplicate of https://github.com/piwik/piwik/issues/10167

**Closed by mattab** 2017-02-18 11:32 UTC
