### ISSUE TITLE
Email report: page url which are too long are truncated in pdf format

### ISSUE THREAD

**Issue by Chardonneaur** [piwik/piwik#20035] opened 2022-11-21 14:26 UTC
When we export the page url report as a pdf, if the urls are too long, they get truncated so impossible to use by the recepient.

What would be great is to have them moving to the next line when they are too long.

**Comment by sgiehl** [comment] 2022-11-21 16:15
@Chardonneaur Might this one be included in the report in #18950 ?

**Comment by bx80** [comment] 2022-11-23 20:47
Closing as a duplicate of #18950

**Closed as completed by bx80** 2022-11-23 20:47 UTC
Labels: duplicate

**Comment by tzi** [comment] 2026-02-09 15:38
Should be fixed in #23919
