### ISSUE TITLE
No visit displayed after updating this mornig

### ISSUE THREAD

**Issue by johnny57** [piwik/piwik#7797] opened 2015-04-30 13:09 UTC
Hello,

I have updated piwik this mornig. After the update, no site want to show any visit. I toke a look in the database (log_visit) and all visits are recorded, but when I watch the report the last visit is just before the update.

I checked with firebug and I saw anything strange. All request are for the piwik folder, except that one in blue for wich I got a 301 code :

http://www.hostingpics.net/viewer.php?id=465850piwik.png

Any idea ?
Thanks in advance for your help.

**Comment by mattab** [comment] 2015-05-01 02:51
Hi @johnny57 
did you setup the Cron archiving script? http://piwik.org/docs/setup-auto-archiving/ or do you use browser archiving? 

If you execute in piwik `./console core:archive --url=...` what does it output?

**Comment by johnny57** [comment] 2015-05-01 07:26
Hi @mattab,

Thank you for your answer.
Maybe was you right for the problem of displaying the informations because tomorrow, before doing anything all reports are dispalyed. 
To answer your question, yes, I use the browser archiving solution, not the cronjob solution. Maybe while the update a bug happend in the archiving process.

But, for the false url the problem is still there. i still have this url 

http://www.buzionweb.fr/index.php?module=API&method=Chat.poll&idSite=21&microtime=true&fromAdmin=true&format=json&_=1430464524071 

in place of (I think) 

http://www.buzionweb.fr/piwik/index.php?module=API&method=Chat.poll&idSite=21&microtime=true&fromAdmin=true&format=json&_=1430464524071

As you can see : 
http://www.hostingpics.net/viewer.php?id=465850piwik.png

All others url requested by the page are right except this one.

**Comment by tsteur** [comment] 2015-05-05 02:02
Hi @johnny57

The false URL seems to be a problem in the Chat plugin maybe caused by this https://github.com/VincentLahaye/piwik-chat/blob/caf658965f261a320e031871f78aeb290f7b7d4e/javascripts/backend/chat.js#L85 as all other URLs seem to work fine. @VincentLahaye what do you think?
 
@johnny57 Can you create an issue for this in https://github.com/VincentLahaye/piwik-chat/issues ?

I'll close it for now but feel free to reopen in case it is caused by us.

**Closed by tsteur** 2015-05-05 02:02 UTC
