### ISSUE TITLE
Auth for tracking API

### ISSUE THREAD

**Issue by maddyexplore** [piwik/piwik#22568] opened 2024-09-09 10:21 UTC
## Summary

We have deployed and using Matomo on-premise. In that, Tracking API seems to be open and can be accessible from any webpage without any authentication. Is there any way to restrict this action and make the tracking Api secure and accessible only from our applications?

## Your Environment

* Matomo Version: 5.1.1
* PHP Version: 8.2.23
* Server Operating System: Linux
* Additionally installed plugins: Nil

**Comment by sgiehl** [comment] 2024-09-09 13:00
Hey @maddyexplore,

I'll close this as duplicate of https://github.com/matomo-org/matomo/issues/20801. As it's basically the same. You will find an answer in this issue as well.

Cheers,

**Closed as not planned by sgiehl** 2024-09-09 13:00 UTC
Labels: duplicate
