### ISSUE TITLE
Scheduled report shows square character in HTML report in date

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#21186] opened 2023-08-27 21:14 UTC
See below screenshot:

<img width="864" alt="image" src="https://github.com/matomo-org/matomo/assets/273120/04e969c1-126b-4463-a1f4-f73acac42771">

I created a scheduled report including graphs. Not PDF but HTML.

Then I clicked on "Download" on the created report.

The issue is visible on every graph.

This is on Matomo 5 on demo.matomo.org .

**Comment by sgiehl** [comment] 2023-08-28 14:21
The "problem" is that various languages are using special space characters (e.g. half width, non breakable, ...) within the date format definition. The font we are using the generate the graphs simply doesn't support those characters.

We implemented a fix for french only in the past, where numbers weren't displayed correctly due to using a special space chart. See https://github.com/matomo-org/matomo/pull/20953

This time we should definitely aim to find a more global solution to fix all problems around that.

This might also be solved when using a new charting library, which we might need to do anyway. See #20570

**Comment by tsteur** [comment] 2023-08-28 20:21
@sgiehl Did this used to work and is a regression? Or did it never work? I don't remember seeing this in the mobile app where we maybe use the same graphs (not 100% sure though).

**Comment by sgiehl** [comment] 2023-08-28 22:14
I guess it kind of used to work at some point before we were using date format definitions from CLDR. Those definitions are updated from time to time. Maybe those unusual spaces in English came in with one of the latest updates.

**Comment by tsteur** [comment] 2023-08-28 23:19
👍  Thanks for that. Could we label it as a regression in that case? cc @Stan-vw

**Comment by Stan-vw** [comment] 2023-08-28 23:54
It's a bit tough to see if this is a proper regression, given the CLDR move sounds like a strategic choice and it's potentially been part of it ever since. But given that it potentially affects A LOT of users / report consumers and it's pretty embarrassing, I'm keen to prioritise is either way.

**Comment by atom-box** [comment] 2024-01-24 17:10
Today a user reported: 

- The characters display correctly in Matomo user interface but
- They fail to display correctly when exported in a pdf report.

![bad-pdf-characters-straight](https://github.com/matomo-org/matomo/assets/22874146/5325f3cc-46b5-4d1f-adf4-461f7ac1e055)

> We are observing boxes under entry page title section. This might be in place of Hindi (Regional languages).
> Please help us with the necessary modifications to remove these boxes.
>

**Comment by mneudert** [comment] 2024-02-14 08:16
Two known problematic characters introduced by CLDR 42 (thin space, narrow non-breaking space) have been treated in #21897 to fix rendering for the default non-unicode font. _That is only an extension to the work done in #20953._

Having #21854 for general font improvements (everything outside graphs), and #20570 to replace the image library, should this be closed as solved? Or is there more we need to improve until a long-term solution is in place?

**Comment by sgiehl** [comment] 2024-02-14 08:49
Let's close this one. Besides the issues you already mentioned, there are also #8665, #21129, #3304 and maybe even more that would benefit from a stable/global solution for that topic. We can now simply add more characters for replacement if other issues are opened.

**Closed as completed by sgiehl** 2024-02-14 08:49 UTC
Labels: Bug, Regression
